### ISSUE TITLE
[feature] Refactor city over base_city and zip over better_zip

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1]
See https://lists.launchpad.net/openerp-community/msg02637.html
and
https://code.launchpad.net/~camptocamp/partner-contact-management/city_into_better_zip/+merge/162771

We will probably do it for v8

**Comment by rvalyi** [comment]
also see https://code.launchpad.net/~savoirfairelinux-openerp/partner-contact-management/city-move/+merge/196023

**Comment by mileo** [comment]
9.0?
