### ISSUE TITLE
[12.0][BUG] Traduções de campos do l10n_br_fiscal

### ISSUE THREAD

**Issue by luismalta** [OCA/l10n-brazil#1014]
**Descreva o bug**
Os campos fiscal_price e discount value do l10n_br_fiscal usados pelo l10n_br_sale, não estão sendo traduzidos mesmo com os termos já existente nos arquivos de traduções.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para o módulo l10n_br_sale
2. Clique em em uma cotação e a abra um item de pedido
4. Ver erro

**Comportamento esperado**
Campos fiscal_price e discount value traduzidos conforme o arquivo de tradução.

**Capturas de tela**
![WhatsApp Image 2020-10-30 at 11 53 40](https://user-images.githubusercontent.com/14153034/97997960-4c8e7000-1dc8-11eb-8ab4-adeca445e329.jpeg)

**Contexto adicional**
Foi verificado que o arquivo l10n_br_fiscal.pot, esta sendo gerado com os termos de traduções desses campos em branco, mas nenhuma manipulação desse arquivo gerou resultados.

**Comment by mileo** [comment]
@luismalta vc já tentou gerar novamente o arquivo .po do sale? 

e/ou copiar o termo que vc quer traduzir do l10n_br_fiscal para o l10n_br_sale, acertando a referência?

**Comment by luismalta** [comment]
@mileo Sim, já tentei ambas as sugestões. Nenhuma delas teve efeito.
