### ISSUE TITLE
[RFC] arrumar os warning na CI com o modulo l10n_br_website_sale

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1026]
@mileo @DiegoParadeda conforme eu comentei o outro dia, desde que vcs fizeram o merge do l10n_br_website_sale os warning da CI nao sao mais legíveis com essa caralhada de warnings da formatação Javascript:

https://travis-ci.com/github/OCA/l10n-brazil/jobs/434577380#L520

Por favor ver para dar uma formatação nisso senão ninguem mais vai prestar atenção nos warnings do Pylint do projeto...

cc @renatonlima @marcelsavegnago

**Comment by mileo** [comment]
@DiegoParadeda detectei um erro ocasional no travis: https://travis-ci.com/github/OCA/l10n-brazil/jobs/442345065#L2744  referente a Cielo. Vc poderia dar uma olhada nisso tb plz.

**Comment by marcelsavegnago** [comment]
> https://travis-ci.com/github/OCA/l10n-brazil/jobs/442345065#L2744

 Boa @mileo Tbm tinha visto isso mas soh detectei na hora que fiz um push na PR #1029 e acabei postando lah o comentário.
https://github.com/OCA/l10n-brazil/pull/1029#issuecomment-728173381
