### ISSUE TITLE
[BUG] Regra de Posição Fiscal o sistema não verifica o Tipo Fiscal do Parceiro

### ISSUE THREAD

**Issue by lepri** [OCA/l10n-brazil#103]
Ao criar uma Regra de Posição Fiscal o sistema não verifica o Tipo Fiscal do Parceiro. Com isso não é possível criar regras para pessoas físicas e jurídicas.

Encontrado na versão 7.0

**Comment by renatonlima** [comment]
Olá @lepri 

Obrigado pela sua iniciativa de contribuir com o projeto, mas isso foi corrigido na branch develop https://github.com/openerpbrasil/l10n_br_core/blob/develop/l10n_br_account/account_fiscal_position_rule.py há algum tempo atrás.

**Comment by lepri** [comment]
Olá @renatonlima,

Eu acabei vendo que foi corrigido, mas na branch develop. Será que não vale corrigir também na branch 7.0?

**Comment by renatonlima** [comment]
Olá Gustavo eu vou aceitar o pull request na v7

**Comment by mileo** [comment]
Podemos fechar?

**Comment by renatonlima** [comment]
Done in https://github.com/OCA/l10n-brazil/pull/134
