### ISSUE TITLE
[RFC][12.0] Aumentar a cobertura de testes do l10n_br_sale_stock

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1037]
Ontem foi feito o merge do PR https://github.com/OCA/l10n-brazil/pull/968 com cobertura de **"57.14% of diff hit (target 81.44%)"**

Como os casos de uso são complexos, abro a discussão para pensarmos nos casos de teste e implementa-los.

cc: @gabrielcardoso21 @sadamo @rvalyi @renatonlima @marcelsavegnago

**Comment by mbcosta** [comment]
A inclusão de casos de uso pode ser feita através de dados de demonstração e testes, o modulo está sendo refatorado aqui https://github.com/OCA/l10n-brazil/pull/1103 se puderem vejam se os dados e testes incluídos atendem ou se teriam outros casos de uso que deveriam ser incluídos.
