### ISSUE TITLE
[BUG] O CFOP não está sendo setado na fatura

### ISSUE THREAD

**Issue by lepri** [OCA/l10n-brazil#105]
Mesmo quando o CFOP é setado na Posição Fiscal, ele não é inserido na fatura. Apesar dos impostos estarem sendo inseridos corretamente.

branch development

**Comment by danimaribeiro** [comment]
Confirmo também o bug, o erro realmente ocorre.

**Comment by mileo** [comment]
Vindo do pedido na visão simplificada?

**Comment by danimaribeiro** [comment]
O que você quis dizer com visão simplificada?

**Comment by mileo** [comment]
Sem o propriedades nas linhas ativado, quando não abre o pop up
Em 19/01/2015 20:56, Danimar Ribeiro notifications@github.com escreveu:O que você quis dizer com visão simplificada?

**Comment by danimaribeiro** [comment]
Eu não tenho 100% de certeza, mas acho que não estava relacionado a isto o problema.
Eu lembro porém que a correção deveria ser feita no módulo l10n_br_account_product, pois é nesse módulo que o cfop_id é criado.
Tem algo relacionado também ao fato do l10n_br_sale_produt estar ou não instalado.

**Comment by mileo** [comment]
Podemos fechar?

**Comment by lepri** [comment]
@mileo por mim pode sim

**Comment by mileo** [comment]
@lepri Feche vc por favor ou precisamos aguardar alguem da OCA

**Comment by mileo** [comment]
Please close this issue
