### ISSUE TITLE
[12.0][BUG] Arredondamento de Impostos

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1054]
Pessoal,

Esta semana estava testando a geração do documento fiscal e identifiquei que na criação de um novo documento fiscal existe um problema no arredondamento do valor dos impostos. 

![image](https://user-images.githubusercontent.com/3595132/103161972-b9baf200-47c8-11eb-88ad-786fd473b506.png)

![image](https://user-images.githubusercontent.com/3595132/103161996-04d50500-47c9-11eb-9d74-39ba216e72d1.png)

Quando troco o percentual do imposto, salvo o documento, abro novamente e volto para o imposto que estava configurado o numero de casas decimais fica correto. 

![image](https://user-images.githubusercontent.com/3595132/103162009-4fef1800-47c9-11eb-8352-a79e0b34c4be.png)

![image](https://user-images.githubusercontent.com/3595132/103162008-45cd1980-47c9-11eb-8207-b37adfc16e93.png)

Obs. Neste momento contornei a situação adicionando um round que atua somente na geração do XML e portanto não foi corrigido no banco dedados.

cc @mileo @rvalyi @renatonlima

**Comment by rvalyi** [comment]
@marcelsavegnago vc ta ciente que a Odoo SA faz os calculos com Float em vez de Decimal no Odoo? Esse fields.Monetary tem Float por tras...
Entao coisas que eram para ser triviais como adicionar 2 centavos com 2 centavos vira um problema de calculo cientifico com epsilons. Me parece que na teoria as ferramentas do Odoo ate funcionam mas é foda para programar sem criar esses problemas.

Para resumir eu diria que em base 10, 1/3 nao cai certo e com um numero de digitos finitos vc cria erros de representação e então de arredondamentos nos cálculos (principalmente qdo esse erro cai no limite para sabe se arredonda para cima ou para baixo). Com os floats em base 2, sao outras fracções, valores como 2/10 que não tem representação binaria finita e coisas com os 20 centavos do contador não são mãos exactamente 20 centavos no Odoo e vc tem que se virar com epsilons e arredondamentos.

Aconselho de vc ler: https://en.wikipedia.org/wiki/IEEE_754
e esse https://github.com/odoo/odoo/blob/12.0/odoo/tools/float_utils.py

Isso já rendeu inumerosas conversas com o Fabien Pinckaers. Basicamente eles não vão mudar tao cedo. No banco ta como Decimal, mas no Odoo ta como float e a gente tem que se virar com as ferramentas de arredoamento. Qualquer ajuda esta bem vinda.

**Comment by marcelsavegnago** [comment]
@rvalyi tinha uma leve noção disso mas nada muito profundo. No caso da NFSe vou propor uma PR fazendo o arredondamento (pretendo utilizar o método round) no momento da exportação dos dados para permitir a geração o XML. O que acha ?

https://github.com/OCA/l10n-brazil/blob/3d0986f187177a395a63cbd0c0d14186cd0bcabf/l10n_br_nfse/models/document_line.py#L107

@mileo O que acha ?

cc @gabrielcardoso21 @luismalta
