### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by edsonblwolf** [OCA/l10n-brazil#1060]
** Descreva o bug **
Estou instalando o módulo l10n_br_account

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. ERROR banco odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['account_cancel', 'l10n_br_account', 'l10n_br_fiscal']

**Comportamento esperado**
Instalação do módulo. Mas pela mensagem não existe o módulo, account_cancel .

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.
git clone -b 12.0 https://github.com/OCA/currency
git clone -b 12.0 https://github.com/OCA/bank-payment
git clone -b 12.0 https://github.com/OCA/account-payment
git clone -b 12.0 https://github.com/OCA/account-invoicing
git clone -b 12.0 https://github.com/OCA/mis-builder
git clone -b 12.0 https://github.com/OCA/contract
git clone -b 12.0 https://github.com/OCA/reporting-engine
git clone -b 12.0 https://github.com/OCA/server-tools
git clone -b 12.0 https://github.com/OCA/storage
git clone -b 12.0 https://github.com/OCA/connector
git clone -b 12.0 https://github.com/OCA/queue
git clone -b 12.0 https://github.com/OCA/web
git clone -b 12.0 https://github.com/OCA/pos
git clone -b 12.0 https://github.com/OCA/partner-contact
git clone -b 12.0 https://github.com/OCA/stock-logistics-barcode
git clone -b 12.0 https://github.com/OCA/stock-logistics-workflow
git clone -b 12.0 https://github.com/OCA/product-attribute
git clone -b 12.0 https://github.com/OCA/purchase-workflow
git clone -b 12.0 https://github.com/OCA/server-ux
git clone -b 12.0 https://github.com/OCA/server-env
git clone -b 12.0 https://github.com/OCA/delivery-carrier

**Comment by marcelsavegnago** [comment]
O account_cancel é nativo do Odoo. 
https://github.com/odoo/odoo/tree/12.0/addons/account_cancel

Instalou as bibliotecas python que são necessárias ?

**Comment by edsonblwolf** [comment]
Obrigado Marcel, ela estava instalada, só precisei atualizar.
Estranho por que instalei o odoo hoje e esta na versão de hoje, será que é necessário atualizar pela interface mesmo depois de atualizado pelo git clone ???

**Comment by marcelsavegnago** [comment]
> Obrigado Marcel, ela estava instalada, só precisei atualizar.
> Estranho por que instalei o odoo hoje e esta na versão de hoje, será que é necessário atualizar pela interface mesmo depois de atualizado pelo git clone ???

Então. Se vc clonou agora e instalou, já estaria atualizado.

**Comment by edsonblwolf** [comment]
Estranho. Agora estou anotando todos os meus passos pra não me perder. Obrigado.
