### ISSUE TITLE
[BUG] Documento Fiscal de Prestação de Serviço via Pedido de Vendas

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1089]
**Descreva o bug**
Quando é criado um documento fiscal de prestação de serviço via pedido de vendas o campo city_taxation_code_id não é preenchido.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Cadastrar Serviço (Configurar Tipo Fiscal, Tipo de Serviço e cadastrar Código de Tributação da Cidade)
2. Criar Pedido de Venda e adicionar o serviço criado no passo anterior
3. Confirmar e Criar Fatura
4. Consultar campo Código de Tributação da Cidade na linha do documento fiscal

**Comportamento esperado**
O esperado é que o campo seja preenchido igual é feito quando o documento fiscal é criado diretamente via módulo Fiscal

cc @mileo @gabrielcardoso21

**Comment by gabrielcardoso21** [comment]
Coloquei o mesmo mecanismo feito no fiscal na passagem dos valores da sale_order_line: https://github.com/OCA/l10n-brazil/pull/1095

**Comment by marcelsavegnago** [comment]
@gabrielcardoso21 desta forma o módulo l10n_br_sale vai ficar com dependência do módulo l10n_br_nfse ?

**Comment by gabrielcardoso21** [comment]
> @gabrielcardoso21 desta forma o módulo l10n_br_sale vai ficar com dependência do módulo l10n_br_nfse ?

Se o seu PR movendo o campo city_taxation_code_id pro fiscal passar o problema está resolvido. Se não, teremos que decidir se o l10n_br_sale vai depender do l10n_br_nfse, se movemos o código pro l10n_br_nfse e fazemos ele depender do l10n_br_sale ou se criamos um módulo l10n_br_sale_nfse com só esse código.

**Comment by marcelsavegnago** [comment]
> > @gabrielcardoso21 desta forma o módulo l10n_br_sale vai ficar com dependência do módulo l10n_br_nfse ?
> 
> Se o seu PR movendo o campo city_taxation_code_id pro fiscal passar o problema está resolvido. Se não, teremos que decidir se o l10n_br_sale vai depender do l10n_br_nfse, se movemos o código pro l10n_br_nfse e fazemos ele depender do l10n_br_sale ou se criamos um módulo l10n_br_sale_nfse com só esse código.

Concordo..

cc @renatonlima @rvalyi  sobre o campo city_taxation_code_id

**Comment by marcelsavegnago** [comment]
@renatonlima e @rvalyi temos algumas possibilidades para tratar esta questão. A dúvida agora é migrar o campo para o l10n_br_fiscal (fiz 3 PRs mas posso fazer tudo em uma só e fazer os commits separados por módulo afetado), seguir com a PR do @gabrielcardoso21  e deixar o módulo l10n_br_sale depender de l10n_br_nfse e a outra opção sugerida pelo @gabrielcardoso21 é criar um módulo chamado l10n_br_sale_nfse. Vocês tem alguma sugestão ?

PRs de Migração do campo city_taxation_code_id para o fiscal 

- https://github.com/OCA/l10n-brazil/pull/1091
- https://github.com/OCA/l10n-brazil/pull/1092
- https://github.com/OCA/l10n-brazil/pull/1093

PR sugerida pelo @gabrielcardoso21 

- https://github.com/OCA/l10n-brazil/pull/1095

cc @mileo
