### ISSUE TITLE
Criação de novos módulos para dividir funcionalidades fiscais de produtos e serviços

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#11]
Refatorar o módulo l10n_br_account deixando apenas as funcionalidades comuns para produtos e serviços, e criar novos módulos l10n_br_account_product e l10n_br_account_service, deixando as funcionalidades fiscais de produtos e serviços separados, permitindo que empresas que trabalham somente com serviços não tenha que instalar funcionalidades fiscais de produtos.

**Comment by citec** [comment]
+1

Renato Lima notifications@github.com wrote:

> Refatorar o módulo l10n_br_account deixando apenas as funcionalidades
> comuns para produtos e serviços, e criar novos módulos
> l10n_br_account_product e l10n_br_account_service, deixando as
> funcionalidades fiscais de produtos e serviços separados, permitindo
> que empresas que trabalham somente com serviços não tenha que instalar
> funcionalidades fiscais de produtos.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/openerpbrasil/l10n_br_core/issues/11

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by renatonlima** [comment]
Desenvolvimento já realizado na branch develop
