### ISSUE TITLE
[RFC][12.0][l10n_br_nfe] melhorar os testes de serialização XML

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1106]
para ajudar no merge do PR https://github.com/OCA/l10n-brazil/pull/1043 e na manutençao do modulo de NFe seria bom melhorar o teste de serializaçao de NFe Odoo que o @gabrielcardoso21 fez. Na vdd teria que melhorar um pouco o framework de exportaçao nos modulos spec_model_driven e l10n_br_nfe.

Atualmente, pros testes rodar minimamente para fazer o PR eu desativei a checagem de nao ter diff no XML gerido com um XML de teste:
https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_nfe-ak-filtered/l10n_br_nfe/tests/test_nfe_serialize.py#L127

Eu tive que fazer isso por varios motivos:

1. o XML de saida vai depender da chave de NFe que vai depender da data e vai dar um diff depois de um tempo.
2. idealmente a NFe de teste tem que sair com o xNome do dest como "NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL" como no XML de teste: https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_nfe-ak-filtered/l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200697231608000169550010000000111855451724-nf-e.xml#L44

Eu chequei a saida com meld comparando com o XML de teste e eu acho que nao tinha outra diferença, mas poderia ter.  Tb esse teste eh muito trivial e tanto o @gabrielcardoso21 qto a Akretion trabalharam depois em melhorar o mapping dos impostos. Idealmente a gente tem outros tests com IPI, simples etc...

Mas enfim, para começar, eu acho que o ideal seria que o codigo de serializaçao como esse do teste `self.nfe.with_context(lang='pt_BR')._document_export()` **retornasse primeiro um "data structure"** (o que o Gabriel chamou de ds_ as vezes no codigo dele) ou que eu chamaria de "binding" nfelib que seria so o objeto Python que representa o XML (e cujas classes estao geridas no nfelib). E **so depois se chamaria o nfe_binding.export(sys.stdout, level=0**) ou algo do tipo que criaria o XML pelo framework gerido pelo generateDS hoje.

**Com 2 passos assim, seria muito mais conveniente a gente poder alterar qualquer coisa da NFe antes de criar o XML. Seria então trivial alterar a chave, para ser igual do XML de teste independente da data o enfiar o xNome correcto.**

Alem dos teste, isso seria bem conveniente para resolver pepinos na prod, do tipo "a Nota X nao ta saindo correctamente, precisamos de algum patch urgentissmo porque o caminhao esta esperando" nao da tempo de testar o framework todo, bota um hotfix com a porra do valor que precisa e libera a porra da nota. Sujo, mas salva a vida. Hoje para resolver qualquer coisa, vc tem que ficar quebrando a cabeça meia hora ou horas...

Nisso **seria legal re-ativar a checagem do XML com xmldiff**.

cc @marcelsavegnago @renatonlima @gabrielcardoso21 @mileo @mbcosta @clementmbr

**Comment by rvalyi** [comment]
nota: @marcelsavegnago vc pode ver como eh um binding NFe e como se navega dentro (aqui para ler mas poderia ser para alterar um valor antes de exportar o XML) aqui e nas linhas depois por examplo:
https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_nfe-ak-filtered/l10n_br_nfe/tests/test_nfe_import.py#L32

**Comment by rvalyi** [comment]
Falei besteira, esse ultimo link nao eh um binding nfelib. Um binding nfelib, vc tem examplos no README do nfelib https://github.com/akretion/nfelib#como-usar

**Comment by marcelsavegnago** [comment]
> Falei besteira, esse ultimo link nao eh um binding nfelib. Um binding nfelib, vc tem examplos no README do nfelib https://github.com/akretion/nfelib#como-usar

@rvalyi Este tnfe https://github.com/akretion/l10n-brazil/blob/bc8a3ee3a03c26453352e61446d09944c6b1dcf1/l10n_br_nfe/models/document.py#L310 seria um exemplo de binding ?

**Comment by marcelsavegnago** [comment]
@rvalyi a única diferença agora está nas tags IPI IPITrib que não são carregadas para o XML. Estou fuçando para resolver mas ainda não tive sucesso :D. Porém, fechando isso já dá para fechar este teste de serialização.

**Comment by rvalyi** [comment]
fechando isso como ja ta bem resolvido aqui https://github.com/OCA/l10n-brazil/pull/1043

**Comment by rvalyi** [comment]
(temos sim que resolver a regressao com o IPI, so fechei a respeito dos outros pontos que ja foram atendidos)
