### ISSUE TITLE
[BUG] partner.inscr_est unique sql constraint

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#111]
Create a partner with inscr_est = 'ISENTO' 

> python constraint : (_check_ie, u'Inscrição Estadual inválida!', ['inscr_est']) returns True.
> https://github.com/OCA/l10n-brazil/blob/7.0/l10n_br_base/res_partner.py#L107

Create a new partner with inscr_est = 'ISENTO' 

> python constraint : (_check_ie, u'Inscrição Estadual inválida!', ['inscr_est']) returns True.
> unique sql constraint returns False

Then u can't save.

**Comment by mileo** [comment]
This constraint should be removed:
https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_base/models/res_partner.py#L91

**Comment by mileo** [comment]
UP

**Comment by mileo** [comment]
@biancatella

**Comment by biancatella** [comment]
valeu @mileo !

**Comment by rvalyi** [comment]
fixed by https://github.com/OCA/l10n-brazil/commit/80d1a7e19f8439d146baa93e6bbc712c14d004f8
