### ISSUE TITLE
[BUG] 12.0 10n_br_purchase

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1115]
Erro é apresentado com o idioma em português, ao entrar em configurações, estando em inglês não acontece o erro

ValueError: Elemento '<xpath expr="//div[@data-key='purchase']//h2[text() = 'Invoicing']/following-sibling::div[1]">' não pode ser localizado na vista principal

Contexto de erro:
Veja `l10n_br_purchase.res.config.settings.form`
[view_id: 1930, xml_id: l10n_br_purchase_stock.l10n_br_purchase_res_config_settings_form, model: res.config.settings, parent_id: 1276]

**Comment by renatonlima** [comment]
Olá @vanderleiromera obrigado pelo bug report, eu fiz um fix no PR #1116 você pode testar local ou no runbot?

**Comment by vanderleiromera** [comment]
Perfeito @renatonlima testado local, tudo ok.
Obrigado
