### ISSUE TITLE
Frete Duplicando em Cotações/Pedido

### ISSUE THREAD

**Issue by Mackilem** [OCA/l10n-brazil#115]
@mileo 
Os testes que realizei relacionando ao frete na emissão de NFe 3.1 até agora estão ok, inclusive na validação com o Sefaz. Mas encotrei alguma coisa nas cotações, segue abaixo.

Problema:

O frete quando utilizado no sale.order está ficando duplicado no campo "total" do formulário.

l10n_br_brazil > branch '7.1'
NFe > branch 'develop'

Passo para reproduzir o erro:

1 - configurar o frete conforme PR-113;
2 - abrir uma cotação com um cliente qualquer e um produto qualquer com o valor de 100 reais;
3 - inserir um valor de 20 reais de frete no campo específico para frete;
4 - clicar no atualizar logo abaixo.

Resultado:

O total do orçamento foi de 140 reais, 100 do produto + 20 do frete + 20 da taxa de frete em impostos.

Resultado Desejado:

O total do orçamento deveria ficar em 120 reais

**Comment by danimaribeiro** [comment]
O correto seria:

```
val = val - (line.insurance_value + line.freight_value + line.other_costs_value)
```

pois a variável val2 vai acumulando, quando tiver mais de 1 item o cálculo da errado.
O segundo ponto é dentro do método _amount_line_tax (um pouco abaixo no mesmo arquivo), onde tem o if:

```
if not tax.tax_code_id.tax_discount:
```

o correto seria:

```
if not tax.tax_discount:
```

tax_code_id é nulo quando é criado um objeto tax, porém o tax_discount existe diretamente no objeto.

**Comment by Mackilem** [comment]
estou finalizando o erro por as mudanças já resolveram o problema.
