### ISSUE TITLE
[RFC] Improve NFS-e Report

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1153]
Last week @ygcarvalh start to improve NFS-E report.

Any suggestions are welcome.

![image](https://user-images.githubusercontent.com/1975978/109440579-8cc9cc00-7a11-11eb-977e-aef1d05b9e25.png)

**Comment by marcelsavegnago** [comment]
@mileo I think this is not the latest version of DANFSE. I had made some changes to the federal tax line. 

Note. Tomorrow I will take an example of the DANFSE generated by the ISSNET portal and add it here

**Comment by mileo** [comment]
![image](https://user-images.githubusercontent.com/1975978/109450761-7ed47500-7a2a-11eb-8c71-01e0c670ded0.png)

@marcelsavegnago You're right, thank you.... I just updated the Kmee's Odoo and it has improved a lot.

**Comment by mileo** [comment]
![image](https://user-images.githubusercontent.com/1975978/109450906-dd99ee80-7a2a-11eb-9f48-91a46f4adf5d.png)

There are some places where the edges are missing or not uniform.

CC: @ygcarvalh
