### ISSUE TITLE
[BUG] Duplicated fiscal messages

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1166]
When you go back 2 draft and confirm again:

![image](https://user-images.githubusercontent.com/1975978/109583889-64100800-7adf-11eb-8b4a-90db314da7e7.png)

**Comment by antoniospneto** [comment]
@mileo o que você acha dessa solucão? #1524

**Comment by antoniospneto** [comment]
@mileo com o merge da pr #1524  acredito que essa issue possa ser fechada
