### ISSUE TITLE
[Q&A] Mudanças dos Códigos de Tipo de Pagamento (NFE)

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1178]
### 436 Rejeição: Informado 99-Outros como meio de pagamento - Como Resolver

Nº do Artigo: 1080 | Avaliação: Não Avaliado | Última atualização: 11/02/2021 14:27:53

Quando for emitida uma NF-e (modelo 55) ou NFC-e (modelo 65) e no Tipo de Pagamento (Campo: tPag - ID: YA02) for informado Outros (tPag = 99), haverá a rejeição pelo motivo - 436: Informado 99-Outros como meio de pagamento .

 ### Exceções e Observações
Não há exceções à regra.

### Entrará em Vigor:
**Homologação: 01/02/2021
Produção: 01/09/2021**

**Importante:** Na nota técnica 2020.006 foram adicionados novas formas de pagamento. Verifique a forma de pagamento do documento correta.
![image](https://user-images.githubusercontent.com/3595132/109996339-e2da9000-7ced-11eb-9ee0-c4d9a48554c0.png)

cc @renatonlima @rvalyi @mileo

**Comment by marcelsavegnago** [comment]
Tratado pela PR https://github.com/OCA/l10n-brazil/pull/1385

**Comment by rvalyi** [comment]
> Tratado pela PR #1385

e tb a minha atualização do nfelib ontem https://github.com/akretion/nfelib/commit/86832c69ceed8809eecbd536cf55fdcd7aec044b
