### ISSUE TITLE
[12.0][BUG] l10n_br_stock_account : Duplicação do picking

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1200]
Quando um picking faturado é duplicado o status de faturamento também é copiado.

![image](https://user-images.githubusercontent.com/3595132/110726999-36bb0c80-81f9-11eb-9921-2ee9354056ce.png)

**Comment by marcos-mendez** [comment]
Pra mim duplicou tambem so nao sei aonde ta o erro.

**Comment by renatonlima** [comment]
@marcelsavegnago,

O campo invoice_state esta com o copy=False, 

https://github.com/OCA/account-invoicing/blob/12.0/stock_picking_invoicing/models/stock_invoice_state_mixin.py#L25

Eu acho que esse problema mencionado por você acabou sendo resolvido com o merge deste PR #1203

Eu acabei de fazer um teste no runbot e o invoice_state não foi copiado?  Você pode testar?

**Comment by marcelsavegnago** [comment]
@renatonlima fiz o teste pelo runbot e continua replicando o status do picking. Nas linhas do picking está OK mas no picking não.

![image](https://user-images.githubusercontent.com/3595132/111346486-0510ce00-865d-11eb-8dec-5497902fd65d.png)

**Comment by marcelsavegnago** [comment]
Resolvido pela PR #1214 . Obrigado @renatonlima
