### ISSUE TITLE
[12.0][BUG] l10n_br_stock_account: Campo fiscal_operation_id vazio na fatura e no documento fiscal

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1202]
Somente para registrar, ontem identifiquei um problema na geração de fatura/documento fiscal via picking. A principio, não é copiado o valor do campo fiscal_operation_id para a linha do produto tanto na fatura como no documento fiscal.

O @mileo havia comentado que poderia ter sido esta PR (https://github.com/OCA/l10n-brazil/pull/1183) mas acredito que não porque fiz o teste sem o módulo l10n_br_sale_stock instalado e o problema persiste.

![image](https://user-images.githubusercontent.com/3595132/110815085-e11e4880-8268-11eb-99b9-ac3d810f587e.png)

![image](https://user-images.githubusercontent.com/3595132/110815112-e8dded00-8268-11eb-84cd-4f2db59ca46a.png)

cc @renatonlima @rvalyi @luismalta @gabrielcardoso21

**Comment by rvalyi** [comment]
galera o @mbcosta ta vendo isso, a gente ja tava ciente dessa limitaçao faz algumas semanas como o Renato comentou no PR https://github.com/OCA/l10n-brazil/pull/1146 que nao interfere com essa limitaçao.

**Comment by renatonlima** [comment]
Esse caso esta acontecendo quando você tem o l10n_br_stock_account + o l10n_br_sale_stock instalados na mesma base de dados e ao criar um picking e gerar uma NF-e para esse picking alguns campos estão ficando em branco porque esta sendo chamado o super _get_invoice_line_values e o values (que tem o fiscal_operation_id=False) vindo do super esta sendo sobreposto do fiscal_values que (tem o valor do fiscal_operation_id vindo do stock.move)

**Comment by marcelsavegnago** [comment]
> Esse caso esta acontecendo quando você tem o l10n_br_stock_account + o l10n_br_sale_stock instalados na mesma base de dados e ao criar um picking e gerar uma NF-e para esse picking alguns campos estão ficando em branco porque esta sendo chamado o super _get_invoice_line_values e o values (que tem o fiscal_operation_id=False) vindo do super esta sendo sobreposto do fiscal_values que (tem o valor do fiscal_operation_id vindo do stock.move)

Me parece que mesmo sem o l10n_br_sale_stock acontece viu. Acabei de testar novamente em uma instalação feita sem o l10n_br_sale_stock

![image](https://user-images.githubusercontent.com/3595132/110830509-0d8d9100-8278-11eb-814c-6e92e99465fd.png)

![image](https://user-images.githubusercontent.com/3595132/110830605-29913280-8278-11eb-81c9-4a15cadf081c.png)

**Comment by marcelsavegnago** [comment]
Problema resolvido pela PR #1203
