### ISSUE TITLE
[RFC] Fluxo dos documentos fiscais (NF-e, NFS-e e etc)

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#1213]
Hoje antes de ser transmitido e autorizado o documento fiscal é confirmado e gerado os movimentos financeiro e contábil da fatura para que os dados de contas a pagar possam ser enviados no documento fiscal, devemos melhorar esse fluxo, para isso foi criado alguns PRs:

https://github.com/OCA/l10n-brazil/pull/983 Para refatorar os eventos dos documentos fiscais;
https://github.com/OCA/l10n-brazil/pull/1125 Criação dos dados financeiro no documento fiscal.

Com esse dois PRs já seria possível alterar o fluxo e confirmar e gerar a movimentação contábil da fatura ligada ao documento fiscal.

**Comment by mileo** [comment]
> Hoje antes de ser transmitido e autorizado o documento fiscal é confirmado e gerado os movimentos financeiro e contábil da fatura para que os dados de contas a pagar possam ser enviados no documento fiscal, devemos melhorar esse fluxo, para isso foi criado alguns PRs:
> 
> #983 Para refatorar os eventos dos documentos fiscais;
> #1125 Criação dos dados financeiro no documento fiscal.
> 
> Com esse dois PRs já seria possível alterar o fluxo e confirmar e gerar a movimentação contábil da fatura ligada ao documento fiscal.

@renatonlima  pode fazer o rebase do #983 ? Eu to com umas coisas pra comentar nele ai com o rebase fica mais fácil.

**Comment by mileo** [comment]
@renatonlima sobre o https://github.com/OCA/l10n-brazil/pull/983 Conseguiu dar uma olhada nele? Alguma coisa que precise que altere?

**Comment by mileo** [comment]
Ah sem esquecer que o PR #849 implementa mais coisas na parte de pagamentos.

**Comment by mileo** [comment]
> @renatonlima sobre o #983 Conseguiu dar uma olhada nele? Alguma coisa que precise que altere?

Ops comentei errado seria o #1125
