### ISSUE TITLE
[RFC]  l10n_br_website_sale tests fail too often 

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1245]
Same as https://github.com/OCA/l10n-brazil/issues/1185

**Yesterday I got my Travis test fail may be 6 times because of your module tests.**
like working on the NFe:
https://travis-ci.com/github/OCA/l10n-brazil/jobs/493302468#L3605

it really sucks to have a 20 min test suite fail because of that and we had similar problems in KMEE modules for around 4 years now since the l10n_br_portal module who killed us during the v8->v10 migration. So please KMEE fix your modules or don't add them to the repo! How is that not hoding back your own development?

cc @mileo diego.paradeda@kmee.com.br @marcelsavegnago @gabrielcardoso21

**Comment by mileo** [comment]
@DiegoParadeda How is the status of this activity? Similar Issue https://github.com/OCA/l10n-brazil/issues/1185

**Comment by DiegoParadeda** [comment]
@rvalyi, this test failed in another module as seen in https://travis-ci.com/github/OCA/l10n-brazil/jobs/493302468#L2561

Line 3605 (described in your issue) refers to a test that is shown as OK: "INFO openerp_test odoo.addons.l10n_br_website_sale.tests.test_sale_process: OK" https://travis-ci.com/github/OCA/l10n-brazil/jobs/493302468#L3609

**Comment by rvalyi** [comment]
Right in this case it seems it passed despite the stack trace. Still I think there is an instability with phantom_js.
With a quick search, in Odoo SA code own code, in v12 I can find:
grep -r phantom_js addons/*/tests | wc -l
46

The same on v14 returns 0 despite they still have some 4 or 5 occurrences elsewhere.

Instead they use their own ChromeBrowser:
https://github.com/odoo/odoo/blob/14.0/odoo/tests/common.py#L671

I cannot remember exactly where it was discussed but I think this is a known problem that phantom_js was instabled and got dropped. 

Also if you look at OCA/website you will find very little phantom_js usage.

I think that given the failure rates of these tests (despite the false positive here) it would be better you take a look at OCA/website and try to test your modules without phantom_js because it is extremely annoying for us to get the tests fail because of these modules we don't even use in any project.

**Comment by rvalyi** [comment]
Further than that this is really a problem if you come to the OCA, make 9 PR's that got usually approved and merged by @mileo (and there is much more to say about some of them, sadly I have no time for it now) and then leave us with your modules to maintain and that slow us down for hundreds of PRs we do to actually make Odoo work in Brazil, At the same time we see KMEE doing weekly fireforks in the project while it seems you guys are not even aware of the maintenance problem you created...

**Comment by DiegoParadeda** [comment]
@rvalyi I have searched for travis runs in which a fail was caused by the usage of phantom_js (in one of the modules maintained by KMEE) and couldn't find one. If that happens again please share the log with me so that I can see what the issue really is

**Comment by marcelsavegnago** [comment]
@DiegoParadeda pelo que entendi o @rvalyi está solicitando que reconsiderem a forma como foram implementados estes testes já que isto tem gerado impacto. Óbvio que vcs tem muito mais condições de julgar do que eu..... mas, lembro de pelo menos 2 ou 3 vezes onde foi necessário intervenção por conta de falhas relacionadas a estes testes (não lembro as PRs agora). Se considerar válido, sugiro que de uma olhada com calma levando em consideração o que foi apresentado e o que de fato é possível fazer sem comprometer os testes necessários. O que acha?

**Comment by DiegoParadeda** [comment]
@marcelsavegnago @rvalyi olhei algumas outras opções pra realizarmos os mesmos testes aqui.

Na v12 encontrei o "browser_js" que é rodado da mesma maneira que o phantom_js.

Na v13 em diante existe realmente uma diferença no common.py que o @rvalyi mostrou no comentário. Na v14 a forma de rodar o teste está bem diferente, sendo iniciado com "start_tour" e que parece ter acesso ao ChromeBrowser realmente.

Vou tentar rodar os testes que vocês mencionaram usando o browser_js pois não parece que o start_tour seria compatível num backport para a v12.

Tirando isso, nunca vi esses testes de front sendo rodados de alguma outra maneira no Odoo, vocês já?

**Comment by marcelsavegnago** [comment]
Grande @DiegoParadeda boaa.. vlwww

Sobre os testes no front sinceramente não lembro de ter visto nada a respeito.

**Comment by rvalyi** [comment]
> @marcelsavegnago @rvalyi olhei algumas outras opções pra realizarmos os mesmos testes aqui.
> 
> Na v12 encontrei o "browser_js" que é rodado da mesma maneira que o phantom_js.
> 
> Na v13 em diante existe realmente uma diferença no common.py que o @rvalyi mostrou no comentário. Na v14 a forma de rodar o teste está bem diferente, sendo iniciado com "start_tour" e que parece ter acesso ao ChromeBrowser realmente.
> 
> Vou tentar rodar os testes que vocês mencionaram usando o browser_js pois não parece que o start_tour seria compatível num backport para a v12.
> 
> Tirando isso, nunca vi esses testes de front sendo rodados de alguma outra maneira no Odoo, vocês já?

Entao, no OCA/website geralmente a galera se contenta de testar a presencia de alguns elementos no HTML da pagina sem criar um navegador headless. Isso claro nao testa o Javascript. Mas eu diria que se for para escolher prefiro que o Javascript nao seja testado do que ter 10% dos tests do projeto falhando por conta da instabilidade do phantom_js (sem brincar deve ser perto desse percentual). Acontece que a gente pensava que o problema vinha sempre do l10n_br_website_sale_delivery mas as vezes ele acontece em outros modulos como l10n_br_website_sale. Geralmente a a gente restarta o build e ele acaba passando na sorte mas a gente perde o maior tempo com isso em testes de 20 min. Eu acho que vc nao teria nenhum log relevante. Mas quando acontecer de novo eu posto aqui (aposto que vai ter hoje).

Valeu por olhar isso!

**Comment by marcelsavegnago** [comment]
> Acontece que a gente pensava que o problema vinha sempre do l10n_br_sale_delivery mas as vezes ele acontece em outros modulos como l10n_br_sale. Geralmente a a gente restarta o build e ele acaba passando na sorte mas a gente perde o maior tempo com isso em testes de 20 min. Eu acho que vc nao teria nenhum log relevante. Mas quando acontecer de novo eu posto aqui (aposto que vai ter hoje).

Foi o que notei tbm.. é meio volátil.

**Comment by rvalyi** [comment]
Bom @DiegoParadeda segue um exemplo real do que acontece hoje de vez em quando com o modulo l10n_br_website_sale:
https://travis-ci.com/github/OCA/l10n-brazil/jobs/492333474

![2021-03-25_22-38](https://user-images.githubusercontent.com/16926/112564941-e75d0a80-8dba-11eb-8fb1-f211dc0546d4.png)


Aqui vc encontra alguns do tipo:
https://travis-ci.com/github/OCA/l10n-brazil/builds

Nao contei exactamente, mas talvez a estatistica esta mais para 1 fail em cada 20 builds ou coisa do tipo. Nao deixa de atrasar a vida de todos contribuidores do projeto.

**Comment by DiegoParadeda** [comment]
Obrigado @rvalyi, vou tentar melhorar o que puder nessa questão lá no PR do  l10n_br_website_sale. Se ainda assim continuar dando problema procuro uma forma de testar o módulo por algum outro caminho

**Comment by rvalyi** [comment]
Essa é outra num modulo da KMEE, l10n_br_portal dessa vez, so para vcs se ligarem que nao é implicancia minha
https://travis-ci.com/github/OCA/l10n-brazil/jobs/495083496#L3250
e olhem que na fase da migraçao v8->v10 os testes nesse modulo atrasaram muito mais nossa vida para um modulo que a gente nunca nem sequer usou...

**Comment by rvalyi** [comment]
mais um aqui mesmo depois do correctivo https://travis-ci.com/github/OCA/l10n-brazil/jobs/495376442#L3863
e inclusive seguido de um bug ni l10n_br_portal tb da KMEE alias.
cagou o merge aqui https://github.com/OCA/l10n-brazil/pull/1109

cc @mileo @DiegoParadeda @marcelsavegnago @renatonlima 

Eu acho que a gente vai consegui levar ate o fim da v12, mas so para vcs se tocarem um pouco e pensar duas vezes antes de "contribuir" qualquer modulo no repo e depois cagar e andar...

**Comment by mileo** [comment]
@DiegoParadeda consegue dar uma olhada nisso novamente amanhã?
