### ISSUE TITLE
[RFC] HR - Personal Information

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1265]
** Sua solicitação de mudança/melhoria está relacionada a um problema? Por favor descreva.**
O Campo Naturalidade esta duplicados

![Screenshot from 2021-03-30 23-28-06](https://user-images.githubusercontent.com/38361760/113081813-c24c0b80-91af-11eb-8114-911d5a80d906.png)

** Descreva a solução que você deseja **
Apagar o campo duplicado

Relacionar o Campo Pai com as Cidades (Mundialmente, visto que a migração de pessoas é uma realidade e há 1,5% do banco de dados de funcionário com pessoas extrangeiras)

** Descreva as alternativas que você considerou **
Deixar só um Campo porém sem a relação com o Pais, não resolve o problema integralmente mas remedia

** Contexto adicional **
Vou tentar fazer, mas se não conseguir aviso

**Comment by marcelsavegnago** [comment]
A duplicidade foi resolvida nesta PR https://github.com/OCA/l10n-brazil/pull/1212

**Comment by marcos-mendez** [comment]
Valeu @marcelsavegnago
