### ISSUE TITLE
[Q&A] Contabilização de Remessa para Conserto

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1279]
Pessoal,

Falando em contabilização com uma posição fiscal especifica tranquilamente conseguimos trocar a conta contábil do produto para outra conta mas a conta contábil da invoice por padrão aceita apenas contas do tipo receivable ou payable.

Seria interessante um campo account_id na posição fiscal ou na operação fiscal para utilizar na substituição da conta contábil da fatura ? viabilizando assim a substituição de uma conta Clientes Nacionais por uma conta Estoques em Poder de Terceiros. 

Seria este o caminho ? ou deve este tipo de contabilização deve ser feito de forma diferente ?

cc @renatonlima @mileo @rvalyi

**Comment by rvalyi** [comment]
Sim @marcelsavegnago o plano era esse, talvez o @renatonlima pode confirmar.

**Comment by rvalyi** [comment]
@marcelsavegnago eu acho que isso vc tem que fazer pela substituçao de contas da posiçao fiscal ligada a operaçao, ou seja é algo nativo do Odoo ja. Uma vantagem da gente nao ter reinventado a roda no nosso modulo...

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago eu acho que isso vc tem que fazer pela substituçao de contas da posiçao fiscal ligada a operaçao, ou seja é algo nativo do Odoo ja. Uma vantagem da gente nao ter reinventado a roda no nosso modulo...

Então, a posição faz a troca da conta contábil da linha da fatura (do produto) mas no caso entendo que além desta troca também é necessário trocar o valor do campo account_id do cabeçalho da fatura. 

Se hoje gerar uma fatura de remessa o sistema vai forçar uma contabilização mais ou menos assim:

D - Clientes Nacionais (conta do tipo receivable)
C - Estoque (AC)

Porém, no caso de uma remessa para conserto a contabilização seria mais ou menos assim:

D - Estoques em Poder de Terceiros (AC)
C - Estoque (AC)

**Comment by marcelsavegnago** [comment]
Uma outra situação similar seria o faturamento de bonificação. Que precisaria ficar mais ou menos assim

Exemplo:

Empresa distribui como amostra 3 pares de sapatos a determinado cliente. O custo de cada par de sapato é R$ 10,00, e a nota fiscal consta:

3 pares de sapatos a R$ 30,00 cada = R$ 90,00

ICMS 18% = R$ 16,20

Contabilização:

1) Pela nota fiscal de remessa como amostra:
D- Amostras de Produtos (Resultado)
C- Estoques (Ativo Circulante)
R$ 30,00

2) ICMS devido na operação:
D- ICMS sobre Amostras (Resultado)
C- ICMS a Recolher (Passivo Circulante)
R$ 16,20

**Comment by mileo** [comment]
> @marcelsavegnago eu acho que isso vc tem que fazer pela substituçao de contas da posiçao fiscal ligada a operaçao, ou seja é algo nativo do Odoo ja. Uma vantagem da gente nao ter reinventado a roda no nosso modulo...

Confirmo o que o @marcelsavegnago comentou, essa troca não ocorre.

**Comment by mileo** [comment]
Um outro detalhe passivo de comentário é a conta do diário, ela preenche a linha da fatura, entretanto só é considerada caso o produto não seja selecionado e mesmo assim ela é enviada como origem map da posição fiscal.

**odoo.src.addons.account.models.account_invoice.AccountInvoiceLine._onchange_product_id**

Se o produto é selecionado a conta do diário não é considerada e então ela é enviada para o map da posição fiscal.

**Comment by marcelsavegnago** [comment]
Pessoal, 

Como acredito que todos sabem o módulo stock_account não dispõe de recurso para seleção da posição fiscal que será utilizada na criação da fatura. Sendo assim, submeti uma PR implementando isto e basicamente consiste basicamente em buscar a posição fiscal configurada na operação fiscal.

https://github.com/OCA/l10n-brazil/pull/1273

Outra coisa que pra mim é importante e faz sentido (mesmo que implementado de outra forma) pelo menos no módulo l10n_br_stock_account é a substituição da conta contábil do cabeçalho da fatura. Para isso eu submeti uma PR adicionando o campo account_id na operação fiscal e durante a criação da fatura se o valor account_id estiver definido na operação fiscal a conta do cabeçalho da fatura será substituído.

https://github.com/OCA/l10n-brazil/pull/1429

Peço que avaliem e caso não seja o caminho eu agradeço por qualquer direcionamento.
