### ISSUE TITLE
[12.0][BUG] l10n_br_nfe: tag vTroco

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1283]
Olá pessoal,

Testando a emissão de NFe percebi que a tag vTroco aparece em todos os XMLs e no caso de documentos sem valor financeiro e consequentemente com o tipo de pagamento 90 - Sem Pagamento, não deve conter a tag vTroco senão será retornado a seguinte mensagem de erro 869 - Valor do troco incorreto.

![image](https://user-images.githubusercontent.com/3595132/114954773-a2fce180-9e31-11eb-845e-265ed6b86dca.png)

cc @rvalyi @renatonlima @mileo

**Comment by antoniospneto** [comment]
Olá @marcelsavegnago , você já encontrou alguma solução para esse problema? ou ainda está utilizando o fix temporário que vc propôs nessa pr? https://github.com/akretion/nfelib/pull/25

**Comment by marcelsavegnago** [comment]
> Olá @marcelsavegnago , você já encontrou alguma solução para esse problema? ou ainda está utilizando o fix temporário que vc propôs nessa pr? [akretion/nfelib#25](https://github.com/akretion/nfelib/pull/25)

Grande @netosjb. Por ora mantive este fix temporário.

**Comment by gabrielcardoso21** [comment]
@marcelsavegnago Passamos pelo mesmo problema em um cliente. Resolvemos ele no PR #1125 com o commit https://github.com/OCA/l10n-brazil/pull/1125/commits/1b2d731d556b444ba0b8c1c8b4f1f7ec6072b93a, fazendo essa seleção diretamente na função _export_field. Se quiser posso extrair só essa parte do commit e fazer um Pull Request separado, acho que já resolve pra maioria dos casos.

**Comment by marcelsavegnago** [comment]
Grande @gabrielcardoso21 se for possível extrair e submeter uma PR com esta correção eu agradeço.

**Comment by gabrielcardoso21** [comment]
Tá na mão https://github.com/OCA/l10n-brazil/pull/1518
