### ISSUE TITLE
[BUG] Loop de tradução spec_driven_model

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1291]
Olá Pessoal,

Quem acompanhou a novela do merge do #1272 viu que tivemos problemas na tradução.

O problema continua, vejam o PR #1285 e o commit de tradução na 12.0:

https://github.com/OCA/l10n-brazil/commit/c0165129b956dfc770c087338b1822b9dd977da2

Considerando a aleatoriedade da ordem que o ORM carrega os modelos a tradução do campo vai sempre mudar e isso deve se repetir sempre.

Vamos precisar remover a tradução de alguma forma no spec_driven_model só que para alguns fields ou até todos os fields gerados por specs.

No commit: https://github.com/OCA/l10n-brazil/commit/47ef80ae6549462c8b130024ddfe47c4bb484ddd removi a description que era outro string traduzível que era sempre alterado.

No caso dos fields fiz uma análise rápida ontem mas seria possível injetar o atributo translate=False nos fields injetados. 

Provável que nesse trecho: https://github.com/OCA/l10n-brazil/blob/12.0/spec_driven_model/models/spec_models.py#L278

@rvalyi @gabrielcardoso21 Vcs que manjam mais do módulo poderiam comentar?

**Comment by rvalyi** [comment]
Eu acho que vc mistura a tradução statica da interface pelos arquivos .pot com a possibilidade de traduzir o conteudo dos campos de cada registro. Por examplo por padrão o nome da categoria dos produtos é traduzivel (attributo translate=True no campo), então vc pode traduzir o nome de cada categoria. No caso dos campos geridos pelo spec_driven_model, nenhum campo tem esse translate=True...

Ou seja pode ser que tem algum problema com a questão dos arquivos .pot, mas esse translate=False eu acho que não tem a ver não.

**Comment by mileo** [comment]
> Eu acho que vc mistura a tradução statica da interface pelos arquivos .pot com a possibilidade de traduzir o conteudo dos campos de cada registro. Por examplo pô padrão o nome da categoria dos produtos é traduzivel (attributo translate=True no campo), então vc pode traduzir o nome de cada categoria. No caso dos campos geridos pelo spec_driven_model, nenhum campo tem esse translate=True...
> 
> Ou seja pode ser que tem algum problema com a questão dos arquivos .pot, mas esse translate=False eu acho que não tem a ver não.

Verdade o slots translate não vai resolver o problema. Vou ver se encontro outra solução e posto aqui.

**Comment by mileo** [comment]
Creio que o único ponto que podemos herdar e customizar então seria no 

**odoo.src.odoo.addons.base.wizard.base_update_translations.BaseUpdateTranslations**

Evitando que essas traduções sejam exportadas, ou um patching no **odoo.tools.translate.trans_export**

**Comment by mileo** [comment]
Pessoal precisamos pensar em uma forma de resolver isso pois os merges estão demorando o dobro do tempo necessário:

![image](https://user-images.githubusercontent.com/1975978/115255997-37529700-a105-11eb-8e33-c752549cd6e6.png)

Uma coisa que eu estava pensando é ordenar os campos e as classes de alguma forma padronizada, se sempre mantermos a mesma ordem a não ser que tenha alteração no modelo de dados não vamos ter problemas.

Revisando o código do spec e tb do models do core vemos bastante registros ordenados, mas pode ser que em algum ponto no spec isso esteja passando despercebido.

**Comment by mileo** [comment]
![image](https://user-images.githubusercontent.com/1975978/115282070-1fd4d780-a120-11eb-9fc2-4e524d75b8cb.png)

Precisamos ver isso logo.

**Comment by mileo** [comment]
5 builds e nada do merge:

![image](https://user-images.githubusercontent.com/1975978/115285232-ff0e8100-a123-11eb-97d1-7fa2fb3f690f.png)

**Comment by mileo** [comment]
@rvalyi vc tem tempo para dar uma olhada nisso? 

![image](https://user-images.githubusercontent.com/1975978/115303612-3851eb80-a13a-11eb-93c9-00a1ebe0b078.png)

**Comment by marcelsavegnago** [comment]
@mileo isso pode ter relação com o weblate ? 

![image](https://user-images.githubusercontent.com/3595132/115304089-e362a500-a13a-11eb-963f-6b8832b7c1a9.png)

**Comment by mileo** [comment]
> @mileo isso pode ter relação com o weblate ?

Não. O weblate esta com problemas desde o revert/force do #820

**Comment by rvalyi** [comment]
bem realmente vamos ter que solucionar isso... Vou tentar ver isso nesses dias.

**Comment by rvalyi** [comment]
pessoal, vou tentar subir um fix para isso daqui pouco hoje ainda ta.

**Comment by rvalyi** [comment]
resolvido com https://github.com/OCA/l10n-brazil/pull/1304
