### ISSUE TITLE
[BUG] Duplicate invoice, Reduplicate fiscal_document_line_ids

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1295]
Ao duplicar uma invoice, as linhas do documento fiscal são duplicadas 2x.

É possível observar múltiplos itens no XML e o valor do troco incorreto, entretanto somente 1/2 dos itens são exibidos.

Os outros provavelmente devem estar c/ active false.

cc: @gabrielcardoso21

**Comment by marcelsavegnago** [comment]
https://github.com/OCA/l10n-brazil/issues/1249

**Comment by mileo** [comment]
> #1249

pior q pesquisei antes de abrir e não achei seu issue ;P
