### ISSUE TITLE
[BUG] DANFSE

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1315]
**
![image](https://user-images.githubusercontent.com/3595132/116439810-54cee180-a826-11eb-9b51-f2bf9f6e14db.png)
**

ping @ygcarvalh

**Comment by marcelsavegnago** [comment]
Grande @ygcarvalh se puder dar uma olhada eu agradeço. :)

**Comment by ygcarvalh** [comment]
> Grande @ygcarvalh se puder dar uma olhada eu agradeço. :)

pode deixar que faço o mais rápido possível
