### ISSUE TITLE
[12.0][BUG] Possível BUG relacionado com a Aba Recebíveis da Invoice

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1327]
**Descreva aqui o Bug**

Ao criar uma invoice e validar a mesma, na aba Recebíveis são apresentadas as parcelas da fatura. Porém, quando o lançamento é postado, os dados desta aba desaparecem. Este comportamento é esperado ?

**Lançamento Não Postado**
![image](https://user-images.githubusercontent.com/3595132/117372490-01046e00-aea0-11eb-9b79-ba21f4591673.png)

**Lançamento Postado**
![image](https://user-images.githubusercontent.com/3595132/117372734-648e9b80-aea0-11eb-82c7-ae6e32155b17.png)

cc @marcos-mendez

**Comment by marcos-mendez** [comment]
Exatamente @marcelsavegnago 

Para os recebiveis funcionar e gerar as linhas precisa deixar sem nada na POSIÇÃO FISCAL, ai funciona.

Outra coisa é que mesmo ele gerando os recebiveis automaticamente, se tenta editar por exemplo para colocar o numero do codigo de barras do boleto de cobrança, essas linhas somem assim que editadas.

Não a campo editável que de para colocar os boletos de referencias ou algo do genero

**Comment by marcelsavegnago** [comment]
> Exatamente @marcelsavegnago
> 
> Para os recebiveis funcionar e gerar as linhas precisa deixar sem nada na POSIÇÃO FISCAL, ai funciona.

Então.. os dados desta aba são populados pelo capo financial_move_line_ids. Este campo é calculado e persistido com store=true (se remove o store=true o campo será calculado e sempre e os dados serão apresentados.. porém, precisa entender se a ideia é ter os dados persistidos neste campo ou apenas apresentados.) 

https://github.com/OCA/l10n-brazil/blob/c0e51470d109ac0a31770644ac258a7e9b6e76d9/l10n_br_account/models/account_invoice.py#L81

https://github.com/OCA/l10n-brazil/blob/c0e51470d109ac0a31770644ac258a7e9b6e76d9/l10n_br_account/models/account_invoice.py#L117

Basicamente este campo é composto apenas das linhas do lançamento contábil que são do tipo recebível e pagável.

> Outra coisa é que mesmo ele gerando os recebiveis automaticamente, se tenta editar por exemplo para colocar o numero do código de barras do boleto de cobrança, essas linhas somem assim que editadas.

Estas linhas não são editáveis mesmo e entendo que está certo assim. Entendo que alterações devem ser feitas no lançamento do diário.
 
> Não a campo editável que de para colocar os boletos de referencias ou algo do genero

Enfim, quando o lançamento é postado o valor deste campo financial_move_line_ids é zerado. 

cc @mileo @renatonlima @rvalyi

**Comment by mileo** [comment]
Isso esta relacionado ao campo ser store=True e o seu depends.

Pois ele não esta dependendo do status do account.move que é "unposted" até a transmissão da fatura. E ai ele não é recalculado posteriormente.
