### ISSUE TITLE
[BUG] Erro de Schema XML quando o campo tem um carácter em branco no final

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1331]
![image](https://user-images.githubusercontent.com/1975978/117520735-24064f00-af80-11eb-9b0c-8c07833352af.png)

![image](https://user-images.githubusercontent.com/1975978/117520754-3c766980-af80-11eb-8918-8d6d0f25587e.png)

**Comment by rvalyi** [comment]
Isso foi solucionado, na v12 ainda.
