### ISSUE TITLE
[BUG][12.0]l10n_br_nfe: CSOSN

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1334]
Na validação do xml recebo esse erro, não sei se é bug, ou alguma configuração incorreta, outro erro foi relatado por @marcelsavegnago na #1283 

![image](https://user-images.githubusercontent.com/65144026/117815222-deb97a00-b22a-11eb-9f69-e894d53d5c48.png)

**Comment by mileo** [comment]
@ygcarvalh pode dar uma olhada?

**Comment by mileo** [comment]
vTroco vc conseguiu resolver?

**Comment by ygcarvalh** [comment]
@vanderleiromera consegue mandar um print do xml da tag do ICMS?

**Comment by ygcarvalh** [comment]
> @ygcarvalh pode dar uma olhada?

esse erro está sendo arrumado no PR https://github.com/OCA/l10n-brazil/pull/1275, porém ainda não foi feito o merge

**Comment by vanderleiromera** [comment]
Jóia, vou testar a pr 1275

**Comment by marcelsavegnago** [comment]
@mileo @ygcarvalh sobre a vTroco eu havia feito um contorno para fins de teste. O @rvalyi orientou a forma correta mas ainda não consegui trabalhar nisso.

https://github.com/akretion/nfelib/pull/25

obs. neste caso seria para tratar a tag vTroco no caso da NFe não ter pagamento financeiro (remessa, devolução e afins)

**Comment by vanderleiromera** [comment]
Corrigido com a PR #1275

**Comment by mileo** [comment]
Como não foi feito o merge, deixamos aberto ok?

**Comment by renatonlima** [comment]
O valor do troco, só é obrigatório se tiver a informação do pagamento, na NFe essa tag não é obrigatória, apenas na NFC-e essa tag é obrigatória porque na tag de pagamento é informado que aquele documento fiscal foi pago. Se é emitida uma NFe a prazo e o cliente não fez o pagamento, a tag tpag deve ir sem pagamento. E o vencimentos devem ir na tag fat dentro das tags de duplicatas.

**Comment by vanderleiromera** [comment]
Solucionado com a #1275
