### ISSUE TITLE
[BUG] Faturas não fiscais multi-empresa

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#1340]
Quando se tem mais de uma empresa no Odoo e ao criar faturas não fiscais dentro do Odoo, é gerado um erro porque as faturas de ambas empresas estão relacionadas ao mesmo fiscal.document dummy.

**Comment by mileo** [comment]
Aquela ideia de associara empresa um document dummy pode ser uma boa para resolver esse caso.

cc: @gabrielcardoso21

**Comment by rvalyi** [comment]
> Aquela ideia de associara empresa um document dummy pode ser uma boa para resolver esse caso.
> 
> cc: @gabrielcardoso21

foi isso que o @renatonlima fez aqui https://github.com/OCA/l10n-brazil/pull/1142 so que teria que fazer isso de forma mais limpa.

**Comment by antoniospneto** [comment]
@renatonlima 

A PR #1476  era pra resolver o bug dessa issue? ou isso ainda é um problema? pois isso ainda é recorrente para mim:

Segue a foto do erro:

![image](https://user-images.githubusercontent.com/634278/147140567-95cc1b34-c59a-4ad2-a7f9-38ccc8052de7.png)
 Log completo do erro: [log_error](https://github.com/OCA/l10n-brazil/files/7764596/log_error.txt

Esse teste foi feito no runbot seguindo os passos a baixo:
1) Logado na empresa "Sua Empresa"  crie uma fatura de fornecedor sem informar o "document type" 
2) Altere para a empresa "TESTE - simples nacional" e tente criar uma nova fatura sem informar o "document type".

**Comment by rvalyi** [comment]
@netosjb Esse problema realmente era para ter sido resolvido por essa PR https://github.com/OCA/l10n-brazil/pull/1476 e alguns commits depois se eu não me engano. Depois a gente validou isso em produção em 3 instalações multi-empresas pelo menos.

Porem eu consigo reproduzir o problema no runboat (https://runboat.odoo-community.org/webui/builds.html?repo=OCA/l10n-brazil&target_branch=12.0) seguindo seu paso a paso https://github.com/OCA/l10n-brazil/issues/1340#issuecomment-999821285 Eu nao sei se realmente é o mesmo problema o algum problema com os dados de demo, mas eu aposto que seja o caso. Vamos manter o issue aberto e tentar resolver isso então.

cc @renatonlima @marcelsavegnago 


Agora cada empresa tem um documento dummy e para cada invoice sem documento fiscal é usado o dummy da empresa. . Nisso vou fechar o issue, mas se vc conseguir reproduzir numa instalação recente a gente abre de novo.
cc @renatonlima @marcelsavegnago

**Comment by antoniospneto** [comment]
@rvalyi fiz os testes mas acontece mesmo sem os dados demos, sempre que uma empresa nova é criada é setado o fiscal dummy que já existe.

pelo que percebi o erro está nesse método:

https://github.com/OCA/l10n-brazil/blob/cc33cc32b8a8169f5d01e5f749e268e3124b9859/l10n_br_fiscal/models/res_company.py#L88

ali dentro do método ele está verificando se já existe um dummy, mas acho que o correto é remover essa verificação e já ir direto para a criação de uma novo dummy.

vou propor uma pr pra essa alteração

**Comment by rvalyi** [comment]
ja funcionava em algumas situaçoes mas dependia da configuraçao no seu banco de dados, agora foi resolvido de forma robusta pelo trabalho do @netosjb no https://github.com/OCA/l10n-brazil/pull/1804
