### ISSUE TITLE
[Q&A] Criar campo email_edoc específico para envio de arquivos e documentos fiscais.

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1345]
Olá Pessoal,

Referente ao envio dos documentos fiscais por email, estava pensando em uma possível melhoria:

a. Criar um campo específico de email_edoc no cadastro do cliente;
b. Não criar o campo e criar um Boolean nos contatos para sinalizar que os documentos devem ser enviados para os contatos que tiverem essa flag ativa.

Qual vocês acham a melhor implementação?

@renatonlima @rvalyi @marcelsavegnago @sadamo @gabrielcardoso21

**Comment by gabrielcardoso21** [comment]
Prefiro o Boolean, porque não vejo motivo para ter dois e-mails de cada cliente no banco de dados. Se um deles não é para ser usado para contato deve estar em alguma observação.
