### ISSUE TITLE
[BUG] Linhas de recebiveis somem após registrar um pagamento

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1363]
** Descreva o bug **
Gerada uma fatura com mais de 1 pagamento, após validada e registrado um pagamento as linhas recebiveis desaparecem. 

@renatonlima @marcelsavegnago @mileo

Estou tentando testar o máximo possível as PRs porém não sei se este seria o comportamento adecuado. 

Vi que vocẽs atualizaram o que corrigiu o erro com o fiscal, mas agora surgiu este erro com o recebivel, tavlez eu esteja errado

https://user-images.githubusercontent.com/38361760/118522105-14ba9a80-b712-11eb-817f-b09d6b35505d.mp4

**Comment by marcelsavegnago** [comment]
> ** Descreva o bug **
> Gerada uma fatura com mais de 1 pagamento, após validada e registrado um pagamento as linhas recebiveis desaparecem.
> 
> @renatonlima @marcelsavegnago @mileo
> 
> Estou tentando testar o máximo possível as PRs porém não sei se este seria o comportamento adecuado.
> 
> Vi que vocẽs atualizaram o que corrigiu o erro com o fiscal, mas agora surgiu este erro com o recebivel, tavlez eu esteja errado
> 
>  Kazam_screencast_00000.mp4

Esse caso tinha sido resolvido. Pode ser que a branch da PR precise de um rebase para incluir as atualizações que foram feitas por PRs mescladas recentemente. Qual PR vc está testando ?

**Comment by marcos-mendez** [comment]
Eu to usando a do odoo bot mesmo, não sei qual é, mas é a que ta no github

Em seg., 17 de mai. de 2021 às 15:25, Marcel Savegnago <
***@***.***> escreveu:

**Comment by antoniospneto** [comment]
@marcos-mendez Acredito que o bug apontado nessa issue estava relacionado com o bug apresentado na pr #1639  o merge da mesma já foi feito então acredito que esse problema esteja resolvido, favor conferir se a issue possa ser fechada.
