### ISSUE TITLE
[BUG] Código do pais "0105" em vez de "1058"

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1382]
Algumas vezes reparei que ao criar uma base de testes nova o código do pais estava incorreto.

E verificando uma instalação só com o l10n_br_base percebi que o código esta correto.

Fiquei pensando que algo na estrutura do spec/nfe/generateds possa estar importando este dado incorretamente, tentei localizar agora rapidamente e não encontrei nenhuma referência.

@gabrielcardoso21 @rvalyi @renatonlima @marcelsavegnago

**Comment by marcelsavegnago** [comment]
Me deparei com isso estes dias tbm. Achei que eu tinha feito alguma cagada na base.

**Comment by mileo** [comment]
Eu já tive algumas vezes e hoje o @DiegoParadeda teve tb.

**Comment by rvalyi** [comment]
teria então algo errado com o Brasil? Sera?

#euavisei

**Comment by rvalyi** [comment]
Verifique se nao teria 2 paises tipo Brazil e Brasil no banco. Uma forma que isso poderia acontecer seria se por examplo por algum motivo nao carregou a traduçao de Brazil para Brasil no hook do l10n_br_base https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_base/hooks.py#L34 e que vc tentou importar uma NFe seja pelos dados de demo, seja pelos testes, por examplo no l10n_br_nfe. Ai ele vai procurar o pais fazendo um search por "Brasil", mas caso nao tiver a traduçao ele nao iria achar. E se por acaso vc tentou importar uma NFe zoada que teria outro codigo, 0105 por examplo, sem achar ele criaria um outro pais Brasil com o codigo 0105. Esse seria uma coisa que poderia explicar.

**Comment by mileo** [comment]
> Verifique se nao teria 2 paises tipo Brazil e Brasil no banco. Uma forma que isso poderia acontecer seria se por examplo por algum motivo nao carregou a traduçao de Brazil para Brasil no hook do l10n_br_base https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_base/hooks.py#L34 e que vc tentou importar uma NFe seja pelos dados de demo, seja pelos testes, por examplo no l10n_br_nfe. Ai ele vai procurar o pais fazendo um search por "Brasil", mas caso nao tiver a traduçao ele nao iria achar. E se por acaso vc tentou importar uma NFe zoada que teria outro codigo, 0105 por examplo, sem achar ele criaria um outro pais Brasil com o codigo 0105. Esse seria uma coisa que poderia explicar.

Sim, na época eu procurei nos xmls importados e não encontrei nenhuma referência de 0105.

**Comment by rvalyi** [comment]
isso foi corrigido quando eu forcei o create em en_US aqui https://github.com/OCA/l10n-brazil/blob/14.0/spec_driven_model/models/spec_import.py#L304
re-abrir se ainda se observar.
