### ISSUE TITLE
[RFC] Remover a dependência do xmlsec

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1414]
A nota paulistana esta usando um método de assinatura próprio, com xmlsec, pois o serviço não esta aceitando a assinatura que usamos na NF-e / GINFES e ISSNET.

Tentamos também usando a abordagem do projeto:
https://github.com/starkbank/nfe-python/blob/master/nfe/utils/rps.py
https://github.com/starkbank/nfe-python/blob/master/nfe/utils/rsa.py

https://github.com/erpbrasil/erpbrasil.assinatura/pull/21

**Comment by mileo** [comment]
Pra quem usa docker, perdi umas horas ontem acertando as dependências: 

https://github.com/kmee/dependencias.odoo/blob/master/Dockerfile

@rvalyi @renatonlima

**Comment by rvalyi** [comment]
Foi feito no erpbrasil.assinatura no ano passado.
