### ISSUE TITLE
[BUG] NFe: Descrição de Produto com mais de 120 caracteres

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1449]
Campo Descrição do produto ou Serviço, Tag xProd (I04): este campo tem tamanho de apenas 120. 

Porém há casos que a descrição é maior do que os 120, como por exemplo quando na DI é exigida uma descrição muito grande e aí fica-se obrigado a usar a mesma descrição na nota.

Para estes casos, a descrição deve ser continuada no campo infAdProd (V01), que tem 500 caracteres. Note que o campo infAdProd é impresso na DANFE logo após o xProd, assim a impressão da informação é feita de forma continua.

**Comment by rvalyi** [comment]
o recorte foi implementado no l10n_br_nfe/models/document_line.py ja uns 2 anos atras.
