### ISSUE TITLE
[BUG] NF-e: Caracteres com espaço no final dos campos

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#1450]
![image](https://user-images.githubusercontent.com/1975978/121607606-b473fb80-ca26-11eb-868b-e8b9d1543359.png)

Um espaço em branco inserido acidentalmente pelo o usuário nos campos de texto causa rejeição da NF-e.

**Comment by renatonlima** [comment]
@gabrielcardoso21 e @mileo 

Seria interessante também que fosse escapado os caracteres especiais na string como barra, tab, enter e etc... mas isso pode ser em outro PR
