### ISSUE TITLE
[BUG]12.0 - Res.partner - Não Salvando endereço na criação

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1478]
** Descreva o bug **
Ao criar um novo cliente, os dados preenchidos como (street number e district) não estão salvando.

**Reproduzir**
Para salvar o numéro e o bairro do cliente é necessário editar o cadastro e informar novamente estes dados

**Comment by antoniospneto** [comment]
@vanderleiromera

Segue o fix para o problema #1651

**Comment by vanderleiromera** [comment]
Solucionado com #1651
