### ISSUE TITLE
[12.0][BUG] l10n_br_purchase_stock: Compra de Serviços

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1480]
**Descreva o bug**
Com este módulo instalado, quando é lançado uma ordem de compra de serviços o botão Criar Conta não está visível. 

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Criar uma Ordem de Compra
2. Selecionar um produto do tipo serviço
3. Confirmar a Ordem de Compra
4. Observar que o botão Criar Conta não está visível.

**Comportamento esperado**
O comportamento esperado é que no caso de itens de serviço o botão Criar Conta fique visível. 

cc @mileo @renatonlima @rvalyi @mbcosta

**Comment by marcelsavegnago** [comment]
Efetuando novos testes, se no serviço a politica de faturamento no caso de compras estiver definida para considerar a quantidade solicitada, o botão Criar Conta fica visível.

![image](https://user-images.githubusercontent.com/3595132/122980908-98018880-d36f-11eb-86e2-0d111d49e2f2.png)

**Comment by marcelsavegnago** [comment]
Pessoal.. estou encerrando esta issue.. 

Pelo que entendi a falha estava mesmo na parametrização do serviço. Os serviços devem ser configurados com a politica de controle de cobrança baseada na quantidade comprada já que não dispõe de nenhum controle para gerenciar o recebimento do mesmo.

![image](https://user-images.githubusercontent.com/3595132/122988852-8d97bc80-d378-11eb-8e33-73881f714a52.png)

**Comment by rvalyi** [comment]
isso mesmo @marcelsavegnago

**Comment by rvalyi** [comment]
ou então cobrado em cima de folha de tempos que seria algo se aproximando do cobrado em cima da entrega.
