### ISSUE TITLE
[BUG] NFS-e Paulistana

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1488]
Nota Fiscal apesar das várias dificuldades, por algum motivo é gerada no sistema da prefeitura, porém no Odoo ele não reconhece como emitida e da o STATUS DE REJEITADA.

![Screenshot from 2021-06-25 13-12-07](https://user-images.githubusercontent.com/38361760/123454604-2156cc00-d5b7-11eb-9eac-d1b340380ba5.png)
![Screenshot from 2021-06-25 13-13-35](https://user-images.githubusercontent.com/38361760/123454646-2a479d80-d5b7-11eb-8599-3dedf9a53a0c.png)

Além disso falta a chave no documento gerado pelo Odoo ou a NUMERO da NFS 

![Screenshot from 2021-06-25 13-13-56](https://user-images.githubusercontent.com/38361760/123454696-3c294080-d5b7-11eb-949c-b1a667b8f95a.png)

Apesar das várias recomendações para que usase o modelo da GINFES e dos outros tipos de notafiscal de serviço os modulo é bastante diferente e tive dificuldades em ver o que precisa ser modificado, além disso a taxonomia e o nomes das classes é diferente. 

Não consegui arrumar isto, está alem da minha capacidade

**Comment by antoniospneto** [comment]
Recentemente implementamos a NFS-e Paulistana em um cliente e confirmo que isso está acontecendo com bastante frequência, mas não é sempre.
