### ISSUE TITLE
[12.0][Q&A] Venda de Serviços com Desconto (NFSe)

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1509]
Para a geração de pedido de venda de serviço com desconto a ideia é tratar como a NFe? No caso de desconto para produto eu entendi até então que o valor será destacado na NFe. 

ping @mileo

**Comment by mileo** [comment]
Conforme comentado no telegram: 

https://github.com/erpbrasil/nfselib.ginfes/blob/master_gen/nfselib/ginfes/v3_01/servico_enviar_lote_rps_envio.py#L2582-L2587

Existem campos para os descontos condicionais e incondicionais
