### ISSUE TITLE
[12.0][BUG] l10n_br_sale: Está carregando a série de NFe quando é criado uma fatura de serviço

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1510]
**Descreva o bug**
Testando tanto no runbot como em uma base de cliente, quando em um pedido de venda de serviço é criado a fatura, a série que o sistema está trazendo é a série da NFe e não da NFSe.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Crie um pedido de venda de serviço
2. Confirme o pedido de venda
3. Clique em Criar Faturas (Criar e Visualizar)
4. Acesse o cadastro da série que foi preenchida na invoice e veja que ela está associada ao documento do tipo 55 e não o documento do tipo SE

![image](https://user-images.githubusercontent.com/3595132/125178593-fe363a00-e1bc-11eb-9c99-4cdad4e0cc00.png)

**Comment by antoniospneto** [comment]
@marcelsavegnago acho que essa issue pode ser fechada
