### ISSUE TITLE
[12.0][BUG] l10n_br_stock_account: Picking fica 2binvoiced quando o documento fiscal volta para digitação

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1513]
**Descreva o bug**
Ao faturar um picking, validar a invoice do mesmo e voltar a invoice para o status de digitação, o picking volta para o status  2binvoiced.

Isto ocorre porque ao voltar a invoice para o status de digitação o sistema faz o cancelamento da mesma e neste momento o módulo stock_picking_invoice altera o picking para 2binvoiced.

Submeti uma PR implementando o método action_invoice_draft() para voltar o picking para o status Invoiced quando a invoice foi para o status de rascunho.

https://github.com/OCA/account-invoicing/pull/969

**Comment by mbcosta** [comment]
@marcelsavegnago com o merge do PR do link esse problema foi corrigido e esse issue já pode ser fechado, certo?
