### ISSUE TITLE
[12.0][BUG] l10n_br_fiscal: soma dos impostos retidos

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1514]
**Descreva o bug**
Os valores totais dos impostos retidos não é somado no documento fiscal.

A principio está relacionado com este trecho.
https://github.com/OCA/l10n-brazil/blob/5c33555ce70824f1a70065f7cccca0c4a77804e3/l10n_br_fiscal/models/document_fiscal_mixin_methods.py#L46

No caso, este método busca os campos com nome parecido removendo o prefixo amount_. Porém, os campos totalizadores dos impostos retidos são diferentes. Ou seja, no documento fiscal o campo tem a seguinte estrutura de nome  **amount_imposto_ret_value** e nas linhas dos documentos fiscais o nome tem a seguinte estrutura **imposto_wh_value**.

Uma alternativa é renomear os campos do documento fiscal, varrer o código para saber se o campo é utilizado em algum lugar e criar um script de migração.

Outra opção seria fazer algo similar a isso

```
    def _compute_amount(self):
        fields = self._get_amount_fields()
        for doc in self:
            values = {key: 0.0 for key in fields}
            for line in doc._get_amount_lines():
                for field in fields:
                    if field in line._fields.keys():
                        values[field] += line[field]
                    # ASSIM .. VEJA O CAMPO FIELD_LIMPO
                    field_limpo = field.replace("amount_", "")
                    field_limpo = field_limpo.replace("_ret_", "_wh_")
                    if field_limpo in line._fields.keys():
                        values[field] += line[field_limpo]
            doc.update(values)
```

**Comment by bmessiaz** [comment]
@marcelsavegnago Teoricamente/contabilmente falando os impostos retidos já estão somados no total do documento, se o código acumular as linhas de itens ok? 

Exemplo: Item 01 Serviço Contábil Mensal  R$ 10.000,00 (valor bruto do serviço prestado)
               Retenções PCC  4,65%  R$ 465,00
                                 IRRF 1,50%  R$ 150,00
                               Total Retido   R$ 615,00
               Valor a pagar Fornecedor R$  9.385,00
               Valor a Pagar DARFS         R$    615,00

              Total do Documento Fiscal R$ 10.000,00

       No caso, só deveriam ser somados, se fosse acumulado o líquido (R$ 9.385,00) nunca vi dessa forma em outros sistemas, em geral, parte-se sempre do bruto, mas.. Odoo é Odoo.

        Qualquer duvida me chama no whatts.  35 99728-4103

Um abraço.

**Comment by marcelsavegnago** [comment]
Blz. obrigado pela força @bmessiaz .. Se puder me ajudar, estou estudando a questão de desconto tanto para NFe como NFSe. No caso de desconto incondicional da NFSEe como seria o lançamento ? (considerando os impostos retidos)

**Comment by bmessiaz** [comment]
Ok @marcelsavegnago tamu junto!

Seguinte: Sobre desconto incondicional que corresponde à uma mera liberalidade do VENDEDOR.

No caso dos IMPOSTOS, estes devem sempre "assumir" o valor base tributável do preço a ser cobrado, isto é,
Valor da mercadoria/serviço - Desconto incondicional = Valor tributável da venda.

Em geral, Desconto Incondicional não é utilizado em Serviços, mas havendo campo na NFSE, se preenchido deve diminuir o valor do serviço prestado antes da incidência dos impostos.

Daí pra frente, os impostos serão calculados normalmente, sempre partindo do valor da mercadoria/serviço - desconto incondicional. 

DIFERENÇA ENTRE DESCONTO INCONDICIONAL E DESCONTO CONDICIONAL

Para fins tributários e contábeis, deve-se atentar para que os descontos incondicionais recebam tratamento diferenciado dos descontos condicionais.

DESCONTOS INCONDICIONAIS
Os descontos incondicionais são considerados parcelas redutoras do preço de vendas, quando constarem da nota fiscal de venda dos bens ou da fatura de serviços e não dependerem de evento posterior à emissão desses documentos; esses descontos não se incluem na receita bruta da pessoa jurídica vendedora e, do ponto de vista da pessoa jurídica adquirente dos bens ou serviços, constituem redutor do custo de aquisição, não configurando receita.
Exemplo:
Mercadorias R$ 10.000,00
(-) Descontos Incondicionais R$ 2.000,00
(=) Valor de Venda/Nota Fiscal R$ 8.000,00
Tais R$ 8.000,00 constituirão a receita bruta da vendedora e, para o comprador, o custo das mercadorias.
Nota: observar que o IPI Faturado e o ICMS Substituição Tributária, cobrados destacadamente na nota fiscal, também são parcelas redutoras da receita bruta.
Teremos então:
No vendedor: contabilização de R$ 8.000,00 de receita de vendas de mercadorias.
No comprador: contabilização de R$ 8.000,00 de aquisição de mercadorias.



DESCONTOS CONDICIONAIS (depende de o pagador cumprir alguma condição contratual)

Já os descontos condicionais são aqueles que dependem de evento posterior à emissão da nota fiscal, usualmente, do pagamento da compra dentro de certo prazo, e configuram despesa financeira para o vendedor e receita financeira para o comprador.
Exemplo:
Serviços de Internet   R$ 200,00 por mes
Desconto condicional  R$ 20,00 (para pagamento até 2o. dia útil do mes subsequente) 
Total Pago                  R$ 180,00

Pra quem Paga: (contabilização)
D-Fornecedor              R$ 200,00
C-Banco                       R$ 180,00
C-Descontos Obtidos    R$ 20,00  

Pra quem Recebe: (contabilização)
C-Clientes                            R$ 200,00
D-Banco                              R$ 180,00
D-Descontos  Concedidos    R$ 20,00

**Comment by marcelsavegnago** [comment]
@bmessiaz... então tanto na venda de produtos como na venda de serviços o desconto deve ser abatido da base de calculo.. OK?.

Estou testando no runbot e no caso do ICMS o desconto é abatido da base de calculo do mesmo.. Já no caso do PIS este abatimento não ocorre.

# Aqui o ICMS
![image](https://user-images.githubusercontent.com/3595132/125689698-530a7fcf-5bc1-4e90-b03b-2a0120540ca6.png)

# Aqui o PIS
![image](https://user-images.githubusercontent.com/3595132/125689754-9cfd5627-c26d-4d6f-b9e1-8ac28f6f4247.png)

O desconto deveria ter sido abatido do PIS e do COFINS tbm certo?

E na nota fiscal de prestação de serviço o desconto não está sendo abatido em nenhuma base de calculo de imposto (ISSQN, PIS, COFINS, CSLL e afins)

cc @renatonlima

**Comment by marcelsavegnago** [comment]
Pelo que entendi, os detalhes do imposto precisa ser implementado aqui certo ?

https://github.com/OCA/l10n-brazil/blob/5c33555ce70824f1a70065f7cccca0c4a77804e3/l10n_br_fiscal/models/tax.py#L654

@renatonlima @mileo @rvalyi

**Comment by marcelsavegnago** [comment]
Na verdade se o desconto deve ser reduzidos da base de dos demais impostos acho que pode ser implementado aqui nos impostos genéricos

https://github.com/OCA/l10n-brazil/blob/5c33555ce70824f1a70065f7cccca0c4a77804e3/l10n_br_fiscal/models/tax.py#L666

**Comment by marcelsavegnago** [comment]
@bmessiaz implementei a redução dos descontos em todos os impostos PIS, confis e afins.. e estou testando com um fatura com todos os impostos retidos e 15 reais de descontos.

![image](https://user-images.githubusercontent.com/3595132/125693000-616d8d63-ebb6-475e-b9d7-292897df5ec3.png)

![image](https://user-images.githubusercontent.com/3595132/125693179-5c404ee9-abfd-486b-9e44-2b1f4222c22a.png)

Preciso confirmar se o ISS é retido.. mas enfim.. no caso vamos considerar que todos são retidos.

**Comment by renatonlima** [comment]
@marcelsavegnago,


Na verdade existem dois métodos genéricos que são usados um para calcular a base de calculo _compute_tax_base e o outro para calcular o valor do imposto _compute_tax. essa logica poderia ser implementada diretamente no método _compute_tax_base o que eliminaria algumas coisas no calculo do ICMS e IPI, mas seria interessante colocar um flag no fiscal.tax.group para incluir ou não o valor de (frete, outras despesas e seguro) na base do imposto

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago,
> 
> Na verdade existem dois métodos genéricos que são usados um para calcular a base de calculo _compute_tax_base e o outro para calcular o valor do imposto _compute_tax. essa logica poderia ser implementada diretamente no método _compute_tax_base o que eliminaria algumas coisas no calculo do ICMS e IPI, mas seria interessante colocar um flag no fiscal.tax.group para incluir ou não o valor de (frete, outras despesas e seguro) na base do imposto

Inclusive adicionar um flag se o desconto deve ser deduzido da base tbm.. oq acha ?

**Comment by marcelsavegnago** [comment]
Vou subir uma PR grosseiramente porca por ora e vou ajeitando.

**Comment by marcelsavegnago** [comment]
Sobre os descontos.
https://github.com/OCA/l10n-brazil/pull/1519

**Comment by bmessiaz** [comment]
@marcelsavegnago Seguinte, temos que ter 2 conceitos em mente quanto aos impostos incidentes em uma NF.
1) Impostos sobre a venda. (Mercadorias e Serviços) (base afetada por desconto incondicional)
2) Impostos retidos (Serviços) (não é afetada por qualquer desconto, porque ao se usar a base tributável do item.

O Desconto incondicional reduz a O Valor Tributável ocorrido na Venda ou Prestação conforme o intem 1) acima.

O cálculo de Impostos retidos, não são afetados por quaisquer Descontos Incondicionais ou Condicionais.
Nas duas imagens que vc mandou não cabe descontos incondicionais afetar a base de calculo dos impostos.

Abraço,

se quiser, me chama e te mostro no excel como é.

Abraço.

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago Seguinte, temos que ter 2 conceitos em mente quanto aos impostos incidentes em uma NF.
> 
> 1. Impostos sobre a venda. (Mercadorias e Serviços) (base afetada por desconto incondicional)
> 2. Impostos retidos (Serviços) (não é afetada por qualquer desconto, porque ao se usar a base tributável do item.
> 
> O Desconto incondicional reduz a O Valor Tributável ocorrido na Venda ou Prestação conforme o intem 1) acima.
> 
> O cálculo de Impostos retidos, não são afetados por quaisquer Descontos Incondicionais ou Condicionais.
> Nas duas imagens que vc mandou não cabe descontos incondicionais afetar a base de calculo dos impostos.
> 
> Abraço,
> 

> 
> Abraço.

Perfeito. Muito obrigado pela ajuda. 

> se quiser, me chama e te mostro no excel como é.

Qualquer coisa entre em contato sim.. obrigado

**Comment by renatonlima** [comment]
@marcelsavegnago,

Eu fiz um PR para a sua branch https://github.com/Escodoo/l10n-brazil/pull/24 para corrigir a definição da base de calculo.

**Comment by renatonlima** [comment]
Sobre a soma dos impostos, 
Eu sugiro alterar os campos no l10n_br_fiscal.document para ficar amount_IMPOSTO_wh_value, pois com essa mudança não seria necessário fazer essa alteração no compute e também não confunde os valores de pis_value e pis_wh_value.

**Comment by marcelsavegnago** [comment]
> Sobre a soma dos impostos,
> Eu sugiro alterar os campos no l10n_br_fiscal.document para ficar amount_IMPOSTO_wh_value, pois com essa mudança não seria necessário fazer essa alteração no compute e também não confunde os valores de pis_value e pis_wh_value.

Farei isso

**Comment by marcelsavegnago** [comment]
> > Sobre a soma dos impostos,
> > Eu sugiro alterar os campos no l10n_br_fiscal.document para ficar amount_IMPOSTO_wh_value, pois com essa mudança não seria necessário fazer essa alteração no compute e também não confunde os valores de pis_value e pis_wh_value.
> 
> Farei isso

https://github.com/OCA/l10n-brazil/pull/1617

**Comment by marcelsavegnago** [comment]
Resolvido na PR #1617
