### ISSUE TITLE
[12.0][RFC] l10n_br_fiscal: amount_price_gross store=true

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1516]
O campo amount_price_gross está como **store=true**.  Tem algum motivo especifico ou podemos remover este parâmetro ?

https://github.com/OCA/l10n-brazil/blob/5c33555ce70824f1a70065f7cccca0c4a77804e3/l10n_br_fiscal/models/document_fiscal_mixin.py#L104

**Comment by rvalyi** [comment]
corrigido aqui https://github.com/OCA/l10n-brazil/pull/1520 com evoluiçoes futuras previstas aqui https://github.com/OCA/l10n-brazil/pull/1652
