### ISSUE TITLE
[BUG] Naturalidade de estrangeiros no permitida nos FUNCIONARIOS

### ISSUE THREAD

**Issue by rosi-quintero** [OCA/l10n-brazil#1528]
AO Adicionar um funcionario estrangeiro nâo è possivel marcar sua naturalidade em vista que as cidades que aparecem sao apenas brasileiras.
![Screenshot from 2021-07-19 20-49-35](https://user-images.githubusercontent.com/87678132/126241633-733bf255-f2d2-456a-abf3-0ba90775a83e.png)

**Comment by marcos-mendez** [comment]
@mileo como eu resolvo isso? Posso contribuir com esse assunto?
@marcelsavegnago se depois puder me dar um luz também agradeço

**Comment by rvalyi** [comment]
@marcos-mendez aqui na visão, esse campo naturalidade nao deveria ter required="1" https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_hr/views/hr_employee_view.xml#L17 , deveria ter um attrs dinamico com required so se o campo country_id abaixo for o Brasil (usando %(...)d para que o id seja avaliado antes de carregar o XML da visão no banco). Vc consegue fazer um PR com esse fix?

**Comment by marcos-mendez** [comment]
Cara, vou tentar. Estou voltando para SP, assim que eu chegar vejo isso

Em sáb., 14 de ago. de 2021 às 14:22, Raphaël Valyi <
***@***.***> escreveu:
