### ISSUE TITLE
[BUG] AttributeError: no such child: {http://www.portalfiscal.inf.br/nfe}NFe

### ISSUE THREAD

**Issue by marcelomarcon** [OCA/l10n-brazil#1536]
** Descreva o bug **
Quando tentamos gerar o pdf a partir de um xml existem ocorre o seguinte erro.

AttributeError: no such child: {http://www.portalfiscal.inf.br/nfe}NFe

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Modulo Fiscal'
2. Clique em 'Guia Documentos > Todos os Documentos'
3. Role para baixo até 'Abra uma nota fiscal de produtos' e tente gerar um pdf a partir de um xml
4. Ver erro

**Comportamento esperado**
Abrir uma tela ou aparecer para realizar o download do danfe ( PDF )

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
![image](https://user-images.githubusercontent.com/85348507/127029683-e1da3739-7c7c-4273-8b2e-fae986da599e.png)

**Comment by antoniospneto** [comment]
Olá Marcelo, o erro é só com o PDF? O XML você está conseguindo exportar ao dá algum erro também ?
A nota fiscal aparece como autorizada para você?

**Comment by marcelomarcon** [comment]
> Olá Marcelo, o erro é só com o PDF? O XML você está conseguindo exportar ao dá algum erro Também ?
> A nota fiscal aparece com autorizada para você?

Então, como estou sem certificado até o momento para testar com uma empresa válida, eu peguei uma nota ( xml ) pessoal e importei no odoo para gerar o pdf ( danfe ) quando clico no botão visualizar pdf , aparece esse erro mostrado acima.

![image](https://user-images.githubusercontent.com/85348507/127033090-8d476477-929d-46dd-bccc-429278b482ed.png)

- Primeira dúvida, é possível fazer esse teste do jeito que estou fazendo usando um xml ja emitido ( Pessoal ).
- Segundo, teria que realmente pegar empresa válida com certificado valido A1 ou A3 para gerar com odoo e então gerar o danfe?
- Eu apenas gostaria de ver gerando o pdf a partir de um xml, devido a ser apenas uma apresentação e não ter em mãos ainda certificados válidos para geração de nota.

**Comment by vanderleiromera** [comment]
Pra testes com Nfe, você pode usar os dados de demonstração, ao qual ja inclui o certificado pra testes.

**Comment by rvalyi** [comment]
Ola @marcelo-ax4b ja peguei esse tipo de erro de impressão do DANFe com NFe de exportação que o destinatario nao tinha alguns campos brasileiros como Instriçao Estatual se nao me engano. As vezes o template odt do danfe.odt aqui pode tentar ler um campo que pode nao estar presente em algumas situaçôes https://github.com/erpbrasil/erpbrasil.edoc.pdf/tree/master/docs

Isso pode ser dado que nao ta correcto no XML da nota, ou então as vezes esse proprio template que nao esta completo e nao testa uma determinada situação antes de ler um campo. O primeiro passo seria saber de onde vem o erro: do XML ou do template .odt?

**No seu caso parece que ele nao esta encontrando o xNome do emitente da sua nota (NFe.infNFe.emit.xNome).** Eu acho que vc deveria checar os settings da sua empresa e dar uns print na serializão da NFe para saber o que nao ta indo:
Vc deve verificar em especial:
https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_nfe/models/res_company.py#L36
https://github.com/OCA/l10n-brazil/blob/12.0/spec_driven_model/models/spec_export.py#L54
https://github.com/erpbrasil/erpbrasil.edoc.pdf/blob/master/src/erpbrasil/edoc/pdf/base.py#L137


Boa sorte.

**Comment by marcelomarcon** [comment]
Olá @rvalyi Grato pela resposta, estarei validando  e seguindo as informações que passou aqui em cima, logo mais darei um retorno se funcionou. grato pela ajuda.

**Comment by marcelomarcon** [comment]
@rvalyi aparentemente os campos estão todos preenchidos. vou validar se pode ser no .odt, se tiver outra ideia para teste ou para debugar estou aberto rsrs

Vlw

**Comment by marcelomarcon** [comment]
> Pra testes com Nfe, você pode usar os dados de demonstração, ao qual ja inclui o certificado pra testes.

Desculpe a pergunta, qual certificado e onde posso encontrar  os dados para testes com certificado ?

**Comment by rvalyi** [comment]
> > Pra testes com Nfe, você pode usar os dados de demonstração, ao qual ja inclui o certificado pra testes.
> 
> Desculpe a pergunta, qual certificado e onde posso encontrar os dados para testes com certificado ?

Salve @marcelo-ax4b se vc instalar os modulos da localização com os dados de demo, vai ver que a\s 3 empresas de demo/teste do Brasil tem certificados de demo:
Sua Empresa, Empresa Lucro Presumido e TESTE - Simples Nacional:

![2021-07-26_17-19](https://user-images.githubusercontent.com/16926/127053743-c8bf7cb4-bc84-465d-b157-308b1adfce54.png)


Com eles vc consegue testar a transmissão de uma nota em ambiente de homologação (ou imprimir um DANFE) se precisar.


Para criar um banco com os dados de demo, no odoo.conf, vc precisa deixar essa parametro em branco:
`without_demo = `

**Comment by antoniospneto** [comment]
@marcelo-ax4b

> * Vá para 'Modulo Fiscal'
> * Clique em 'Guia Documentos > Todos os Documentos'
> * Role para baixo até 'Abra uma nota fiscal de produtos' e tente gerar um pdf a partir de um xml
> * Ver erro

Eu tentei seguir esse fluxo mas não encontrei, você está testando alguma PR em especifico ?

**Comment by marcelomarcon** [comment]
> > > Pra testes com Nfe, você pode usar os dados de demonstração, ao qual ja inclui o certificado pra testes.
> > 
> > 
> > Desculpe a pergunta, qual certificado e onde posso encontrar os dados para testes com certificado ?
> 
> Salve @marcelo-ax4b se vc instalar os modulos da localização com os dados de demo, vai ver que a\s 3 empresas de demo/teste do Brasil tem certificados de demo:
> Sua Empresa, Empresa Lucro Presumido e TESTE - Simples Nacional:
> 
> ![2021-07-26_17-19](https://user-images.githubusercontent.com/16926/127053743-c8bf7cb4-bc84-465d-b157-308b1adfce54.png)
> 
> Com eles vc consegue testar a transmissão de uma nota em ambiente de homologação (ou imprimir um DANFE) se precisar.
> 
> Para criar um banco com os dados de demo, no odoo.conf, vc precisa deixar essa parametro em branco:
> `without_demo = `

Olá @raditv  eu segui os passos, consegui criar banco de testes, porem quando, clico em enviar, aparece como authorizada, porem quando clico em visualizar pdf ou visualizar xml, nada acontece. segue GIF abaixo
![2XkWiTbdXY](https://user-images.githubusercontent.com/85348507/127055207-9a8311d2-b44c-43c6-8d8a-2f9981375cd9.gif)

**Comment by marcelsavegnago** [comment]
@marcelo-ax4b vai na configuração da empresa, Aba Fiscal, Aba Documentos Eletrônicos e configura o processador de documentos.

![image](https://user-images.githubusercontent.com/3595132/127056550-14c879d8-a913-4de8-8f88-1b8720ed04e2.png)

**Comment by marcelomarcon** [comment]
> @marcelo-ax4b vai na configuração da empresa, Aba Fiscal, Aba Documentos Eletrônicos e configura o processador de documentos.
> 
> ![image](https://user-images.githubusercontent.com/3595132/127056550-14c879d8-a913-4de8-8f88-1b8720ed04e2.png)

Eu segui os passos acima, coloquei o processador como a tela acima, e mesmo assim nada acontece. estou usando odoo enterprise. teria alguns passos a mais alem dessa configuração para a configuração.

**Comment by marcelsavegnago** [comment]
Veja então qual o tipo de documento fiscal vc está utilizando.. seria o 55 para produtos e SE para serviços.

**Comment by antoniospneto** [comment]
@marcelo-ax4b 

Tente informar este processador:

![image](https://user-images.githubusercontent.com/634278/127068564-426d89fc-db45-4dcf-b6ea-356edfed701b.png)

**Comment by marcelomarcon** [comment]
@netosjb instalei o modulo, informei esse processador, porem, agora esta dando outros erros.

Quando clico em visualizar pdf, ocorre o erro abaixo.  Imagino que seja algum campo que esteja faltando ser preenchido e esta como False. ou dependendo a nota da erro de SSL

Esse Erro com FIXME que inclusive esta no codigo no arquivo document_line.py estou imaginando se estou usando a branch errada do l10n-brazil

![image](https://user-images.githubusercontent.com/85348507/127073381-71568c4f-d2d1-472d-8c75-d0a82742ae15.png)

![image](https://user-images.githubusercontent.com/85348507/127072274-88012562-641e-4777-8cff-c228f03c1bda.png)

![image](https://user-images.githubusercontent.com/85348507/127072923-a890c240-d6ba-4e69-ad48-698c6b56749b.png)


**Obs: teste com todas as notas que vem configuradas no Odoo. exemplo abaixo.**

![image](https://user-images.githubusercontent.com/85348507/127072420-7a5a1b5f-767a-4b20-a738-bf04d405e28a.png)

**Comment by antoniospneto** [comment]
@marcelo-ax4b 

Quanto ao erro do SSL, comigo também estava acontecendo um erro similar, eu consegui resolver usando um certificado valido.

**Comment by rvalyi** [comment]
Ola @marcelo-ax4b, aquele erro do bool has not attribute replace com a linha FIXME, eu nao sei dizer porque sobre essa comentario FIXME, talvez seja apenas para lembrar de tirar o hardcode nfe40_ e usar o nome do prefix automaticamente (nao sei). Mas o importante é que esse campo nfe40_choice11 esta vindo vazio e nao deveria. Vc deveria botar uns prints aqui https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_nfe/models/document_line.py#L238 para tentar entender porque.

Os outros erros que vc tenta visualizar o pdf, pelo jeito esse arquivo.datas (shame on you Odoo SA de usar datas com s seus jumentos!) é porque o arquivo ta vazio mesmo. Talvez porque o servidor nao te respondeu mesmo, nao sei dizer, foi a KMEE que implementou a parte de transmissão do XML da NFe. Com certeza da para melhorar a gestão de erros.

**Comment by marcelsavegnago** [comment]
@marcelo-ax4b dá uma olhada nas configurações fiscais do produto

https://github.com/OCA/l10n-brazil/blob/5eb8f8162aee0b19664ec6c2d9ef7c2790808482/l10n_br_nfe/models/document_line.py#L238

**Comment by marcelomarcon** [comment]
@marcelsavegnago @rvalyi @netosjb obrigado pela atenção de todos, amanhã vou dedicar o dia para tentar achar o que esta ocorrendo e vou postando aqui. se conseguir achar o motivo estarei postando aqui assim outros que tiverem o mesmo problema poderão resolver sem dores de cabeça.

Sobre a implementação. achei estranho usar o libreoffice para gerar. imagino que existem outras maneiras de fazer isso que seria até mais rapido e daria menos trabalho. usando xsd ou até mesmo inkscape para gerar templates. mas enfim.

Estarei validando sobre a linha do FIXME e ver o que consigo descobrir sobre.

**Comment by rvalyi** [comment]
Ola @marcelo-ax4b . Foi a KMEE que fez essa lib libreoffice. A vantagem é que fica facil customizar o DANFE, algo que empresas que trabalham com NFC-e gostam parece. Agora sim é lento. Poderia se tornar mais rápido usando o Libreoffice como servidor em vez de criar um novo processo a cada impressão se precisasse. De qualquer modo outras formas de imprimir estão bem vindas. 

Na AKRETION, nosso plano ate a KMEE contribuir a impressão com essa lib libreoffice era de fazer um micro-serviço em volta dessa lib Java madura https://github.com/wmixvideo/nfe para imprimir e transmitir assim como eu fiz pros CNAB e boletos por examplo. Hoje porem a solução atual atende nossos clientes legal e então a gente não foca mais nessa integração. Mas com certeza muitas coisas podem ser melhoradas, a gestão dos erros sendo uma delas.

**Comment by marcelomarcon** [comment]
Olá @rvalyi então eu acredito que fazer essa lib usando inkscape que é um programa pra design seria mais facil e intuitivo, e o bacana do inkscape salva em svg que é um xml. seria mais facil para montar um modelo, incluir logo, ja que é um programa de vetorização assim como core e illustrator. ja usei ele para renderizar certificados de escola quando o aluno conclui o curso.

**Comment by rvalyi** [comment]
Seria legal sim, depois bota la uma forma de escolher a lib e cada cada um pega o que ele achar melhor para ele. No inicio a gente tb considerava plugar a lib da Trustcode em qweb.
Mas assim, so para esclarescer ja imprimimos milhares de NFe com a lib com o libreoffice então da para botar ela para funcionar tb ta.

**Comment by marcelomarcon** [comment]
Pessoal, ontem fiz a install dos modulos fiscal NFE e Fiscal e deu para acessar e tentar gerar nota fiscal sem problemas. agora recriando a base e instalando com demo. esta dano esse erro de permissão. alguem ja passou por isso. 

Obs: usuário tem permissão, está no grupo que tem permissão. problema ocorre com todas as empresas e até mesmo com ususário presumido.

![image](https://user-images.githubusercontent.com/85348507/127157260-793ca861-d04f-404c-ac7a-5399e3f0f956.png)

**Comment by rvalyi** [comment]
a principio, o usuário tem que estar no grupo de "usuarios de NFe", pois os objetos tecnicos que vem do XSD da NFe como esse detPag precisam dessa permissão para ser acessado. Isso acontece dentro desse hook na instalação do modulo l10n_br_nfe:
https://github.com/OCA/l10n-brazil/blob/12.0/spec_driven_model/hooks.py#L16
Ve que no runbot esse problema nao acontece então vc deve ter feito algo errado...

**Comment by marcelomarcon** [comment]
Os usuarios estavam no grupo NFe, até mesmo por           que em outras instalações a havia funcionado. porem descobri que era um bug do odoo, realizei uma nova instalação e agora estou conseguindo acessar as notas.

Agora so tenho erro de SSL imagino que pode ser o certificado de teste que pode não estar valido mais.

![image](https://user-images.githubusercontent.com/85348507/127169719-68b33fb7-a1ce-4b83-bad7-f1ca9473b29e.png)

e quando tento visualizar o pdf, tenho o erro abaixo.

![image](https://user-images.githubusercontent.com/85348507/127170193-302803ad-1dc9-46c7-a66a-607dacd75c37.png)

**Comment by antoniospneto** [comment]
@marcelo-ax4b 

Sem antes validar e enviar para sefaz a nfe acho que você não vai conseguir gerar a danfe, você terá que primeiro resolver o problema do certificado,  aqui tive que usar o certificado da minha empresa para conseguir testar.

**Comment by marcelsavegnago** [comment]
> @marcelo-ax4b
> 
> Sem antes validar e enviar para sefaz a nfe acho que você não vai conseguir gerar a danfe, você terá que primeiro resolver o problema do certificado, aqui tive que usar o certificado da minha empresa para conseguir testar.

Na verdade não precisa transmitir para visualizar a danfe.. mas precisa ter o processador configurado e o modulo l10n_br_nfe instalado.

**Comment by marcelo-ax4b** [comment]
@marcelsavegnago processador está configurado. porem

**Comment by marcelomarcon** [comment]
> > @marcelo-ax4b
> > Sem antes validar e enviar para sefaz a nfe acho que você não vai conseguir gerar a danfe, você terá que primeiro resolver o problema do certificado, aqui tive que usar o certificado da minha empresa para conseguir testar.
> 
> Na verdade não precisa transmitir para visualizar a danfe.. mas precisa ter o processador configurado e o modulo l10n_br_nfe instalado.

Processador está configurado, porem quando clico em gerar o danfe ( visualizar pdf ) eu tenho o erro abaixo
![image](https://user-images.githubusercontent.com/85348507/127197593-b29566be-942d-41a3-8c23-77898cfe0719.png)

![image](https://user-images.githubusercontent.com/85348507/127197847-9186a079-2f33-4139-bea9-40ab999d4564.png)

Ja viu esse tipo de erro? algum campo que falta configurar ou está configurado errado talvez?

**Comment by marcelsavegnago** [comment]
Acho que já vi.. eu estava usando uma versão anterior da lib erpbrasil.edoc.pdf  (v 0.1.2) para contar uma problema mas não lembro se era este ai. Qualquer desinstala a lib erpbrasil.edoc.pdf e instala essa 0.1.2 e testa soh para ver se muda algo.

Obs. Não é o caminho correto.. massss é válido para teste.

**Comment by rvalyi** [comment]
bota uns print desse dhRecbto aqui é vé o que ta acontecendo https://github.com/erpbrasil/erpbrasil.edoc.pdf/blob/master/src/erpbrasil/edoc/pdf/danfe_formata.py#L134
Depois vé como deveria ser para o parse funcionar num simples console Python por examplo. Ai depois ainda vai ter que entender porque essa data ta errada, mas ver o que tem dentro pode ajudar. Na pior se vc ta apenas testando a localizaçao por cima, força esse `return ''` de cima para destravar e poder avançar se quiser.

**Comment by marcelomarcon** [comment]
> bota uns print desse dhRecbto aqui é vé o que ta acontecendo https://github.com/erpbrasil/erpbrasil.edoc.pdf/blob/master/src/erpbrasil/edoc/pdf/danfe_formata.py#L134
> Depois vé como deveria ser para o parse funcionar num simples console Python por examplo. Ai depois ainda vai ter que entender porque essa data ta errada, mas ver o que tem dentro pode ajudar. Na pior se vc ta apenas testando a localizaçao por cima, força esse `return ''` de cima para destravar e poder avançar se quiser.

Boa, vou testar aqui
