### ISSUE TITLE
[BUG] regressão: validação das informações de pagamento bloca validação de NFe

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1559]
Pessoal, nesse PR https://github.com/OCA/l10n-brazil/pull/1538 a gente tentou integrar uma contribuição da KMEE que não tava finalizada (#1457 ), mas fazendo uns tests agora no Runbot me parece que isso cria uma regressão, quando tanto validar uma nota de venda, eu tenho esse erro sempre:

![2021-08-11_12-07](https://user-images.githubusercontent.com/16926/129054622-c38748f9-52d9-4859-acd9-d6f3871fa338.png)

E uma NFe de venda normal, apenas com um produto. Os dados de pagamentos deveriam ser geridos pela validação e não ser exigido na hora da validação. Isso bloca o fluxo.

Tou fazendo algo errado?

cc @marcelsavegnago @renatonlima @mileo

**Comment by marcelsavegnago** [comment]
Fiz o teste local com uma fatura com tipo de documento 55 e de fato, quando tenta validar a fatura o sistema já retorna a mensagem sobre os dados de pagamento.

**Comment by marcelsavegnago** [comment]
Mas tem que lembrar que quando a fatura é validada de fato o sistema já gera o xml da NFe e então não temos uma etapa no meio para separar este momento.

**Comment by rvalyi** [comment]
ai talvez a gente reverte essa checagem e deixa para checar numa checagem semelhante a da validaçao do schema na hora da exportaçao. Tipo alem de validar o schema a gente testaria isso pelo XML ou no objeto. O que vc acha? Hoje isso bloca gostoso, não da para ficar assim...

**Comment by marcelsavegnago** [comment]
> ai talvez a gente reverte essa checagem e deixa para checar numa checagem semelhante a da validaçao do schema na hora da exportaçao. Tipo alem de validar o schema a gente testaria isso pelo XML ou no objeto. O que vc acha? Hoje isso bloca gostoso, não da para ficar assim...

Por mim ok.. faria na hora de enviar .. certo ?

**Comment by rvalyi** [comment]
a gente pode simplesmente reverter o PR agora, e depois ver uma validação na hora de enviar sim. Mas me parece necessário de reverter o PR agora antes de alguém se ferrar em prod com isso...

**Comment by marcelsavegnago** [comment]
> a gente pode simplesmente reverter o PR agora, e depois ver uma validação na hora de enviar sim. Mas me parece necessário de reverter o PR agora antes de alguém se ferrar em prod com isso...

Bora

**Comment by marcelsavegnago** [comment]
Falando em reversão.. precisava de um apoio master para liberar o weblate que ta blocado desde a ultima reversão já que o weblate estava trazendo os commits revertidos para a branch master.

**Comment by rvalyi** [comment]
about the Weblate, @renatonlima and me spent like a full day trying to understand and fix it back but with no luck. As far as we have seen, it's because Weblate got a local cache of the branch before we force pushed on it to revert the mistake done on 12.0 so Weblate got in conflict forever when trying to pull the 12.0 OCA branch again. @gurneyalex if you are not in hollidays and if you hear us, I believe you are the Weblate wizard and we would need you to void the 12.0 git cache for OCA/l10n-brazil if you could do that for us please...

**Comment by rvalyi** [comment]
but as for reverting #1457 it's better to do it with a new PR that we can merge quickly.
