### ISSUE TITLE
[12.0][RFC] l10n_br_contract: dificuldade com o uso do módulo contract_variable_quantity

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1563]
Item para discutir.

Quando utilizado o módulo contract + contract_variable_quantity + l10n_br_contract, estou com dificuldade quando é  executado a linha abaixo:

https://github.com/OCA/l10n-brazil/blob/732388573fe1af70f2b1254a366a4e784469d981/l10n_br_contract/models/contract_line.py#L41

Quando é executada a linha acima o sistema substitui a quantidade a ser faturada que foi calculada pela quantidade original da linha do contrato. Ou seja, não respeita a quantidade calculada pelo módulo contract_variable_quantity.

Estou fazendo alguns testes mas se alguém tiver alguma dica eu agradeço :)

**Comment by rvalyi** [comment]
@marcelsavegnago não foi corrigido aqui esse https://github.com/OCA/l10n-brazil/pull/1565 ?
