### ISSUE TITLE
[BUG] odoo.addons.base.models.ir_ui_view: O campo `nfe_version` não existe

### ISSUE THREAD

**Issue by edsonblwolf** [OCA/l10n-brazil#1566]
** Descreva o bug **
Uma descrição clara e concisa do que do erro.
Instalei o módulo nfelib com o pip igua a documentação e acontece esse errro:
https://pastebin.com/1JXUV5bh

Baixei o módulo com git clone na pasta de addons e fui instalar o  l10n_br_nfe e acontece esse erro:
https://pastebin.com/ui0Chfxg

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Ver erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Capturas de tela **
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by marcos-mendez** [comment]
pip3 install nfelib==4.0.0


Em seg., 16 de ago. de 2021 às 03:13, edsonblwolf ***@***.***>
escreveu:

**Comment by marcos-mendez** [comment]
pip3 install nfelib==4.0.0

**Comment by edsonblwolf** [comment]
root@unc:~# pip3 instalar nfelib==4.0.0 ERRO: Não foi possível encontrar uma versão que satisfaça o requisito nfelib==4.0.0 (das versões: 0.1) ERRO: Não foi encontrada distribuição correspondente para nfelib==4.0.0

**Comment by rvalyi** [comment]
Ola @edsonblwolf e @marcos-mendez realmente eu trabalhei no empacotamento da nfelib esses dias e a forma como estava documentada nao funciona mais, eu atualizei o README, tem que instalar dessa forma:
https://github.com/akretion/nfelib#como-instalar

Na duvida, sempre fazer como esta no requirements.txt do projeto OCA onde esta testada extensivamente:
https://github.com/OCA/l10n-brazil/blob/12.0/requirements.txt#L14

Vc pode precisar desinstalar para instalar de novo...

Pode me confirmar se resolveu para vc?

**Comment by edsonblwolf** [comment]
Deu certo de primeiro pelo requeriments.txt, obrigado. É só prestar atençao mesmo. Grande abraço.
