### ISSUE TITLE
Não gera o boleto

### ISSUE THREAD

**Issue by edsonblwolf** [OCA/l10n-brazil#1581]
** Descreva sua dúvida **
###Boleto
https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_account_payment_brcobranca
https://github.com/OCA/l10n-brazil/issues/696
https://github.com/akretion/boleto_cnab_api

Instalei e fiz todas as configurações, igua ao link acima, já era pra gerar os boletos?

** Contexto adicional **
Eu estando com fatura aberta ele me gera esse erro abaixo e não aparece como opção no ecommerce:

https://pastebin.com/Nvp6SBSA

Desde já gradeço.

**Comment by mbcosta** [comment]
ola @edsonblwolf 
A impressão do Boleto através do Menu de Impressão não está funcionando eu explico o motivo no PR https://github.com/OCA/l10n-brazil/pull/1593 você deve usar o botão 
![image](https://user-images.githubusercontent.com/6341149/131141577-80426ac4-b5dc-442f-9a12-e8f8fd8d1626.png)


Sobre " não aparece como opção no ecommerce", a arquitetura é feita para alterar apenas os módulos dependentes, como a implementação do Boleto não depende diretamente do ecommerce nada referente foi feito, isso precisaria ser feito no modulo que implementa o ecommerce dentro da localização incluindo a dependência do modulo de Boletos/CNAB, acredito que seja esse https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_website_sale importante notar que o modulo está marcado como alpha e por isso tem uma mensagem a respeito 

![image](https://user-images.githubusercontent.com/6341149/131142915-0ad3b441-f4a7-464b-8357-781024453ab3.png)

Portanto se você pretende usa-lo vai precisar implementar e validar o que for necessário para a sua especificação, uma questão importante é que hoje os Boletos são gerados em Faturas/Notas Fiscais Confirmadas/Validadas se o seu caso for de criar os Boletos antes disso, por exemplo já no Pedido de Venda, isso hoje não é possível e uma alteração da estrutura do modulo para atender esse caso só será avaliada em futuras versões, v14 para frente.

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/1593
