### ISSUE TITLE
[8.0] Ordenar corretamente os campos l10n_br_base

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/l10n-brazil#159]
Ordem atual de campos.
![ordenar campos](https://cloud.githubusercontent.com/assets/854781/8353606/3c7cdc7a-1b16-11e5-8665-ec8d07071731.PNG)

Desejado:
![desejado](https://cloud.githubusercontent.com/assets/854781/8353613/575f9e92-1b16-11e5-9d36-f36e8b7bc6f2.PNG)

**Comment by renatonlima** [comment]
:+1:

**Comment by renatonlima** [comment]
Um outro lugar onde seria importante fazer esta reordenação é o form child_ids dentro da visão do parceiro...

**Comment by danimaribeiro** [comment]
:+1:  Crio um novo PR para esta outra view.

**Comment by renatonlima** [comment]
Na verdade esta dentro da mesma view, mas ok eu faço este pull request e pode mandar o outro PR

Obrigado pela contribuição!
