### ISSUE TITLE
[BUG] 12.0 Warnings ao criar e validar a fatura

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1596]
Ao criar a fatura recebo esses warnings

![Screenshot from 2021-08-27 17-29-23](https://user-images.githubusercontent.com/65144026/131194861-503432ad-076f-4434-9f9e-440215539463.png)

**Comment by rvalyi** [comment]
@vanderleiromera valeu por reportar. Vc esta com o modulo l10n_br_delivery atualizado? Houve um update grande dele a semana passada https://github.com/OCA/l10n-brazil/pull/1301 ).
o campo incoterm_id deveria existir por conta dessa herança  https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_delivery/models/fiscal_document_mixin.py#L15  
Vc poderia verificar?

**Comment by vanderleiromera** [comment]
Vou checar e retorno

**Comment by vanderleiromera** [comment]
@rvalyi obrigado pela atenção, nesse DB não tem o modulo delivery instalado, então o warning do incoterm_id. Instalando o modulo não recebo mais os erros. A dúvida que fiquei, o modulo delivery precisa ser carregado como dependência, mesmo sem uso..Grato

**Comment by marcos-mendez** [comment]
Você deficiu o plano de contas?

Em sex., 27 de ago. de 2021 às 19:33, Vanderlei P. Romera <
***@***.***> escreveu:

**Comment by vanderleiromera** [comment]
Oh @marcos-mendez sim está definido, tudo funciona correto, mas tenho TOC com warnings, o Raphael explicou sobre a herança do  incoterm_id,  instalando o delivery não aparecem mais.

**Comment by marcos-mendez** [comment]
Entendi, eu tmb tenho TOC com esses warning, o foda é que o inconterm é
algo da entrega, não fazia muito sentido ele pra mim ali, mas tudo bem,
vamos que vamos, estou aqui para aprender

Em sáb., 28 de ago. de 2021 às 19:04, Vanderlei P. Romera <
***@***.***> escreveu:

**Comment by vanderleiromera** [comment]
Exato, agora também fiquei com essa dúvida, da dependência do módulo delivery.

**Comment by rvalyi** [comment]
@vanderleiromera @marcos-mendez eu acho que eu entendi o problema: quando o @mbcosta terminou a migraçao do modulo l10n_br_delivery, ele acabou botando o campo incoterm_id dentro do SHADOWED_FIELDS do documento fiscal https://github.com/OCA/l10n-brazil/commit/a76bb9361380617f0890705ef650209c695d0bbf#diff-daae38396c6672c56badcaa22a10ae32a938909cd9387c12b0ec96268c9c5ea2

Isso para que seja possivel ter o incoterm_id dentro de um picking por examplo (pela herança do mixin do documento fiscal) mas tb que quando vc escreve o incoterm_id num invoice esse incoterm_id seja seja tb propagado ate o documento fiscal quando vc chamar o write, mesmo que ele tem o mesmo nome incorterm_id no invoice e no documento fiscal e que então so o mecanismo do framework do _inherits nao daria conta de fazer essa copia sem adicionar o campo no SHADOWED_FIELDS.

So que fazendo isso, quando instalar o l10n_br_account apenas ele ja tenta fazer esse write e da esse warning mesmo que nao tiver o l10n_br_delivery instalado.

Por isso, nesse PR para resolver o problema https://github.com/OCA/l10n-brazil/pull/1599/, eu adicionei o campo no documento fiscal (pelo mixin) ja ao nivel do l10n_br_account e nao mais ao nivel do l10n_br_delivery como o @mbcosta tinha feito.

@vanderleiromera @marcos-mendez  vcs podem verificar se resolve certinho? Valeu por reportar.

**Comment by rvalyi** [comment]
eu nao mudo minha analisa do problema, mas eu fiz um fix que eu acho melhor aqui https://github.com/OCA/l10n-brazil/pull/1600

@vanderleiromera @marcos-mendez vcs podem verificar se resolve certinho?

**Comment by marcos-mendez** [comment]
Rafa eu vou testar aqui e te falo, mas só por ler o código pra mim parece
certo, obvio que é só um achismo, mas enfim, vou testar e te falo

Em sáb., 28 de ago. de 2021 às 20:29, Raphaël Valyi <
***@***.***> escreveu:

**Comment by vanderleiromera** [comment]
solucionado com a pr #1600
