### ISSUE TITLE
[BUG] l10n_br_fiscal migração partir da 12.0.5.10.0

### ISSUE THREAD

**Issue by falexandresilva** [OCA/l10n-brazil#1612]
** Descreva o bug **

No meu sistema atual, mostra que a versão do l10n-br-fiscal é a 12.0.5.10.0, mas na versão atual não existe pasta de migration para essa versão (https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_fiscal/migrations). 

`ERROR stx-14 odoo.modules.migration: module l10n_br_fiscal: Each pre-migration file must have a "migrate(cr, installed_version)" function.`

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Tentar atualizar o módulo l10n_br_fiscal para a versão mais atual("12.0.17.4.1") a partir da 12.0.5.10.0

**Comportamento esperado**
Atualização do módulo com sucesso.

** Capturas de tela **
NA.

** Contexto adicional **
NA.

**Comment by rvalyi** [comment]
Ola @falexandresilva seja bem vindo. Vc poderia anexar uma stack trace antes desse erro?

Outra coisa, que versão do openupgradelib vc esta usando? A openupgradelib esta sempre em evoluição e como se trata de trabalho expert, o pessoal usa direito a versao do Github e não a versão publicada no Pypi que ja tem 2 anos.

Portanto vc pode desinstalar a antiga versão `sudo pip uninstall openupgradelib`
e instalar a nova versão com:

`sudo pip install git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib`

Sera se com essa versão não funciona? Pois veja bem nem todas migrações maiores dos módulos precisam de um script de migração, na maioria das vezes, o proprio Odoo sabe realizar a migração com a opção odoo `--update=l10n_br_fiscal`. Agora as vezes a mudança é mais radical e a gente escreve sim um script migração. Não podemos descartar um bug no l10n_br_fiscal/migrations mas vale a pena vc testar com essa ultima versão do openupgradelib e passar o stack trace completo.

**Comment by rvalyi** [comment]
Será se esse problema aconteceu no odoo.sh? Alguém reportou o mesmo problema no odoo.sh hoje e parece devido ao ambiente odoo.sh mesmo de acordo com o Pedro Baeza que é um cara que manja bastante do Odoo https://github.com/OCA/openupgradelib/issues/242#issuecomment-912075604

@falexandresilva vc poderia confirmar? Se for o caso, será a mesma resposta do que o Pedro deu: pressionar  Odoo SA para ficar compatível ou sair do odoo.sh.

**Comment by falexandresilva** [comment]
Não foi no odoo.sh. É tudo da OCA, inclusive o odoo baixei do OCA\OCB. Ainda não consegui testar a  remoção da versão do Pypi (Já havia executado esse comando sudo pip install git+https://github.com OCA/openupgradelib.git@master#egg=openupgradelib, mas não lembro se havia dado o Unistall da versão anterior). Amanhã quando fizer isso eu reporto aqui. Obrigado pela atenção!!!

**Comment by falexandresilva** [comment]
Este problema foi resolvido com a desinstalação e reinstalação do openupgradelib. Obrigado.
