### ISSUE TITLE
12.0[BUG] Criar fatura sem informar operação e tipo de documento

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1618]
Não sei se abordagem esta correta...

- Criando fatura sem  informar operação e tipo de documento

![faturasemoperação](https://user-images.githubusercontent.com/65144026/132097822-4be30603-f293-474c-8ef7-89081432676f.png)

-  Assim fica o l10n_br_fiscal.document.line 

![document line](https://user-images.githubusercontent.com/65144026/132097856-957f4b2c-1002-4553-9909-75f096056929.png)

Na issue #1609 #[comment](https://github.com/OCA/l10n-brazil/issues/1609#issuecomment-912007797) o @marcelsavegnago  relatou algo nesse sentido..

Update nas tabela  fiscal esses dados se multiplicaram ao exponencial, que ocasionaram lentidao de leitura ao account.invoice...

**Comment by marcelsavegnago** [comment]
@vanderleiromera não entendi direito. Você fez a inclusão de uma fatura sem operação fiscal? deu certo ou deu problema ? percebi que na view da linha da invoice os campos de operação fiscal e linha da operação fiscal estão obrigatórios e entendo que não deveria ser obrigatório neste caso. Se for isso, entendo que cabe analisar.

Não entendi a relação da multiplicação do registro. Isso aconteceu quando vc fez um update direto no banco ?

**Comment by vanderleiromera** [comment]
@marcelsavegnago sim, inclusão sem operação fiscal, não tenho erro, tudo normal, em algum momento foi atualizado a tabela fiscal, apareceu uma enorme quantidade no l10n_br_fiscal.document.line desses registros, como na segunda imagem. Ao gravar uma fatura sem fiscal ela fisca exatamente como a da imagem... não se deu pra entender...(na verdade também não sei o que houve com os milhares de registros nessa tabela, só deduzi...)

**Comment by vanderleiromera** [comment]
Solucionado #1805

**Comment by rvalyi** [comment]
> Solucionado #1805

ah legal @vanderleiromera que bom que vc ta vivo ainda, segura firme que a localização ta melhorando todo dia e chegando na 14 tb!

**Comment by vanderleiromera** [comment]
Apanhando igual bode amarrado, mas vamos chegar lá !
