### ISSUE TITLE
NF-E Natureza da operação

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#163]
Atualmente a natureza da operação é referente ao small name da primeira CFOP.
Não seria melhor a natureza ser referente a descrição da categoria da operação?

**Comment by renatonlima** [comment]
:+1: Também sugiro deixar o campo name da categoria fiscal o mesmo tamanho da natureza da NFe para não estourar o campo na NFe

**Comment by renatonlima** [comment]
Uma outra sugestão interessante seria criar um campo calculado na fatura para criar a descrição da natureza, pois uma nota fiscal pode ter CFOP diferentes (hoje só pega a descrição do primeiro CFOP), então este campo calculado poderia concatenar as categorias fiscais, exemplo: se você tiver em uma nota fiscal com os CFOPs 5.101, 5102 e 5.401 o campo natureza ficaria: Venda, Revenda e Venda ST.

**Comment by mileo** [comment]
:+1:

**Comment by mileo** [comment]
@lfdivino Da uma olhada nisso plz

**Comment by buguelos** [comment]
galera não estou conseguindo de forma alguna criar as pastas de importação e exportação para nfe 
me gera sempre esse erro 
Validação !

As seguintes configurações estão faltando:
Empresa - Pasta de exportação
Empresa - Pasta de importação

**Comment by mileo** [comment]
Boa noite, 

Quando tiver uma duvida não relacionada ao issue / PR aberto por favor crie um novo.

Referente a configuração das pastas vc verificou: configuração > empresas > fiscal > produto > nfe? 

Colocando o caminho de uma pasta com permissão de escrita?

Abraços

Luís Felipe Mileo

De: buguelos notifications@github.com
Enviado: 26/03/2016 10:12 PM
Para: OCA/l10n-brazil
Cc: Luis Felipe Miléo
Assunto Re: [l10n-brazil] NF-E Natureza da operação (#163)

galera nãovc estou conseguindo de forma alguna criar as pastas de importação e exportação para nfe 
me gera sempre esse erro 
Validação !

As seguintes configurações estão faltando:
Empresa - Pasta de exportação
Empresa - Pasta de importação

**Comment by buguelos** [comment]
me desculpa não sabia sou newbie to odoo fiquei muito empolgado Luís Felipe Mileo gostaria muito em colaborar tenho inglês  fluente sou expert em contabilidade fiscal em market em ecommerce tenho formação em TI  comecei a utilização desde o inicio parei por 2 anos agora estou meio confuso com github!!

**Comment by mileo** [comment]
Já foi integrado: https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/sped/nfe/document.py#L103
