### ISSUE TITLE
[Q&A]  Informações de Pagamento na Nota Fiscal Eletrônica

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#1631]
Galera uma duvida, como vocês estão fazendo para popular os campos  das **Informações de Pagamento** na nota fiscal ?

Pelo que percebi essas informação não são carregadas automaticamente, é preciso digitar manualmente ou existe alguma parametrização ?

![image](https://user-images.githubusercontent.com/634278/133181886-4573d8b4-39e4-43f4-b855-8edb1d1058ec.png)

Por acaso isso é algo que ainda tem que ser implementado ?

Os campos em questão são esses:

> Nas novas versões foi inserido um campo opcional: o Indicador da Forma de Pagamento campo “indPag” (Grupo YA01 linha 01) com as seguintes opções :
> 
> 0 = Pagamento à Vista
> 1 = Pagamento à Prazo 
> 
> Em seguida você vai informar o Meio de Pagamento campo “tPag“ (Grupo YA01 linha 2) com as seguintes opções:
> 
> 01 = Dinheiro 
> 02 = Cheque 
> 03 = Cartão de Crédito
> 04 = Cartão de Débito 
> 05 = Crédito Loja 
> 10 = Vale Alimentação 
> 11 = Vale Refeição 
> 12 = Vale Presente 
> 13 = Vale Combustível 
> 15 = Boleto Bancário 
> 90 = Sem pagamento (apenas para NFe)
> 99 = Outros
> 
> E para finalizar o Valor de Pagamento campo “vPag” (Grupo YA01 linha 3).

@rvalyi  @marcelsavegnago  @mileo

**Comment by antoniospneto** [comment]
Ping @britoederr @vanderleiromera @marcos-mendez

**Comment by marcos-mendez** [comment]
Até agora tenho a mesma dúvida que você @netosjb 

Na versão 11 era diferente pois eu usava trust que acabou não atendendo, minha migração esta sendo feita mais lentamente que a OCA

porém já antecipo que isso tmb muda um pouco dependendo do gateway. 

Vou dar uma investigada e te falo, qualquer coisa me chama no telegram @inavigator

**Comment by vanderleiromera** [comment]
Ainda não implementei o fiscal, mas em homologação só valida setando manual.

**Comment by antoniospneto** [comment]
@marcos-mendez @vanderleiromera obrigado por compartilhar a experiencia de vocês, bom saber que tem mais gente com a mesma situação.

**Comment by rvalyi** [comment]
Eu não olhei bem, mas bem capaz que esteja faltando algo mesmo. De uma forma geral tem bastante melhoria a ser feito para mapear os pagamentos. O @mileo tinha embarcado numa coisa gigantesca https://github.com/OCA/l10n-brazil/pull/820 que foi revertida depois. Algumas coisas boas tinham, mas o problema mesmo era que o custo/beneficio disso tudo não batia. Basicamente, a gente assume no l10n_br_fiscal que se o cara quer usar pagamentos, ele vai instalar o modulo account. Então a gente quer usar a parte de pagamentos do account e não copiar ela dentro do modulo l10n_br_fiscal que ja ta obeso.

Sem falar que copiar código sem teste assim, cria problemas na migração, cria uma dependência artificial entre o fiscal e o account onde nao tinha (ja que se a Odoo SA mudasse algo pros pagamentos teriamos que adaptar no fiscal tb) e tb cria problema de licença porque o codigo da Odoo SA nao assinou o Contributor Licence Agreement da OCA e ela não tem a menor intençao de assinar. Dai tem que ser algo simples, umas 200 linhas no maximo que não atrapalha nas migrações. Se alguem quiser usar pagamentos sem o modulo account, a gente ta super aberto para botar uns hooks para a pessoa puder plugar um modulo opcional para isso, porem ja que nem 1% de quem usa vai funcionar nesse cenario, não da para ser o padrão para geral. Pois é assim que se cria monstros impossível de manter depois.

cc @renatonlima

**Comment by antoniospneto** [comment]
Uma solucão está sendo discutida na pr #1640 estou fechando a issue.
