### ISSUE TITLE
[12.0][BUG] Problema em atualização de base (account.tax.group)

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1632]
Aparentemente relacionado com o refactor do account.tax.group PR #1602 

Claro que pode ser algo apenas neste ambiente mas eh uma base foi recentemente atualizada com sucesso.

`2021-09-14 23:17:00,576 7192 ERROR db odoo.modules.registry: Model l10n_br_coa.account.tax.group.account.template has no table.`

ping @netosjb @felipemotter @renatonlima @rvalyi

**Comment by antoniospneto** [comment]
@marcelsavegnago estranho, estou testando aqui

**Comment by marcelsavegnago** [comment]
Então.. eu rodei atualização do módulo l10n_br_base e deu essa mensagem.. dai fiz a atualização do l10n_br_coa e aparentemente foi..

**Comment by antoniospneto** [comment]
opa @marcelsavegnago  pois então eu fiz o teste aqui, montei uma base com o código antes da #1602  depois atualizei o source code com o merge da #1602 dei update nos módulos e funcionou certinho.

**Comment by marcelsavegnago** [comment]
tentou atualizar inicialmente pelo l10n_br_base ?

Enfim, o ambiente aqui parece que está ok.. :D

**Comment by antoniospneto** [comment]
mas você precisa dar update em todos os módulos que foram alterados não ?

**Comment by marcelsavegnago** [comment]
Não necessariamente, mas em tese rodar um update começando pelo l10n_br_base garante que todos os demais sejam atualizados e em tese deveria rodar suave :D heheheh (mas nem sempre)

**Comment by rvalyi** [comment]
Então pessoal, a respeito do #1602 tem que atualizar com --update=l10n_br_coa dai ate onde eu testei em prod funciona bem. Normal, o esquema ligado ao modulo mudou, teve atualização minor ou major (major no caso), tem que dar update do modulo. 

Agora, ao contrario de que talvez vcs pensaram, o l10n_br_coa NAO DEPENDE do l10n_br_base, portanto, atualizar o l10n_br_base NAO VAI mandar atualizar o l10n_br_coa (sem falar que nao teria porque atualizar o l10n_br_base no caso). Podem confirmar se ta OK e se podemos fechar o issue?

**Comment by marcelsavegnago** [comment]
Grande @rvalyi Ok.. estou finalizando a issue.
