### ISSUE TITLE
[Q&A] Forma de pagamento - Leiaute NFe

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#1633]
@rvalyi 

Percebi que após a atualização do leiaute da NFe na PR #1553 houve uma regressão com as informações de pagamento.
Antes da PR a forma de pagamento era exibida dessa forma:
![image](https://user-images.githubusercontent.com/634278/133363614-3f228a95-9822-48d8-a5bf-30fa3799ce55.png)
![image](https://user-images.githubusercontent.com/634278/133363645-c8575822-adb5-41a3-9661-c78f0526e00c.png)

Após o merge da PR não é mais carregado as opções da Forma de Pagamento, o campo que era uma caixa de seleção virou um campo de texto normal:

![image](https://user-images.githubusercontent.com/634278/133363788-e081eac9-3524-4fc5-952e-d53ab9b27a7e.png)

Isso foi intencional ou passou despercebido? talvez sejam os Esquemas da NFe que mudaram?

**Comment by rvalyi** [comment]
Ola @netosjb eu nao parei para olhar bem esse seu issue, mas houve sim um select de pagamento que virou mesmo um campo txt nos ultimos esquemas, vé o que eu eu tinha comentado a respeito https://github.com/OCA/l10n-brazil/pull/1553#issue-705769360 "Se ha duvida: sim os tipo de bandeira e de pagamento ficaram mesmo com texto livre agora em vez da seleção de antes."  Eu tb estranhei, mas vc pode abrir o XSD e verificar como eu verifiquei.
Seria disso que se trata?

**Comment by antoniospneto** [comment]
Fala @rvalyi ontem eu dei uma olhada, mas realmente não foi muito profundo, hoje a noite vou estudar com mais calma, logo te passo meu feedback, obrigado!

**Comment by antoniospneto** [comment]
Pois é, o governo modificou como essa informação é apresentada no esquema da nfe:

```
<xs:element name="tPag">
    <xs:annotation>
        <xs:documentation>Forma de Pagamento:</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
            <xs:pattern value="[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
```

Que pena que agora não dá mais de extrair a tabela de meio de pagamento direto do esquema.

Mas obrigado pela atenção @rvalyi! Estou fechando a issue.
