### ISSUE TITLE
Erro atualização l10n_br_coa - v 12.0.3.1.0

### ISSUE THREAD

**Issue by edsonblwolf** [OCA/l10n-brazil#1635]
** Descreva o bug **
O erro ocorre quando clico no botão update, log em anexo.
https://pastebin.com/fdpKjUz0

**Comportamento esperado**
Esperava que fizesse uma atualização do módulo.

** Capturas de tela **
https://ibb.co/tp5TDG6

** Contexto adicional **
Esta estranho, aparece pra atualizar da mesma versão, antes fiz um git pull na pasta, estou fazendo correto?

**Comment by vanderleiromera** [comment]
Tenta atualizar usando linha de comando vide [comentário](https://github.com/OCA/l10n-brazil/issues/1632#issuecomment-919610038) do rvalyi pr #1632

**Comment by antoniospneto** [comment]
@edsonblwolf se você atualizou o código fonte do repositório l10n-brazil acredito que tenha mais modulo que você precisa por no comando --update

**Comment by edsonblwolf** [comment]
Instalei o module_auto_update e executei ele dentro do odoo e resolveu o problema, obrigado pela força.

**Comment by marcelsavegnago** [comment]
Eu também passei por isso hoje.. fiz update do l10n_br_base primeiro para contornar isso e depois fiz o update do coa por conta de outro problema.
