### ISSUE TITLE
[12.0][BUG] - Devolução, apos concluida retorna criação da fatura novamente

### ISSUE THREAD

**Issue by vanderleiromera** [OCA/l10n-brazil#1638]
** Descreva o bug **
Configuração da Venda

![sale_order](https://user-images.githubusercontent.com/65144026/134049728-901f8b8f-dc43-40c1-8a3c-b571cbcffcb1.png)

O processo de devolução funciona tudo certo, o problema é que a fatura retorna pra ser faturada novamente

![invoice](https://user-images.githubusercontent.com/65144026/134049955-fae2a03f-e68c-44e6-ade7-ed9c2c863d65.png)

**Reproduzir**

Problema surgiu com o merge da pr #1574

**Comment by renatonlima** [comment]
Olá @vanderleiromera,


Isso é um comportamento padrão do core do Odoo, se você faturou 10 unidades de uma linha de pedido de venda e depois essas 10 unidades foram devolvidas (criada uma devolução) a quantidade faturada será 0, isso acontece para deduzir as devoluções das quantidades faturas e também para no caso de trocas.

**Comment by vanderleiromera** [comment]
Olá @renatonlima, mas algo não estou entendendo, aqui a fatura volta novamente pra ser faturada, e faturando ela veja como fica na imagem, ela gerou a nota número 5

![037](https://user-images.githubusercontent.com/65144026/134068479-aaae3741-f835-4420-820e-e6fdaa4e3d25.png)


Neste caso o saldo do cliente deveria ser 0. Mas faturando novamente volta o valor origin al da fatura sem o retorno...

**Comment by vanderleiromera** [comment]
Faltou informar que o botão Create Invoice, fica habilitado apos devolução ...

![fatura](https://user-images.githubusercontent.com/65144026/134097036-b16b68e4-9f1d-4904-b7f7-9744f1848cbd.png)

Permitindo a criação da mesma fatura devolvida

**Comment by vanderleiromera** [comment]
A solução provisória foi na devolução deixa o faturamento = no invoincing, e a fatura da devolução criar por fora.
