### ISSUE TITLE
[12.0][BUG] Problema na geração DANFE quando o sinal & está presente nos dados fiscais adicionais

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1646]
Estou mapeando ainda mas existe um problema na geração do DANFE quando na mensagem fiscal adicional o caracter & está presente. 

Enfim, todo o processo de geração do DANFE ocorre mas o pdf não é gerado.
https://github.com/erpbrasil/erpbrasil.edoc.pdf/blob/712f0ca7768b4f94caf23d80d43a2c88dd2d16ce/src/erpbrasil/edoc/pdf/base.py#L90

**Comment by marcelsavegnago** [comment]
Para contornar esta situação tive que fazer da seguinte forma:

![image](https://user-images.githubusercontent.com/3595132/135207456-cd939d5f-aa66-495e-a799-6c69ceb30102.png)

@renatonlima @rvalyi esta mudança pode impactar em algo que eu não tenha observado ?

**Comment by marcelsavegnago** [comment]
Obs. Outro ajuste que precisei fazr para visualizar a nota fiscal ainda não enviada foi o seguinte

![image](https://user-images.githubusercontent.com/3595132/135207729-059488a0-d6c2-423a-babe-eb5e0e992b10.png)

OBS. Estou deixando registrado aqui para eu não esquecer de tratar tbm no caso de uma PR

**Comment by antoniospneto** [comment]
@marcelsavegnago  

Testei aqui e acontece a mesma coisa, fui um pouco mais longe e testei informando o "&" no endereço também:
![image](https://user-images.githubusercontent.com/634278/135697865-79ef2683-cd20-4db5-a721-8d8e7847fb61.png)

Chega a dar erro ainda antes da geração da DANFE, acontece já  ao tentar enviar o xml:
![image](https://user-images.githubusercontent.com/634278/135697877-c1b2a123-d91a-4091-b217-71dd53756a93.png)
![image](https://user-images.githubusercontent.com/634278/135697627-c8a22da4-7dff-462b-be66-8f7da18652b7.png)

Pelo que pesquisei o "&" é um caractere reservado do XML, acho que a solução é substituir conforme você fez, só tinha que ver uma forma de fazer isso para todos os campos do documento, antes de montar o xml.
