### ISSUE TITLE
[BUG] o valor da alíquota do ICMS está sendo somando ao valor total da fatura. (SIMPLES NACIONAL)

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#1648]
Na emissão de nota fiscal para empresas do simples nacional, o imposto de ICMS SN está sendo somado no total da fatura, mas isso está errado.

Configuração do imposto na linha da fatura (produto):
![image](https://user-images.githubusercontent.com/634278/135555782-2efdce37-6c5c-428c-ba1b-7e3630536cf3.png)

Linha do imposto na Fatura:
![image](https://user-images.githubusercontent.com/634278/135555236-c532bae1-770e-4c34-8bcc-91c674f43595.png)

Valores totais da fatura:
![img](https://user-images.githubusercontent.com/634278/135556537-623efa2e-d85f-4bef-af80-4bd343618497.png)

Olha como fica os lançamentos contábeis da fatura:
![image](https://user-images.githubusercontent.com/634278/135557285-e6bf8039-1cd2-4fae-a464-eeedc7da8790.png)

Qual será que a melhor forma de resolver isso ? alguém já passou por esse problema ou já tem algo em mente?
Será que é por falta de um lançamento contrário  ao imposto (débito) igual acontece na empresa normal ??
Ou será melhor uma solução alternativa? pensei em calcular o compo ICMS SN sem ser pela definição dos mecanismos padrão de imposto, para esse tipo de lançamento não acontecer.

Ou talvez excluir essa linha de imposto antes de validar a fatura, bom, pelo menos é isso que estou fazendo manualmente para  lançar a fatura e gerar a nota fiscal e ta dando muito certo. talvez esse seria o caminho mais curto sem muita refatoração de código. O proposito dessa linha pelo que vi é calcular esses campos:
![image](https://user-images.githubusercontent.com/634278/135559431-dcf5f022-ad57-4d14-9847-eb298670faf6.png)
Depois desses campos estarem calculados a linha do imposto ICMS SN não tem mais serventia.. é o que me parece.

@rvalyi @renatonlima @marcelsavegnago

**Comment by marcelsavegnago** [comment]
No caso do ISS eu precisei cadastrar um ISSQN Saída Dedutivel. Desta forma tenho a linha do imposto e a linha de deducao da receita. Enfim, no caso do ICMS SN eu não olhei muito.

**Comment by antoniospneto** [comment]
@marcelsavegnago opa! vou tentar configurar algo parecido pra ver como fica :) acho que pode ser uma solução boa.
esse find pretendo estudar melhor essas questões ainda to um pouco perdido rsss. obrigado 👍🏻

**Comment by marcelsavegnago** [comment]
Na hora de criar, se baseia neste Cofins de Saída Dedutivel que tem ai no teu lancamento.

**Comment by vanderleiromera** [comment]
Aqui uma situação de duplicação no calculo da fatura, entrada de produto com ST incluso na nota, ao validar a fatura o imposto é duplicado.

![st](https://user-images.githubusercontent.com/65144026/135618243-938800eb-a9a6-416b-ad38-6b56bbd35472.png)

**Comment by antoniospneto** [comment]
@vanderleiromera pois é parece um problema parecido.

Pessoal, talvez configurar um flag no imposto informando se é para criar ou não um lançamento no diário, pelo que percebi é que as vezes o imposto existe mas é um controle diferente, nem tudo é necessário lançar no diário.

**Comment by marcelsavegnago** [comment]
@netosjb acho que o caminho nao é esse nao. Entendo que o lancamento do diário deve ser feito para garantir a contabilização e controle adequado.

**Comment by rvalyi** [comment]
pessoal, a gente tem clientes do Simples que não usam o modulo fiscal, mas a gente ainda não tem cliente do Simples que usa o modulo fiscal. Aquela famosa questão que não é empresa pequena que banca uma P&D dessa...  Mas nisso realmente não seria surpreendente alguns erros desse tipo com o Simples.

**Comment by antoniospneto** [comment]
@rvalyi  entendi, mas mesmo assim ainda tá bem legal, tem esses pequenos bug, mas aos poucos a gente vai testando e arrumando.

@marcelsavegnago vou ver melhor com a minha contabilidade, mas é que eu acho que pro simples nacional não precisa fazer o lançamento contábil em um diário ou livro razão do valor do crédito do ICMS, esse valor eu só preciso informar na nfe pra quem receber a nota saber o quanto tem de direito de aproveitamento de crédito de ICMS. Não é um lançamento para eu saber ou deduzir a quantidade de ICMS que vou pagar pro estado, até por que tem casos que o cliente não terá direto ao crédito de ICMS e os campos do ICMS SN irão zerado e isso não irá fazer diferença do quanto irei pagar de ICMS, também não fará diferença no custo do meu produto, pois o que vou pagar já está incluso no imposto unificado do simples e ele é calculado diretamente com base na tabela de faturamento do simples nacional, no final do período, uma vez por mês.
Também se for seguir a logica de fazer esses lançamentos contábeis do imposto separado, não unificado, por que fazer só com ICMS? ai teria que fazer com o IPI, PIS, CONFIS, e etc, isso tudo também existe no simples, mas tá tudo unificado em uma guia, o lançamento desse imposto é feito apenas uma vez por mês, não tem necessidade do controle linha por linha da fatura.
Obs: esse é só um pensamento meu, não sei se estou certo, não sou contador então minha opinião não vale como informação técnica e precisa ser valida por um, mas acho interessante a gente discutir aqui diferentes pontos de vista.

O simples nacional não tem tantas exigências/obrigações por isso acho que pode ser interessante o flag para não criar o lançamento contábil, eu tenho ainda mais outra solução em mente rsss.. depois vou testar e se ficar legal apresento aqui pra gente discutir mais um pouco :)

Obrigado a todos pelo feedback

**Comment by antoniospneto** [comment]
> @netosjb acho que o caminho nao é esse nao. Entendo que o lancamento do diário deve ser feito para garantir a contabilização e controle adequado.

Ressalto que não sou contra essa solução, até vou testar aqui também e agradeço pela dica, isso pode ser feito como um controle extra, mas acho que não seja uma obrigação.
Pelo que vi nada impede a gente de fazer segregação dos impostos do simples nacional, mas fazer ao pé da letra pode ficar um pouco complexo e pro meu caso de uso não tem necessidade.

**Comment by antoniospneto** [comment]
@marcelsavegnago 

Configurei a conta dedutível para o grupo de imposto ICMS SN e funcionou certinho, é bem prático configurar, obrigado!

![image](https://user-images.githubusercontent.com/634278/135696559-c4ac2370-4d82-4333-aabd-d004d29a8f6a.png)

@vanderleiromera acho que essa dica vale pra sua situação também.

**Comment by vanderleiromera** [comment]
Valeu @netosjb vou testar aqui.
