### ISSUE TITLE
[feature] Adicionar o módulo account_cancel nas dependências do l10n_br_account

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#166]
Para cancelar uma Fatura/Nota Fiscal é necessário este módulo para permitir o cancelamento dos lançamentos contábeis e retornar a fatura/Nota Fiscal para rascunho.

**Comment by danimaribeiro** [comment]
No módulo de nfe tem a dependência deste módulo:
https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/blob/8.0/nfe/__openerp__.py#L41
Não vejo problemas em adicionar.

**Comment by mileo** [comment]
LGTM

**Comment by mileo** [comment]
@renatonlima Please close this issue
