### ISSUE TITLE
[12.0][BUG] Validação de Conta de Fornecedor

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1675]
Ao fazer a validação de uma conta de fornecedor criada via um pedido de compra, recebo a seguinte mensagem.

![image](https://user-images.githubusercontent.com/3595132/137894051-061bb05f-b8dd-4fc9-9a2d-9e98ba3ad453.png)

No caso entendo que uma conta de fornecedor deveria assumir o codigo da serie digitado mas ao tentar registrar um evento fiscal o sistema tenta buscar o id da série. 

Testado localmente e via runbot.

cc @renatonlima @rvalyi @netosjb @felipemotter

**Comment by marcelsavegnago** [comment]
Pelo que entendi é criado um evento de envio do XML ao validar uma conta de fornecedor e este tenta por sua vez criar um registro de evento fiscal que tem como campo obrigatório o document_serie_id.

Faz sentido esta criação do evento ? 
![image](https://user-images.githubusercontent.com/3595132/137896508-dff239a8-23d5-4156-8409-8087ea3a96bc.png)

![image](https://user-images.githubusercontent.com/3595132/137896206-67aa3306-0944-473c-be01-a89917269329.png)

**Comment by antoniospneto** [comment]
@marcelsavegnago 

Isso acontece comigo tbm, pretendo investigar isso em breve

**Comment by marcelsavegnago** [comment]
@netosjb boa..

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/1814
(so para deixar claro, esse código não era nosso).
