### ISSUE TITLE
Entrada do Marcel Savegnago no PSC (committer) do projeto

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1685]
Ola pessoal, devido ao impressionante trabalho do @marcelsavegnago no projeto esses últimos 18 meses assim como sua atividade extensa nos outros repos da OCA onde ele fez o dever de casa primeiro, solicitamos a entrada dele no PSC do projeto, ou seja para ser committer tb (alem de @renatonlima @mileo e eu):
https://odoo-community.org/groups/contributors-15/contributors-226330?mode=thread&date_begin=&date_end=

Solicitamos o apoio daqueles de vcs que que apreciaram o trabalho do @marcelsavegnago e acham que ele esta pronto para essa responsabilidade como achamos @renatonlima e eu e assim ajudar a escalar o projeto ainda mais. Em especial achamos que o Marcel tem um know-how bem complementar na questão das NFSe alem de uma cultura geral para ajudar em varios aspectos do projeto.

cc @mileo @mbcosta @netosjb @felipemotter @britoederr @vanderleiromera @gabrielcardoso21 @luismalta @marcos-mendez @crsilveira

**Comment by vanderleiromera** [comment]
Sensacional, ele merece, parabéns @marcelsavegnago

**Comment by felipemotter** [comment]
Merecido!!! vai poder contribuir ainda mais.

**Comment by rvalyi** [comment]
Eh mas é na lista aqui que tem que apoiar: https://odoo-community.org/groups/contributors-15/contributors-226330?mode=thread&date_begin=&date_end=

**Comment by marcelsavegnago** [comment]
Opa... agradeço o apoio e podem contar comigo.

Recentemente dei uma afastada por problemas pessoais mas to aqui. 

Obrigado ai pessoal. tmj  e fico muito feliz com o apoio e a confiança.

**Comment by rvalyi** [comment]
sera se um dia o @netosjb segue o mesmo caminho? Hoje ele ja teve um fix incluído no brcobranca hoje (a libe Ruby usado pros boletos e CNAB) https://github.com/kivanio/brcobranca/pull/226 parabens tb!

**Comment by rvalyi** [comment]
fechando o issue já que o Marcel entrou.
