### ISSUE TITLE
[BUG][]14.0][l10n_br_fiscal]

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1687]
Se vc criar um novo documento fiscal, por examplo NFe na v14 e começar a digitar algo no tipo de documento fiscal, o name_search do tipo de documento fiscal da esse erro:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/.repo_requirements/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 1801, in name_search
    return self.browse(ids).sudo().name_get()
  File "/home/odoo/build/OCA/l10n-brazil/setup/l10n_br_fiscal/odoo/addons/l10n_br_fiscal/models/data_abstract.py", line 91, in name_get
    return [(r.id, "{} - {}".format(r.code, truncate_name(r.name))) for r in self]
  File "/home/odoo/build/OCA/l10n-brazil/setup/l10n_br_fiscal/odoo/addons/l10n_br_fiscal/models/data_abstract.py", line 91, in <listcomp>
    return [(r.id, "{} - {}".format(r.code, truncate_name(r.name))) for r in self]
  File "/.repo_requirements/odoo/odoo/fields.py", line 998, in __get__
    recs._fetch_field(self)
  File "/.repo_requirements/odoo/odoo/models.py", line 3071, in _fetch_field
    self._read(fnames)
  File "/.repo_requirements/odoo/odoo/models.py", line 3138, in _read
    cr.execute(query_str, params + [sub_ids])
  File "<decorator-gen-3>", line 2, in execute
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: operator does not exist: integer = record
LINE 1: ...ent_type" WHERE "l10n_br_fiscal_document_type".id IN ((31, '...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by marcos-mendez** [comment]
@rvalyi eu clonei o v14 do github e não consigo nem instalar o fiscal, tenho que usar alguma PR especial?

**Comment by rvalyi** [comment]
Não deve não. Qual problema vc tem? Vc tem que checar se sua configuração é diferente do Runbot ou do Travis.

**Comment by antoniospneto** [comment]
@marcos-mendez 

Não sei se é o seu caso, mas a unica coisa q eu tive q mudar para montar o ambiente para o 14.0 foi instalar o node-less.
Abra uma issue com o erro pra gente poder ajudar.

**Comment by marcos-mendez** [comment]
@netosjb e @rvalyi https://github.com/OCA/l10n-brazil/issues/1693

Abri aqui. 

Qual seria a confiugração do travis. 

O node-less é solicitado desde o odoov12 que eu me lembro, não passei por isso

**Comment by rvalyi** [comment]
@marcos-mendez para as dependencias do Odoo 14, vc pode ver https://github.com/odoo/docker/blob/master/14.0/Dockerfile
e para as dependencias especificas do repo l10n-brazil na 14.0, vc pode ver https://github.com/OCA/l10n-brazil/blob/14.0/.travis.yml e https://github.com/OCA/l10n-brazil/blob/14.0/requirements.txt
Sobre o erpbrasil.assinatura, o @mileo ta uns meses sem conseguir fazer a release que nao depende do xmlsec para facilitar a instalação, o @renatonlima pediu os credenciais para fazer a release de novo... Mas instalar a versão atual do pypi funciona quando conseguir instalar.

**Comment by crsilveira** [comment]
> Se vc criar um novo documento fiscal, por examplo NFe na v14 e começar a digitar algo no tipo de documento fiscal, o name_search do tipo de documento fiscal da esse erro:
> 
> ```
> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/.repo_requirements/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
>     result = request.dispatch()
>   File "/.repo_requirements/odoo/odoo/http.py", line 684, in dispatch
>     result = self._call_function(**self.params)
>   File "/.repo_requirements/odoo/odoo/http.py", line 360, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/.repo_requirements/odoo/odoo/http.py", line 348, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/.repo_requirements/odoo/odoo/http.py", line 913, in __call__
>     return self.method(*args, **kw)
>   File "/.repo_requirements/odoo/odoo/http.py", line 532, in response_wrap
>     response = f(*args, **kw)
>   File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1389, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/.repo_requirements/odoo/odoo/api.py", line 392, in call_kw
>     result = _call_kw_model(method, model, args, kwargs)
>   File "/.repo_requirements/odoo/odoo/api.py", line 365, in _call_kw_model
>     result = method(recs, *args, **kwargs)
>   File "/.repo_requirements/odoo/odoo/models.py", line 1801, in name_search
>     return self.browse(ids).sudo().name_get()
>   File "/home/odoo/build/OCA/l10n-brazil/setup/l10n_br_fiscal/odoo/addons/l10n_br_fiscal/models/data_abstract.py", line 91, in name_get
>     return [(r.id, "{} - {}".format(r.code, truncate_name(r.name))) for r in self]
>   File "/home/odoo/build/OCA/l10n-brazil/setup/l10n_br_fiscal/odoo/addons/l10n_br_fiscal/models/data_abstract.py", line 91, in <listcomp>
>     return [(r.id, "{} - {}".format(r.code, truncate_name(r.name))) for r in self]
>   File "/.repo_requirements/odoo/odoo/fields.py", line 998, in __get__
>     recs._fetch_field(self)
>   File "/.repo_requirements/odoo/odoo/models.py", line 3071, in _fetch_field
>     self._read(fnames)
>   File "/.repo_requirements/odoo/odoo/models.py", line 3138, in _read
>     cr.execute(query_str, params + [sub_ids])
>   File "<decorator-gen-3>", line 2, in execute
>   File "/.repo_requirements/odoo/odoo/sql_db.py", line 101, in check
>     return f(self, *args, **kwargs)
>   File "/.repo_requirements/odoo/odoo/sql_db.py", line 298, in execute
>     res = self._obj.execute(query, params)
> Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/.repo_requirements/odoo/odoo/http.py", line 640, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/.repo_requirements/odoo/odoo/http.py", line 316, in _handle_exception
>     raise exception.with_traceback(None) from new_cause
> psycopg2.ProgrammingError: operator does not exist: integer = record
> LINE 1: ...ent_type" WHERE "l10n_br_fiscal_document_type".id IN ((31, '...
>                                                              ^
> HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
> ```

Alterando a linha 71 :+1: 
    @api.model
    def _name_search(
        self, name, args=None, operator="ilike", limit=100, name_get_uid=None
    ):
        if operator == "ilike" and not (name or "").strip():
            domain = []
        elif operator in ("ilike", "like", "=", "=like", "=ilike"):
            domain = expression.AND(
                [
                    args or [],
                    [
                        "|",
                        "|",
                        ("name", operator, name),
                        ("code", operator, name),
                        ("code_unmasked", "ilike", name + "%"),
                    ],
                ]
            )
  -->>>          recs = list(self._search(
                expression.AND([domain, args]),
                limit=limit,
                access_rights_uid=name_get_uid,
            ))
            return recs

        return super()._name_search(
            name, args=args, operator=operator, limit=limit, name_get_uid=name_get_uid
        )

https://github.com/crsilveira/l10n-brazil/commit/3d1160108c542fabf4469058a8b3d8c996d67b79
parece resolver, este problema.

**Comment by rvalyi** [comment]
@crsilveira esse do name_search ja esta no radar https://github.com/OCA/l10n-brazil/issues/1687

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/1766
