### ISSUE TITLE
[12.0][RFC][sale_invoice_plan] base de imposto não respeita a quantidade do item da fatura gerada pelo sale_invoice_plan

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1697]
**Sua solicitação de mudança/melhoria está relacionada a um problema? Por favor descreva.**
Ao utilizar este módulo, percebi até então que a base de cálculo do imposto não respeita a quantidade faturada. No caso foi vendido 1 unidade de um servico e ao faturar 0,33% dele o sistema ignora os 0,33% e assume a base de calculo total.

Este módulo permite definir um plano de faturamento para o pedido de venda. No cenário que estou trabalhando é vendido um projeto com a quantidade 1 e se faz necessário gerar uma fatura para cada pagamento e não uma única fatura com recebimento previsto em 3x.

**Descreva a solução que você deseja**
A principio pensei em localizar este módulo mas talvez apenas uma melhoria no módulo l10n_br_account resolva o problema e evitamos ter que localizar mais um módulo

**Comment by marcos-mendez** [comment]
Marcel isso aconteceu comigo já também quando vende meia hora de serviço. 

Eu fiz uma produto com meia hora de preço pra não perder a venda. Mas acho que isso de refazer ou melhorar o account é melhor que fazer um submodulo. Né?

**Comment by marcelsavegnago** [comment]
> Marcel isso aconteceu comigo já também quando vende meia hora de serviço.
> 
> Eu fiz uma produto com meia hora de preço pra não perder a venda. Mas acho que isso de refazer ou melhorar o account é melhor que fazer um submodulo. Né?

Eh não cheguei a testar com quantidade quebrada para ver como está funcinando independente do sale_invoice_plan.. Vou dar uma olhada.. Obrigado @marcos-mendez

**Comment by marcelsavegnago** [comment]
@rodrigonevest favor testar no runboat da 12.0 e verificar se o problema ainda está com problema.
