### ISSUE TITLE
separate cpf and cnpj fields

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#17]
if we want to be more compatible with the the denormalization of addresses in the the res.partner table, we will need to start by splitting the cnpj_cpf field into a cpf and a cnpj field.

**Comment by renatonlima** [comment]
Isso não é necessário, já que tanto os dados de contato quanto de empresa esta no mesmo objeto res.partner o que já esta normalizado e também evitando que em outras partes do código tenha que checar se é uma empresa ou não para pegar o campo cnpj ou cpf
