### ISSUE TITLE
[12.0][Q&A] fiscal_quantity e fiscal_price

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1711]
@renatonlima @rvalyi falando dos campos fiscal_quantity e fiscal_price de fato são necessários ? a principio gera um pouco de confusão para o usuário e me parece ser algo que afeta a integração com outros módulos OCA e que podem gerar necessidade de localização dos mesmos por questões relacionadas com estes campos (exemplo sale_invoice_plan). 

A ideia destes campos é de fato permitir valores diferentes do que está em uma ordem de venda vs o documento fiscal gerado ?

**Comment by renatonlima** [comment]
@marcelsavegnago,

Nos documentos fiscais como a NF-e existem os campos (preço unitário e quantidade) comercial e os campos (preço unitário e quantidade) fiscal, na maioria dos casos os campos comercial e fiscal serão iguais, mas existe alguns casos que não, por exemplo existe na receita federal uma relação de unidade de medidas de exportação para cada NCM então podemos ter um item controlado o estoque em unidade mas ao exportar a quantidade fiscal tem que ser em kilos, ai neste caso é definido no cadastro de produto a unidade de medida e o fator de conversão já que são unidades de medidas diferentes.

Uma breve explicação também tem neste link: https://site.guinzo.com.br/ucomeutrib/

**Comment by marcelsavegnago** [comment]
Grande @renatonlima de fato se faz util esses campos sim.. percebi ao evoluir um pouco no trabalho com o modulo sale_invoice_plan.. no caso o sistema vai usar a unidade de medida e quantidades quebradas para gerenciar internamente .. mas fiscalmente a quantidade deveria ser 1 e nao 0.33 por exemplo.. entao o lugar mais adequado me pareceu corrigir na quantidade fiscal para 1 e manter q quantidade do sistema 0.33.

**Comment by marcelsavegnago** [comment]
Pra mim.. a q questão está respondida e portanto estou finalizando..

Mutio obrigado pelo retorno @renatonlima
