### ISSUE TITLE
[IMP] - l10n_br_coa_simple

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1738]
** Descreva o bug **
Ao instalar o modulo é gerado os seguintes planos de contas que parecem ser meio esquisitos

Não sei ao certo se foi um teste que passou para o MERGE v12.0 e deveria ter sido tirado ou se simplesmente tem que remover manualmente, não tenho informações sobre.

![Screenshot from 2021-12-03 16-38-44](https://user-images.githubusercontent.com/38361760/144663048-a0d210e0-a4c9-4b8d-953f-011c6f0d8d11.png)

Acredito que os nomes estejam certo mas parece hacer um append desse AVOID_TRAVIS_ERROR por algum motivo que desconheço, não consegui identificar como isso aconteceu. 

Teste executado em LXC e no RUNBOT

**Comment by rvalyi** [comment]
essas contas nao tem a ver com o modulo l10n_br_coa_simple mas vem dos dados de demo do modulo l10n_br_account_payment_order
https://github.com/OCA/l10n-brazil/blob/584b51d47236b14388a0654d8895f25bd1b16230/l10n_br_account_payment_order/demo/account_account.xml

@mbcosta foi vc que botou nomes de contas com "AVOID_TRAVIS_ERROR' ou é algo que recuperamos do modulo da KMEE? sabe o motivo desses nomes? Agora se tratando de dados de demo, dificilmente isso seria um "bug".

Parece que na v10 ja tinha uma conta com nome assim (na v8 não) https://github.com/OCA/l10n-brazil/blob/10.0/l10n_br_account_payment_order/demo/account_payment_order_demo.xml, mas apenas uma.
E parece que foi vc quem botou esse nome @mbcosta https://github.com/OCA/l10n-brazil/commit/f0c4556d20b7c8948dc5c66e4a84ddaf89be94f0

Teria sido para evitar de ter o mesmo codigo ou mesmo nome de conta quando instalar algum dos planos talvez?

**Comment by marcos-mendez** [comment]
Bom, por isso que informei que não sabia se era algo dos dados demo ou se era um problema do Módulo,por isso disse que é um erro esquisito. 

Enfim, se você falarem eu fecho a Issue, coloquei como BUG porque não é nem dúvida nem nem discussão é só uma questão dessa descrição do Travis.

**Comment by marcos-mendez** [comment]
Ele só dá essas opções aqui, então eu abri como Bug, mas posso colocar QUESTION sei lá
![Screenshot from 2021-12-03 17-43-33](https://user-images.githubusercontent.com/38361760/144670353-b7c8ab00-b7e3-4691-8a2b-2ee3e3cedb20.png)

**Comment by marcos-mendez** [comment]
Outra coisa estranha que ao instalar o l10n_br_coa_simple, ele acusa o carregamento do CSV de dados, porém estes não constam no banco de dados. 

Talvez seja algum erro de procedimento meu. Só para reportar aqui se alguem conseguir entender o que acontece, não parece ser erro de funcionamento, mas talvez algo que não tá aparecendo mesmo

![Screenshot from 2021-12-03 17-53-51](https://user-images.githubusercontent.com/38361760/144671545-b2f07a5d-0644-4799-bebd-735388fdb9b0.png)
![Screenshot from 2021-12-03 17-53-28](https://user-images.githubusercontent.com/38361760/144671549-f79efd2c-d42e-42d1-a817-b0cf0a2600d4.png)

Somente 13 tipos de Planos de contas. Weird

**Comment by marcos-mendez** [comment]
O Neto me ajudou. Acho que limpando o account.invoice table resolver o problema de instalação. Acho que era bom verificar isso desde 0. Ou seja, Informar o cara que ele não consegue instalar o módulo se houver uma account.invoice no banco. 

Em relação ao alerta acho que não é dificil de fazer, Porém a nível de encontrar onde faço isso é um processo. 

Estou mudando esta Issue para implementação. Para colocar isto como algo possível e a futuro de fazer

**Comment by marcos-mendez** [comment]
Agora QUESTION

https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_account/tests

Este teste, não posso copiar ele e colar no coa coa_simple e no outro coa para garantir que isto ocorra quando são tentados instalar do zero? Tipo assim verificar o account.invoice ler ele e deixar ou não instalar.

**Comment by marcelsavegnago** [comment]
@marcos-mendez eu me perdi. Se forem assuntos distintos eu sugiro gerar issues separadas para facilitar o entendimento e acompanhamento.

**Comment by marcos-mendez** [comment]
@marcelsavegnago bom dia amigão, Obrigado pelo retorno. Vamos lá. Eu fui instalar o l10n_br_coa e ele veio com aqueles nomes estranhos (DADOS DEMO ativados + uma linha no account.invoice)

Apos o @netosjb me explicar u limpei o banco de dado direto no SQL para não ter duvida, porque segundo o neto não podem haver itens do diário (o que não constava, mas havia sim account.invoice) 

Ai reinstalei o l10n_br_coa_simple e foi. 

A minha sugestão depois do processo de entender o que ocorria no meu caso na sexta feira é colocar uns testes tipo pré instalação do módulo que alerte o cabra quenem quando falta um pacote python sabe? Fulano você ta com uma account.invoice, apague para poder instalar este módulo. 

Ficou meio esquisito porque foi o que eu fui descobrindo no dia. Mas posso fechar e abrir uma para cada coisa. O @rvalyi não se manifestou mais sobre os nomes do Travis lá, Eu também não sei se é pra tirar. Enfim, não sei. Aguardo orientações de vocês se devo abrir duas (uma para cada coisa Nome do Travis aparecendo/ testes pre instalação)

**Comment by mileo** [comment]
A localização quando instalada com dados de demonstração vem com 3 empresas cadastradas, sendo que duas delas carregam um plano de contas, o simple e a outra o genérico.

Alem disso é como o @rvalyi comentou, algumas contas são criadas para fazer com que alguns testes executem sem problemas e isso é normal. Vc pode ver num runbot sem localização que até existem diários de testes e contas (pelo menos nas versões anteriores isso era normal).

Ai a questão mais importante é que em uma base de produção os planos de contas não são carregados automaticamente e se algum é carregado, se vc não fizer nenhum lançamento vc pode trocar para qualquer outro, basta ir em contabilidade > configurações e selecionar o plano de contas desejado. Se já existem lançamentos contábeis o procedimento é mais complicado.

**Comment by mileo** [comment]
Então isso não é um bug e sim um comportamento normal.

**Comment by mbcosta** [comment]
ola @rvalyi o "issue" já foi fechado mas só para esclarecer as suas perguntas que podem ser as duvidas de outros, sim foi eu que inclui essas Contas Contábeis isso foi feito devido a forma como o Travis instala os módulos em dois passos e carrega primeiro um Plano de Contas genérico, sobre os nomes foi o que você escreveu "evitar de ter o mesmo codigo ou mesmo nome de conta quando instalar algum dos planos " existe uma restrição contra Contas Contábeis com o mesmo nome, e com o AVOID_TRAVIS_ERROR deixa claro o motivo da existência dessas contas( pode ser pensando em colocar outro texto para diferenciar se isso for um problema ), dessa forma também é possível testar os dados de demonstração tanto na instalação feita pelo Travis quanto localmente onde é possível instalar primeiro o l10n_br_account e assim ter o Plano de Contas da localização sem conflitos e sem a necessidade de configurar as Contas Contábeis a serem usadas no l10n_br_account_payment_order e l10n_br_account_payment_brcobranca.

Com todo respeito, considerar o Nome de um Dado de Demonstração um BUG é um equivoco bem grande, é fundamental que alguém que queira trabalhar com qualquer área de T.I. ou mesmo de engenharia em geral se preocupe a no minimo buscar identificar o tipo/categoria de problema encontrado, principalmente quando se trata de algo que não entende ou domina. Um BUG é um erro em uma funcionalidade ou um método especifico que já está na "branch" principal e que está causando erros em Ambientes de Produção, possui uma prioridade bem maior de atenção e foco na solução e isso pode incluir soluções temporárias/gambiarras/hotfix/patchs para "estancar o problema" e não ter o erro, importante dizer que é algo que faz os principais desenvolvedores pararem o que estiverem fazendo para buscar resolver isso o mais breve possível, usar isso de forma indiscriminada soa como um "Falso Alarme" é como dizer que "Tem um incêndio em algum lugar" e quando a equipe responsável chega não encontra nada, isso com o tempo acaba tirando a credibilidade de quem faz isso, por essas razões uma dúvida sobre Nomes usados nos Dados de Demonstração não tem como ter qualquer relação com um problema do tipo/categoria BUG já que isso nem aparece no Ambiente de Produção.

**Comment by marcelsavegnago** [comment]
> Com todo respeito, considerar o Nome de um Dado de Demonstração um BUG é um equivoco bem grande, é fundamental que alguém que queira trabalhar com qualquer área de T.I. ou mesmo de engenharia em geral se preocupe a no minimo buscar identificar o tipo/categoria de problema encontrado, principalmente quando se trata de algo que não entende ou domina. Um BUG é um erro em uma funcionalidade ou um método especifico que já está na "branch" principal e que está causando erros em Ambientes de Produção, possui uma prioridade bem maior de atenção e foco na solução e isso pode incluir soluções temporárias/gambiarras/hotfix/patchs para "estancar o problema" e não ter o erro, importante dizer que é algo que faz os principais desenvolvedores pararem o que estiverem fazendo para buscar resolver isso o mais breve possível, usar isso de forma indiscriminada soa como um "Falso Alarme" é como dizer que "Tem um incêndio em algum lugar" e quando a equipe responsável chega não encontra nada, isso com o tempo acaba tirando a credibilidade de quem faz isso, por essas razões uma dúvida sobre Nomes usados nos Dados de Demonstração não tem como ter qualquer relação com um problema do tipo/categoria BUG já que isso nem aparece no Ambiente de Produção.

Concordo com tudo o que disse e assino embaixo. Por ora, estou tentando de alguma forma disciplinar a abertura de issues. 

A abertura de issues é algo extremamente importante mas não deve ser utilizado a esmo.

Segue abaixo um exemplo de uma issue que pra mim não tem sentido algum ter sido registrado no projeto da localização.
https://github.com/OCA/l10n-brazil/issues/1740
Obs. se eu estiver errado por favor me avise :)
