### ISSUE TITLE
[Q&A] - Formatação de texto nos contratos

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1740]
![Screenshot from 2021-12-06 12-41-15](https://user-images.githubusercontent.com/38361760/144876435-5ee1c58b-9aed-47e3-bb5e-d9c162709326.png)
** Descreva sua dúvida **
Pessoal, ao verificar o módulo de contratos surgiu esta dúvida. Os equipamentos , ordens de seriço e outros smartbuttons ficam com o texto sobre escrito dentro da DIV HTML

Para eu fazer a correção disto devo fazer na l10n-brazil ou devo submeter para o OCA/contract.

Além disso, é uma boa prática inserir somente um <br></br> no html para esta correção ou devo ter outra abordagem?

**Comment by marcelsavegnago** [comment]
> Para eu fazer a correção disto devo fazer na l10n-brazil ou devo submeter para o OCA/contract.

Bom.. acho que está fácil entender. O problema tem origem onde? Em algum módulo da localização ou algum módulo de contratos? 

Enfim, com base nesta origem vc determina onde deve ser feito o trabalho %-)

**Comment by marcelsavegnago** [comment]
De qualquer forma estou finalizando esta Issue porque não vejo relação alguma com a localização. Caso eu esteja errado pode reabrir.

**Comment by marcos-mendez** [comment]
Ok, ja fechei então @marcelsavegnago 

Cara pra mim é dificil saber de onde vem o erro porque eu só identifico ele na Interface.

Quando vou adicionar o html pela inspeção do console do navegador por se um tag do tipo <span> ele não permite adicionar quebra de linha no html. 

Realmente não sei aonde facer esta modificação

**Comment by marcelsavegnago** [comment]
@marcos-mendez bom.. ai vai depender de analise feita com um pouquinho de paciência e sem afobar :D 

Chegou testar no runbot do projeto contrato ? Isso ai pode ser várias coisas inclusive até o seu template mas não vejo nenhuma relação com a localização (para isso basta olhar o código do módulo de localização do contrato e ver se tem alguma alteração sendo feita nesta seção.. pelo que lembro não)

**Comment by marcelsavegnago** [comment]
Estas são as views que foram localizadas no módulo l10n_br_contract

- https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_contract/views/contract_view.xml
- https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_contract/views/contract_line.xml
- https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_contract/views/res_company.xml

**Comment by marcos-mendez** [comment]
![Screenshot from 2021-12-06 13-23-48](https://user-images.githubusercontent.com/38361760/144883222-27b44e68-e25d-4199-b5a2-be9fcae75d40.png)
@marcelsavegnago eu verifiquei no RunBot e efetivamente acontece a mesma coisa.

Informação util, isto acredito que só aconteça no portugues pois as palavras são mais longas do que em ingles (ticket / equipment)

Acontece mesmo sem template, apesar de que ao envés de dar uma quebra de linha o Odoo deixa 3 pontinhos ... quando não consegue acabar a palavra, fica bonitinho tmb, mas tem que saber o que que é o que. 

![Screenshot from 2021-12-06 13-20-58](https://user-images.githubusercontent.com/38361760/144882969-352198a9-5a62-4b40-8782-f1465ec55ecb.png)

Efetivamente agora acredito que seja do oca/contract e não do l10n_br_contract porque aconteceu no runbot do field-service_agreement ok?

No caso eu tenho que mexer na views é isso?

**Comment by marcelsavegnago** [comment]
@marcos-mendez provavelmente tem que submter alguma alteração para o projeto de contratos.. Mas sinceramente não sei te falar. Se considerar válido, submete uma issue lah em OCA/contract.

Mas a única coisa que me parece certo analisando o módulo l10n_br_hr_contract é que esta questão não faz parte do escopo da localização.
