### ISSUE TITLE
[14.0][BUG] Problema no CRM depois de instalado o l10n_br_base

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1744]
**Descreva o bug**
Problema ao abrir um lead no CRM depois de instalado o módulo l10n_br_base

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Crie uma nova instancia com dados demo
2. Instale o módulo CRM
3. Instale o módulo l10n_br_base
2. Acesse o módulo CRM
2. Clique em uma oportunidade que aparece no dashboard
3. Veja o erro

**Erro**
```
Traceback (most recent call last):
  File "/Users/marcelsavegnago/Projetos/odoo/odoo-lab-14/odoo/src/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/marcelsavegnago/Projetos/odoo/odoo-lab-14/odoo/src/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'street_name' on model 'crm.lead'
```

OBs. É possível simular isso no runbot da localização.

**Comment by antoniospneto** [comment]
@marcelsavegnago acho que é por causa que o módulo l10n_br_crm ainda não foi migrado, acho que esses campos tão declarado lá

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago acho que é por causa que o módulo l10n_br_crm ainda não foi migrado, acho que esses campos tão declarado lá

Então, este campo street_name quem implementa no res.partner é o modulo base_address_extended https://github.com/odoo/odoo/blob/e24b039ea120597ff5438deca3c69c7a1d54cd31/addons/base_address_extended/models/res_partner.py#L13

Na 12.0 o módulo l10n_br_crm implementa no modelo crm.lead apenas o street_number.
https://github.com/OCA/l10n-brazil/blob/0bf1c72dedc713fb376d7b713f601974955cd651/l10n_br_crm/models/crm_lead.py#L45

Mas ok.. eu também imagino que possa ser por conta da localização do CRM mas tenho um pouco de dúvida se a instalação do l10n_br_base deveria afetar o funcionamento do CRM nativo desta forma.

**Comment by marcelsavegnago** [comment]
Resolvido com a migração do módulo l10n_br_crm
https://github.com/OCA/l10n-brazil/pull/1746
