### ISSUE TITLE
[12.0][14.0][RFC] l10n_br_crm: Corrigir arquivo CONTRIBUTORS.rst

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1761]
https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_crm/readme/CONTRIBUTORS.rst
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_crm/readme/CONTRIBUTORS.rst

**Comment by rvalyi** [comment]
Ok, tb 2 consideraçoes: eu acho melhor colocar dessa maneira quando for mexer nisso (agrupando por empresa qdo tiver): https://github.com/OCA/dms/tree/14.0/dms#contributors
Outra coisa, no caso do seu port do CRM, realmente vc fez uma contribuição significativa para a gente mencionar sim no caso (e é bom que os autores e mantainedores dos modulos decidem a forma como querem dar biscoito ou nao para as contribuiçao, pelo menos é melhor do que querer decidir no trabalho dos outros. No caso do l10n_br_crm foi a gente).
