### ISSUE TITLE
[12.0]CNAB_RETURN_LOG

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#1782]
** Descreva o bug **
Não é possível inserir nenhum dados no MENU CNAB_RETURN_LOG

![Screenshot from 2022-01-18 16-26-29](https://user-images.githubusercontent.com/38361760/150005067-253189af-2aed-44de-aa81-e786685b96cd.png)

Ao mesmo tempo me surge uma dúvida se: É aqui que é colocado o arquivo de retorno do banco?

Estou fazendo algo errado?

Testado em LXC e no RUNBOT

**Comment by antoniospneto** [comment]
@marcos-mendez 

Essa tela você deve utilizar para apenas visualizar os retornos, não utilize a função create.

A importação do arquivo de retorno deve ser pelo caminho Pagamentos -> Import Batch File

**Comment by marcos-mendez** [comment]
@netosjb Obrigado pela breve resposta.

Neste caso tenho um problema. Sómente posso importar CSV, XLS e XLSX. 

No caso do bradesco o arquivo tipo texto termina com .RET 

Qual seria o procedimento neste caso?

**Comment by marcos-mendez** [comment]
![Screenshot from 2022-01-18 16-37-57](https://user-images.githubusercontent.com/38361760/150006850-311563a6-588f-4c54-a449-a4a87ae87775.png)

Anexo aqui um PRINT @netosjb

**Comment by antoniospneto** [comment]
@marcos-mendez 

Na configuração do Diário correspondente ao banco em questão, você deve fazer a configuração dos campos relativos ao retorno.

Faça o seguinte no diário:

Na aba configurações avançadas, marque a opção **Journal used for import** após isso uma nova aba será exibida "Import Related Infos" nessa aba você deve configurar de acordo com sua implementação do banco.

Depois tente novamente fazer a importação do retorno

**Comment by marcos-mendez** [comment]
@netosjb acho que agora foi, Muítissimo obrigado pelas instruções.
