### ISSUE TITLE
[14.0][RFC] Melhorar o suporte a busca de CEP pelos provedores ViaCEP, APICEP

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#1783]
Cenário Atual
-------------
Hoje o módulo l10n_br_zip que implementa a consulta de endereços pelo número de CEP utiliza a biblioteca python pycep-correios que na versão 5.0.0 implementou além da consulta de endereços dos Correios também implementa outros dois provedores [ViaCEP](https://viacep.com.br/), [APICEP](https://apicep.com/api-de-consulta/). Por padrão o módulo l10n_br_zip utiliza a busca dos Correios e os testes de busca de CEP são baseados no resultado do web service dos Correios, como comentado no PR https://github.com/OCA/l10n-brazil/pull/1774/files#r786104923 o resultado do retorno das buscas de cada provedor pode ser levemente diferentes 

Descrição das Mudanças Necessárias
--------------------------------------

Para melhorar o suporte de busca de CEP dos provedores [ViaCEP](https://viacep.com.br/), [APICEP](https://apicep.com/api-de-consulta/) deve ser implementado as seguintes mudanças no módulo l10n_br_zip:

* Tratar os resultados da busca de CEP desses provedores principalmente de CEPs específicos de endereços que possuem o número do logradouro;
* Implementar testes no módulo para a busca de CEPs dos novos provedores.

**Comment by mbcosta** [comment]
@renatonlima a biblioteca foi renomeada para BrazilCEP https://pypi.org/project/pycep-correios/ https://pypi.org/project/brazilcep/, fiz a alteração na v16 https://github.com/OCA/l10n-brazil/pull/2572 , procurei tratar a questão dos retornos que tem "Nome Logradouro, Número" no commit https://github.com/OCA/l10n-brazil/pull/2572/commits/102a3dc3703f7e2c5261773ee5885511934d65eb
