### ISSUE TITLE
[12.0][REM] Associar um Produto Taxa a um Modo de Pagamento é ilegal no Brasil

### ISSUE THREAD

**Issue by mbcosta** [OCA/l10n-brazil#1793]
Conforme relatado no PR de migração do modulo l10n_br_account_payment_order https://github.com/OCA/l10n-brazil/pull/1792 pelo @felipemotter associar um "Produto Taxa" a um Modo de Pagamento é ilegal no Brasil referencia "link" https://raphaelgfaria.jusbrasil.com.br/artigos/848816195/taxa-de-emissao-de-boleto-e-ilegal#:~:text=Da%20simples%20leitura%20dos%20artigos,39 

![image](https://user-images.githubusercontent.com/6341149/151668163-74ac33df-9768-42ca-b33c-49734802bf87.png)

![image](https://user-images.githubusercontent.com/6341149/151668296-765f3bf0-10ea-4f76-bcef-415b5aa1b7ca.png)

Pelo o que está escrito isso é ilegal desde 2008, eu acredito que todos os PSC irão concordar que dentro dos repositórios da OCA  existe um senso de Responsabilidade e qualquer código que possa facilitar práticas ilegais não deve ser incluído no repositório, isso na minha opinião tem a mesma importância de um BUG ou problema de Consistência de Dados.

Eu não tinha conhecimento sobre esse problema legal, o código foi extraído de outro repositório e não tive esse caso de uso nas implementações que fiz.

@mileo como a KMEE participou da construção dessa implementação gostaria de um retorno de vocês sobre esse assunto ou se essa implementação do "Produto Taxa" teria um uso diferente do que está sendo apontado como sendo ilegal no Brasil ou se vocês também não usam isso.

Aguardo um retorno dos PSC o mais breve possível porque pelo o que entendi até agora isso é ilegal e por isso pretendo remover o código o mais breve possível.

E se alguém souber de outro caso onde o código esteja permitindo a pratica de crimes previstos em lei por favor reportem que acredito que será tratado de forma séria por todos desenvolvedores do projeto.

cc @renatonlima @rvalyi @marcelsavegnago @netosjb

**Comment by felipemotter** [comment]
Como falei na PR #1792 eu preferiria retirar, além de ilegal a utilização pode dificulta manter o fundamental do módulo .

**Comment by antoniospneto** [comment]
Concordo com a remoção, acho que é importante manter o módulo com um escopo bem definido, fica mais fácil de manter.

**Comment by mbcosta** [comment]
Obrigado a todos pelo retorno, a remoção foi feita na v12
