### ISSUE TITLE
Exportação em TXT

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#18]
Fui criar um reembolso de fornecedor manualmente me deparei com um erro ao importar no emissor de SP:

Rejeitado: Linha 15: O registro "N10d" não pode vir após um registro "N02"

Sendo que a CST é 00 não deveria entrar no trecho de exportação da CST 400 e 900. 

Erro causado pela maneira que se esta comparando o string.

> > > icms_cst = '00'
> > > icms_cst in ('400')
> > > True

**Comment by Daniel-Furcht** [comment]
Verifique o meu Pull Request, que adiciona outros CSOSNs, lá encontrara os comentarios deste problema, já apontados pelo Sr. Renato. No post do Sr. Raphael, encontrara a explicação.
Se puderes testar meu Pull Request e comentar sua experiencia, agradeço.

**Comment by mileo** [comment]
Definitivamente o uso de uma tupla funciona.

icms_cst = '00'
if icms_cst in ('00',):
    print "CST 00"
if icms_cst in ('20',):
    print "cst 20"
if icms_cst in ('10',):
    print "cst 10"
if icms_cst in ('40', '50'):
    print "cst 40 e 50" 
if icms_cst in ('41',):
    print "cst 41"
if icms_cst in ('51',):
    print "cst 54"
if icms_cst in ('60',):
    print "cst 60"
if icms_cst in ('70',):
    print "cst 70"
if icms_cst in ('90',):
    print "cst 90" 
if icms_cst in ('101',):
    print "cst 101" 
if icms_cst in ('900',):
    print "cst 900"
if icms_cst in ('400'):
    print "cst 400"

> > > CST 00
> > > cst 400

**Comment by Daniel-Furcht** [comment]
Isso, é uma mudança pequena no código, mas surte o efeito esperado..
Em breve estarei postando o restante das CSOSNs para uso em empresas do Simples Nacional.

**Comment by Daniel-Furcht** [comment]
Corrigido no último commit ;).
