### ISSUE TITLE
[BUG] Problemas relacionados ao Fiscal Dummy.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#1813]
Conforme já  discutido no telegram da localização, hoje o módulo l10n_br_account apresenta problemas de desempenho, que dependendo o uso pode crescer de forma exponencial, esses problemas estão relacionado ao documento fiscal dummy.

O fiscal dummy tem como proposito preencher os dados fiscais de uma invoice não fiscal, caso não fosse utilizado o dummy, os dados da invoice seriam replicados no modelo fiscal_document e no fiscal_document_line, sujando e aumentando os dados no banco de dados sem necessidade. 

Essa foi a maneira encontrada para evitar a duplicação de dados e deixar a ORM do Odoo feliz.

O problema: A ORM do Odoo não está lidando bem com isso, temos alguns problemas que já foram identificados:

1) Bug na duplicação da invoice, conforme relatado por @marcelsavegnago #1805.
As linhas associadas ao documento fiscal dummy duplicam a cada vez que uma invoice ( não fiscal ) for copiada. crescendo de forma exponencial. porém esse problema pode ser solucionado conforme proposto na pr.

2) Ao salvar um invoice, todas as invoices que também estão associados ao fiscal_dummy tem os seus computes chamados.
Diferente do bug 1, não cresce de forma exponencial, porém se torna um problema grave quando você tem um número muito grande de invoice não fiscal emitidas. ainda mais em conjunto com o bug 1. Esse problema foi reportado inicialmente pelo @rvalyi e @renatonlima. Eu pude confirmar e é exatamente isso que está acontecendo. Esse problema pode ser mais difícil de ser resolvido devido a limitação da ORM do Odoo ( assim como qualquer ORM apesar dos grandes benefícios, sempre tem as limitações).

3) Fiscal dummy no ambiente multi-company, não é um problema de desempenho, mas vou deixar relatado aqui por estar associado ao mesmo assunto #1804. 

Conforme relatado por @rvalyi não vale a pena corrigir o bug 1 o e o bug 3 se não tiver uma solução para o bug 2.

Então estou abrindo essa Issue para deixar aqui registrado os problemas e discutir a solução, por favor me corrijam caso eu tenho falado alguma besteira.

@OCA/local-brazil-maintainers

**Comment by antoniospneto** [comment]
Sobre o bug 2, é nesse exato momento que o bug acontece, depois que é invocado o método create da invoice, o framework Odoo chama o método recompute, dentro do método a lista de records passa a ser todas as invoices associadas ao dummy.

![image](https://user-images.githubusercontent.com/634278/154849899-206fe231-1594-4a74-a905-1b589a6891cc.png)

**Comment by marcelsavegnago** [comment]
Não sei não mas acho que o caminho será deixar os documentos não fiscais seguirem o fluxo dos documentos com tipo de documento fiscal. Não sei se diria que o ORM está errado.

**Comment by rvalyi** [comment]
tentativa de fix pro bug 2) que é aquele que condiciona um pouco o restante dos fixes https://github.com/OCA/l10n-brazil/pull/1816

**Comment by rvalyi** [comment]
na vdd foi preciso desse tb para resolver https://github.com/OCA/l10n-brazil/pull/1804
