### ISSUE TITLE
[Q&A]

### ISSUE THREAD

**Issue by Gerson-Ceccon** [OCA/l10n-brazil#1820]
Boa noite pessoal, estou a muitos dias tentando intalar a localizacao brasileira no Odoo12/Ubuntu 18.04, ate consegui fazer com que os modulos aprecam na lista de Apps porem, ao tentar instalar o modulo l10n_br_nfe o mesmo reclama que esta faltando o erpbrasil.edoc.pdf, mas este esta instalado, consigo ver atraves do comando "pip list" outras dependencias tambem estao atendidas, favor ver anexadas as imagens

![image](https://user-images.githubusercontent.com/56683035/156252748-cc2e7a08-b8db-4b12-80b6-6e7effb1b6af.png)

imagem do pip list
![image](https://user-images.githubusercontent.com/56683035/156253078-d397acbc-af09-4f31-8ad2-b4ad975a7223.png)

O que poderia estar errado?

Gostaria de sugerir um tutorial de como instalar a localizacao brasileira nas versoes do Odoo, e muito dificil achar estas informacoes

Obrigado

Desculpem se estou no forum errado

**Comment by marcelsavegnago** [comment]
Bom dia.

Vc instalou os módulos pelo arquivo requirements.txt existente na pasta l10n-brazil ? Se sim, instalou em um ambiente Python virtual ? Se sim, ao rodar o Odoo vc está com o ambiente virtual do python ativo ?

**Comment by Gerson-Ceccon** [comment]
Bom dia Marcel,
Após baixar o odoo 12 e localização brasileira (neste último há uma dúvida
de qual  melhor versão para instalar), instalei as dependências via
requirement.txt, não está em ambiente virtual. Tudo do erpbrasil incluindo
o erpbrasil.edoc.pdf instalei via comando pip install, pois via
requirement.txt não instalou.

Obrigado

**Comment by marcelsavegnago** [comment]
Por ora o que vi de estranho é a versão da lib erpbrasil.edoc.pdf. No arquivo requirements.txt a versão indicada é a 1.0.1 e no teu ambiente está a 0.2.0

**Comment by Gerson-Ceccon** [comment]
Tentei com a 0.2.0 e 1.0.2, nenhuma delas funcionou, aparecem na lista de
módulos instalados mas Odoo não reconheceu nenhuma delas
Será que tenho de mudar para 1.0.1?

Obrigado

**Comment by Gerson-Ceccon** [comment]
Boa noite tentei com a versao erpbrasil.edoc.pdf (1.0.1) e funcionou, n'ao
sei o que mudou
Obrigado Marcel
