### ISSUE TITLE
Addons version numbers not compliant

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-brazil#183]
I noticed the addon version numbers in this repo are not compliant with OCA rules.

You should change them from 8.0 to 8.0.1.0.0.

**Comment by danimaribeiro** [comment]
I see you changed from 8.0 to 8.0.0.
Should we still change to 8.0.1.0.0?

**Comment by rvalyi** [comment]
@danimaribeiro yes we should. It has been renumbered as 8.0.0 because so did the script but the OCA version numbers have 5 digits now indeed.
