### ISSUE TITLE
[BUG][12.0][l10n_br_account_payment_brcobranca] Data da Ocorrência errada.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#1839]
No processamento do arquivo de retorno da cobrança bancária, do módulo BRCobrança,  a data da ocorrência está ficando errada, atualmente está sendo registrado a data atual no momento que é feito o processamento do arquivo no Odoo, o correto é pegar a data de ocorrência de dentro do arquivo. 

No exemplo a baixo, estou dando a entrada do arquivo no Odoo hoje (21/03) mas o arquivo de retorno é do dia 18/03.
O correto é registrar as ocorrências como dia 18 e não dia 21.

![image](https://user-images.githubusercontent.com/634278/159265871-58ab21e1-00ac-4501-b57d-11bac7f8528d.png)

**Comment by marcelsavegnago** [comment]
ping @mbcosta

**Comment by mbcosta** [comment]
ola @netosjb @marcelsavegnago a atribuição está ocorrendo aqui https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py#L194 mas acredito que o problema é a o IF 

![image](https://user-images.githubusercontent.com/6341149/159301519-1c1728c7-310e-40cf-8506-ec824f80131b.png)

Uma possível solução:
```
if linha_cnab.get("data_ocorrencia"):
    
     data_ocorrencia = datetime.datetime.strptime(
                        str(linha_cnab["data_ocorrencia"]), "%d%m%y"
                    ).date()
```

OBS.: é preciso confirmar se os Bancos estão usando um formato padrão na Data "%d%m%y" ou se muda, para tratar as diferenças

Infelizmente existe o problema da falta de padrão entre os CNAB, por exemplo no Unicred não tem um campo especifico para essa Data mas no Itau tem, na mesma posição no Unicred é a Data Liquidação ( deveríamos considerar essa mesma data como sendo a Data da Ocorrência? Parece que sim nesse caso ). 

Recentemente houve uma atualização do BRCobranca e umas das coisas que eu penso que podemos propor lá é a padronização do JSON do arquivo de retorno com os campos e a formatação esperada para evitar tratar esses erros no nível da localização, como nesse caso onde todos JSON deveriam retornar esse campo data_ocorrencia em um mesmo formato.

**Comment by antoniospneto** [comment]
Resolvido com o merge da #1881 
Obrigado @mbcosta ;)
