### ISSUE TITLE
Improvements to 9.0

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/l10n-brazil#186]
1. Try to keep the place where tax computation is done in just one place. I don't think is necessary to override here in l10n_br_account.
   https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account/models/account.py#L38
2. I think we can use just one of those two fields:
   "Included in Price" and "Discount this Tax in Price", maybe remove the one created by the localization.
3. Taxes like "PIS", "COFINS", "IPI" could be calculated within the core (not sure yet).
   "ICMS" - the problematic one, this probably will remain here: 
   https://github.com/odoo-brazil/l10n-brazil/blob/8.0/l10n_br_account_product/account.py#L164
4. Add calculation of taxes for services, there are some code here:
   https://github.com/kmee/l10n-brazil/commits/feature/withholding
   The rules for those retentions are very strange.

To be continued.

**Comment by rvalyi** [comment]
@danimaribeiro also the tax computation can probably be made more object oriented with tax classes and subclasses. I think we should 1st get green and merge, but after that we would happily accept such refactor.

**Comment by danimaribeiro** [comment]
Those refactor will ne necessary to make it work with the account.

**Comment by rvalyi** [comment]
@danimaribeiro when I said merge 1st, I mean for 8.0. But for 9,0 you are absolutely right indeed.

**Comment by rvalyi** [comment]
@danimaribeiro I know it has been like 2 weeks, but @renatonlima told me we would manage to get the tests in before monday. Not his fault he is working like mad since months, taking care of many things I was doing before... But once we have theses tests, refactoring will become much safer.

**Comment by mileo** [comment]
As i say yesterday to @danimaribeiro in gitter, this is the correct approach. 

In 9.0 we realy need to think about what methods must been overrited or not. Try to do things easily is the 9.0 challange for l10n_br and a planned roadmap to use the new concepts!
