### ISSUE TITLE
[12.0][BUG] l10n_br_purchase_stock: nao permite gerar a fatura quando o produto é do tipo serviço

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1861]
**Descreva o bug**
Aparentemente quando configurado na empresa que a geração de faturas é baseada no picking, o módulo aplica a mesma regra quando o produto é do tipo serviço.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Configure a empresa para que o faturamento de compras seja baseado no picking
2. Gere um pedido de compra com produto do tipo serviço
3. Confirme o pedido de venda
4. Veja que não foi habilitado o botão gerar fatura.

**Comment by antoniospneto** [comment]
@marcelsavegnago 

Se você alterar a politica de faturamento direto dentro do cadastro do produto em questão não resolve ? 
![image](https://user-images.githubusercontent.com/634278/165838919-e706fd0e-b5b9-490c-b1f6-928e760ace22.png)

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago
> 
> Se você alterar a politica de faturamento direto dentro do cadastro do produto em questão não resolve ? ![image](https://user-images.githubusercontent.com/634278/165838919-e706fd0e-b5b9-490c-b1f6-928e760ace22.png)

Acho que eu havia configurado isso já. Mas testo novamente.

**Comment by rvalyi** [comment]
@marcelsavegnago se puder confirmar se o problema ainda existe...

**Comment by antoniospneto** [comment]
@marcelsavegnago verificar se a PR #2711 resolve esse problema.
