### ISSUE TITLE
[Q&A]Mudança do status do documento fiscal de notas de entrada (emitidas por parceiros)

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1874]
Pessoal,

Sobre as notas fiscais de compra tenho algumas dúvidas.

- Tem algum local para persistir o xml/pdf enviado pelo parceiro?
- Qual seria a estratégia para mudar o status de em_digitação para autorizado ou algo do genero quando a nota fiscal é emitida pelo parceiro?
- Na rotina de fechamento alguém já exporta os documentos das notas fiscais de entrada emitida pelos parceiros ?

ping @renatonlima @rvalyi @mileo

**Comment by marcos-mendez** [comment]
O Marcel, antigamente era feito pela chave da NFE e não pelo PDF. No caso
da kimenz na v11 o campo seria este aqui

FATURAS > COMPRAS > FATURAS DE FORNECEDOR

[image: Screenshot from 2022-04-14 08-44-54.png]

Em qua., 13 de abr. de 2022 às 23:49, Marcel Savegnago <
***@***.***> escreveu:
