### ISSUE TITLE
[Q&A] Falhas constantes nos testes de comunicação com o Banco Central

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1877]
Recentemente as falhas de comunicação com o Banco Central parecem ter se tornado mais constantes. Por ora tenho reiniciado os testes do travis nas PRs quando ocorre a falha.

**Comment by rvalyi** [comment]
Eu posso estar errado, mas vi que isso acontecia mais bem de noite, talvez uma hora que eles costumam fazer alguma manutenção. Até agora acontecia de forma razoável para rê iniciar qdo dava pau, tipo umas 2 no mês no máximo. Agora se for realmente mais frequente da para botar um mock no teste.

**Comment by marcelsavegnago** [comment]
Vamos monitorando.

**Comment by rvalyi** [comment]
pois é realmente piorou...

**Comment by marcelsavegnago** [comment]
> pois é realmente piorou...

Então.
