### ISSUE TITLE
[12.0][BUG] l10n_br_account/l10n_br_fiscalt: Desconto

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1878]
Olá pessoal,

O módulo l10n_br_fiscal implementa em document_fiscal_line_mixin o campo discont_value e o módulo nativo account implementa o campo discount que é percentual. Sendo assim, acredito que esta linha está errada. Ok ?

Campo implementado pelo l10n_br_fiscal
https://github.com/OCA/l10n-brazil/blob/1ec5bb7a89772d33ca18aecfae2cc98a72adcbca/l10n_br_fiscal/models/document_fiscal_line_mixin.py#L180

Campo implementado pelo account
https://github.com/odoo/odoo/blob/0f9b472b68c2db019e7563ebb695f5f69687aa15/addons/account/models/account_invoice.py#L1750

https://github.com/OCA/l10n-brazil/blob/1ec5bb7a89772d33ca18aecfae2cc98a72adcbca/l10n_br_account/models/account_invoice_line.py#L147

cc @renatonlima @rvalyi @netosjb @felipemotter @mileo

**Comment by netosjb** [comment]
@marcelsavegnago acho que o tratamento dessa pr pode não estar correto.
O Odoo já tem por padrão o field **discount** que é pela porcentagem (%)
Na localização foi criado um outro campo chamado **discount_value** que eu acho que a intenção é guardar o valor bruto do desconto em valores mesmo não em %.
se fizer essa alteração eu acho que vai bugar o cálculo dos impostos e dos totais na nota fiscal

Veja essa parte do código que está na localização:
https://github.com/OCA/l10n-brazil/blob/e0c9e7cb7db259c8206acacccdc72c7fd9de4f77/l10n_br_repair/models/fiscal_line_mixin.py#L108-L111

se você informar a % do desconto no campo  **discount** o **discount_value** será calculado também.

**Comment by rvalyi** [comment]
foi resolvido na 14 6 meses atras.
