### ISSUE TITLE
[12][BUG][payment_pagseguro] Problema ao criar a charge sem o soft_descriptor

### ISSUE THREAD

**Issue by daniloferreira** [OCA/l10n-brazil#1884]
Ao testar o módulo payment_pagseguro utilizando o sandbox do Pagseguro acontece um badrequest

Etapas para reproduzir o comportamento:
1.Realizar as configurações como descrito no readme do módulo
2. Preencher as informações do cartão e clicar em 'Pagar'
Então acontece este erro
![image](https://user-images.githubusercontent.com/1631858/164354387-dec87199-4382-4f3d-aa79-bd737bc34102.png)
E na aplicação mostra que houve o badrequest:
```
2022-04-21 01:28:41,509 77274 INFO ***** odoo.addons.payment_pagseguro.models.payment_transaction: _create_pagseguro_charge: Values received:
{'error_messages': [{'code': '40002',
                     'description': 'must not be empty',
                     'message': 'invalid_parameter',
                     'parameter_name': 'soft_descriptor'}]} 
```
                     
**Comportamento esperado**
Olhando o código de fato não é passado este campo:
https://github.com/OCA/l10n-brazil/blob/1ec5bb7a89772d33ca18aecfae2cc98a72adcbca/payment_pagseguro/models/payment_transaction.py#L239-L247

Incluindo o campo soft_descritor a  integração funcionou normalmente
```
"payment_method": {
                "soft_descriptor": self.sale_order_ids.company_id.name,
                "type": "CREDIT_CARD",
                "installments": 1,
                "capture": False,
                "card": {
                    "encrypted": self.payment_token_id.pagseguro_card_token,
                },
            },
```

Não seria o caso de sempre passar este campo, como nos exemplos da própria documentação do pagseguro?
![image](https://user-images.githubusercontent.com/1631858/164357017-2e2598f1-6eec-4f66-85f7-e04f2c35199a.png)

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/1885
