### ISSUE TITLE
[Q&A] Contas de compensação fora do ativo/passivo

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#1905]
Hoje na localizaçao, tanto os account.account.type no l10n_br_coa e o plano de contas l10n_br_coa_generic estão considerando as contas de compensação dentro do balanço.

Cheguei a propor a PR #1903 , mas no odoo hoje não é permitido colocar contas reconciliáveis com types off-balance, então apesar de achar mais correto, ficaria incompatível com os planos de contas da localização na forma que estão hoje.

Não sei opinar se a reconciliação é necessária ou não, por isso por hora acabei fechando a PR. Mas talvez uma discussão seja valida.

PS: acredito que até os próprios planos de contas talvez seriam plauzíveis de alteração, para que as contas de compensação fiquem fora das contas de ativo/passivo. Mas acredito que dentro do contexto atual, existem coisas mais importantes.

**Comment by Bmessiazy** [comment]
Oi Felipe Motter
Minha visão e experiência de trabalhos já auditados pelas big 4 de Auditoria. (PWC, EY, KPMG, Deloitte)Contas de Compensação devem ser Off Balances.
Aparecem no balancete para conciliação, mas não no Balanço, diretamente.Eh um grupo de contas auxiliares, conforme meu PR.Elas apoiam as Notas Explicativas na públicacao do balanço anual para as empresas obrigadas.
Abraço.
Enviado do Yahoo Mail no Android 
 
  Em qua., 11 11e mai. 11e 2022 às 2:15, ***@***.***> escreveu:   


Hoje na localizaçao, tanto os account.account.type no l10n_br_coa e o plano de contas l10n_br_coa_generic estão considerando as contas de compensação dentro do balanço.

Cheguei a propor a PR #1903 , mas no odoo hoje não é permitido colocar contas reconciliáveis com types off-balance, então apesar de achar mais correto, ficaria incompatível com os planos de contas da localização na forma que estão hoje.

Não sei opinar se a reconciliação é necessária ou não, por isso por hora acabei fechando a PR. Mas talvez uma discussão seja valida.

PS: acredito que até os próprios planos de contas talvez seriam plauzíveis de alteração, para que as contas de compensação fiquem fora das contas de ativo/passivo. Mas acredito que dentro do contexto atual, existem coisas mais importantes.

**Comment by douglascstd** [comment]
Olá @felipemotter tudo bem?

Entendo a necessidade da reconciliação como forma de extrair o saldo de uma linha de um lançamento de diário, assim é possível controlar o lançamento inicial e verificar se foi totalmente "abatido".

Existe alguma explicação porque não pode usar reconciliação nestas contas?

Encontrei na v14 na view do cadastro de account.account:
![image](https://user-images.githubusercontent.com/20867090/168388794-b3eb8f81-c92f-4c83-a3c3-9a301b01f68e.png)

A restrição que entendo que as contrapartidas devem ser SEMPRE entre as contas de compensação. E como o @Bmessiazy deve estar fora do balanço patrimonial.

Acho válido sim aprofundar neste assunto. Felipe, gostaria de ajudar neste assunto.

**Comment by antoniospneto** [comment]
@douglascstd  não entendo o por que, mas parece que é uma limitação imposta pelo odoo:
existe uma constrain proibindo isso:
```
            if record.internal_group == 'off_balance':
                if record.reconcile:
                    raise UserError(_('An Off-Balance account can not be reconcilable'))
```
fonte:
https://github.com/odoo/odoo/blob/39dcee1cc1ef1ed4c4a85494b689f4f604e32de6/addons/account/models/account_account.py#L98

**Comment by felipemotter** [comment]
Na verdade, o que não permite reconciliação é o type off-balance. Quando eu fiz a pr para alterar as contas de compensação para o type off-balance estourou um erro que não era permitido contas reconciliaveis com esse tipo. Por isso deu Travis vermelho.


Sobre os plano de contas, eu vi em alguns fóruns contábeis que o mais ideal seria as contas de compensação em um grupo totalmente diferente, fora do ativo e do passivo. Por exemplo, em um plano de contas que vai até o 5, o grupo de compensação deveria ser o 6.  Softwares especiais pra escritórios de contabilidade, como o Domínio, tem a mesma recomendação para criar planos de conta.

**Comment by douglascstd** [comment]
@felipemotter entendi...
parece ser um conceito fechado de que esse tipo de conta não pode ter essa reconciliação:
![image](https://user-images.githubusercontent.com/20867090/168390635-03088eb4-0e5b-43ca-9199-6c497b93dadd.png)

A questão é como o seria possível controlar no Odoo um lançamento em conta de compensação, quando o lançamento de "retorno".

**Comment by douglascstd** [comment]
https://github.com/odoo/odoo/blob/fe379bc22e649c623dfb6ed8aefb106b4846d02e/addons/account/models/account_account.py#L98-L105

**Comment by douglascstd** [comment]
> @douglascstd não entendo o por que, mas parece que é uma limitação imposta pelo odoo: existe uma constrain proibindo isso:
> 
> ```
>             if record.internal_group == 'off_balance':
>                 if record.reconcile:
>                     raise UserError(_('An Off-Balance account can not be reconcilable'))
> ```
> 
> fonte: https://github.com/odoo/odoo/blob/39dcee1cc1ef1ed4c4a85494b689f4f604e32de6/addons/account/models/account_account.py#L98

Isso mesmo Neto.. estava buscando isso agora. :-)

Se a função Reconcile do Odoo ativo não está disponível, aí me questiono: "Qual seria o método que posso usar quando quero fazer esse link entre os lançamentos nas contas Off-Balance?"

Um exemplo disso é o registro de um contrato (off-balance), e mensalmente emito uma fatura (Balance). Neste Caso teria algo como:
No contrato:
C-Compensação Passivo | D-Compensação Ativo (valor total)
Na Fatura:
D-Clientes | C-Receita (valor da fatura)
D-Compensação Passivo | C-Compensação Ativo (Valor da fatura) **** Seria essa reconciliação com o lançamento do Contrato

Pode ser que já exista alguma função que faça esse link. Mas ainda não encontrei.

**Comment by marcelsavegnago** [comment]
> Na verdade, o que não permite reconciliação é o type off-balance. Quando eu fiz a pr para alterar as contas de compensação para o type off-balance estourou um erro que não era permitido contas reconciliaveis com esse tipo. Por isso deu Travis vermelho.
> 
> Sobre os plano de contas, eu vi em alguns fóruns contábeis que o mais ideal seria as contas de compensação em um grupo totalmente diferente, fora do ativo e do passivo. Por exemplo, em um plano de contas que vai até o 5, o grupo de compensação deveria ser o 6. Softwares especiais pra escritórios de contabilidade, como o Domínio, tem a mesma recomendação para criar planos de conta.

https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_coa_complete/data/account.account.template.csv#L456

Não sei se eh bem isso.. mas neste plano consideramos o 6.

Porém, este módulo precisa de uma boa revisão nos parametros de quais contas sao reconciliaveis e inclusive seus tipos.. ta zoado

**Comment by Bmessiazy** [comment]
Oi Felipe,
               Entendi sobre outros grupos, não eh o que já vi, nem a estrutura que julgo ideal, mas se tem essa limitação, usa os grupos 7 e 8.  Em geral os grupos 3,4,5,6 são utilizados para custeio e vendas.o próprio odoo usa o 6 pra vendas.               O importante eh resolver.
               Abraço.
Enviado do Yahoo Mail no Android 
 
  Em sex., 13 13e mai. 13e 2022 às 22:46, Marcel ***@***.***> escreveu:   



Na verdade, o que não permite reconciliação é o type off-balance. Quando eu fiz a pr para alterar as contas de compensação para o type off-balance estourou um erro que não era permitido contas reconciliaveis com esse tipo. Por isso deu Travis vermelho.

Sobre os plano de contas, eu vi em alguns fóruns contábeis que o mais ideal seria as contas de compensação em um grupo totalmente diferente, fora do ativo e do passivo. Por exemplo, em um plano de contas que vai até o 5, o grupo de compensação deveria ser o 6. Softwares especiais pra escritórios de contabilidade, como o Domínio, tem a mesma recomendação para criar planos de conta.


https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_coa_complete/data/account.account.template.csv#L456

Não sei se eh bem isso.. mas neste plano consideramos o 6.

Porém, este módulo precisa de uma boa revisão nos parametros de quais contas sao reconciliaveis e inclusive seus tipos

**Comment by Bmessiazy** [comment]
Felipe,
       Contas de Compensação podem ser conciliaveis, aliás, essa e a característica principal para elas existirem.       Exemplo, quando vc manda remessa pra consertos, eh registrado nelas...e fica .aberto...nas duas pontas.....grupo 1 e grupo 2. Se a conta ficar c saldo, significa que existem bens em poder de terceiro. Logo, a contabilidade tem que cobrar o retorno do bem e da NF, senão a Sefaz vai cobrar imposto como venda. Ok?        Então, sendo ela reconciliavel, quando retornar a remessa, tem que marcar contra a emissão e zerar o saldo.         Leitura, se tem saldo não conciliado, falta devolução, se tem saldo 0,00 tá tudo certo.
        Abraço!

Enviado do Yahoo Mail no Android 
 
  Em sex., 13 13e mai. 13e 2022 às 22:46, Marcel ***@***.***> escreveu:   



Na verdade, o que não permite reconciliação é o type off-balance. Quando eu fiz a pr para alterar as contas de compensação para o type off-balance estourou um erro que não era permitido contas reconciliaveis com esse tipo. Por isso deu Travis vermelho.

Sobre os plano de contas, eu vi em alguns fóruns contábeis que o mais ideal seria as contas de compensação em um grupo totalmente diferente, fora do ativo e do passivo. Por exemplo, em um plano de contas que vai até o 5, o grupo de compensação deveria ser o 6. Softwares especiais pra escritórios de contabilidade, como o Domínio, tem a mesma recomendação para criar planos de conta.


https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_coa_complete/data/account.account.template.csv#L456

Não sei se eh bem isso.. mas neste plano consideramos o 6.

Porém, este módulo precisa de uma boa revisão nos parametros de quais contas sao reconciliaveis e inclusive seus tipos
