### ISSUE TITLE
[14.0][BUG] Atualização do módulo l10n_br_fiscal versão 14.0.2.2.0 > 14.0.4.15.0

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1908]
Entre as versões 14.0.2.2.0 > 14.0.4.15.0 houve a remoção da tabela l10n_br_fiscal.payment e como não tem script de migração da o seguinte erro:

![image](https://user-images.githubusercontent.com/3595132/168497402-4e7b741a-0f51-4bc6-8e2a-eed9e5b6b0a0.png)

Algum tempo atrás eu estava avaliando este assunto para saber como deveria ser o script de migração mas pelo que me lembro acabei não localizando nenhuma referencia. 

@rvalyi se tiver alguma referência e puder me passar eu agradeço.

obs. por ora apaguei o registro na tabela ir.model

**Comment by antoniospneto** [comment]
@marcelsavegnago acho que ninguém pensou que alguém iria querer migrar o banco de dados nessa fase inicial :sweat_smile:

**Comment by marcelsavegnago** [comment]
Sim..... tentei achar algum exemplo script de migração para apagar esta tabela mas não achei.

Como eu ainda não tinha dados nesta tabela eu apaguei da tabela ir.models antes de atualizar
