### ISSUE TITLE
[BUG][l10n_br_account] o PR #1804 criou uma regressão com as restrições de integridade SQL

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#1911]
Nesse PR https://github.com/OCA/l10n-brazil/pull/1804 o @netosjb moveu do pre_init_hook pro post_init_hook o preenchimento das colunas fiscal_document_id e fiscal_document_line_id pelos valores dos registros "dummy" na tabelas account_invoice e account_invoice_line respectivamente.

Bem que eu falei que eu tava com pé atras com isso mas na hora eu deixei a bola passar entre as pernas. O problema disso é que se instalar o modulo account primeiro com registros de invoices (por examplo) de demo, o ORM da erros como:

```
odoo.schema: Table 'account_invoice': unable to set NOT NULL on column 'fiscal_document_id'
odoo.schema: Table 'account_invoice_line': unable to set NOT NULL on column 'fiscal_document_line_id'
```

O erro não é gravissimo mas basicamente o ORM naõ consegue mais instalar a restrição de integridade nas tabelas. Foi exatamente para evitar isso que eu preenchia os valores dos possíveis registros ANTES do ORM tentar inicializar os modelos e restrições do módulo l10n_br_account. Vi isso ao fazer um forward por do PR para a v14 no PR https://github.com/OCA/l10n-brazil/pull/1688

Talvez eu faço um port com esse mesmo problema de inicio e deixo para corrigir depois.

cc @renatonlima @marcelsavegnago @felipemotter

**Comment by rvalyi** [comment]
o problema foi solucionado no https://github.com/OCA/l10n-brazil/pull/1688 voltando a usar o pre_init_hook aqui https://github.com/akretion/l10n-brazil/commit/f9169b20e0d376cac8cdf1c2e2d6e0270975f11f

Poderia ter um backport disso para a 12.0, mas tb como eu falei o problema não é gravissimo. Capaz tb que no segundo update, depois das colunas terem sido preenchidas o ORM conseguir instalar o NOT NULL mesmo que der erro da primeira vez.

**Comment by antoniospneto** [comment]
boa @rvalyi parece que esse caso acabou passando despercebido por mim

**Comment by rvalyi** [comment]
sem problema. tb o impacto nao foi grand não, eu comentei mais para explicar o porque da mudança no PR da 14

**Comment by rvalyi** [comment]
foi solucionado na 14.0 pelo menos então vou fechar.
