### ISSUE TITLE
[14.0][BUG] Ao alterar a inscrição estadual da empresa o sistema apaga o valor do estado

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#1918]
**Descreva o bug**
Ao alterar a inscrição estadual da empresa o sistema apaga o valor do estado

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Cadastro da Empresa
2. Apague a inscrição estadual
3. Salve o registro
4. Veja que o valor do Estado foi apagado

Obs.. E acontece o contrario tbm.. Ao alterar  o estado o sistema apaga o valor da inscrição estadual

**Comment by augustodinizl** [comment]
encontrei o erro aqui: 
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_base/models/res_company.py#:~:text=def%20_inverse_state(,state_tax_number_ids%20%3D%20state_tax_number_ids

nesse primeiro write, ele está sobrescrevendo o id. do estado (ao meu ver)

**Comment by antoniospneto** [comment]
@marcelsavegnago isso foi resolvido no #2033?
