### ISSUE TITLE
[12.0][BUG] Ao criar um documento fiscal esta pulando a sequencia indevidamente

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#1919]
No PR #1819 que implementa a funcionalidade de passar para a próxima numeração caso exista um documento fiscal com a mesma numeração existe um erro na implementação dessa funcionalidade. 

Hoje esta sendo verificado apenas o número do documento fiscal, mas deveria verificar não apenas o número do documento fiscal, mas a série, emitente e empresa porque caso exista um documento fiscal de entrada, ou outro tipo de documento fiscal com a mesma numeração, vai ser pulado indevidamente a numeração do documento fiscal e a sequencia da serie do documento fiscal.

**Comment by rvalyi** [comment]
foi corrigido pelo https://github.com/OCA/l10n-brazil/pull/1819
