### ISSUE TITLE
[14.0][RFC] Ocultar seleção de Tipo de Documento - lançamentos diferentes de invoice

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#1949]
Aparece a seleção de "Tipo de Documento" no lançamento de diário:

![image](https://user-images.githubusercontent.com/20867090/171481885-1978fa39-6367-4f67-94f8-db8267878dee.png)

![image](https://user-images.githubusercontent.com/20867090/171627657-581f86c9-4cad-4342-bd7f-3bd43645acbf.png)

Seria interessante que esse campo fosse ocultado para esse para esses lançamentos.

**Comment by antoniospneto** [comment]
Resolve com o #2036
