### ISSUE TITLE
Nome truncado no arquivo txt ao emitir nf a pessoa física

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#20]
Nome truncado  no arquivo txt ao emitir nf a pessoa física

**Comment by renatonlima** [comment]
Luiz,

Na exportação em txt do OpenERP não existe nenhuma limitação de caracteres, mas o layout na NFe existe uma limitação de 60 caracteres, acredito que ao importar o txt no emissor deve truncar a razão social quando for maior do 60 caracteres. Você chegou a olhar o arquivo txt? ou só a NFe exportada no emissor?

**Comment by Daniel-Furcht** [comment]
Ola.
Neste nome que esta truncado existe algum caracter especial? Tipo um '.' ou ';' ?. No caso de um ponto em um campo, o emissor do Sefaz SP simplesmente trunca o texto...

**Comment by mileo** [comment]
Eu estava acompanhando o cliente ao emitir via acesso remoto uma nota de
devolução para pessoa física e notei o problema.

Pedi o txt para o cliente e realmente o registro E esta desta maneira:

[image: Imagem inline 1]

Me veio na cabeça agora a questao dos contatos.... Vou dar uma olhada
direito amanhã e posto aqui.

Usando 7.0 c / rs-ocb

Abraços

Em 25 de outubro de 2013 14:56, Renato Lima notifications@github.comescreveu:

> Luiz,
> 
> Na exportação em txt do OpenERP não existe nenhuma limitação de
> caracteres, mas o layout na NFe existe uma limitação de 60 caracteres,
> acredito que ao importar o txt no emissor deve truncar a razão social
> quando for maior do 60 caracteres. Você chegou a olhar o arquivo txt? ou só
> a NFe exportada no emissor?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/20#issuecomment-27108428
> .

## 

Luis Felipe Miléo
skype: luisfelipemileo
http://mileo.co http://blog.mileo.co
https://launchpad.net/~mileo
https://github.com/mileo
