### ISSUE TITLE
Valor da duplicata menor do que da fatura

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#200]
Ao criar uma nota fiscal com valores de frete, seguro ou outras despesas diretamente da fatura ou gerada de um picking não é incluído no account.invoice.tax os totais destes campos e a duplicata (contas a receber/pagar) é gerado com o valor errado, segue exemplo:

![image](https://cloud.githubusercontent.com/assets/211005/10729259/474250da-7bcf-11e5-9d6b-7d89a3498749.png)

**Comment by danimaribeiro** [comment]
Testando com o odoo-brazil ou OCA?

**Comment by renatonlima** [comment]
Eu tetei com OCA mas com a Odoo-brasil deve ter o mesmo problema...

2015-10-27 15:37 GMT-02:00 Danimar Ribeiro notifications@github.com:

**Comment by mileo** [comment]
Com a ST tinha um problema parecido.  Da um print nos lançamentos contábeis por favor!

Acho q deve ter algum imposto faltando conta!

**Comment by mileo** [comment]
#225 FIXED

**Comment by renatonlima** [comment]
@mileo I will review PR #225 and close this issue
