### ISSUE TITLE
[BUG] impostos na fatura

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2009]
Pessoal eu acho que o merge da PR #1997 trouxe um problema de volta, se alguém mais puder verificar.

Ao fazer o lançamento de um fatura de venda (55 - NFe) pelo account, com os impostos configurado, ao validar a fatura a mesma é confirmada com os lançamentos contábeis incorretos, 

![image](https://user-images.githubusercontent.com/634278/178357724-baa8c610-d339-4636-836e-bae86ca78fab.png)
![image](https://user-images.githubusercontent.com/634278/178357816-5ad647c2-1e5c-44cf-a3ec-ba137169c654.png)
![image](https://user-images.githubusercontent.com/634278/178357913-6f7d897a-d80f-4964-b005-06d719050002.png)

**Comment by rvalyi** [comment]
Ola @netosjb certeza que vc quis mencionar o PR https://github.com/OCA/l10n-brazil/pull/1999 ele parece muito inofensivo. Não seria algum outro?

**Comment by antoniospneto** [comment]
> Ola @netosjb certeza que vc quis mencionar o PR #1999 ele parece muito inofensivo. Não seria algum outro?

Ops, realmente errei, o correto que eu quero dizer é o #1997.

**Comment by rvalyi** [comment]
cc @renatonlima @marcelsavegnago

**Comment by marcelsavegnago** [comment]
cc @douglascstd @augustodinizl

**Comment by rvalyi** [comment]
Eu acho que ta legal na 14.0 agora. Comentar para re-abrir senão.

**Comment by antoniospneto** [comment]
@rvalyi acho que esse bug dos tax_ids ainda existe , mas não é tão crítico, eles somem mas é apenas na visão, por trás os valores ainda estão lá , podemos deixar fechado , valeu!

**Comment by rvalyi** [comment]
então melhor deixar aberto se ainda existe para não perder, valeu.

**Comment by antoniospneto** [comment]
Vou fechar a issue, se isso voltar a ser um problema a gente reabre
