### ISSUE TITLE
Validação nos campos m2m de impostos

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#201]
Criar validações para não permitir impostos do mesmo domínio na fatura, esta validação deveria ser incluído:
- NCM
- Cadastro de Produtos
- Linha de Pedido de Compras
- Linha de Pedido de Venda
- Linha da Fatura 

![image](https://cloud.githubusercontent.com/assets/211005/10769866/5e0b4316-7ccf-11e5-8745-46bbc4869ae5.png)

**Comment by mileo** [comment]
Importante! Posso fazer daqui umas 2 semanas.

**Comment by mileo** [comment]
@renatonlima não estou conseguindo simular esse comportamento, vc já resolveu?
Ele carrega só a primeira dominio
