### ISSUE TITLE
problema com a tradução no modulo l10n_br_nfe / commits [UPD] Update l10n_br_nfe.pot

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#2035]
temos um numero de commits totalmente maluco do arquivo l10n_br_nfe.pot feito pelo bot [oca-travis](https://github.com/OCA/l10n-brazil/commits?author=oca-travis) tanto nas branches 12.0 e 14.0

Quando olhar os diffs parece que a ordem de alguns campos muda no l10n_br_nfe.pot. Poderia tambem ser a questão de varios campos ter o mesmo label, eu não sei dizer.

Mas temos que resolver e rapidamente senão o numero de commits vai crescer loucamente e isso vai engordar o repo todo para fazer clones e outras operaçoes. Corrigir depois de forma retroativa tambem seria bem bem complicado. Então bora analisar isso...

cc @renatonlima @marcelsavegnago @netosjb @felipemotter @mileo

**Comment by mileo** [comment]
Nós ja tivemos esse problema no passado, foi resolvido antes do primeiro merge da NF-e.

Que até demorou pra acontecer por conta disso.

Foi algo referente a ordem das classes pelo que me lembro.

Da pra procurar nas discussões antigas.

Houve alguma alteração recente no spec driven?

**Comment by rvalyi** [comment]
Eu me lembro que ja rolou esse conversa sim.

ate agora na v14: temos o problema desde o inicio ou seja desde o merge do PR da migração do PR l10n_br_nfe #1974 no 10 de Junho 2022 com 
commits do tipo: l10n_br_nfe.pot desse tip https://github.com/OCA/l10n-brazil/commit/91d0eeb2d4ac4d965e7a7c115109f58fff5a009f

exactamente o mesmo tipo de commit rolando na 12.0 um pouco antes (26 de Maio): https://github.com/OCA/l10n-brazil/commit/fa892fa75187509402ca3b0e86c5ba306da90c83

Porem se a gente olha o historico, na 12.0 la em Março 2022 por examplo não parecia ter esse problema, so ver essa pagina e as paginas um pouco antes e depois: https://github.com/OCA/l10n-brazil/commits/12.0?after=a07dd5487a64dc660ddd352204069c7da2b711f2+679&branch=12.0&qualified_name=refs%2Fheads%2F12.0

Eu ainda nao identifiquei o momento exacto do problema, mas parece ter sido entre Março e Maio 2022 na branch 12.0. Eh importante notar que durante um bom tempo (2020 e 2021) o bot de tradução nao passava porque tivemos que reverter um merge bem zoado (...) e que isso tinha criado um problema de cache git no bot de tradução. Porem o historico permite afirmar que esse problema de commits aleatorios do arquivo l10n_br_nfe.pot é mais recente e não tem a ver com a volta das traduções.

**Comment by rvalyi** [comment]
@mileo aqui no ano passado, vc falava de um problema semalhante https://github.com/OCA/l10n-brazil/pull/1272#issuecomment-821806603
vc falava que talvez era por causa do campos com o mesmo nome me varias classes com vBC.
Porem agora faz um tempão que eu tinha resolvido esse problema com os campos de impostos, principalmente com a filtragem das class ICMS* e ICMSSN* na geração do l10n_br_nfe_spec

O problema que nos temos agora é com 2 campos da NFe apenas:

- nfe40_vOutro
- nfe40_vDesc

Pelo git blame eu pude identificar os ultimos commits afetando esses campos, eles estão bem dentro da faixa de datas que vemos o problema de traduçoes aparecer:

```nfe40_vOutro = fields.Monetary(related="amount_other_value")```
introduzido em May 30 
https://github.com/OCA/l10n-brazil/commit/dbf77f82397492374519cfc3f9db1f15602e9303

```nfe40_vDesc = fields.Monetary(related="amount_discount_value")```
ultima mudança: Apr 15, 2021 
https://github.com/OCA/l10n-brazil/commit/b6e0b822a3a815bff69b77dacc1bffd9a921f584
o related foi de amount_discount para amount_discount_value

EDIT: 
não houve mudança no modulo **spec_model_driven** no periodo da aparição do problema. No **l10n_br_nfe_spec** teve mudança do formato dos digits dos float para compatibilizar com a v14 mas não pode ser a causa do problema.

To be continued...

**Comment by rvalyi** [comment]
fix proposto aqui https://github.com/OCA/l10n-brazil/pull/2037
