### ISSUE TITLE
Não preenchimento da tag <autXML> cnpj.do.contador </autXML>

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2039]
Na transmissão de uma NF-e para a SEFAZ da Bahia , onde é obrigatório o preenchimento da tag <autXML>, a localização não insere tal tag no xml gerado, tal variável se encontra preenchida do cadastro da empresa

## Module
(https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_nfe_spec)

## Describe the bug
Tal variável não é copiada do campo CNPJ do contador configurado na empresa para o campo "nfe40_autXML/nfe40_CNPJ"

## To Reproduce
**Affected versions**:
14.0
1. Preenchimento dos dados cadastrais corretamente (constando o cnpj do contador)
2.emissão do xml
3.verificar no xml gerado a falta da tag <autXML>

**Comment by rvalyi** [comment]
implementado em https://github.com/OCA/l10n-brazil/pull/2040
