### ISSUE TITLE
[14.0] Contract - Fatura emitida do contrato preenche campo "ICMS ou ISSQN" sempre ICMS, mesmo quando serviço.

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2044]
A criação de faturas de serviço geradas a partir do módulo de contrato, tem o campo "ICMS ou ISSQN" com o valor "ICMS", com isso o efeito é que ao alterar qualquer informação na linha da fatura os campos CFOP e NCM, que são obrigatórios, são exigidos. 

Para contornar esse problema é possível apagar a alinha da fatura, e refazer com os mesmos dados, assim o campo "ICMS ou ISSQN" é preenchido corretamente com ISSQN

**Para reproduzir o problema:**
Criação de uma linha de operação fiscal: _Aquisição de Serviços_
![image](https://user-images.githubusercontent.com/20867090/181073450-1689575d-a21d-44e3-921d-352336bdd9e3.png)

Selecionar Tipo _Fiscal de Produto= Serviço_ | _ICMS ou ISSQN = ISSQN_
![image](https://user-images.githubusercontent.com/20867090/181073555-c253e61d-b107-4e98-a0ec-561b8f8fe961.png)

Criar contrato teste, preencher:
1- Selecionar fornecedor
2- Posição _Fiscal = Compras_ | Operação _Fiscal = Compras_
3- Selecionar os campos Operational Line e Operational
4- Selecionar o produto "_[ODOO_DEV] Customized Odoo Development]_"
5- Os campos Operational Line e Operational deverão assumir: Aquisição de Serviço e Compras respectivamente
![image](https://user-images.githubusercontent.com/20867090/181074650-06a087dc-b056-47ee-9769-1aa9ac1d3369.png)

Emitir fatura manualmente:
![image](https://user-images.githubusercontent.com/20867090/181075371-f72f95dd-47f3-41c6-9aa9-1fbcee4e73b6.png)

Abrir a linha da Fatura:
![image](https://user-images.githubusercontent.com/20867090/181073675-ad3d0f96-59ff-48bf-ac9a-905e6c40ac2d.png)

**Comment by marcelsavegnago** [comment]
@douglascstd Vou dar uma olhada agora..

**Comment by marcelsavegnago** [comment]
Pessoal.. to pensando se nao vale a pena deixar o form da linha do contrato igual eh no vendas e compras. Ou seja, incluir a página Fiscal Taxes. Oq acham ?
cc @rvalyi @renatonlima @mileo

**Comment by marcelsavegnago** [comment]
Mas tem algo importante que cabe discussão. O sistema sempre deve recalcular os impostos antes de faturar ou deve respeitar o que ficou definido no contrato ?

**Comment by marcelsavegnago** [comment]
Resolvido na PR https://github.com/OCA/l10n-brazil/pull/2047
