### ISSUE TITLE
[12.0][14.0][BUG] Base de cálculo de INSS precisa ser editável

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2072]
As faturas onde contem material de insumo e mão de obra, a legislação permite tributar o INSS somente da parte de mão de obra da fatura, assim a alíquota cadastrada deve incidir somente nesta parte.
Hoje a base de cálculo é fixa e não permite edição

Este problema está presente nas versões 12.0 e 14.0, assim seria importante aplicar para as duas versões. Vale para faturas de Clientes e Fatura de Fornecedores

**Instrução Normativa RFB nº 971, de 13 de novembro de 2009** 
[Fonte](http://normas.receita.fazenda.gov.br/sijut2consulta/link.action?idAto=15937)
![image](https://user-images.githubusercontent.com/20867090/183160231-29c55069-978c-4735-9a78-c01f55965575.png)

Sugestão:
Incluir um flag, possibilitando a edição do valor de base do INSS, essa alteração deverá acionar o cálculo de impostos.
![image](https://user-images.githubusercontent.com/20867090/183161658-5879e24c-6d4d-43d8-9d97-844126e0f7ab.png)

**Comment by douglascstd** [comment]
@marcelsavegnago

**Comment by marcelsavegnago** [comment]
@douglascstd no caso de existir um padrão, uma possibilidade seria o cadastro de novos impostos como INSS 11% (redução de 30%).. já evitaria de alguém ter que alterar a base na unha. O que acha ?

![image](https://user-images.githubusercontent.com/3595132/220179464-ce0879e6-294c-4537-80b0-c91700719a00.png)

**Comment by douglascstd** [comment]
Essa base é variável... dependendo da quantidade de material utilizado no serviço prestado...
Isso pode ser diferente em cada nota emitida.

Essa redução é da base de cálculo?  Nesse exemplo seria 30% reduzido ou seja em uma nota de $1000 a base de cálculo seria $700?

Se for desta forma isso ja atenderia parcialmente. Pois se isso é cadastrado no Imposto, seria necessario cadastrar um imposto em cada emissao de NF. O ideial é que fosse possível editar no momento do cadastro da linha da fatura.

**Comment by marcelsavegnago** [comment]
@douglascstd sim.. se cadastrar o imposto e informar o percentual de redução de 30 %, a base de calculo de uma nota de 1000 será 700.
