### ISSUE TITLE
[12.0][Sale] Valor financeiro é zerado após salvar Sale Order

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2083]
O valor líquido a receber de uma ordem de venda não se mantém após salvar.
![image](https://user-images.githubusercontent.com/20867090/185165747-d89b0df1-b344-4408-aa5f-a4cf8fa17605.png)

Para reproduzir:
1- Criar Sale Order
1.1 No form de seleção de produto, selecionar imposto Retido para PIS e COFINS.
1.2 Antes de salvar a Sale Order, observe o campo abaixo do total "Amount Financial" (amount_financial_total) onde aparecerá o valor líquido a receber "Amount Financial" (amount_financial_total) 
2- Salvar Sale Order
2.1 O campo "Amount Financial" (amount_financial_total) assumirá o valor de 0 (_zero_)

### **Vídeo v12**
https://user-images.githubusercontent.com/20867090/185164343-80ef3d03-b402-476f-8e72-4d07cce22da5.mp4

Na **v14**, esse problema não é apresentado:
Uploading SO-v14 withholding.mp4…

**Comment by rvalyi** [comment]
Olá @douglascstd ainda temos esse bug na v14?

**Comment by douglascstd** [comment]
> Olá @douglascstd ainda temos esse bug na v14?

Esse problema só encontrei na v12 mesmo.

**Comment by rvalyi** [comment]
OK ai nesse caso na OCA a gente costuma fechar o issue. Se alguém quiser propor algum backport do fix na V12, é bem-vindo. Mas o conselho mesmo seria migrar para a v14 ou para a v16 em breve.
