### ISSUE TITLE
[14.0] - MultiCompany - Erro ao criar uma empresa em qualquer que for o regime.

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#2085]
Após a instalação da l10n-brazil em uma base limpa ao criar duas empresas para uso do Odoo em modo MULTICOMPANY é reportado o seguinte erro

```
Due to security restrictions, you are not allowed to modify 'Fiscal Document Line' (l10n_br_fiscal.document.line) records.

Records: dummy (id=14)
User: Administrator (id=2)

This restriction is due to the following rules:
- Fiscal Document line multi-company

Note: this might be a multi-company issue.

Contact your administrator to request access if necessary.
```

## Module
l10n_br_fiscal

Creio eu que o conflito esta aqui mas é especulação

## Describe the bug
![Screenshot from 2022-08-19 11-45-16](https://user-images.githubusercontent.com/38361760/185644690-39924cba-5a6c-4726-bd40-1343bf95f65e.png)

## To Reproduce
ERRO acontece também no RUN_BOT 
![Screenshot from 2022-08-19 11-46-55](https://user-images.githubusercontent.com/38361760/185645118-8d2f7274-9c47-4d13-b10a-d7102c6177f1.png)

1. Criar uma empresa no multi empresas pela interface do odoo

**Comment by marcos-mendez** [comment]
Vou fechar, já resolvi o problema, mas ta com bug e não veio a descrição

**Comment by marcos-mendez** [comment]
> Vou fechar, já resolvi o problema, mas ta com bug e não veio a descrição

Eu resolvi não instalando a l10n_br ou seja: NAO RESOLVI rsrs

**Comment by antoniospneto** [comment]
@marcos-mendez, confirmo que tinha o problema, fiz a correção aqui #2115 se puder revisar.

**Comment by rvalyi** [comment]
corrigido por https://github.com/OCA/l10n-brazil/pull/2115
