### ISSUE TITLE
[12.0][BUG] Possível problema na geração de faturas via job de contrato de recorrência

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2088]
Como reproduzir. 
1o Incluir um contrato em cada empresa
2o Executar o Job de geração de faturas via contrato

Normalmente o sistema vai retornar um problema por nao encontrar o icms.regulation da empresa do Odoobot que no caso seria o id 1

**Comment by rvalyi** [comment]
o Odoobot tomou juiz depois desse fix https://github.com/OCA/l10n-brazil/pull/2087
Falta fazer o port para a v14...

**Comment by marcelsavegnago** [comment]
> Falta fazer o port para a v14...

@rvalyi pode deixar.
