### ISSUE TITLE
[l10n_br_sale]product_id_change field uom

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#21]
Ao criar uma order.line em uma sale.order:

Onde o produto tenha uma unidade de medida ( product_uom) diferente da padrão ( unidades ) carregada na visão por padrão antes de se escolher o item.

O metodo product_id_change da localização recebe a unidade de medida UN como parametro e ao chamar o super a "UN" é mantida.

```
def product_id_change(self, cr, uid, ids, pricelist, product, qty=0,
                      uom=False, qty_uos=0, uos=False, name='',
                      partner_id=False, lang=False, update_tax=True,
                      date_order=False, packaging=False,
                      fiscal_position=False, flag=False, context=None,
                      parent_fiscal_category_id=False, shop_id=False,
                      parent_fiscal_position=False,
                      partner_invoice_id=False, **kwargs):

    uom=False

    result = super(sale_order_line, self).product_id_change(
        cr, uid, ids, pricelist, product, qty, uom, qty_uos, uos, name,
        partner_id, lang, update_tax, date_order, packaging,
        fiscal_position, flag, context)
```

Criei tambem uma base demo com o modulo de sale instalado e a configuração de gerenciar varias unidades de medida, ao vender um CD por exemplo, cadastrado com a unidade Dúzia ela não é carregada e a venda pode ser finalizada com a unidade UN. 

Caso se insira na venda um produto com uma unidade de medida de categoria diferente o método do product_id_change do core verifica se são de mesma categoria e altera o produto.

Outra consideração é que o caso se tenha uma unidade_uom diferente da unidade de venda, com a devida propoção entre as duas cadastrada no produto. 

O OpenERP mantem a proporção entre elas no lançamento da venda.

Agora se o produto esta castrado com unidade de estoque duzia e venda em duzia, o OpenERP lança a venda com UN e não cria a proporção com a UDV, mesmo que cadastrado nas configurações da unidade de medida.

Isso confunde um pouco o operador do sistema, setando a uom como False não tive problemas, a uom do cadastro é carregada e qualquer alterção na unidade de medida o metodo product_uom_change do core faz o seu trabalho.

Se alguem puder simular esse problema agradeço.

Miléo

**Comment by rvalyi** [comment]
Agora esta resolvido na 7.0 e na develop. A gente aplicou um patch um pouco diferente Luis, pois passamos False direitamente no on_change da view em vez de fazer o hack que vc suggeriu. E a forma como o modulo sale nativo faz.

Tb depois de fazer o merges das branches web_context_tunnel nao vai mais precisar lutar com esse tipo de coisas.

**Comment by mileo** [comment]
Obrigado!

[]s

2014-03-08 22:45 GMT-03:00 Raphaël Valyi notifications@github.com:

> Closed #21 https://github.com/openerpbrasil/l10n_br_core/issues/21.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/21
> .

## 

Luis Felipe Miléo
skype: luisfelipemileo
http://mileo.co http://blog.mileo.co
https://launchpad.net/~mileo
https://github.com/mileo

**Comment by renatonlima** [comment]
Eu já tinha feito esta correção no develop https://github.com/openerpbrasil/l10n_br_core/commit/bcaf76f1aecc989fa4edae72e2691cfa1de15135
