### ISSUE TITLE
[14.0][l10n_br_account] Frete, Seguro e Outros Custos 

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2128]
Precisa ser melhor investigado mas apenas para registrar, aparentemente frete, seguro e outros custos não está funcionando legal na fatura.

Por ora, para conseguir avançar em um projeto eu fiz um pequeno hack porco forçando a criação de linhas contábeis do frete, seguro e outros custos.
https://github.com/Escodoo/l10n-brazil/commit/666e36545dae704dccadbef213b2ae3bd7527259

cc @renatonlima @rvalyi @netosjb @felipemotter @vanderleiromera  @marcos-mendez

**Comment by marcos-mendez** [comment]
Marcel pode me explicar como gerar o bug? Vou ver aqui o que podemos fazer

**Comment by marcelsavegnago** [comment]
> Marcel pode me explicar como gerar o bug? Vou ver aqui o que podemos fazer

Vc pode criar um pedido de venda e informar o valor do frete, seguro e outros custos ou até mesmo fazer isso diretamente na invoice (veja na linha do produto a aba Other.

**Comment by mbcosta** [comment]
@marcelsavegnago testando o l10n_br_sale parece existir outro problema ( ou talvez esteja relacionado ) com esses campos no Pedido de Vendas, usando os dados de demonstração ao tentar preenche-los pelo campo dos Totais informando por exemplo valor 100 acaba ficando da forma abaixo:

![image](https://user-images.githubusercontent.com/6341149/191348331-d03afa22-448e-4e02-8b37-330cba542959.png)

![image](https://user-images.githubusercontent.com/6341149/191348432-4e659a7d-9d0f-478c-92b3-a6af60890d02.png)

![image](https://user-images.githubusercontent.com/6341149/191348531-5319d06d-6baf-46bd-b535-8d9303556ade.png)

![image](https://user-images.githubusercontent.com/6341149/191348618-37b31500-78f0-48cf-8a96-0035b5909cbe.png)

Apesar dos três campos estarem preenchidos apenas um está sendo salvo, até onde entendi o código só está permitindo uma alteração/inclusão por vez, talvez o problema esteja em algo do método _compute_amount do modulo l10n_br_fiscal https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_fiscal/models/document_fiscal_mixin_methods.py#L38 porque é possível verificar que no inicio do metodo os campos estão com os valores informados mas ao final eles já não tem o mesmo valor, bom isso é apenas uma hipótese estou procurando entender e testar melhor

**Comment by rvalyi** [comment]
foi corrigido em https://github.com/OCA/l10n-brazil/pull/2347, certo?
