### ISSUE TITLE
[14.0][l10n_br_account] Não é possível selecionar Operação Fiscal, em uma fatura que retorna para Rascunho

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2131]
Após a fatura emitida, e retornada a provisória (Rascunho), não aparece as opções de Operação Fiscal:
![image](https://user-images.githubusercontent.com/20867090/191360642-64d9d0c0-4f20-4c72-b0ec-9af23dc9ba10.png)

## Module
Account_invoice

## To Reproduce
1. Criar fatura
1.1 Sem selecionar documento fiscal
2. Aprovar e Postar
3. Retornar fatura para provisório
4. Selecionar documento fiscal (01. Nota Fiscal)
5. Selecionar Operação fiscal - Neste momento não aparece lista de opção

**Comment by mbcosta** [comment]
Olá @douglascstd obrigado por reportar o problema, você pode colocar no modo debug e ao colocar o mouse sobre o campo deverá aparecer mais informações sobre ele, será importante ver se tem algo especifico no atributo Domínio, que define quando um campo deve ou não aparecer

![image](https://user-images.githubusercontent.com/6341149/191783487-4adc2a13-ba36-4878-9f39-591dd049bd79.png)

Pelo o que entendi você está testando com os dados de demonstração, é isso mesmo? Isso é no runboat? É importante saber, quais módulos da localização foram instalados, pela menção ao Unicred acredito que o l10n_br_account_payment_order também está instalado, você confirma isso? Se está usando os dados de demonstração em qual das empresas está sendo feito o teste? Eu fiz um teste em uma base nova de demonstração e em três das quatro empresas e acessando o Fiscal > Documentos > NFe apareceram as Operações Fiscais

![image](https://user-images.githubusercontent.com/6341149/191785873-f161e3c0-c7bd-44ab-bb0f-fc4cd6980e7e.png)

Na empresa My Company (Chicago) acontece um problema referente ao Diário, mas isso é outra questão 

![image](https://user-images.githubusercontent.com/6341149/191786838-56cbf183-a96b-4768-9c02-e1909b9626aa.png)

Importante saber também se o seu ambiente está atualizado, ou se tem customizações, pela imagem que você colocou o campo Operação Fiscal está como obrigatório mas no meu teste não estão, por isso é preciso saber os principais módulos instalados, se o teste está sendo feito no runboat boa parte das questões já serão respondidas.

**Comment by douglascstd** [comment]
Olá Magno tudo bem? Obrigado pela atenção e resposta detalhada.

A instância que usei para teste foi o RunBoat da Localização Brazil:
https://github.com/OCA/l10n-brazil

Os módulos instalados são todos que estão na localização, não fiz qualquer instalação a mais..

As informações avançadas do campo (incluindo o domínio)
![image](https://user-images.githubusercontent.com/20867090/191840806-e74359b5-a85a-49a8-96ce-256595be00bf.png)

A empresa usada: My Company (San Francisco)
![image](https://user-images.githubusercontent.com/20867090/191841845-c26b9497-2a1c-46f9-9ea7-7c35292b5cef.png)

Esse foi o Boat que usei:
http://oca-l10n-brazil-14-0-1038ea0b0949.runboat.odoo-community.org/web#id=24&action=305&model=account.move&view_type=form&cids=&menu_id=228

Quando você diz:
"Eu fiz um teste em uma base nova de demonstração e em três das quatro empresas e acessando o Fiscal > Documentos > NFe apareceram as Operações Fiscais"
Você está acessando o Documento Fiscal, não havia testado desta forma. Testei entrando em:
Faturamento >> Fornecedor >> Faturas

Espero que ajude você na reprodução desta mesma falha. Eu detectei esse mesmo comportamento em um cliente que utiliza a ODOO EE v14, com módulos da OCA. E consegui repetir o mesmo problema no Runboat da OCA.

**Comment by antoniospneto** [comment]
olhando ali o domínio do campo, parece ser por causa do campo **state**, pelo que vi os valores possíveis para esse campo são **draft**, **posted** ou **cancel**, parece que não existe mais o valor "approved"

**Comment by douglascstd** [comment]
> 

Obrigado Neto pela observação.
O campo "fiscal_operation_id" funciona corretamente na 1a emissão, e só não aparece mais opção de seleção após o Processo:
1. Emissão (Postado)
2. Cancelado
3. Retornar para Rascunho
Só depois disso, então, esse campo não apresenta mais nenhuma alternativa de seleção.
Não acredito que seja o domínio, pois funciona corretamente na 1a emissão.

**Comment by douglascstd** [comment]
> 

Obrigado Neto pela observação.
O campo "fiscal_operation_id" funciona corretamente na 1a emissão, e só não aparece mais opção de seleção após o Processo:
1. Emissão (Postado)
2. Cancelado
3. Retornar para Rascunho
Só depois disso, então, esse campo não apresenta mais nenhuma alternativa de seleção.
Não acredito que seja o domínio, pois funciona corretamente na 1a emissão.

**Comment by douglascstd** [comment]
Fiz um vídeo para mostrar o que acontece:

https://user-images.githubusercontent.com/20867090/192305872-03bc8df7-c523-4f97-acd4-6d79176dcc39.mp4

**Comment by antoniospneto** [comment]
Desculpa eu olhei errado, o state do domínio é o da operação fiscal e não  o da fatura..

**Comment by antoniospneto** [comment]
fiz um teste aqui pelo runboat e pude confirmar que o problema persiste, o erro é por causa do campo **fiscal_operation_type**, é um campo invisível e é usado no domínio da operação, quando vc cria uma fatura nova ele vem preenchido  por padrão como "out" mas quando vc salva com o tipo de documento nulo essa informação se perde.

**Comment by douglascstd** [comment]
Forcei no form para aparecer o campo fiscal_operation_type
![image](https://user-images.githubusercontent.com/20867090/192392528-b8f37dea-60f6-45f3-9469-071eeb5f8bc5.png)
Parece que só existem 3 seleções possíveis (in, out ou all) e esse campo passa a ser Vazio.... Será que não está aí o erro??

Fiz uma busca desta variável e parece que esse é um lugar que encontrei, será que neste código não deveria ter algo que direcionasse para all, caso não encontre valor nesta condição?
[                doc.fiscal_operation_type = tpNF_2_operation[doc.nfe40_tpNF]](https://github.com/OCA/l10n-brazil/blob/caa4bf617ae516f83ce697a5402f73dff99c28b4/l10n_br_nfe/models/document.py#L308)

**Comment by antoniospneto** [comment]
@douglascstd  fiz uma pr para solucionar isso: #2135

**Comment by douglascstd** [comment]
> @douglascstd  fiz uma pr para solucionar isso: #2135 

Perfeito.. Muito obrigado Neto.
