### ISSUE TITLE
[14.0][BUG] l10n_br_sale: Frete, Seguro e Outros Custos informados pelos Totais

### ISSUE THREAD

**Issue by mbcosta** [OCA/l10n-brazil#2132]
No l10n_br_sale quando o parâmetro para definir os campos Frete, Seguro e Outros Custos por Valor Total ( a outra opção é por Linha ) apenas um campo está sendo salvo por vez, usando os dados de demonstração ao tentar preenche-los por exemplo com o valor 100 acaba ficando da forma abaixo:

![image](https://user-images.githubusercontent.com/6341149/191772176-fff63cc6-2f86-4176-886f-d55321a041fc.png)

Apesar dos três campos estarem preenchidos apenas um é salvo

![image](https://user-images.githubusercontent.com/6341149/191772280-b9cdf599-cb59-410d-b85a-87ddc716ee1e.png)

O calculo para ratear os valores na linha parece certo

![image](https://user-images.githubusercontent.com/6341149/191772346-7e194ad1-166f-460d-905f-f5763e03222a.png)

![image](https://user-images.githubusercontent.com/6341149/191772398-c3955a40-6a63-4af2-b5f3-b3f09d05524c.png)

Até onde entendi o problema pode estar em algo do método _compute_amount do modulo l10n_br_fiscal https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_fiscal/models/document_fiscal_mixin_methods.py#L38 ou está faltando ou precisa ser incluído algo nos métodos herdados porque é possível verificar que no inicio do método os campos estão com os valores informados mas ao final eles já não tem o mesmo valor, bom isso é apenas uma hipótese estou procurando entender e testar melhor, testei incluindo o código abaixo antes desse doc.update(values) https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_fiscal/models/document_fiscal_mixin_methods.py#L54 é isso funciona

            if doc.company_id.delivery_costs == "total":
                values["amount_freight_value"] = doc.amount_freight_value
                values["amount_insurance_value"] = doc.amount_insurance_value
                values["amount_other_value"] = doc.amount_other_value

Tentei incluir esse mesmo código nos métodos herdados no l10n_br_sale https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_sale/models/sale_order.py#L213 mas não funcionou.

Talvez o código esteja considerando que os valores Totais são sempre a soma dos Valores das Linhas, o que realmente são a maioria dos casos, mas teria essa exceção a ser considerada.

Existe uma questão pendente que pode acabar sendo resolvida devido a esse problema, essa funcionalidade de permitir informar os campos Frete, Seguro e Outros Custos tanto por Linha quanto por Total deveria já ser possível nas Notas Fiscais, quer dizer mesmo que apenas o l10n_br_fiscal ou o l10n_br_account estejam instalados sem o l10n_br_sale isso já deveria ser possível, mas isso pode ser algo no futuro, um Roadmap,
 
cc @renatonlima @rvalyi @marcelsavegnago @mileo

**Comment by douglascstd** [comment]
Imagino que para cada um dos campos de custo extra, deveria existir uma seleção de conta contábil para onde seria enviado esse custo, imaginando que se não fosse inserido, ele aplicaria a mesma conta de despesa do produto.
O mesmo poderia ser utilizado para os custos gerais:
- Se informado usaria a conta informada
- Se não informado, usaria a conta do produto de cada uma das linhas
Acredito que deveria ter um checkbox com a pergunta:
Os custos deverão ser rateados nas linhas? ( um rateio entre todas as linhas da fatura )

**Comment by antoniospneto** [comment]
@douglascstd mas o certo é contabilizar esses valores tudo na conta do produto, da forma que está, não? por exemplo esses valores na nota fiscal vão ser tudo somado na  conta "receita bruta dos produtos vendidos" normalmente é essa a conta padrão que está no produto.. O custo de fato desses valores extras vão ser lançados em outro momento, por exemplo o frete, a despesa vai ser lançada quando fazer o registro do conhecimento de frete que vai vir da transportadora.

Depois no balanço contábil que vai ser se calculado a receita liquida, que vai ser a receita bruta que vem da fatura menos as despesas/custos..

bom pelo menos é assim que costumo fazer hehe

**Comment by marcelsavegnago** [comment]
> * Os custos deverão ser rateados nas linhas? ( um rateio entre todas as linhas da fatura )

 Acho que isso já tem. No caso a configuração é por empresa mas eh possível forçar para ser por total mesmo que seja por linha
![image](https://user-images.githubusercontent.com/3595132/197012676-2f7625d4-fae8-42ad-b32e-19aa5f97a036.png)

**Comment by marcelsavegnago** [comment]
Correção.. o forçar ainda nao foi aceito.. mas esta proposto nesta PR https://github.com/OCA/l10n-brazil/pull/1988

https://github.com/OCA/l10n-brazil/pull/1988/commits/ff19b1916403ed7fb9f16dc6873adb5d7bdb6128

https://github.com/OCA/l10n-brazil/pull/1988/commits/d8aae123b618f472a26ba179f9ffa5f5594ac61d

**Comment by antoniospneto** [comment]
@mbcosta com o merge do https://github.com/OCA/l10n-brazil/pull/2136 esses problemas foram resolvidos ?
