### ISSUE TITLE
[12.0][l10n_br_fiscal] Ao criar um novo documento fiscal com emissor sendo o parceiro, o sistema permite incluir faturas de compra com o mesmo parceiro, serie e numero

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2151]
Ao criar um novo documento fiscal com o emissor sendo o parceiro,  o sistema permite incluir faturas de compra com o mesmo parceiro, serie e numero. Pelo que percebi, o partner_id do record está vazio neste momento. Já na alteração do documento a verificação ocorre normalmente.

![image](https://user-images.githubusercontent.com/3595132/193627802-559b57eb-a6ed-422c-89d4-d66cc4751844.png)

Para reproduzir:
- Crei uma fatura de compra com algum tipo de documento fiscal e numero de serie 1 e numero do documento 123
- Valide a fatura
- Crie uma nova fatura de compra para o mesmo parceiro da fatura anterior e com a mesma série e número de documento. 
- Veja que ao salvar o documento o sistema deixa passar com os mesmos dados

cc @douglascstd @netosjb @rvalyi @renatonlima @mbcosta @felipemotter

**Comment by marcelsavegnago** [comment]
Pelo que entendi o campo partner_id não é do tipo herdado e portanto na hora de criar o documento fiscal o mesmo não é está disponível quando executa o método _check_number.

**Comment by douglascstd** [comment]
O mesmo comportamento acontece na v14. Testado no runboat OCA/l10n-brazil

![image](https://user-images.githubusercontent.com/20867090/193816287-5e669fe5-6990-4d0c-a030-f41112b64e14.png)

**Comment by antoniospneto** [comment]
@marcelsavegnago parece que a limitação que você caiu é a mesma que eu cai nessa PR: https://github.com/OCA/l10n-brazil/pull/2014
