### ISSUE TITLE
Localização l10n-brazil  -  erro python setup.py install

### ISSUE THREAD

**Issue by cs-tecnologia** [OCA/l10n-brazil#2152]
Boa Tarde, 

Estou iniciando com Odoo e estou enfrentando algumas dificuldades com a localização l10n-brazil.

Quando executo a instalação ao final da erro:
C:\Arquivos de Programas\odoo14\server\addons>**pip3 install -r .\requirements.tx**t

![image](https://user-images.githubusercontent.com/114611246/193621868-7940df28-1078-444b-8dbd-67f23dac8d76.png)

Por gentileza, se houver algum tutorial de localização, poderiam me enviar.
Agradeço antecipadamente

**Comment by vanderleiromera** [comment]
Primeira coisa a fazer mude o sistema operacional para linux, no windows voçe pode ir de wsl2

**Comment by rvalyi** [comment]
algumas respostas foram parar aqui https://github.com/OCA/l10n-brazil/issues/2154

**Comment by marcos-mendez** [comment]
@cs-tecnologia OBVIAMENTE a resposta do vanderlei é a melhor. Mas assim entendo que é uma  resposta que apesar da melhor também é a mais dolorida.

O Odoo em teoria deveria funcionar em qualquer sistema independentemente do seu gosto por sistema operacional. A comunidade DEVERIA prestar suporte a isso, mas enfim. Sei que aprender Linux não é algo fácil da noite pro dia. E sinceramente o WSL me parece como ir no McDonalds e pedir uma Salada, ridiculo. 

Se você precisa testar no Windows e não tem mais remédio antes do `pip -r requirements.txt `da um `$pip install pycopy-fcntl`

Pelo meu ponto de vista toda a api de 32 bits do Windows vai ter te passar por uma grande modificação e tem algumas coisas ainda que são interpretadas com backports do python no windows então isso deve resolver temporariamente o seu problema nos próximos 2 anos até existir um service pack ou algo assim do windows 11 que faça um backport mais estável. 

Por ultimo recomendo que você use algum orquestrador de container tipo LXD ou Docker pois facilita  a vida no longo prazo do Odoo. Seja bem vindo a comunidade, primeira vez que vejo você por aqui. No que puder ajudar estou a disposição. 

O Canal to telegram é o https://t.me/odoobrazil

**Comment by antoniospneto** [comment]
@marcos-mendez 

DEVERIA é uma palavra forte, o complicado do Windows é que ninguém que eu conheça aqui o utiliza, ninguém testa neste ambiente, todas as ferramentas e scripts que eu conheço para auxiliar a implementação são feitas pensando para ser executado no LINUX, se alguém tiver conhecimento no mesmo está livre para vir aqui comentar e ajudar, mas acho muito importante alertar o usuário novo que seguir esse caminho pode ser bem mais dificil e talvez ele tenha que enfrentar o problema sozinho e com pouco material disponível, não por que o pessoal aqui não tem interesse em ajudar e sim porque não tem a pratica ou conhecimento neste ambiente..

**Comment by marcos-mendez** [comment]
> @marcos-mendez
> 
> DEVERIA é uma palavra forte, o complicado do Windows é que ninguém que eu conheça aqui o utiliza, ninguém testa neste ambiente, todas as ferramentas e scripts que eu conheço para auxiliar a implementação são feitas pensando para ser executado no LINUX, se alguém tiver conhecimento no mesmo está livre para vir aqui comentar e ajudar, mas acho muito importante alertar o usuário novo que seguir esse caminho pode ser bem mais dificil e talvez ele tenha que enfrentar o problema sozinho e com pouco material disponível, não por que o pessoal aqui não tem interesse em ajudar e sim porque não tem a pratica ou conhecimento neste ambiente..

@antoniospneto DEVERIA é porque no caso era pra ser, o Odoo tem um release inclusive de executável em Windows, por isso Deveria e não DEVE. 

Eu vejo que a Odoo precisa desses ambientes para micro e pequenas empresas então por isso ele continuam liberando o .exe do Odoo. Infelizmente eles abraçam mais do que conseguem carregar e como você bem disse não tem nem documentação sobre, e falo da própria Odoo não estou nem citando a OCA. Note que em todo momento mencionei a Odoo e não a OCA.

Acho que o mais honesto seria não lançar simplesmente o .exe e assim não criar espectativas do pessoal mais novo que baixa, testa e tals, maaaas não consegue desenvolver e obviamente crescer no framework, ai a curva de aprendizado acaba sendo a de mecanica de foguetes, tem aque aprender linux, depois toda a infra por tras da l10n_br e no final das contas temos uma estação espacial que poucos são capazes de atingir e/ou chegar. Mesmo sendo 100% OpenSource

**Comment by rvalyi** [comment]
por favor comentar e re-abrir se ainda for relevante com o HEAD da 14.0
