### ISSUE TITLE
Primeira coisa a fazer mude o sistema operacional para linux, no windows voçe pode ir de wsl2

### ISSUE THREAD

**Issue by cs-tecnologia** [OCA/l10n-brazil#2154]
Perfeito, vou fazer isto 
obrigado

**Comment by marcelsavegnago** [comment]
???

**Comment by vanderleiromera** [comment]
Pelo visto temos um bug  @@ ...

**Comment by rvalyi** [comment]
fechando esse issue porque na verdade isso foi apenas as respostas de continuação do issue https://github.com/OCA/l10n-brazil/issues/2152
