### ISSUE TITLE
[14.0]Custos extras não lançados na invoice quando selecionado parâmetro total.

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2173]
Senhores, boa tarde
acompanhei a issue #2132 , porém tenho algumas considerações:
Tais campos: "Insurance value", "other costs" e "freight value" não são adicionados ao total da invoice gerada pela S.O, (comportamento testado/validado no runbot: http://oca-l10n-brazil-14-0-pr2170-ad52243857e3.runboat.odoo-community.org/web#id=24&action=580&active_id=24&model=account.move&view_type=form&cids=3&menu_id=414)
## Module
The name of the module that has a bug.

## Describe the bug
Valores adicionais não são computados na invoice, nem lançados no CoA
## To Reproduce
**Affected versions**:14.0 

1.Definir custos adicionais na S.O
2.Criar uma Fatura pela S.O
3.Os valores adicionais não constam na Invoice 

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

![Screenshot at Oct 18 13-16-00](https://user-images.githubusercontent.com/25938418/196490631-4f1bb425-d6a4-431e-8aab-a7c1e1810432.png)
![Screenshot at Oct 18 13-17-34](https://user-images.githubusercontent.com/25938418/196490636-75a4dac8-7cbb-4de9-bac9-0f0f0b4e3844.png)
![Screenshot at Oct 18 13-18-46](https://user-images.githubusercontent.com/25938418/196490639-75249b11-b719-4b1c-bbe5-f4076033f792.png)
![Screenshot at Oct 18 13-19-57](https://user-images.githubusercontent.com/25938418/196490643-0be79b8c-cc36-43b6-a094-e6a7429f36a2.png)
g)

ping: @marcelsavegnago, @mbcosta, @rvalyi , @renatonlima, @mileo

**Comment by antoniospneto** [comment]
pois é parece que isso passou despercebido, outra coisa que acho interessante também é adicionar esses três campos no rodapé da fatura.

**Comment by marcelsavegnago** [comment]
> pois é parece que isso passou despercebido, outra coisa que acho interessante também é adicionar esses três campos no rodapé da fatura.

Vc fala de adicionar ali nos totais do formulário da fatura neh ?

**Comment by antoniospneto** [comment]
> > pois é parece que isso passou despercebido, outra coisa que acho interessante também é adicionar esses três campos no rodapé da fatura.
> 
> 
> 
> Vc fala de adicionar ali nos totais do formulário da fatura neh ?

Isso mesmo, igual é feito no pedido

**Comment by marcelsavegnago** [comment]
@augustodinizl acredito que isto deve ter sido resolvido.. Por confirmar por favor ?
