### ISSUE TITLE
[14.0] l10n_br_fiscal: problema para atualizar base depois da extração do fiscal closing para outro módulo

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2217]
Somente com o objetivo de relatar, hoje ao atualizar a base de um cliente recebemos mensagem de erro referente ao modelo l10n_br_fiscal.closing.

**Comment by marcos-mendez** [comment]
Era o mesmo que eu tava passando na semana passada ne @neto?

**Comment by marcelsavegnago** [comment]
Este problema foi resolvido com o script de migração que instala o l10n_br_fiscal_closing.
