### ISSUE TITLE
[14.0] l10n_br_zip botão de pesquisa está submetendo o formulário

### ISSUE THREAD

**Issue by aleprovencio** [OCA/l10n-brazil#2220]
## Module
l10n_br_zip

## Describe the bug
Ao digitar um CEP e clicar no botão de pesquisa o endereço é buscado corretamente porém o form é submetido

## To Reproduce
1. ao editar uma empresa digite um CEP no campo correspondente
2. clique no botão de pesquisa (lupa)

**Expected behavior**
O endereço deveria ser preenchido mas sem o formulário ser submetido, para continuar com o fluxo normal de edição

**Comment by antoniospneto** [comment]
Acho que não é possível submeter um action sem salvar o estado do formulário atual, não sei qual seria a melhor solução para esse caso, talvez com javascript, owl ? alguém já viu algum comportamento parecido em outros lugares do odoo que daria de aproveitar aqui ?

**Comment by antoniospneto** [comment]
@aleprovencio 

eu acabei de testar aqui mas não parece ser um problema, apesar do form ser submetido, ele volta automaticamente para o estado de edição:

![image](https://user-images.githubusercontent.com/634278/199812544-c9785bb8-4fe3-40e9-ab1b-72d425103242.png)

**Comment by mileo** [comment]
Uma forma de implementar isso seria colocar um onchange no botão: https://github.com/OCA/l10n-brazil/pull/985

**Comment by antoniospneto** [comment]
o onchange talvez possa ser um pouco invasivo, as vezes o usuario já tem o endereço digitado e não quer alterar, também as vezes da erro na API. eu sinceramente eu acho que já tem bem legal do jeito que está.

**Comment by aleprovencio** [comment]
@netosjb reparei que na edição de clientes realmente é retornado para a tela de edição, contudo o mesmo não acontece ao editar a empresa padrão do sistema.
