### ISSUE TITLE
Erro ao criar certificado digital E-CNPJ

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2223]
l10n_br_fiscal

Ao selecionar o arquivo pfx, e inserir a senha, da erro de SENHA e:

 File "/home/odoo/odoo14/core/l10n-brazil/l10n_br_fiscal/models/certificate.py", line 115, in _compute_name
    format_date(self.env, c.date_expiration.date()),
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/odoo14/core/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo14/core/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'bool' object has no attribute 'date'

**Comment by antoniospneto** [comment]
@mileo 

acho que isso tem a ver com a pr #2201 mesclado recentemente.

acho que é preciso por uma verificação para informar a data em branco caso não exista: https://github.com/kmee/l10n-brazil/blob/a9d012bcbe6b74a29e21dc1c6c68d3d444b90d14/l10n_br_fiscal/models/certificate.py#L115

**Comment by mileo** [comment]
> @mileo
> 
> acho que isso tem a ver com a pr #2201 mesclado recentemente.
> 
> acho que é preciso por uma verificação para informar a data em branco caso não exista: https://github.com/kmee/l10n-brazil/blob/a9d012bcbe6b74a29e21dc1c6c68d3d444b90d14/l10n_br_fiscal/models/certificate.py#L115

Detectamos isso nos testes da v15/16 se eu não me engano a correção já foi feita. Vou dar uma olhada e já faço o PR.

**Comment by DiegoParadeda** [comment]
[804ae617d890c74320ef130a06cddc9ead325c70](https://github.com/kmee/l10n-brazil/commit/804ae617d890c74320ef130a06cddc9ead325c70)

https://github.com/OCA/l10n-brazil/pull/2193
