### ISSUE TITLE
[12.0][14.0] l10n_br_account: Problema em relação ao documento fiscal "dummy"

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2229]
## Módulo
l10n_br_account

## Descreva o bug
Hoje na localização é possível fazer com que faturas com um tipo de documento fiscal definido apontem para um único fiscal dummy, consequentemente, podemos ter varias faturas fiscais apontadas para o mesmo documento fiscal, gerando inconsistências nos dados. 
Todos os campos nas faturas que são herdados do documento fiscal serão compartilhados, se mudar o valor em um, mudará em todas as faturas.

## Para reproduzir:
**Versões afetadas**: 12.0, 14.0.

Etapas para reproduzir o comportamento:
1. Crie uma fatura sem definir um tipo de documento fiscal (document_type_id). (Fatura 1) e Salve.
3. Crie uma segunda fatura sem definir um tipo de documento fiscal (document_type_id). (Fatura 2) e Salve.
5. Edite o tipo do documento  da Fatura 1 para "55 - Nota Fiscal Eletrônica" e Salve.
6. Edite o tipo do documento  da Fatura 2 para "55 - Nota Fiscal Eletrônica" e Salve.
7. Edite o número do documento  (document_number) da Fatura 1 para "Teste123"
8. Abra a Fatura 2, veja que o número do documento será "Teste123". O mesmo da fatura 1..

**Comportamento esperado**
O valor do número do documento (document_number) da Fatura 2, deveria estar em Branco.

**Contexto adicional**
 A PR #2228 resolve outros problemas relacionado ao documento fiscal dummy, porém esse caso é mais complexo de resolver.

**Comment by rvalyi** [comment]
teria que lidar com isso no write do account.move eu diria: caso definir o fiscal_document_type_id, teria que desligar do dummy e criar um novo documento fiscal para essa nota. E o contrario tb: se escrever False no fiscal_document_type_id, ai teria que ligar ao dummy. Isso não resolveria?

**Comment by antoniospneto** [comment]
@rvalyi pois é, vou pensar em alguma solução para propor em uma PR, essa questão está bem crítica para nós.
Está acontecendo bastante casos em que o usuário salva uma fatura, sem informar o tipo de documento fiscal e depois volta para o modo de edição para preencher o tipo do documento fiscal, porém como o dummy já estava ativado, isso faz com que todos os account.move associados ao dummy ficam com o tipo de documento definido, isso acaba desencadenado diversos bugs, nas faturas, nos pagamentos, na reconciliação bancária, etc, tudo que envolve os account.move que não são documentos fiscais. Isso altera totalmente o fluxo normal, o sistema passa achar por exemplo que um  lançamento contábil de um pagamento seja considerado uma nota fiscal, causando varios erros por causa das inconsistencias.

**Comment by rvalyi** [comment]
eu imagino. Mas tb parece fácil resolver. Eu falei do write, mas pode ser usando métodos _inverse tb eu acho.

O write do account.move.line tb ainda não tá perfeito aí dá para ajeitar junto...

**Comment by antoniospneto** [comment]
> eu imagino. Mas tb parece fácil resolver. Eu falei do write, mas pode ser usando métodos _inverse tb eu acho.
> 
> O write do account.move.line tb ainda não tá perfeito aí dá para ajeitar junto...

O problema de criar um novo `fiscal_document_id` é sincronizar os dados que já estão na fatura, por hora eu vou bloquear a digitação do tipo do documento fiscal caso o dummy já esteja definido.

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/2547
