### ISSUE TITLE
[14.0] l10n_br_account_payment_brcobranca Falha na utilização da sequência do Nosso Número quando Sequencial único por empresa

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2244]
O problema acontece quando é criado um Payment Mode que utiliza o sistema CNAB BRCobrança, e na sequencia se tenta criar um novo Payment Mode (de qualquer tipo), o sistema apresenta erro:

![image](https://user-images.githubusercontent.com/20867090/206580304-623fca58-7015-4d35-a5f1-8005fbd9aad4.png)

## Module
l10n_br_account_payment_brcobranca

## To Reproduce
1. Selecionar na configuração da empresa. Definições»Empresa»Integração Bancária»Boleto» Tipo de nosso número: Sequencial Único por empresa
![image](https://user-images.githubusercontent.com/20867090/206580753-a0069c28-49c6-4142-a5ad-1c1474e9e06b.png)
2. Criar um modo de Pagamento com configurações para uso do CNAB BR Cobrança.
![image](https://user-images.githubusercontent.com/20867090/206580903-374b389b-5132-47d2-bd71-f0baa7bc67c3.png)
3. Criar um novo modo de Pagamento com configurações do tipo Manual
![image](https://user-images.githubusercontent.com/20867090/206581087-344fc49b-05c3-44f5-a5af-91dafc1bd23c.png)
4. Salvar. É apresentado a seguinte Falha:
![image](https://user-images.githubusercontent.com/20867090/206581176-8ad6e07d-a496-4d9c-a92f-b2fff5fdd55c.png)

### A alternativa usada para conseguir criar os Modos de Pagamento foi:
1- Arquivar o Modo de Pagamento (do CNAB)
2- Criar os Modos de Pagamentos necessários
3- Desarquivar o Modo de Pagamento (do CNAB)

**Comment by marcelsavegnago** [comment]
@mbcosta acredito que este seja o momento de tratar esse comentário que vc deixou no ROADME do módulo l10n_br_account_payment_order

* Confirmar a necessidade de ter a definição da Sequencia do "Nosso Numero" em três lugares diferentes:
    - Cadastro da Sequencia no cadastro da Empresa, o campo é o mesmo usado no Modo de Pagamento porém nesse caso só funciona se a empresa usar apenas um CNAB, caso passe a usar mais de um essa informação vai precisar ser movida de qualquer forma para o cadastro do Modo de Pagto, portanto não seria melhor deixar apenas a opção de informar isso no Modo de Pagto e remover essa opção no cadastro da Empresa ?
    - Numero Sequencial baseado no número da Fatura, até onde foi visto a sequencia do "Nosso numero" é independente da sequencia da Fatura, alguém sabe dizer se existe esse caso de uso ? Se sim, seria importante ter uma referencia sobre a qual caso se refere ex.: Banco X CNAB 240 e assim ficar claro para outros desenvolvedores o uso.
    - Cadastro no Modo de Pagto, deve ser mantido e é melhor ser feito apenas aqui para centralizar o cadastro e por segurança devido as permissões de acesso o usuário que pode cadastrar um Modo de Pagto pode não ter acesso ao cadastro da Empresa.

**Comment by marcelsavegnago** [comment]
> Confirmar a necessidade de ter a definição da Sequencia do "Nosso Numero" em três lugares diferentes:
> * Cadastro da Sequencia no cadastro da Empresa, o campo é o mesmo usado no Modo de Pagamento porém nesse caso só funciona se a empresa usar apenas um CNAB, caso passe a usar mais de um essa informação vai precisar ser movida de qualquer forma para o cadastro do Modo de Pagto, portanto não seria melhor deixar apenas a opção de informar isso no Modo de Pagto e remover essa opção no cadastro da Empresa ?

Acredito que para permitir uma dinamica maior esta opção poderia ser removida. 

> * Numero Sequencial baseado no número da Fatura, até onde foi visto a sequencia do "Nosso numero" é independente da sequencia da Fatura, alguém sabe dizer se existe esse caso de uso ? Se sim, seria importante ter uma referencia sobre a qual caso se refere ex.: Banco X CNAB 240 e assim ficar claro para outros desenvolvedores o uso.

Eu já vi empresas e normalmente empresas pequenas que buscam manter o numero do boleto igual o da fatura mas acho inviavel.. Assim que tiver que cancelar um boleto e gerar um novo entendo que já perderia de alguma forma a sequencia

> * Cadastro no Modo de Pagto, deve ser mantido e é melhor ser feito apenas aqui para centralizar o cadastro e por segurança devido as permissões de acesso o usuário que pode cadastrar um Modo de Pagto pode não ter acesso ao cadastro da Empresa.

Eu manteria apenas esta opção mas entendo que precisa melhorar os critérios de obrigatoriedade do sequencial do nosso numero e entendo que deveria ficar a cargo da empresa decidir se quer ou nao utilizar o mesmo sequencial para modos diferentes (sem sei se teria alguma limitação tecnica que impediria isso)

**Comment by mbcosta** [comment]
obrigado @douglascstd e @marcelsavegnago por relatarem o problema realmente estava no ROADMAP do modulo ver essa questão eu procurei resolver deixando apenas a possibilidade de informar o campo sequencial do "Nosso Número" no Modo de Pagamento no PR https://github.com/OCA/l10n-brazil/pull/2452 , se puderem vejam de testar. Sobre  

"mas entendo que precisa melhorar os critérios de obrigatoriedade do sequencial do nosso numero e entendo que deveria ficar a cargo da empresa decidir se quer ou nao utilizar o mesmo sequencial para modos diferentes (sem sei se teria alguma limitação tecnica que impediria isso)"

Marcel não teria um limitação técnica mas o problema é que como é um sequencial se for usado por mais de um Modo de Pagamento a sequencia vai "furar", exemplo:
- Modo de Pagto 1 CNAB -X Nosso Número 001
- Modo de Pagto 2 CNAB -Y Nosso Número 002, nessa sequencia do Nosso Número deixaria de existir o 001
- Modo de Pagto 1 CNAB -X Nosso Número 003, nessa sequencia do Nosso Número deixaria de existir o 002 e assim por diante

**Comment by antoniospneto** [comment]
com o merge da https://github.com/OCA/l10n-brazil/pull/2452 acho que essa issue pode ser fechada
