### ISSUE TITLE
Deletar records quando desvinculados do documento fiscal

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#2247]
Existem diversos campos dos documentos fiscais o2m e que ao serem desvinculados do documento passam a ser lixo dentro do banco de dados. Um exemplo são os campos nfe40_vol(modelo nfe.40.vol) e nfe40_dup(modelo nfe.40.dup).

![WhatsApp Image 2022-12-10 at 11 21 32](https://user-images.githubusercontent.com/6812128/206860796-e9b079d7-b2bd-405f-beba-ec623d6eaf63.jpeg)
![d76e2883-8c2e-45ad-9c76-448ef13fc5c2](https://user-images.githubusercontent.com/6812128/206860807-00d997f1-6c31-42bd-92bd-c8e147b13aaf.jpg)
![image](https://user-images.githubusercontent.com/6812128/206860828-cd157b31-bcf1-49c0-8aa1-b9d7a84609c0.png)

Não é um problema absurdo, porque é um caso que acredito ser raro de acontecer, mas consome espaço desnecessáriamente.

A solução seria colocar ondelete='cascade' no campo que faz vinculo com o documento fiscal nos modelos filhos, porém eles são gerados automaticamente pela nfelib e o ideal seria alterar diretamente nela, talvez já na branch com xsdata. O que você acha @rvalyi ?

**Comment by rvalyi** [comment]
Boa @felipemotter . Na verdade eu jà tinha visto isso e eu acertei no PR da NFe com xsdata, veja por examplo:
pros volumes:
https://github.com/akretion/l10n-brazil/blob/14.0-xsdata-l10n_br_nfe/l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py#L5360
para as duplicatas:
https://github.com/akretion/l10n-brazil/blob/14.0-xsdata-l10n_br_nfe/l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py#L5456

Então no gerador xsdata-odoo eu deteto que esses m2o são dentro de um parente e uso até o novo atributo xsd_implicit (porque esse m2o não existe explicitamente no xsd, apenas existe o o2m relacionado) para sinalizar isso e neste caso eu tb boto aquele delete="cascade" que faltava no generateds-odoo.

Então assim que a gente puder fazer o merge do https://github.com/OCA/l10n-brazil/pull/1979 sera solucionado.

cc @antoniospneto @renatonlima @marcelsavegnago

**Comment by rvalyi** [comment]
resolvido na 14.0 com https://github.com/OCA/l10n-brazil/pull/2457
