### ISSUE TITLE
[Q&A]Payment Mode em pedidos de venda gerados via e-commerce

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2251]
Pessoal.. Sabendo que o payment mode se torna peça fundamental principalmente para determinar o código correto para o sefaz, no momento, quando um pedido de venda é criado via e-commerce este valor precisa ser definido manualmente. 

Até então é possível definir um modo de pagamento padrão para os parceiros e quando o pedido é gerado este modo de pagamento é definido no pedido de venda (módulo account_payment_partner). Porém, me parece que o local mais adequado seria adicionar o campo payment_mode no modelo payment_acquirer e assumir este valor no pedido de vendas. 

Estou avaliando o caso e a principio pretendo propor isso no repositório adequado mas de qq forma gostaria da opinião dos senhores.

**Comment by antoniospneto** [comment]
@marcelsavegnago no caso é pra preenchimento da tag da nfe "tPag" certo ?
![image](https://user-images.githubusercontent.com/634278/207122774-56a31818-de35-4177-a775-8018a824ddfc.png)

Eu acho que dá pra fazer é ter a opção de buscar esse valor de dentro do payment_acquirer tbm. Por lá dentro o código do valor do meio de pagamento fiscal.

Depois dá uma olhada na PR #2246 estou sugerindo uma refatoração nessa parte do preenchimento das tag de cobrança / pagamento da nfe.

**Comment by mileo** [comment]
> Pessoal.. Sabendo que o payment mode se torna peça fundamental principalmente para determinar o código correto para o sefaz, no momento, quando um pedido de venda é criado via e-commerce este valor precisa ser definido manualmente.
> 
> Até então é possível definir um modo de pagamento padrão para os parceiros e quando o pedido é gerado este modo de pagamento é definido no pedido de venda (módulo account_payment_partner). Porém, me parece que o local mais adequado seria adicionar o campo payment_mode no modelo payment_acquirer e assumir este valor no pedido de vendas.
> 
> Estou avaliando o caso e a principio pretendo propor isso no repositório adequado mas de qq forma gostaria da opinião dos senhores.



> Pessoal.. Sabendo que o payment mode se torna peça fundamental principalmente para determinar o código correto para o sefaz, no momento, quando um pedido de venda é criado via e-commerce este valor precisa ser definido manualmente.
> 
> Até então é possível definir um modo de pagamento padrão para os parceiros e quando o pedido é gerado este modo de pagamento é definido no pedido de venda (módulo account_payment_partner). Porém, me parece que o local mais adequado seria adicionar o campo payment_mode no modelo payment_acquirer e assumir este valor no pedido de vendas.
> 
> Estou avaliando o caso e a principio pretendo propor isso no repositório adequado mas de qq forma gostaria da opinião dos senhores.

Vale sim, entretanto alguns adquirentes permitem o pagamento de várias formas( pix, boleto, cartão de crédito...) teria que pensar em uma forma efetiva de resolver isso.
