### ISSUE TITLE
[14.0] Alerta no runboat - res.partner: inconsistent 'compute_sudo' for computed fields: nfe40_CNPJ...

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2252]
2022-12-12 20:45:39,634 65 WARNING b8a18928a-f374-4c64-87d5-69b7abd9bcda odoo.modules.registry: res.partner: inconsistent 'compute_sudo' for computed fields: nfe40_CNPJ, nfe40_CPF, nfe40_CEP, nfe40_fone, nfe40_IE, nfe40_choice7 

cc @rvalyi @renatonlima

**Comment by rvalyi** [comment]
@marcelsavegnago eu corrigi isso no último commit do PR para mudar o framework de generateDS pro xsdata https://github.com/OCA/l10n-brazil/commit/c50adfb61d18d980d836d6e7781d7b96a62ca4c1

Se esse merge ainda demorar a gente poderia fazer um cherry-pick disso num outro PR antes.

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago eu corrigi isso no último commit do PR para mudar o framework de generateDS pro xsdata [c50adfb](https://github.com/OCA/l10n-brazil/commit/c50adfb61d18d980d836d6e7781d7b96a62ca4c1)
> 
> Se esse merge ainda demorar a gente poderia fazer um cherry-pick disso num outro PR antes.

Se puder fazer o cherry pick eu acho interessante que já resolve de vez.

**Comment by rvalyi** [comment]
https://github.com/OCA/l10n-brazil/pull/2254
