### ISSUE TITLE
[14.0][BUG] l10n_br_account: geração de faturas sem o financeiro

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2253]
**A geração de documentos fiscais sem financeiro não está funcionando.**

Ao gerar um documento fiscal, utilizando um CFOP configurado para não gerar financio, o documento deveria ser criado sem gerar o financeiro ( contas a receber ) porém o financeiro é gerado.

A inconsistência pode ser verificada no **runboat** gerando uma nota fiscal com a operação fiscal **Bonificação**
Essa operação utiliza os CFOPs 5910 e 6910 que estão marcados para não gerar financeiro:
![image](https://user-images.githubusercontent.com/634278/207182761-329da9ce-d2d6-4df2-b91e-d84207980b96.png)

Geração da Fatura, veja que o financeiro foi gerado indevidamente:
![image](https://user-images.githubusercontent.com/634278/207181750-1152d605-1af2-4cb6-8038-32e13a0162df.png)

Pelo que pude constar essa é uma das funcionalidades que ficou pendente na migração da 12.0 para o 14.0.

**Comment by rvalyi** [comment]
Segura aí que eu tenho um fix para isso. Vou tentar mandar hoje.

**Comment by antoniospneto** [comment]
@rvalyi eu ia dar uma olhada nisso, mas vou aguardar então, valeu!

**Comment by rvalyi** [comment]
Vc ia dar uma olhada é na transmissão com xsdata :-) isso eu vou subir o PR, foi que eu testei qdo teve a treta do anglo saxon e que eu validei que funcionária na 14 tb...

**Comment by rvalyi** [comment]
puts a Odoo SA mudou algo no create do account.move.line desde 18 meses que eu prototipei uma solução para isso e não ta funcionado mais de forma limpa... Tou quebrando a cabeça aqui para nao ter que sobrecarregar o create sem poder chamar o super() mas ate agora nao achei... Vou parar por hoje.

**Comment by rvalyi** [comment]
sou teimoso, eu consegui...
tento subir o PR amanha... Mas so para dar um teaser, eu acho que é a maior gambiarra que eu já fiz no Odoo até agora. Sobrecarregando o create do account.move.line eu chego a fazer dentro:

```
    @api.model_create_multi
    def create(self, vals_list):
        ....
        type(self)._stock_only_items = set()
        for count, vals in enumerate(vals_list):
            if vals.get("is_stock_only"):
                type(self)._stock_only_items.add(count)
```
e depois eu faço um override de `def _get_fields_onchange_subtotal_model(...)` que não esta sendo chamado mais com um self relevante nem com argumentos suficiente, o que me obriga e jogar variaveis no dicionario do type(self) porque no self não pode porque ele tem um `__slot__` o que não permite de acrescentar algum attributo no `__dict__` do objeto e porque não posso botar um contador no self._context porque ele é um frozendict. Então nesse override eu chego a fazer:

```
    @api.model
    def _get_fields_onchange_subtotal_model(self, price_subtotal, move_type, currency, company, date):
        ....
        if not type(self)._create_vals_counter:
            type(self)._create_vals_counter = 0
        else:
            type(self)._create_vals_counter += 1
        if self.is_stock_only or type(self)._stock_only_items and type(self)._create_vals_counter in type(self)._stock_only_items:
            amount_currency = 0

```

bom, faz o trabalho, agora vamos ver se eu consigo dormir com uma gambiarra dessa na consciência rs

**Comment by marcelsavegnago** [comment]
cc @douglascstd @augustodinizl

**Comment by rvalyi** [comment]
Acabei atrasando por conta do SPED e da resolução dos testes do repo, mas eu pretendo arrumar logo o que eu tava fazendo.

**Comment by augustodinizl** [comment]
> sou teimoso, eu consegui...
> tento subir o PR amanha... Mas so para dar um teaser, eu acho que é a maior gambiarra que eu já fiz no Odoo até agora. Sobrecarregando o create do account.move.line eu chego a fazer dentro:
> 
> ```
>     @api.model_create_multi
>     def create(self, vals_list):
>         ....
>         type(self)._stock_only_items = set()
>         for count, vals in enumerate(vals_list):
>             if vals.get("is_stock_only"):
>                 type(self)._stock_only_items.add(count)
> ```
> e depois eu faço um override de `def _get_fields_onchange_subtotal_model(...)` que não esta sendo chamado mais com um self relevante nem com argumentos suficiente, o que me obriga e jogar variaveis no dicionario do type(self) porque no self não pode porque ele tem um `__slot__` o que não permite de acrescentar algum attributo no `__dict__` do objeto e porque não posso botar um contador no self._context porque ele é um frozendict. Então nesse override eu chego a fazer:
> 
> ```
>     @api.model
>     def _get_fields_onchange_subtotal_model(self, price_subtotal, move_type, currency, company, date):
>         ....
>         if not type(self)._create_vals_counter:
>             type(self)._create_vals_counter = 0
>         else:
>             type(self)._create_vals_counter += 1
>         if self.is_stock_only or type(self)._stock_only_items and type(self)._create_vals_counter in type(self)._stock_only_items:
>             amount_currency = 0
> 
> ```
> 
> bom, faz o trabalho, agora vamos ver se eu consigo dormir com uma gambiarra dessa na consciência rs

Cara, se até a SEFAZ opera com certificado vencido, o que é uma "gambiarrinha branca"?

Parabéns pelo trabalho à todos!!!!

**Comment by antoniospneto** [comment]
resolvido com o #2347
