### ISSUE TITLE
Atualização da tabela NCM

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2258]
É necessária a atualização da tabela NCM, foram incluídos novos códigos.
Sugestão: alguma API para atualização automática da tabela.

**Comment by antoniospneto** [comment]
Reparamos isso também,

Alguém sabe o melhor local/fonte para extrair esses dados atualizado ?
Algum lugar que já traga o código + descrição + taxa de ipi + taxa ii + unidade de medida, que ai acho que fica mais facil alimentar o CSV dos NCM que segue esse padrão:

**"id","code","exception","name","tax_ipi_id:id","tax_ii_id:id","uoe_id:id"**
"ncm_00000000","0000.00.00",,"Sem NCM",,,
"ncm_01012100","0101.21.00",,"Cavalos, asininos e muares, vivos. Cavalos: Reprodutores de raça pura","tax_ipi_nt","tax_ii_0","uom.product_uom_unit"

https://raw.githubusercontent.com/OCA/l10n-brazil/14.0/l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv

**Comment by rodmad85** [comment]
Os dados atualizados oficial são deste site.
[https://www.gov.br/receitafederal/pt-br/assuntos/aduana-e-comercio-exterior/classificacao-fiscal-de-mercadorias/download-ncm-nomenclatura-comum-do-mercosul](url)

**Comment by rodmad85** [comment]
ou deste
[https://portalunico.siscomex.gov.br/classif/#/sumario?perfil=publico](url)

**Comment by antoniospneto** [comment]
tem essa tabela TIPI que tem a informação do IPI:
https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/legislacao/documentos-e-arquivos/tipi-em-excel.xlsx

O tax_ii que é o imposto de importação eu não achei onde pegar, tem esse site para consulta mas não tem um formato para exportação:

https://www.mercosur.int/politica-comercial/ncm/

**Comment by antoniospneto** [comment]
resolvido com o #2470
