### ISSUE TITLE
[12.0][14.0][CNAB Cobrança][OFX] Conflito no uso do campo conta corrente, entre os módulos CNAB Cobrança e Importação de OXF

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2261]
Problema de incompatibilidade entre uso do campo Conta corrente, entre o app CNABCobrança e importação de OXF...
O app OFX usa o campo conta corrente.. e os arquivos OXFs dos bancos não tem um padrão de como compor a verificação com o campo OFX ACCTID

Existem bancos que usam o dígito, tem outros que usam sem dígito, outros incluem agência.

Imagino que o app CNAB Cobrança utiliza os campos da cota corrente (conta, dígito, agencia, dig da agência) da forma correta.
Agora para fazer a importação do OFX, para fazer funcionar, necessita incluir no campo conta corrente, o mesmo conteúdo do que o campo ACCTID do arquivo OFX..

Acho que, para ficar "Bonito", seria melhor ajustar o app importação OFX, ou até localizar para Brasil.

Campo ACCTID:
![image](https://user-images.githubusercontent.com/20867090/208436261-929b53db-bbe6-44dd-96b7-452b9f4994ef.png)

Campo Conta Corrente para atender CNAB:
![image](https://user-images.githubusercontent.com/20867090/208436563-d4568044-9fa7-4346-8e2e-763b6a889d88.png)

Campo Conta Corrente para atender Importação OFX:
![image](https://user-images.githubusercontent.com/20867090/208436968-2d53d573-eff6-4b86-9de9-18375a4295df.png)

Essa necessidade de incluir o campo ACCTID do OFX no campo "conta" da conta corrente, vai impactar na operação do CNAB Pagamento #2181 #2168 

## Module
l10n_br_account_payment_brcobranca
account_statement_import_ofx - https://github.com/OCA/bank-statement-import

1. Cadastrar conta corrente (Banco do Brasil) para atender as necessidades do CNAB Cobrança
2. Fazer importação de Arquivo OFX
3. Aparecerá o erro de que o arquivo OFX é incompatível

@mbcosta @marcelsavegnago @antoniospneto

**Comment by antoniospneto** [comment]
O módulo OFX vai cruzar o o valor de ACCTID com o campo "name" do modelo **partner.bank** (conta bancária)
nativamente o "name" é um valor computado com base no valor do "número da conta" minha sugestão é alterar o método que computa o "name" para incluir o digito verificador, ou permitir que o usuário defina um valor manualmente para o "name" já que cada banco pode assumir uma formatação diferente na forma de escrever a conta no "ACCTID".

**Comment by marcelsavegnago** [comment]
Olhando brevemente não vejo uma solução que seja diferente da criação do campo ACCTID no cadastro da conta. No caso, pelo pouco que vi parece que o deve precisar herdar o método https://github.com/OCA/bank-statement-import/blob/f70f63dd4453dcbbb969564a4d0b163d88575b99/account_statement_import/wizard/account_statement_import.py#L195 e incluir mais um teste quando a conta não é encontrada. 

```
@api.model
def _match_journal(self, account_number, currency):
       journal = super._match_journal(account_number, currency)
       if not journal and tipodoaqruivo == ofx:
           faz a busca pelo ACCTID
       return journal
```

Masssss não tenho certeza se resolveria.. precisaria olhar mais fundo :D. Debugar é preciso :D

**Comment by augustodinizl** [comment]
> https://github.com/OCA/bank-statement-import/blob/f70f63dd4453dcbbb969564a4d0b163d88575b99/account_statement_import/wizard/account_statement_import.py#L195

creio que uma boa abordagem, seja adicionar o campo ACCTID no modelo "res.partner.bank", em texto-puro, creio que aí possamos usar ele no .ofx pq o módulo de importação já consome os dados desse modelo, o que acham?

visto que essa configuração é algo simples demais, e de uma importância para a localização, creio que seja uma boa colocar tal campo no l10n_br_base que já insere alguns campos nesse modelo

**Comment by marcelsavegnago** [comment]
Eu entendo que isso pode ser feito no respositorio https://github.com/OCA/bank-statement-import/

Um modulo como account_statement_import_ofx_field_acctit (como sugerido pelo Douglas em algum lugar que nao lembro)

**Comment by augustodinizl** [comment]
consegui mapear a "origem" desse "problema", a dependência do módulo responsável (https://pypi.org/project/ofxparse/ no módulo: https://github.com/OCA/bank-statement-import/tree/14.0/account_statement_import_ofx), foi feita pra aceitar o número da conta sem o dígito, estou abrindo uma issue no módulo original pra ver o melhor curso-de-ação pra esse caso...

Quaisquer sugestões são extremamente bem-vindas

Ps.: coloquei essa issue lá no módulo original: https://github.com/OCA/bank-statement-import/issues/537

**Comment by mileo** [comment]
Podemos fechar esse PR visto que a solução já ocorreu no https://github.com/OCA/bank-statement-import/pull/539

**Comment by rvalyi** [comment]
sim
