### ISSUE TITLE
ICMS na base de calculo PIS e COFINS em compras

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#2262]
Hoje conseguimos facilmente retirar o ICMS da base do PIS e COFINS com a PR #1063, ativando a flag base_without_icms dentro do tax group. No caso de notas de saída já existe uma decisão do STF para a retirada da base, porém no caso de notas de entrada o entendimento não é tão certo e existe uma tendência a não alterar essa base. Alguns links explicando melhor esses entendimentos um tanto estranhos:

https://busca.legal/como-ficam-os-creditos-pis-e-da-cofins-com-decisao-stf/
https://www.jota.info/tributos-e-empresas/tributario/tese-do-seculo-entenda-julgamento-icms-base-pis-cofins-07032022

Essas informações também foram confirmados por contadores e consultorias contábeis que conhecemos. O fato é que muitas empresas preferem não retirar o ICMS da base de calculo nas notas de entrada. 

Assim pergunto: é possível fazer essa distinção da retirada do ICMS da base na entrada e na saída? Se sim, como? Se não, seria interessante essa funcionalidade para a localização? qual o melhor caminho que podemos seguir?

**Comment by marcelsavegnago** [comment]
cc @douglascstd

**Comment by crsilveira** [comment]
Consegui fazer isso , criando outro grupo do Pis e do Cofins,  tipo Grupo:  COFINS Remove Base

**Comment by felipemotter** [comment]
@crsilveira foi o que eu pensei também, mas acho um pouco estranho. Talvez jogar essa flag pra um outro modelo deixaria mais dinâmico.

**Comment by antoniospneto** [comment]
Com a nova MP do Governo: https://www12.senado.leg.br/noticias/materias/2023/01/13/mp-tira-icms-da-base-de-calculo-do-pis-e-da-cofins foi definido essa questão tornando não ser mais possível considerar o ICMS na base ao calcular os créditos de PIS e CONFIS na entrada.

Então acho que podemos fechar essa issue
