### ISSUE TITLE
[14.0] Documento Fiscal de Compra - Em Digitação

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2275]
Na 14.0 o status do documento fiscal fica Em Digitação e nao aparece nenhum botão de envio simbolico do documento fiscal igual na 12.0

![image](https://user-images.githubusercontent.com/3595132/209684081-e8cfa3cb-35c2-467f-9088-08779d90df25.png)

**Comment by rvalyi** [comment]
foi resolvido na 14
