### ISSUE TITLE
XML e do PDF de documentos fiscais emitidos por parceiros.

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2277]
Uma questão que pra mim ainda está pendente é persistência dos PDFs e XMLs de documentos fiscais emitidos pelos parceiros.

Entendo que seria possível (talvez com alguns ajustes.. nao sei) gerar tais arquivos com os próprios dados existentes no Odoo. Porém, nao sei se vale a pena o esforço e se seria mais correto do que persistir os arquivos originais.

Sendo assim entendo que temos duas opções: 

1. Persistir tais arquivos da mesma forma como são persistidos os arquivos de documentos emitidos pela compania
2. Criar campos especificos para tais documentos.

Na 1a opção se o campo file_report_id estiver como editável no modelo de dados l10n_br_fiscal.document.electronic já ajudaria na questão do PDF mas teria uma certa complexidade em relação ao XML já que precisaria de um evento de autorização e nele o arquivo. (Aqui vem uma segunda questão, permitir o registro de eventos em documentos fiscais emitidos por parceiros teria alguma necessidade. Por exemplo, cartas de correção geradas pelo parceiro, seria interessante ter isto registrado?). 
No caso do l10n_br_fiscal_closing em tese não precisaria de praticamente nenhuma mudança. Talvez só na forma de separar os arquivos no pdf.

Na 2a opção poderiamos ter dois campos do tipo binário, incluir na view e deixar visivel apenas para documentos que o emissor é o parceiro. No caso do l10n_br_fiscal_closing teria que adaptar para pegar tais arquivos para incluir no zip.

Enfim.. alguma ideia? 

cc @renatonlima @rvalyi @antoniospneto @felipemotter @douglascstd

**Comment by rvalyi** [comment]
> Uma questão que pra mim ainda está pendente é persistência dos PDFs e XMLs de documentos fiscais emitidos pelos parceiros.
> 
> Entendo que seria possível (talvez com alguns ajustes.. nao sei) gerar tais arquivos com os próprios dados existentes no Odoo. Porém, nao sei se vale a pena o esforço e se seria mais correto do que persistir os arquivos originais.

Realmente não valeria a pena não, temos que persistir os originais mesmos, na ha a menor duvida.

> 
> Sendo assim entendo que temos duas opções:
> 
> 1. Persistir tais arquivos da mesma forma como são persistidos os arquivos de documentos emitidos pela compania
> 2. Criar campos especificos para tais documentos.

Tem tb a opção 3 que é o que todo mundo faz fora do Brasil e que fazem nossos clientes aqui tb: enfiar o XML da NFe do fornecedor num anexo (ir.attachment) do invoice de entrada.

Sobre a forma como a gente gerencia os documentos de saída: vc tem que ver que esse lance da pasta de documentos fiscais de saída é tb muito uma arquitetura "legacy" da forma como funcionava a lib pysped que a gente usava inicialmente para transmitir. Outros emissores plugaveis como o UNINFE tem tb esses conceitos de pastas porque numa época de sistema no desktop era o facil de se fazer. Mas nem porque era o fácil ou o legacy é a coisa para se fazer. Pensa que cloud e pasta não andam muito bem junto (os tais dos "12 factors").

Eu acho que a gente pode amadurecer melhorias nisso, mas de imediato, te aconselho de jogar esses arquivos nos anexos.
Talvez poderia ter um campo calculado para apontar pro anexo certo?
Podemos sim extender o l10n_br_fiscal_closing para juntar esses anexos tb.

Sobre a questão dos campos e dos eventos e de DFe, o @renatonlima deve subir uns PRs esses dias tb (realmente o design dos eventos atual não atende muito bem, talvez vale a pena esperar ele subir a proposta de refator). Mas para mim o pre-requisito para implementar a DFe é de mudar do generateDS pro xsdata (sim aquele meu PR para testar), porque so assim a gente tem alguma chance de ter isso limpo sem ser mais código que depois fica sem manutenção.

**Comment by marcelsavegnago** [comment]
> Tem tb a opção 3 que é o que todo mundo faz fora do Brasil e que fazem nossos clientes aqui tb: enfiar o XML da NFe do fornecedor num anexo (ir.attachment) do invoice de entrada.

Por ora fiz uma proposta considerando a opção 3. A principio ficou simples e já atenderia muito bem.
https://github.com/OCA/l10n-brazil/pull/2278

**Comment by marcelsavegnago** [comment]
Fechando a Issue. Foi implementando na PR #2278
