### ISSUE TITLE
[14.0] Data do documento fiscal diferente da data da BILL

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2279]
O campo document_date do documento fiscal está não assume o valor do campo invoice_date da fatura e sim o do dia da criação do documento no sistema. Entendo que ao criar um documento fiscal a data do mesmo deveria ser igual a data da fatura.. certo?

**Comment by antoniospneto** [comment]
@marcelsavegnago foi fixado aqu: https://github.com/OCA/l10n-brazil/pull/2480
