### ISSUE TITLE
[14.0] l10n_br_stock_account - Erro ao abrir movimento de estoque

### ISSUE THREAD

**Issue by renanteixeira** [OCA/l10n-brazil#2281]
## Module
l10n_br_stock_account

## Describe the bug
Ao acessar um movimento de estoque e clicar sobre qualquer item, é apresentado o erro:
`Error: While parsing modifiers for field quantity_done: for modifier "readonly": Unknown field parent.state in domain
`

![image](https://user-images.githubusercontent.com/6026211/210645991-90b2a7c1-fb48-4cdb-a635-caf35ef7033b.png)

## To Reproduce
**Affected versions**:
Odoo CE e EE 14.0

1. Inventário -> Relatórios -> Movimentos de Estoque
2. Clicar sobre qualquer registro
![image](https://user-images.githubusercontent.com/6026211/210645913-57275c06-038c-44c3-9bde-8fe8585c8f68.png)
![image](https://user-images.githubusercontent.com/6026211/210645991-90b2a7c1-fb48-4cdb-a635-caf35ef7033b.png)

**Expected behavior**
Exibir a visão de formulário do modelo stock.move, a imagem abaixo é removendo o atributo:
https://github.com/OCA/l10n-brazil/blob/a58b8d7486f9546d03ac54bde1baabd305b63a72/l10n_br_stock_account/views/stock_account_view.xml#L31

![image](https://user-images.githubusercontent.com/6026211/210645576-fad9f60a-62fb-4ee6-b078-beadc4ebf267.png)

**Additional context**
Testes locais (CE e EE) e no Runboat

**Comment by rafnixg** [comment]
Hello @renanteixeira , were you able to find a solution to this problem?

**Comment by renanteixeira** [comment]
Hello @rafnixg 

For now, I'm using the option to comment the line below

https://github.com/OCA/l10n-brazil/blob/d9c11156b2f218d156f842621e6e21d50795d991/l10n_br_stock_account/views/stock_account_view.xml#L31

**Comment by rafnixg** [comment]
thanks for answering
