### ISSUE TITLE
[14.0] Erro ao instalar l10n_br_account_nfe

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [OCA/l10n-brazil#2283]
### Module
l10n_br_account_nfe

### Describe the bug
Estou com o seguinte erro ao instalar o módulo l10n_br_account_nfe
![image](https://user-images.githubusercontent.com/101650554/210874449-9996d6e8-cb18-43f1-b53a-0658edef79fe.png)

Alguém já teve o mesmo problema e solucionou?

**Comment by rvalyi** [comment]
se vc ta instalando o modulo com os dados de demo (parece que sim) verifique que vc ja carregou os dados de demo do modulo l10n_br_base e tb verifique se vc instalou os modulos l10n_br_coa_simples e l10n_br_coa_generic antes pois são necessarios pros dados de demo e teste. O hook que deve puxar esses 2 modulos na hora de instalar o l10n_br_account não esta funcionando na v14 (na v12 sim) e por isso deve ser feito manualmente, esse problema é conhecido, qualquer PR para resolver é bem vindo.
