### ISSUE TITLE
[ainda carece de investigação mais aprofundada] CNPJ/CPF não sendo renderizado em todas as ocorrências em uma SO

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2295]
Situação: Existem alguns casos na v14, onde foi notado um comportamento "aleatório", onde o CNPJ/CPF não é renderizado na tela view da SO
## Module
The name of the module that has a bug.
l10n_br_sale
## Describe the bug
Necessite
## To Reproduce
**Affected versions**:
14
1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

ping.: @marcelsavegnago

**Comment by marcos-mendez** [comment]
@augustodinizl fechou porque? foi resolvido? Eu tinha notado isso tmb

**Comment by augustodinizl** [comment]
> @augustodinizl fechou porque? foi resolvido? Eu tinha notado isso tmb

pq era uma personalização que não tinha sido aprovada a PR ainda, no código aprovado, esse erro não procede.
tem relação à variável VAT.

**Comment by marcos-mendez** [comment]
Obrigado

Em ter., 31 de jan. de 2023 às 11:41, Augusto D. Lisbôa <
***@***.***> escreveu:
