### ISSUE TITLE
[14.0] l10n_br_nfe - Endereço de Entrega da Fatura sem CPF / CNPJ

### ISSUE THREAD

**Issue by renanteixeira** [OCA/l10n-brazil#2299]
## Module
**l10n_br_nfe**

## Describe the bug
Quando é adicionado um endereço entrega na fatura (Pelo pedido de venda e utilizando o contato "filho" do tipo de "**Endereço de entrega**"), ao confirmar a fatura é exibido a mensagem:
`XML validation errors:Element '{http://www.portalfiscal.inf.br/nfe}xLgr': This element is not expected. Expected is one of ( {http://www.portalfiscal.inf.br/nfe}CNPJ, {http://www.portalfiscal.inf.br/nfe}CPF ).`

![image](https://user-images.githubusercontent.com/6026211/212706168-2a823483-e22e-41b4-840f-5290e1fb04b3.png)
![image](https://user-images.githubusercontent.com/6026211/212708990-34dc7499-6361-4ada-833b-3d09d9ff5c33.png)
![image](https://user-images.githubusercontent.com/6026211/212709089-74a4a3b8-7e29-4681-9c30-9ccf397baaf8.png)

![image](https://user-images.githubusercontent.com/6026211/212705677-600b4268-e78e-4f0c-bafd-4ec37ad8c0a5.png)
![image](https://user-images.githubusercontent.com/6026211/212705848-14f94dff-1c22-4ada-9f13-f26bc9f06fbd.png)

- Na view para adicionar um contato "filho" no Odoo, não é possível adicionar campos como CPF / CNPJ, nesse caso o padrão deveria ser o CNPJ / CPF do contato relacionado

![image](https://user-images.githubusercontent.com/6026211/212706034-4d870d90-565d-4f4b-a8c1-be4c7ef47c81.png)

- O problema é "Solucionado" quando é exibido direto o formulário completo do sub-contato, alterado para ser do tipo "Empresa" e informado o mesmo CNPJ do cadastro principal.

![image](https://user-images.githubusercontent.com/6026211/212709451-9766213c-7bf7-477d-a9e7-b1c753265a18.png)
![image](https://user-images.githubusercontent.com/6026211/212709579-2190be5d-ea01-49e1-92f5-ef051c2d73a9.png)

## To Reproduce
**Affected versions**:
14.0, CE e EE

1. Adicionar um contato do tipo "Endereço de Entrega" em qualquer contato com os dados fiscais completos (Empresa, CNPJ)
![image](https://user-images.githubusercontent.com/6026211/212710403-d12b784a-7c21-4473-8937-54abb55e5d68.png)
2. Realizar um pedido de venda, criação e confirmação da fatura.
![image](https://user-images.githubusercontent.com/6026211/212710513-ef46d192-cf24-43e1-be85-58fd004e9a32.png)

**Expected behavior**
É esperado que XML seja gerado com o campo CNPJ, CPF, ID do Estrangeiro na tag <entrega> caso seja definido um endereço de entrega na venda / fatura.

**Additional context**
Testado no Enterprise e Runboat

**Comment by antoniospneto** [comment]
Realmente essa forma nativa do endereço de entrega não se encaixa bem para o Brasil.. Mas não concordo que isso seja um bug, mas sim uma funcionalidade que falta implementar/adequar para a localização Brasileira.

**Comment by antoniospneto** [comment]
No Brasil é mais comum você selecionar um parceiro de verdade (commercial_partner) não um "contato" que é uma parte de outro parceiro.
