### ISSUE TITLE
[l10n_br_account] Calculo automatico do MVA ajustado referenciado na Tabela de ICMS dos estados

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#23]
![aliquota_icms](https://f.cloud.github.com/assets/1975978/1441717/f650745a-41af-11e3-9371-7288383f2aff.jpg)

Exemplo:

Ao comprar uma mercadoria com mesmo NCM de diferentes UFs o IVA ajustado deve ser caculado com referencia na formula:

MVA ajustada = [(1+ MVA-ST original) x (1 - ALQ inter) / (1- ALQ intra)] -1

Hoje o openerp só permite que utilizemos o MVA ajustado

**Comment by Daniel-Furcht** [comment]
Lembrando ainda que temos mais uma variável envolvida. Certos produtos de uma mesma NCM podem ter alíquotas podem ter alíquotas interestaduais diferenciadas. Por exemplo a  8471.70.12 (Discos Rígidos) podem ter alíquotas interestaduais de 12% ou 4% conforme índice de nacionalização. Com isso a MVA ajustada muda muito... Para diferenciar podemos usar as CSTs, mas teríamos de duplicar a NCM em questão.

**Comment by mileo** [comment]
Exato.

Cheguei em uma solução não muito elegante da seguinte forma criado dois
campos no account.tax:

1 - fields.boolean ( Marcar para calular a MVA ajustada )
2 - ICMS Intraestadual

No calculo da icms st caso o boolean estivesse selecionado calculava a MVA
ajustada.
Funcionou legal com 4 linhas de código.

O mais ideal era que a tabela de icms por estado existisse... Devo resolver
esse problema definitivamente na próxima semana mas o importante é propor
um merge que seja aceito beneficiando a todos e que não impacte quem já
esta em produçao na 7.0.

[]s

Em 30 de outubro de 2013 21:53, Daniel Furcht
notifications@github.comescreveu:

> Lembrando ainda que temos mais uma variável envolvida. Certos produtos de
> uma mesma NCM podem ter alíquotas podem ter alíquotas interestaduais
> diferenciadas. Por exemplo a 8471.70.12 (Discos Rígidos) podem ter
> alíquotas interestaduais de 12% ou 4% conforme índice de nacionalização.
> Com isso a MVA ajustada muda muito... Para diferenciar podemos usar as
> CSTs, mas teríamos de duplicar a NCM em questão.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/23#issuecomment-27450449
> .

## 

Luis Felipe Miléo
skype: luisfelipemileo
http://mileo.co http://blog.mileo.co
https://launchpad.net/~mileo
https://github.com/mileo

**Comment by Daniel-Furcht** [comment]
Jogando no ventilador..
E se isso fosse definido nas regras  de posição fiscal, afinal ali da para capturar se a operação é interna ou interestadual.
A fórmula tambem pode ser sempre a mesma, independente de ser estadual ou interestadual, pois se as alíquotas forem iguais, a MVA Interna = MVA Ajustada.
MVA Ajus    MVA Orig    Aliq.Inter  Aliq.Intra
34,00%  34,00%  12,00%  12,00%
42,07%  34,00%  12,00%  17,00%
54,99%  34,00%  4,00%   17,00%

**Comment by mileo** [comment]
l10n_br/account.py
http://pastebin.com/sZuUUtua
l10n_br_account/account
http://pastebin.com/NnhxHKuR

[]s

**Comment by mileo** [comment]
UP

**Comment by mileo** [comment]
@kram3r @renatonlima

**Comment by mileo** [comment]
@danimaribeiro

**Comment by danimaribeiro** [comment]
Parece certo,
não sei o calculo correto.

**Comment by renatonlima** [comment]
Olá Pessoal,

Este issue é um pouco antigo (de 2013) eu já fiz esta mudança em 2014, com a mudança, você pode informar no ICMS ST além do MVA a alíquota de ICMS de destino e é feito o calculo do diferencial corretamente. Eu criei recetemente um issue para adicionar o percentual limite de crédito do ICMS da operação de destino https://github.com/OCA/l10n-brazil/issues/205 porque em alguns casos quando a aliquota de origem é menos do que a de destino o ICMS ST sai negativo.

**Comment by renatonlima** [comment]
@mileo @danimaribeiro 

Nos testes que eu coloquei no OCA/8.0 faz um testes de uma NFe com ICMS ST, https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/test/account_customer_invoice.yml#L317

Um produto tem MVA e o outro apenas a diferença de alíquota, neste caso falta apenas implementar o https://github.com/OCA/l10n-brazil/issues/205

**Comment by renatonlima** [comment]
Então acho que dar para fechar este issue
