### ISSUE TITLE
Implementar a conexão via /orders no módulo payment_pagseguro

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2308]
Estamos homologando pagamentos com o payment_pagseguro de acordo com os e-mails trocados com o pagseguro o endpoint que deve ser utilizado agora não é mais o /charges e sim o /orders. 

![image](https://user-images.githubusercontent.com/3595132/213724019-eb4f536e-f5cd-4911-9250-bdbb82f7dfce.png)

@mileo está sabendo de algo ?

cc @augustodinizl @douglascstd

**Comment by marcos-mendez** [comment]
Marcel é isso mesmo acho. Eu uso eles tmb

**Comment by mileo** [comment]
Verifiquei e o direcionamento esta correto. Devemos implementar a integração com o /orders.
