### ISSUE TITLE
[14.0] Valores: "adicionais" (Frete, Seguro, Outros) e descontos nas Purchase lines não estão contabilizando na purchase order, ou na Bill

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2313]
## Module
l10n_br_purchase
## Describe the bug
Os seguintes valores: 
![image](https://user-images.githubusercontent.com/25938418/214144077-9d5555ab-080c-44aa-aff7-9312326afc30.png)
não estão mapeados nas Purchase orders, sendo somente visíveis nas linhas, no form inicial e na view do documento fiscal, porém não são contabilizados na P.O, e na bill.
Além disso, o desconto inserido nas linhas da fatura de fornecedor, também não é considerado nos cálculos.
## To Reproduce
Crie uma Purchase order e tente criar uma bill assim como cria uma "sale order", estabelecendo custor de frete, seguro e outros.
**Affected versions**:
14.0

**Expected behavior**
Poderíamos considerar o fluxo de tais informações como sendo exatamente o mesmo adotado nas sale.order.

**Additional context**
![Screenshot at Jan 23 17-07-23](https://user-images.githubusercontent.com/25938418/214145434-458df02d-a3c2-47e7-bbfd-8a62c7357679.png)
![Screenshot at Jan 23 17-06-30](https://user-images.githubusercontent.com/25938418/214145458-bc4137be-1840-4da5-8006-16bf861b3e22.png)
![Screenshot at Jan 23 17-03-36](https://user-images.githubusercontent.com/25938418/214145466-73ee5296-c187-4ad2-be35-2592dfd33f08.png)
![Screenshot at Jan 23 17-02-47](https://user-images.githubusercontent.com/25938418/214145472-3e23cd52-7ab4-49ac-83ef-80a450591b6d.png)
![Screenshot at Jan 23 17-01-26](https://user-images.githubusercontent.com/25938418/214145474-1ac5a004-25b0-4f95-82b6-ac8e0e7393e3.png)
![Screenshot at Jan 23 16-36-48](https://user-images.githubusercontent.com/25938418/214145477-a7236ae5-c111-492a-94e2-c4d28bba982a.png)

O que acham? @marcelsavegnago , @douglascstd

**Comment by marcelsavegnago** [comment]
@augustodinizl este problema ainda persiste ?

**Comment by augustodinizl** [comment]
@marcelsavegnago , apesar de tais valores não virem ainda explicitados no total da invoice gerada, os mesmos estão somados no total, acredito que falte somente um ajuste "estético", porém eu poderia fechar esta issue se mais pessoas concordarem, pois os totais estão somando corretamente agora. 
![image](https://github.com/OCA/l10n-brazil/assets/25938418/6173495b-868b-4b4b-8532-337991a81e2b)
