### ISSUE TITLE
Possui patrimônios no repositório OCA

### ISSUE THREAD

**Issue by GuilhermeKimoto** [OCA/l10n-brazil#2324]
Boa Tarde pessoal, OCA possui módulo de gerenciamento de Patrimônios ?

**Comment by marcos-mendez** [comment]
Sim, inventory pressume valorização de patrimonio, stock-warehouse e etc

Em ter., 31 de jan. de 2023 às 17:53, Guilherme Kimoto <
***@***.***> escreveu:

**Comment by antoniospneto** [comment]
@GuilhermeKimoto bem vindo a comunidade.

Esse espaço é especifico para reportar bugs relacionados aos módulos da localização Brasileira. 
Para essas outras duvidas, você pode usar o canal no Telegram: https://t.me/odoobrazil ou o próprio forum do Odoo: https://www.odoo.com/pt_BR/forum.

Mas sim, existe um módulo na OCA para esse fim: https://odoo-community.org/shop/assets-management-82#attr=9357

Lembre sempre de pesquisar os termos em inglês você achará mais facilmente no Google.
