### ISSUE TITLE
[14.0] ERRO NO CALCULO DE IMPOSTOS: ICMS COM CALCULO INCORRETO

### ISSUE THREAD

**Issue by GabrielBatista191** [OCA/l10n-brazil#2327]
## Module
l10n_br_fiscal

## Describe the bug
Quando eu faço uma ordem de compras e no produto, coloco os impostos relacionados (ipi, cofins e icms) o icsm não está utilizando o valor base para calcular a sua porcentagem, exemplo: produto R$ 1.249,95, PIS1,65% R$ 20,62; ICMS12% R$ 149,99,00 TOTAL = R$ 1.420,00(calculo correto). No caso, o ICMS está pegando a soma do produto + pis e calculando em cima desse valor. Só que, no final do calculo total, apenas o PIS está sendo usado, o ICMS mesmo somando errado, está vindo zerado.

**PIS CALCULADO CERTO**
![image](https://user-images.githubusercontent.com/71337084/216065967-6360cd92-169d-4ed9-8856-08bc48b4182f.png)

**ICMS CALCULADO ERRADO, USANDO A SOMA BASE DO PRODUTO + PIS**
![image](https://user-images.githubusercontent.com/71337084/216066107-30f267b0-62ed-4265-9e96-45dfc5ccedb1.png)

**VALOR TOTAL SÓ COM O PIS CALCULADO E SEM O ICMS**(_QUE FOI CALCULADO ERRADO_) **ADICIONADO**
![image](https://user-images.githubusercontent.com/71337084/216066300-4a846c1a-6abe-4f7e-91b3-c495f0b05fb6.png)

 
## To Reproduce
Vendas > Pedidos > Criar um pedido de venda > Adicionar os impostos(pis, icms) 

**Expected behavior**
O valor do icms tem que ser calculado com base no valor do produto e ser adicionado no valor total

**Comment by antoniospneto** [comment]
Consegue postar uma foto de como está o lançamento das linhas contábeis ? aba journal itens.
Obs: você tem que ativar a opção mostrar contabilidade completa na configuração de permissões do usuário.

Eu acho que faltou configurar os impostos dedutíveis e ativar a flag pra remover o pis da base do ICMS.

**Comment by GabrielBatista191** [comment]
@antoniospneto 
![image](https://user-images.githubusercontent.com/71337084/216072298-9fe154c5-ea44-4449-bcdc-5fab8b664295.png)
Essa foto é de uma solicitação de cotação, que está com o mesmo erro. Há algum campo em especifico que não esteja ai que queira ver?

**Comment by GabrielBatista191** [comment]
@antoniospneto 
**ESSE É UMA SOLICITAÇÃO DE COTAÇÃO BEM SIMILAR**
![image](https://user-images.githubusercontent.com/71337084/216072790-2c1379d3-3855-478f-86d3-b9c19a65bdc1.png)


**ESSE É O ITENS DE DIARIO DELA** 
![image](https://user-images.githubusercontent.com/71337084/216073010-e6382d25-84dc-4d82-9c87-53ec4892ef25.png)

**Comment by felipemotter** [comment]
@GabrielBatista191 não sei se entendi direito. Mas você está querendo adicionar o valor do icms mais o valor do produto?

Até onde eu sei, o total com icms, pis e cofins vai ser o próprio valor do produto. Você não adiciona ao valor total, ele já está incluso.

A base do ICMS é o total dos produtos num geral(tem excessões).

Referente a base do PIS e Cofins, ela é o valor dos produtos menos o ICMS.

**Comment by antoniospneto** [comment]
você confirmou a fatura ? confirma ela para os impostos aparecerem nos itens do diário

**Comment by GabrielBatista191** [comment]
@felipemotter Não adicionar, mas no exemplo dessa ultima nota, apenas o imposto do IPI que da 75 reais, está sendo calculado em cima do valor dos produtos. O icms está sendo calculado em cima do valor do produto + frete + pis. e ele devia ser calculado em cima apenas do produto.

**Comment by GabrielBatista191** [comment]
@antoniospneto confirmei sim, está até paga, la aparece todos os impostos, mas os cálculos estão errados. O icms é calculado de forma errada e não é adicionado ao valor final da nota.

**Comment by GabrielBatista191** [comment]
![image](https://user-images.githubusercontent.com/71337084/216080049-24891acf-c5ae-42f1-9780-c27ca63400a3.png)


A base para o ICMS é 1500, mas ele está usando 1500 do produto + 75 do IPI + 200 de frete

**Comment by felipemotter** [comment]
A venda é para consumidor final? Se for, esse é o comportamento esperado.

https://onclick.com.br/inclusao-do-frete-na-base-de-calculo-do-icms-e-do-icms-st/

**Comment by GabrielBatista191** [comment]
@felipemotter Não, Felipe. Tanto venda quanto compra são todas B2B

**Comment by felipemotter** [comment]
Verifique suas configurações, como está o perfil fiscal do cliente, como estão as operações e até mesmo o ICMS.

**Comment by GabrielBatista191** [comment]
@felipemotter 
![image](https://user-images.githubusercontent.com/71337084/216150076-d80f1d9a-6137-47ca-b1a9-2b707531f1c8.png)
essa foto ficou mais explicativa a respeito do calculo dos impostos

**Comment by GabrielBatista191** [comment]
@felipemotter @antoniospneto Há alguma configuração prévia de instalação de aplicativos? ou configurações para empresas B2B?

**Comment by antoniospneto** [comment]
@GabrielBatista191 tente debugar a parte onde a calcula base do ICMS, veja quais os parâmetros que ele recebe e se estão corretos, a configuração dos impostos é um pouco complexa, depende de muitos modelos, se você debugar vai encontrar o erro mais rapidamente.
