### ISSUE TITLE
[14.0] Erro ao instalar l10n_br_cnab_structure

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [OCA/l10n-brazil#2328]
## Module
l10n_br_cnab_structure

## Describe the bug
Ao instalar o módulo CNAB Structure, obtenho o seguinte erro:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: Carregamento do Módulo l10n_br_cnab_structure falhou: arquivo l10n_br_cnab_structure/data/l10n_br_cnab.structure.csv não pode ser processado:
 Nenhum registro encontrado para id externo 'l10n_br_account_payment_order.payment_mode_type_cnab240_out' no campo 'Payment Method'

```

![image](https://user-images.githubusercontent.com/101650554/216074919-78936db9-a563-48dc-86a4-37adc6603de2.png)

**Comment by antoniospneto** [comment]
@IgorOliveiraAX4B 

Esse dado que ele não encontrou ele busca do módulo l10n_br_account_payment_order
Confira se o módulo está atualizado, qualquer coisa atualize ele só para garantir.

**Comment by igoroliveira-ax4b** [comment]
Resolvido
Além disso tive que instalar sem demo data
Obrigado!
