### ISSUE TITLE
[14.0] Smartbutton Detalhes Fiscais com mensagem de erro

### ISSUE THREAD

**Issue by LFPSGS** [OCA/l10n-brazil#2336]
Ao criar uma fatura no Odoo 14 e postá-la, o módulo l10n_br_account cria um smartbutton chamado "Detalhes Fiscais" (open_fiscal_document) e é um botão herdado da view l10n_br_account.invoice.form.

Ao clicar no botão, recebo uma mensagem de erro: "Please select multiple invoices to merge in the list view.". Pelo que eu entendi olhando o arquivo account_invoice.py essa action chama um método que determina qual o tipo de documento fiscal está atrelado à fatura para chamar uma view apropriada. Este erro é um problema intermitente, porque me parece que as vezes o contexto está carregado e funciona e as vezes não.

![Screen Shot 2023-02-08 at 17 51 53](https://user-images.githubusercontent.com/29111440/217648302-bcab70e9-6a0a-40ad-8991-eee91353f28d.png)

Não seria mais simples colocar um smartbutton com um link direto para uma view padrão de notas fiscais?

Enfim, agradeço à ajuda!
Luiz Fernando Gondin

**Comment by felipemotter** [comment]
@LFPSGS não consegui replicar o comportamento, é preciso de mais informações para poder entender o que está acontecendo. (que tipo de fatura e documento é, por onde você iniciou o processo, etc)


Se você quer encontrar uma solução ou a origem do problema, recomendo debugar para chegar a origem.

**Comment by LFPSGS** [comment]
@felipemotter Eu criei uma fatura de cliente simples (direto no Faturamento > Clientes | sem um pedido de venda), com 1 linha de produto e configurei 1 tipo de documento como NFE Modelo 55 (cod, nome, prefixo, sufixo, sequencia e serie), o resto foi preenchimento padrão do Odoo (condição de pagamento, forma de pagamento, produto, preço, operação (venda), impostos).

Simultaneamente, no app Fiscal, o Odoo criou um documento  (Outgoing Document) com a sequencia e serie configurada no tipo de documento. Se eu vou através do app Fiscal, eu consigo transmitir a NFE normalmente, a única coisa estranha é o comportamento desse botão.

**Comment by antoniospneto** [comment]
@LFPSGS você chegou a verificar se pelo runboat o comportamento é o mesmo ? eu tentei reproduzir o erro aqui mas sem sucesso, quando eu clico no "Detalhes Fiscais" a visão abre normalmente:

![image](https://user-images.githubusercontent.com/634278/217684336-c5f4ea6a-e61b-4cfe-b262-ec187623f33a.png)

Como o @felipemotter disse, recomendo debugar o Odoo para tentar identificar a origem do problema.
