### ISSUE TITLE
[14.0] Erro ao tentar abri "Documento Fiscal"

### ISSUE THREAD

**Issue by GabrielBatista191** [OCA/l10n-brazil#2340]
Olá pessoal! Estou com esse erro ao acessar o **Documento fiscal** 

![image](https://user-images.githubusercontent.com/71337084/218180106-76548684-5b32-4316-90d1-3b12dc776511.png)

. **Fiscal > configuração > Documento Fiscal**. Tentamos debugar o código mas ainda sim, o erro não está claro pra nós de onde vem. Já o  viram antes?

**Comment by antoniospneto** [comment]
@GabrielBatista191 testei aqui, mas não consegui reproduzir o erro pelo runboat : http://oca-l10n-brazil-14-0-4aaa48a85317.runboat.odoo-community.org/

Como pode ver a visão dos tipos de documentos fiscais está abrindo certinho:

![image](https://user-images.githubusercontent.com/634278/218183803-4ff9ed3d-d155-4e9c-ba0a-5c5f23964d7f.png)


tem certeza que sua base tá atualizada ? veja no terminal do servidor se é apresentando mais informação do erro.

**Comment by antoniospneto** [comment]
Como não houve como reproduzir o erro acho que essa issue pode ser fechada

@OCA/local-brazil-maintainers
