### ISSUE TITLE
l10n_br_nfe: Perca das regras de acesso aos modelos da NF-e após atualizar o Odoo.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2349]
## Módulos
l10n_br_nfe
l10n_br_nfe_spec
spec_drive_model

## Descrição do Bug

Após atualizar o módulo **l10n_br_nfe_spec** todas as regras de acessos aos modelos da NF-e são perdidos.
Ao tentar acessar uma nota fiscal  o seguinte erro é exibido:
```
INFO devel odoo.addons.base.models.ir_model: Access Denied by ACLs for operation: read, uid: 2, model: nfe.40.vol 
WARNING devel odoo.http: You are not allowed to access 'Dados dos volumes' (nfe.40.vol) records.

No group currently allows this operation.

Contact your administrator to request access if necessary. 
```

## Para reproduzir:
**Versões afetadas**:

12.0
14.0

Etapas para reproduzir o comportamento:
1. Inicie uma base limpa do Odoo.
2. Instale o módulo l10n_br_nfe
3. Atualize o módulo l10n_br_nfe_spec
4. Tentar acessar ou criar um documento fiscal de uma NF-e
5. Você irá receber o seguinte erro de acesso:
![image](https://user-images.githubusercontent.com/634278/219824964-f4b5d1b4-24a6-472b-be3f-81638e68106c.png)

**Comportamento esperado**

A visualização da nota fiscal deveria ser exibida sem problemas.

## O que eu acho que pode estar causando o problema

As regras de controle de acesso para os modelos envolvendo a NF-e não são inseridas do jeito tradicional, é de forma dinâmica, por um script (hook) que é chamado na instalação do módulo  spec_driven_model.

O que acontece é que ao atualizar o módulo o Odoo pensa que todas essas restrições devem ser deletadas, pois os registros existem no banco de dados mas não existem mais dentro dos arquivos data do módulo (mecanismo padrão do Odoo)

O script que está no hook resolveria o problema, porém na atualização o mesmo não é chamado, permanecendo assim a implementação deste Odoo sem os ACLs para os modelos da NF-e.

**Comment by antoniospneto** [comment]
ah esqueci de comentar, se desinstalar o módulo spec_driven_model e instalar de volta o problema resolve, só que talvez pode ser perigoso fazer isso em produção, alguns dados podem ser perdidos.
Uma solução para resolver em produção é adicionar as regras de volta manualmente.

**Comment by marcelsavegnago** [comment]
Eu estou com duas instancias q soh de derrubar o servico odoo e subir novamente ja da pau nas.colunas da nfe. A forma de resolver neste caso eh atualizando o modulo... vou tentar simular local e printar a msg de erro.. obs. V14

**Comment by antoniospneto** [comment]
Legal @marcelsavegnago seu comentário vai ser importante pra gente entender melhor certinho o que tá acontecendo
