### ISSUE TITLE
[14.0][BUG] Erro no l10n_br_account envolvendo hash no account.move

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#2350]
Fim da semana passada entrou alguns commits no odoo/odoo na versão 14.0 referente ao hash no account move e pelo visto quebrou a compatibilidade da localização.

Erro ao instalar o l10n_br_account:
parte 1:
![erro-1](https://user-images.githubusercontent.com/6812128/220161470-bc81e269-c8dd-45d8-8b21-9b2b44e69366.png)
parte 2:
![erro-2](https://user-images.githubusercontent.com/6812128/220161478-ebb171a6-c07a-43ca-b881-4c21751bbe81.png)

Commit em questão: https://github.com/odoo/odoo/commit/1dcd071b27779e7d6d8f536c7dce7002d27212ba

**Comment by antoniospneto** [comment]
Eu testei aqui localmente e consegui resolver removendo o campo **active** dos modelo **document** e **document_line**
não sei exatamente o por que mas é isso que está conflitando com algo..
