### ISSUE TITLE
[14.0][BUG] Erro de formatação da chave ao salvar NFSe emitida pelo parceiro

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#2355]
Ao salvar uma NFSe emitida pelo fornecedor, ocorre um erro de formatação da chave de acesso conforme abaixo:

![image](https://user-images.githubusercontent.com/6812128/221177109-7bf27c23-55ec-43c0-9b5d-c23ce4623810.png)

Para poder salvar a fatura, apenas deixamos o campo em branco, mas o cliente preferia que a informação fosse salva também, existe alguma solução para isso?

**Comment by antoniospneto** [comment]
O campo da chave `document_key`  é bem específico para NF-e / NFC-e 

Para NFS-e o correto é utilizar o campo `verify_code` (código de verificação) fiz uma pr para melhorar a utilização deste campo: https://github.com/OCA/l10n-brazil/pull/2440

Eu acho que seria também interessante esconder o campo `document_key` (chave) quando o documento for uma nota fiscal de serviço.
