### ISSUE TITLE
[12.0] Faturamento: Preço do produto é alterado quando troca um imposto

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2367]
1. Crie uma nova fatura de venda e adicione o produto "Serviço de Comissão" a ela. O preço padrão do produto deve ser carregado automaticamente.
2. Verifique o valor do produto na fatura e altere-o para qualquer valor diferente do preço padrão. Por exemplo, altere o valor de R$ 100 para R$ 150.
3. Troque o imposto de "INSS" para qualquer outro imposto, como "INSS 11%", por exemplo.
4. Verifique que o preço do produto voltou a ser o preço padrão de R$ 100, em vez do valor alterado anteriormente de R$ 150.

Obs. Teste feito no runboat

cc @rvalyi @antoniospneto @renatonlima @felipemotter @douglascstd @augustodinizl

**Comment by antoniospneto** [comment]
@marcelsavegnago isso ainda é um problema ? na 14.0 eu testei e isso não acontece mais.

**Comment by marcelsavegnago** [comment]
Acredito que não seja problema mais. Caso eu identifique algo pode deixar que reabro a Issue
