### ISSUE TITLE
14.0 - Impostos duplicados ao gerar a fatura. valor da fatura divergente da cotação. calculando imposto a mais.

### ISSUE THREAD

**Issue by marcelomarcon** [OCA/l10n-brazil#2373]
## Module
l10n_brazil > l10n_br_account -> **Brazilian Localization Account**

## Describe the bug
Usando a versão 14.0 da OCA l10n_Brazil quando adicionado os impostos de ICMS, IPI, PIS, COFINS os mesmos ficam com o valor dobrado na geração da fatura. exemplo. se a venda é de 1000,00 e o icms é de 12%. ao invez de ficar com imposto de 120,00. ele fica como 240,00. isso ocorre tambem para os outros impostos. 

Para resolver isso memomentaneamente. foi alterado o arquivo.  `/l10n-brazil/l10n_br_account/models/account_invoice.py` na linha 365 e alterado de: `taxes_mapped[grouping_key]["amount"] += tax_vals["amount"]` 
para `taxes_mapped[grouping_key]["amount"] = tax_vals["amount"]`

isso resolveu a parte dos impostos estarem com seus valores dobrados. porem o valor ainda difere da cotação e na fatura. 

**Fatura antes de realizar a alteração do arquivo acima. os impostos estão duplicando os valores.**
![image](https://user-images.githubusercontent.com/85348507/223210398-ca07fcd7-bb2b-47c4-b3b1-6e16d3ffbf94.png)

**Cotação na imagem abaixo com a alteração.**
![image](https://user-images.githubusercontent.com/85348507/223205120-9ee5028c-6346-498a-aaa3-9400dc2f20c0.png)

**Fatura na imagem abaixo com a alteração do script mostrada acima.**
![image](https://user-images.githubusercontent.com/85348507/223205219-6d614bb0-7cea-4b1f-9664-fb8eee5acd4e.png)

Ambos estão com o valor final diferente. na fatura. deveria estar com o valor tambem de 1050,00 reais. somando o 1000,00 apenas o IPI de 5%.

## To Reproduce
1 - Criar uma nova cotaçao em Vendas > Pedidos > Cotações.
2 - Ao adicionar o produto e colocar seu valor como exemplo 1000,00. acessar o item do pedido ( produto ) ir na aba contabilidade e adicionar os impostos. exemplo. IPI SAIDA 5%, ICMS SAIDA 12%, PIS SAIDA 0.65%, COFINS 3%.
![image](https://user-images.githubusercontent.com/85348507/223206312-3aa05a58-01ef-47db-9404-7c8591247137.png)

3 - Confirmar, e clicar na statusbar Entrega.
![image](https://user-images.githubusercontent.com/85348507/223206526-2f21b251-2859-471f-acd3-da16f2618621.png)

4 - Acessar a parte de entrega e clicar em validar. ( deve ter produto em estoque ).
![image](https://user-images.githubusercontent.com/85348507/223206770-138f541f-0d31-4987-ba37-c458b633ecdf.png)

5 - Após clicar em validar. volte na aba de cotações e gere uma fatura clicando no botão "criar fatura" abaixo de editar.
![image](https://user-images.githubusercontent.com/85348507/223206981-8f317fee-c628-40d5-984f-f94822a41425.png)
6 - Com a fatura criada. click em fatura na statusbar no canto superior direito.
![image](https://user-images.githubusercontent.com/85348507/223207182-6912f095-73b5-4fb6-83ad-c9236c419478.png)

**Expected behavior**
O valor final da fatura deve estar igual ao valor final da cotação. no caso de 1050.00 ( um mil e cinquenta reais ).

**Additional context**
`Odoo 14.0, Python 3.8, Ubuntu server 20.04 LTS, Postgres 14`

**Comment by rvalyi** [comment]
Ola @marcelomarcon realmente a gente começou a testar essa parte dos totais de impostos nos objetos Odoo so recentemente na 14.0, seria interessante vc testar tb com essa minha PR https://github.com/OCA/l10n-brazil/pull/2363 pois corrige algumas coisas relacionadas a totais de impostos, seria interessante se vc puder testar o mesmo cenário com esse PR e dar um retorno... A principio na v12 essas coisas funcionam então não deveria ser impossível resolver na 14.0

**Comment by marcelomarcon** [comment]
> Ola @marcelomarcon realmente a gente começou a testar essa parte dos totais de impostos nos objetos Odoo so recentemente na 14.0, seria interessante vc testar tb com essa minha PR #2363 pois corrige algumas coisas relacionadas a totais de impostos, seria interessante se vc puder testar o mesmo cenário com esse PR e dar um retorno... A principio na v12 essas coisas funcionam então não deveria ser impossível resolver na 14.0

OLá @rvalyi. eu passei 3 dias debugando para tentar encontrar o que estava acontecendo. eu consegui apenas resolver a parte da duplicaçõa dos impostos. mas não consegui encontrar como ele ainda está somando os outros impostos. fiquei um bom tempo debugando e passando por todas as funções. em relação a sua PR #2363, eu cheguei a testar na quinta feira. e estava ( ao menos para min ) com o mesmo erro. ainda duplicando os valores e tambem trazendo a somatória dos impostos. não sei se houve alguma alteração desde la ou faltam alguma configuração de minha parte. se tiver alguma atualização sobre ou quiser que eu realize um novo teste. estou a disposição. estarei baixando a mesma nesse momento para realizar o teste novamente. obrigado.

**Comment by ATSTI** [comment]
Fiz os testes aqui tbém, e cheguei no mesmo problema, mesmo usando o PR #2363.

**Comment by felipemotter** [comment]
Veja se a PR #2347 ajuda

**Comment by ATSTI** [comment]
Aqui pra mim, não mudou nada, mesmo com este PR :

**Comment by ATSTI** [comment]
Aqui pra mim, não mudou nada, mesmo com este PR :
![ksnip_20230313-115643](https://user-images.githubusercontent.com/5469157/224740768-e9ff6d36-da73-43bb-aa87-53a8eb044d5e.png)
![ksnip_20230313-115648](https://user-images.githubusercontent.com/5469157/224741326-7344070c-6cbd-4c5b-bbcf-7d51d029f3f3.png)

**Comment by ATSTI** [comment]
uma coisa q vi diferente no que vc colocou lá, é que o seu IPI , tem débito e crédito nele, aqui eu não credito o IPI.

**Comment by antoniospneto** [comment]
> Aqui pra mim, não mudou nada, mesmo com este PR : ![ksnip_20230313-115643](https://user-images.githubusercontent.com/5469157/224740768-e9ff6d36-da73-43bb-aa87-53a8eb044d5e.png) ![ksnip_20230313-115648](https://user-images.githubusercontent.com/5469157/224741326-7344070c-6cbd-4c5b-bbcf-7d51d029f3f3.png)

ATSTI, mas explique por favor quais são os erros que você notou nesse seu caso.
pois os valores no lançamento contábeis parecem estar corretos.
O valor total da fatura tbm está ok.
Única coisa que eu notei de errado é o caso do ICMS ali no rodapé está sendo exibido zerado, mas isso é um problema que não está sendo abordada na PR #2347 do @felipemotter , mas a gente comentou sobre e o motivo disto estar acontecendo.

**Comment by ATSTI** [comment]
o Total devia ser  1.100 e não 1.200, ( qtde 100 x 10,00 = 1.000 + 100,00 (10% ipi) ).
Os valores contábeis corretos , seriam : 
    Manutenção - D - 1.000
    IPI Entrada  -  D -    100
    Mercado      -  C - 1.100

**Comment by antoniospneto** [comment]
> o Total devia ser 1.100 e não 1.200, ( qtde 100 x 10,00 = 1.000 + 100,00 (10% ipi) ). Os valores contábeis corretos , seriam : Manutenção - D - 1.000 IPI Entrada - D - 100 Mercado - C - 1.100

ah sim, desculpe olhei rápido de mais e me confundi,  no seu caso se vc ativou a dedução dos impostos, da forma que o sistema está hoje vc deve configurar uma linha dedutível para todos, inclusive para o IPI. 

O sistema somou o IPI na linha do serviço de manutenção, pq ele espera que você vá deduzir ele, mas como não foi configurado a linha de dedução do IPI, essa diferença acaba sendo jogada para o valor da fatura.

**Comment by ATSTI** [comment]
desmarcando a dedução dos impostos , realmente esta correto o valor , vou fazer mais testes .
![ksnip_20230313-173550](https://user-images.githubusercontent.com/5469157/224826591-2565ca29-6292-453a-a228-fd8ccc1035dd.png)

**Comment by antoniospneto** [comment]
@marcelomarcon  se puder testar novamente com a base atualizada, os lançamentos contábeis estão ok na 14.0 atual.
