### ISSUE TITLE
[l10n_br_account] Lentidão ao validar NF

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#24]
Alguns clientes tem observado uma lentidão ao validar a NF. Testando na minha maquina:

Ubuntu 13.04
Intel® Core™ i7-3517U CPU @ 1.90GHz × 4 
64-bit
8gb de RAM, DDR3
HD SSD 

Uma NF com 150 itens demora em media 3 minutos para ser aprovada.

Se for mesmo esse tempo para um NF grande com varias parcelas (6x) seria interesante criar uma ação a ser processada no servidor para que o usuário continue trabalhando.

Alguem observou algo semelhante?

Tentei simular sem a localização foi bem rápido.

Abraços

**Comment by mileo** [comment]
Caso utilize worker=5 (2x numero de cores cpu + 1)

Recebo uma mensagem de estouro de CPU ...

Acredito que haja algo errado com o algoritmo, mas ainda estou tentando detectar onde esta o problema.

Se alguém tiver um problema parecido, fique a vontade para entrar em contato.

OBS: Como que coloca label nos issues?

**Comment by rvalyi** [comment]
Ola Luis,

o que tem que investigar nesse caso sao os writes e o re-calculo dos campos
calculados em seguida. Provavelmente tem como fazer otimizaçoes. Se
precisamos pedir mudanças de API no core é essential detetar onde antes da
v8 sair, para nao ficar blocado assim mais um ano.
ode tb analisar se teria como usar a chave "multi" nos campos calculados
para nao re-calcular coisas.

O multi-core nao vai ajudar aqui. Isso nao é paralelisado no Python nao
(alem disso o Python tem o GIL
https://wiki.python.org/moin/GlobalInterpreterLock ) que impediria esse
tipo de coisa. A unica coisa e que ao botar worker > 1 ele va usar o
Gunicorn e usar os parametros padroes deles (possiveis de mudar pela conf)
de timeout e max de memoria para monitorar os workers do Gunicorn, no seu
caso 3 minutos estora o timeout padrao. A unica coisa que o Gunicorn
paralelisa sao os requests em paralelo por examplo quando tem varios
usuarios.

Atts.

2013/10/31 Luis Felipe Miléo notifications@github.com

> Caso utilize worker=5 (2x numero de cores cpu + 1)
> 
> Recebo uma mensagem de estouro de CPU ...
> 
> Acredito que haja algo errado com o algoritmo, mas ainda estou tentando
> detectar onde esta o problema.
> 
> Se alguém tiver um problema parecido, fique a vontade para entrar em
> contato.
> 
> OBS: Como que coloca label nos issues?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/24#issuecomment-27533577
> .

## 

Raphaël Valyi
Founder and consultant
http://twitter.com/rvalyi http://twitter.com/#!/rvalyi
+55 21 2516 2954
www.akretion.com

**Comment by mileo** [comment]
Boa Noite Rafa,

Obrigado pela dica, vamos aos testes:

workers = 5
limit_memory_soft = 671088640
limit_memory_hard = 805306368
limit_request = 8192

p/ 300s / 5 minutos:

limit_time_cpu = 300
limit_time_real = 300

Nada de aprovar a NF e nenhum erro apresentado

p/ 3600s / 1 hora:

limit_time_cpu = 3600
limit_time_real = 3600

Fui fazer outra coisa e esperei aprovar não sei quanto tempo deu.

p/ 600s / 10 minutos:

limit_time_cpu = 600
limit_time_real = 600

A nf aprovou com 04 min e 06 s

Será que alguém consegue testar um caso semelhante uma nf com mais de 100
itens?

Abraços

Em 31 de outubro de 2013 21:09, Raphaël Valyi
notifications@github.comescreveu:

> Ola Luis,
> 
> o que tem que investigar nesse caso sao os writes e o re-calculo dos
> campos
> calculados em seguida. Provavelmente tem como fazer otimizaçoes. Se
> precisamos pedir mudanças de API no core é essential detetar onde antes da
> v8 sair, para nao ficar blocado assim mais um ano.
> ode tb analisar se teria como usar a chave "multi" nos campos calculados
> para nao re-calcular coisas.
> 
> O multi-core nao vai ajudar aqui. Isso nao é paralelisado no Python nao
> (alem disso o Python tem o GIL
> https://wiki.python.org/moin/GlobalInterpreterLock ) que impediria esse
> tipo de coisa. A unica coisa e que ao botar worker > 1 ele va usar o
> Gunicorn e usar os parametros padroes deles (possiveis de mudar pela conf)
> de timeout e max de memoria para monitorar os workers do Gunicorn, no seu
> caso 3 minutos estora o timeout padrao. A unica coisa que o Gunicorn
> paralelisa sao os requests em paralelo por examplo quando tem varios
> usuarios.
> 
> Atts.
> 
> 2013/10/31 Luis Felipe Miléo notifications@github.com
> 
> > Caso utilize worker=5 (2x numero de cores cpu + 1)
> > 
> > Recebo uma mensagem de estouro de CPU ...
> > 
> > Acredito que haja algo errado com o algoritmo, mas ainda estou tentando
> > detectar onde esta o problema.
> > 
> > Se alguém tiver um problema parecido, fique a vontade para entrar em
> > contato.
> > 
> > OBS: Como que coloca label nos issues?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/openerpbrasil/l10n_br_core/issues/24#issuecomment-27533577>
> > 
> > .
> 
> ## 
> 
> Raphaël Valyi
> Founder and consultant
> http://twitter.com/rvalyi http://twitter.com/#!/rvalyi
> +55 21 2516 2954
> www.akretion.com
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/24#issuecomment-27536829
> .

## 

Luis Felipe Miléo
skype: luisfelipemileo
http://mileo.co http://blog.mileo.co
https://launchpad.net/~mileo
https://github.com/mileo

**Comment by Daniel-Furcht** [comment]
Não tenho base de dados para estes testes. Tens algo como base de testes para isso?
Trabalho na area de servidores, posso fazer testes de otimização do postgresql e do python.

**Comment by mileo** [comment]
Me add no skype nos falamos

[]s

Em 1 de novembro de 2013 00:54, Daniel Furcht
notifications@github.comescreveu:

> Não tenho base de dados para estes testes. Tens algo como base de testes
> para isso?
> Trabalho na area de servidores, posso fazer testes de otimização do
> postgresql e do python.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/24#issuecomment-27544831
> .

## 

Luis Felipe Miléo
skype: luisfelipemileo
http://mileo.co http://blog.mileo.co
https://launchpad.net/~mileo
https://github.com/mileo

**Comment by mileo** [comment]
OpenERP:
[image: Imagem inline 1]

Postgres:
[image: Imagem inline 3]

Em 1 de novembro de 2013 01:01, Luis Felipe Miléo luisfelipe@mileo.coescreveu:

> Me add no skype nos falamos
> 
> []s
> 
> Em 1 de novembro de 2013 00:54, Daniel Furcht notifications@github.comescreveu:
> 
> Não tenho base de dados para estes testes. Tens algo como base de testes
> 
> > para isso?
> > Trabalho na area de servidores, posso fazer testes de otimização do
> > postgresql e do python.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/24#issuecomment-27544831
> > .
> 
> ## 
> 
> Luis Felipe Miléo
> skype: luisfelipemileo
> http://mileo.co http://blog.mileo.co
> https://launchpad.net/~mileo
> https://github.com/mileo

## 

Luis Felipe Miléo
skype: luisfelipemileo
http://mileo.co http://blog.mileo.co
https://launchpad.net/~mileo
https://github.com/mileo

**Comment by mileo** [comment]
Ai botei um script que insere umas as taxas coringas nas todas ncms....
Isso sim fez o postgres trabalhar um pouco.... De resto tinha processamento
e memoria de sobra sempre.

[image: Imagem inline 1]

Em 1 de novembro de 2013 16:07, Luis Felipe Miléo luisfelipe@mileo.coescreveu:

> OpenERP:
> [image: Imagem inline 1]
> 
> Postgres:
> [image: Imagem inline 3]
> 
> Em 1 de novembro de 2013 01:01, Luis Felipe Miléo luisfelipe@mileo.coescreveu:
> 
> Me add no skype nos falamos
> 
> > []s
> > 
> > Em 1 de novembro de 2013 00:54, Daniel Furcht notifications@github.comescreveu:
> > 
> > Não tenho base de dados para estes testes. Tens algo como base de testes
> > 
> > > para isso?
> > > Trabalho na area de servidores, posso fazer testes de otimização do
> > > postgresql e do python.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/24#issuecomment-27544831
> > > .
> > 
> > ## 
> > 
> > Luis Felipe Miléo
> > skype: luisfelipemileo
> > http://mileo.co http://blog.mileo.co
> > https://launchpad.net/~mileo
> > https://github.com/mileo
> 
> ## 
> 
> Luis Felipe Miléo
> skype: luisfelipemileo
> http://mileo.co http://blog.mileo.co
> https://launchpad.net/~mileo
> https://github.com/mileo

## 

Luis Felipe Miléo
skype: luisfelipemileo
http://mileo.co http://blog.mileo.co
https://launchpad.net/~mileo
https://github.com/mileo

**Comment by Daniel-Furcht** [comment]
Não consigo ver as imagens....

**Comment by rvalyi** [comment]
Luis,

outra coisa que voce poderia fuçar seria verificar os index nos campos da localizaçao e ver se addicionar alguns accelera sensivelmente a coisa (select=True na declaraçao do campo)

Atts.

**Comment by mileo** [comment]
@rvalyi : Vou ter que olhar isso mais quando sobrar um tempo. Obrigado

Algo que pude constatar rapidamente que boa parte da demora esta relacionada a chamada função no account.invoice da localização action_move_create.

Mas implementar a função sem a chamada do super tem que ser bem estudado.

Atts
