### ISSUE TITLE
[14.0] Erro no cálculo de impostos

### ISSUE THREAD

**Issue by klausmoreira** [OCA/l10n-brazil#2409]
## Module
l10n_br_account

## Describe the bug
O seguinte problema ocorre:
Configuro as taxas para Revenda (ICMS, PIS, IPI, COFINS)
Quando gero um uma cotação de venda com produto de custo exemplo R$ 500,00, tenho ali no total da cotação R$525,00, sendo 500 do produto e 25 do IPI (5%).
Ao faturar, não tenho os impostos e não tenho os itens de diário correspondente aos impostos

1 - Cotação (valor exibindo IPI de 5%)
![1](https://user-images.githubusercontent.com/129325740/228641918-8d07c3eb-28ba-4e2a-9109-4863bb2aa668.png)

2 - Faturamento, impostos sendo exibindos na tabela One2many, porém não constam no total
![2](https://user-images.githubusercontent.com/129325740/228642034-e3c6e9d6-0a40-4bd3-ba63-340c7a89f28b.png)

3 - Faturamento, impostos não são criados no 'Itens de diário'
![3](https://user-images.githubusercontent.com/129325740/228642118-478ce6f2-3f54-474e-9a30-5024280595cc.png)

**Comment by douglascstd** [comment]
Cheguei a ver um problema parecido. Klaus você pode fazer um teste, e fazer uma alteração na linha da fatura (apenas para constar mudança e executar o "on change")

Quando acontecia comigo, detectei que o erro era que na emissão da fatura não estava sendo executado os calculos novamente dos impostos, e não preenchia o lançamento de diário com os impostos. Com esse "on change" os impostos eram carregados corretamente.

**Comment by douglascstd** [comment]
acabei de ver que tem um PR que deve resolver isso: #2416

**Comment by antoniospneto** [comment]
@klausmoreira se puder testar novamente com a base atualizada.. se possivel pelo runboat. Essas questões dos lançamentos contábeis das faturas já estão funcionando bem na 14.0 atual.
