### ISSUE TITLE
Nada acontece ao tentar ativar a MDF-e e CT-e

### ISSUE THREAD

**Issue by luiz-alonso** [OCA/l10n-brazil#2413]
## Module
Fiscal

## Describe the bug
Tentei ativar a MDF-e e CT-e os campo de checkbox retorna para false

## To Reproduce
runboat b67da7eb

1. Definições -> Fiscal
2. Ativar checkbox MDF-e e CT-e
3. Salvar

**Comment by felipemotter** [comment]
Estes documentos fiscais não estão funcionais.

**Comment by luiz-alonso** [comment]
Oi Felipe bom dia! 
Entendi e obrigado pelo retorno.
