### ISSUE TITLE
[14.0] Impostos no Itens de Diário

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [OCA/l10n-brazil#2415]
### Module
l10n_br_account

### Describe the bug
O erro ocorre ao gerar uma fatura, seja pelo pedido de venda, ou criando a fatura direto, os lançamentos de impostos estão sendo somados ao valor do produto que já está com os impostos incusos.
Como exemplo a imagem abaixo, as linhas de impostos estão somando ao valor de R$1050,00 (que já é o valor do produto + ICMS + IPI + PIS + COFINS)
![image](https://user-images.githubusercontent.com/101650554/229843737-76d85344-fe16-4137-a6c5-171a115921ff.png)

**Comment by marcelsavegnago** [comment]
@IgorOliveiraAX4B tem algumas PRs relacionadas. Seria importante uma ajuda na revisão, testes e afins

https://github.com/OCA/l10n-brazil/pull/2412
https://github.com/OCA/l10n-brazil/pull/2408
https://github.com/OCA/l10n-brazil/pull/2363

Outra coisa.. se estiver interessado em contribuir o primeiro passo seria assinar a CLA https://odoo-community.org/about/cla (facilita na hora de citar vc em alguma PR ou até mesmo solicitar revisão)

**Comment by rvalyi** [comment]
e agora #2416 ainda...

**Comment by douglascstd** [comment]
Igor, se você puder detalhar melhor o caminho que vc fez para chegar neste problema, isso ajuda a reproduzir e verificar se não tem alguma configuração errada.

Qual versão?
Esse teste foi feito no runboat? (se não, você consegue reproduzir?)
Quais são os passos para conseguir reproduzir o mesmo erro?

@IgorOliveiraAX4B IgorOliveiraAX4B

**Comment by antoniospneto** [comment]
@IgorOliveiraAX4B  essa parte do lançamento contabeis está funcionando bem atualmente, se puder testar novamente..
