### ISSUE TITLE
[14.0] [l10n_br_base] import 'email_validator'

### ISSUE THREAD

**Issue by rpsjr** [OCA/l10n-brazil#2421]
odoo     | 2023-04-07 16:16:19,287 1 ERROR sindifam werkzeug: Error on request:
odoo     | Traceback (most recent call last):
odoo     |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
odoo     |     execute(self.server.app)
odoo     |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
odoo     |     application_iter = app(environ, start_response)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
odoo     |     return self.app(e, s)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
odoo     |     return application_unproxied(environ, start_response)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
odoo     |     result = odoo.http.root(environ, start_response)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
odoo     |     return self.dispatch(environ, start_response)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in __call__
odoo     |     return self.app(environ, start_wrapped)
odoo     |   File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 766, in __call__
odoo     |     return self.app(environ, start_response)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1460, in dispatch
odoo     |     odoo.registry(db).check_signaling()
odoo     |   File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 104, in registry
odoo     |     return modules.registry.Registry(database_name)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 65, in __new__
odoo     |     return cls.new(db_name)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
odoo     |     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 457, in load_modules
odoo     |     force, status, report, loaded_modules, update_module, models_to_check)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 349, in load_marked_modules
odoo     |     perform_checks=perform_checks, models_to_check=models_to_check
odoo     |   File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 179, in load_module_graph
odoo     |     load_openerp_module(package.name)
odoo     |   File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 385, in load_openerp_module
odoo     |     __import__('odoo.addons.' + module_name)
odoo     |   File "/odoo/external-src/l10n-brazil/l10n_br_base/__init__.py", line 6, in <module>
odoo     |     from . import models
odoo     |   File "/odoo/external-src/l10n-brazil/l10n_br_base/models/__init__.py", line 15, in <module>
odoo     |     from . import res_partner_pix
odoo     |   File "/odoo/external-src/l10n-brazil/l10n_br_base/models/res_partner_pix.py", line 6, in <module>
odoo     |     from email_validator import EmailSyntaxError, validate_email
odoo     | ModuleNotFoundError: No module named 'email_validator' - - -

## Module
l10n_br_base

## Describe the bug
missing email_validator python dependence 

## To Reproduce
**Affected versions**:v14

1. install l10n_br_base without email_validator py3

**Expected behavior**
manifest py3 dependence been check stops module installation

**Comment by rvalyi** [comment]
ola @rpsjr isso não parece ser bug nehnum, é apenas que na sua instalação está faltando o pacote python email_validator que é dependência desde as melhorias feitas pela Engenere para suportar as chaves PIX no modulo l10n_br_base. vc pode acrescentar ele no seu requirements.txt se vc usar ou com com python -m pip install email_validator. Por favor confirme se resolve.

**Comment by rvalyi** [comment]
obs: apenas jogar o módulo Odoo no addons path e instalar não puxa as eventuais dependências não. Mas se vc instalar o módulo OCA pelo pip, ele puxa, porém no geral na Akretion a gente acha que instalar os módulos Odoo pelo pip acaba tornando os desenvolvimento e o debug mais complexo e a gente não recomenda de instalar os módulos OCA pelo pip, ou pelo menos até que o Odoo e o ecosistema dele se torna mais estavel, que é algo que a gente ainda accredita que vai acontecer...

**Comment by rpsjr** [comment]
Perfeito!
