### ISSUE TITLE
[14.0][BUG]l10n_br_fiscal not allowed in the multicompany configuration

### ISSUE THREAD

**Issue by rosi-quintero** [OCA/l10n-brazil#2446]
We are testing the multicompany configuration and altought it works with a single company, when multicompany is activated the Account Packages are not selectable. This generates an error when creating a res.partner in the contacts module. 

Im sending 2 printscreen so you can check this

![Screenshot from 2023-04-17 16-06-58](https://user-images.githubusercontent.com/87678132/232586999-f5be901e-b9bd-4a6c-9c77-13e641308c55.png)
![Screenshot from 2023-04-17 16-09-58](https://user-images.githubusercontent.com/87678132/232587115-c6ae462c-0d7d-4f04-acfb-628dc411b591.png)

I'll appretiate if someone can guide me on this settings as i didn't found any documentation available.

Thanks

**Comment by douglascstd** [comment]
I guess it's missing COA configuration, that's indicate the payable and receivable account in the partners.

The workaround it fullfil the fields on the partners forms

**Comment by rvalyi** [comment]
My bet is about the same as Douglas: in the accounting configuration, you should first ensure each company as its own Chart Of Account generated properly. We use the localization with multi-companies with nearly all our customers at Akretion, so the design is pretty solid for supporting it... 

That being said, make no mistake, a  multi-companies setup of Odoo (specially in your case) is still very challenging, make sure the person pretending to implement it has a solid 5 years of Odoo experience first or look for another company (unless you are willing to eat these years of learning curve yourself).
