### ISSUE TITLE
[14.0][BUG] - l10n_br_fiscal Ao ocorrer erro de digitação ou alteração do documento

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#2447]
Ao ser alterado o CPF/CNPJ do vendedor na view do res.parnter (no caso deste exemplo) especificamente se houve um erro de digitação por exemplo o campo nfe40_CNPJ e nfe40_CPF na tabela res_partner não é atualizado.

Ou seja se preserva o primeiro valor digitado mesmo este sendo equivocado

Talvez o ideal seja colocar um onchange para reparar esta falha já que isto impossibilita a emissão de NFe neste caso (se for um CNPJ invalido ou CPF inválido)

**Comment by marcos-mendez** [comment]
Complementando o erro, seria interessante também que ao clicar no action button do vendedor ao envés de abrir o res.user abrisse o res.partner para já efetuar a correção destas informações já que atualmente o botão abre o res.user

![image](https://user-images.githubusercontent.com/38361760/232909293-a8f54232-08b9-4c42-b770-00540e0b6a78.png)

**Comment by marcelsavegnago** [comment]
> Complementando o erro, seria interessante também que ao clicar no action button do vendedor ao envés de abrir o res.user abrisse o res.partner para já efetuar a correção destas informações já que atualmente o botão abre o res.user

@marcos-mendez esse comportamento nao é nativo do Odoo não ? se for, não caberia isso na localização e sim direto na Odoo ou algum módulo novo para a OCA (em algum repo como account-invoicing talvez...)

**Comment by marcelsavegnago** [comment]
@marcos-mendez Eu sugiro que tente abrir as issues com um assunto por vez. Este complemento que vc fez não parece ter relação alguma com o problema relatado ou estou enganado ?

**Comment by marcos-mendez** [comment]
@marcelsavegnago eu acho que são coisas relacionadas @marcelsavegnago veja que ao alterar o CPF do vendedor ou dados do "emitente" como é tratado pelo ORM o Odoo não atualiza o campo nfe40_CNPJ e nem o nfe40_CPF. 

Se esta alterção precisa ser corrigida precisa ser corrigida na localização pois no Odoo normal não existe sequer este campo

Ao mesmo tempo se precisa ser corrigida na l10n_br acredito que também deva ser corrigido o botão onde se acesam estes dados (atualmente ao clicar na caixinha azul do lado do nome do vendedor abre o res.user, e não o res.partner, adicionando passaso adicionais ao processo)

PS: Me chama a atenção que isso tenha passado pois inviabiliza 100% o funcionamento do l10n_br_fiscal caso tenha sido usado um CNPJ gerado ou CPF gerado para testes.

**Comment by marcelsavegnago** [comment]
> Ao mesmo tempo se precisa ser corrigida na l10n_br acredito que também deva ser corrigido o botão onde se acesam estes dados (atualmente ao clicar na caixinha azul do lado do nome do vendedor abre o res.user, e não o res.partner, adicionando passaso adicionais ao processo)

Pelo que entendi, o campo "vendedor" é implementado pelo Odoo. Se for esse o caso, acredito que a localização (l10n_br) não precise modificar a abertura do campo para exibir o res.partner em vez do res.user, a menos que essa funcionalidade tenha sido implementada especificamente pela localização.

Em minha opinião, essa demanda não parece ser algo que deva ser tratado na localização. Além disso, acredito que não há motivos para classificá-la como um BUG.

Entendo que essa questão se refere exclusivamente ao modelo de dados do vendedor e não aos outros tópicos. Porém, mesmo que seja necessário melhorar o fluxo, se outros usuários estiverem interessados, esse interesse seria comum, independentemente da localização no Brasil.

Dessa forma, acredito que é importante avaliar cuidadosamente a necessidade e o impacto de qualquer modificação no modelo de dados do vendedor antes de tomar uma decisão sobre como proceder.

**Comment by antoniospneto** [comment]
Confirmo que realmente havia o problema, mas o mesmo foi reparado aqui https://github.com/OCA/l10n-brazil/pull/2505

@marcos-mendez podemos fechar a issue ?

**Comment by marcos-mendez** [comment]
Obrigado Neto mais uma vez a comunidade a tua responsavelmente amen. Digo isso porque depois ainda tenho que ser chamado no grupo do telegram de 171 ou coisas piores. NADA mais nocivo para uma comunidade open source do que um líder com o ego tóxico e com transtornos napoleonicos. Obrigado novamente amanhã cedo farei o Pull novamente e atualizarei o meu repositório.

**Comment by antoniospneto** [comment]
@marcos-mendez 

> Obrigado Neto mais uma vez a comunidade a tua responsavelmente amen. Digo isso porque depois ainda tenho que ser chamado no grupo do telegram de 171 ou coisas piores. NADA mais nocivo para uma comunidade open source do que um líder com o ego tóxico e com transtornos napoleonicos. Obrigado novamente amanhã cedo farei o Pull novamente e atualizarei o meu repositório.

@marcos-mendez 

Obrigado por compartilhar seus sentimentos sobre a liderança do projeto. Percebo que você está chateado com algumas críticas que recebeu, mas, do meu ponto de vista, acredito que o líder do projeto tem contribuído de forma significativa.

Em minha experiência, ele tem mostrado abertura para o diálogo e recebido críticas de maneira construtiva. Entendo que existam diferenças de percepção e que às vezes possa haver desentendimentos, mas isso faz parte do processo de trabalho em equipe/comunidade.

As críticas, por mais duras que possam parecer, são, na maioria das vezes, oportunidades para crescermos e melhorarmos. Por mais que seja difícil recebê-las, é fundamental para o nosso desenvolvimento pessoal e profissional.

Eu encorajo você a tentar enxergar as críticas como uma oportunidade de aprendizado e melhoria, e usá-las como uma ferramenta para aprimorar suas futuras contribuições. Ao mesmo tempo, todos nós, incluindo o líder do projeto, podemos trabalhar para melhorar a maneira como damos e recebemos feedback.

**Comment by marcos-mendez** [comment]
Adoro seu espirito progressista Neto. vou me reservar a testes e fico feliz
com isso. Abraços

PS: Essa do CNPJ no 14 tava dando alguma outra treta, mas acabava afetando
o bus.bus que acho que é com o Odoo lida com a mensageria. eu descobri isso
por acaso com um Firebase que tenho integrado, se achar de novo ele reporto
nessa mesa issue pra facilita o rastreamento. Abraço

Em dom., 11 de jun. de 2023 às 22:14, Antônio Neto ***@***.***>
escreveu:
