### ISSUE TITLE
[14.0][bug]l10n_br_fiscal - Contato Técnico exclusivo CNPJ

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#2450]
Explicitar que o campo contato técnico deve ser um res.partner do tipo empresa com CNPJ Infelizmente isto não está claro e infezlimente o XML é gerado erroneamente! Caso o responsável for uma pessoa fisica dentro de uma empresa herdada como 
![image](https://user-images.githubusercontent.com/38361760/233179901-5ca14005-6260-4961-a88b-5bfcd5601df6.png)

O mesmo não vale para o contado o que é bem estranho

Aliás poderia ser colocado um filtro para que só is_company=true no domain fosse filtrado. 

 [image](https://user-images.githubusercontent.com/38361760/233178893-2b5c3407-b9b2-4756-b2bd-dee482242b42.png)

![image](https://user-images.githubusercontent.com/38361760/233179322-3c2f78f0-1fb5-46da-8937-49b1f0b5f3a8.png)
XML gerado como CPF infelizmente não é aceito e também não está explicito no código

**Comment by antoniospneto** [comment]
O problema existe de fato, mas não é nada crucial, acho que o foco do pessoal está em resolver outros problemas mais sérios, um usuário normal nem terá acesso a essa tela apenas o administrador do sistema. 
Claro que se alguém fizer uma PR com essa correção será bem vinda e estará ajudando a melhorar a usabilidade na localização.

**Comment by pablomatoskmee** [comment]
Pra eu entender melhor, a correção é para que o campo 'Contador' e 'Suporte Técnico', busquem e aceitem somente res.partner do tipo company, certo?

**Comment by antoniospneto** [comment]
só pra deixar linkado, a solução está sendo proposta aqui #2531
