### ISSUE TITLE
[14.0] KeyError: 'nfe40_choice4' na nota de crédito parcial

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#2477]
Estamos com esse problema em um cliente ao confirmar uma nota de crédito parcial:
![image](https://github.com/OCA/l10n-brazil/assets/6812128/34b0789a-5f62-42a6-a7e1-91b50db56317)

@rvalyi você sabe o que pode ser?

**Comment by rvalyi** [comment]
Olá @felipemotter : sim cópia a definição desse campo do módulo l10n_br_nfe_spec de antes do merge da semana passada e cópia ela manualmente no objeto onde o mixin era injectado no módulo l10n_br_nfe.

Eh porque o generateDS gerava esses campos choice a partir do xsd. Mas o xsdata não (e mesmo se a gente fizesse no xsdata-odoo a numeração poderia mudar, essa numeração era um ponto de fragilidade no generateDS de qualquer forma, podia ter uma atualização de xsd com alguma NT que ia bagunçar a numeração toda).

Deve ser bem simples de resolver. Nem todos campos choice são utilizados, mas alguns são e esse parece ser e eu esqueci ele.

Mas é super simples de resolver. Deu para
 entender? Manda um PR depos por favor.

**Comment by rvalyi** [comment]
esse problema pode ser diferente mas é semelhante a esse na 12 https://github.com/OCA/l10n-brazil/issues/2473

**Comment by felipemotter** [comment]
@rvalyi pretendo mexer nisso logo, assim que tiver a solução eu mando a PR.

**Comment by rvalyi** [comment]
corrigido por https://github.com/OCA/l10n-brazil/pull/2478
