### ISSUE TITLE
Erro de "operation line" ao inserir uma nota (anotação) numa PO

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2494]
Ao tentar inserir uma nota numa Purchase order line, o sistema acusa falta do preenchimento no campo: Operation line .
Tal comportamento não ocorre na Sale order line
## Module

l10n-purchase_stock

## Describe the bug
Ao tentar inserir uma nota numa Purchase order line, o sistema acusa falta do preenchimento no campo: Operation line .
Tal comportamento não ocorre na Sale order line

## To Reproduce
**Affected versions**:
14.0
1. Crie uma Purchase order
2. Adicione um produto
3. tente inserir uma "nota" abaixo do produto

**Expected behavior**
Tal linha, possui aspecto não-fiscal, e seria somente um campo de anotações, portanto, não necessita do campo "operation"

**Additional context**
![telegram-cloud-photo-size-1-5143202841832303435-y](https://github.com/OCA/l10n-brazil/assets/25938418/5fdda1c3-ee1d-41bb-9cf2-4115e26f6084)

ping: @marcelsavegnago @douglascstd

**Comment by antoniospneto** [comment]
@augustodinizl com as PRs https://github.com/OCA/l10n-brazil/pull/2866, https://github.com/OCA/l10n-brazil/pull/2907
talvez esse problema tenha sido resolvido, no pedido de vendas é de certeza, mas é bom conferir se no compras tá ok também.
Pode conferir novamente?

**Comment by augustodinizl** [comment]
> conferir se no compras tá ok

Graaaande @antoniospneto , bom dia, acabei de testar no runboat, no compras ainda não foi... 
![image](https://github.com/OCA/l10n-brazil/assets/25938418/b661259d-2099-4c3b-ac0f-8a1e15bb22fa)
