### ISSUE TITLE
CFOP incorreto na Fatura

### ISSUE THREAD

**Issue by Daniel-Furcht** [OCA/l10n-brazil#25]
O CFOP na fatura depende da ordem das alterações no pedido de venda.
Ex.: Ordem que funciona corretamente:
Seleciona cliente,
aba "Outras Informações", seleciona possibilidades das Regras Posição Fiscal (Padrão = Revenda, seleciono Venda ST).
Seleciona o Produto
Confirma.

Que não funciona:
Seleciona cliente,
Seleciona produto,
aba "Outras Informações", seleciona possibilidades das Regras Posição Fiscal (Padrão = Revenda, seleciono Venda ST).
Confirma.

Neste segundo caso o CFOP não é alterado na fatura, ficando com informação obtida do padrão "Revenda".

**Comment by renatonlima** [comment]
Daniel,

Hoje nos documentos como pedido de venda, compras, movimentações de estoque e documentos fiscais (Notas fiscais) existe os campos categoria fiscal e posição fiscal nos objetos e nas linhas (para ter a possibilidade de ter CFOP diferentes em cada linha dos documentos) porém os campos categoria fiscal e posição fiscal nos documentos servem apenas como um valor padrão no momento em que é criado as linhas, depois que você criar um pedido de venda e as linhas do pedido por exemplo se você alterar esses campos no pedido de venda, ele não vai alterar as linhas do pedido, porque o que deve prevalecer é os dados das linhas.

**Comment by Daniel-Furcht** [comment]
Ola Renato. Correto o que escreveste, mas o que constatei que as alterações no pedido de venda não vão corretamente para a fatura...

**Comment by renatonlima** [comment]
Você quer dizer no pedido de venda ou nos itens?

**Comment by Daniel-Furcht** [comment]
No pedido, se alterar após selecionar os produtos e confirmar o pedido, esta alteração não fica na fatura, ou seja, no pedido esta alterado e na fatura aparece o default da empresa.
