### ISSUE TITLE
'base_address_city'. 

### ISSUE THREAD

**Issue by RenanBelarmino** [OCA/l10n-brazil#2503]
Alguem esta com problema ao chamar esse modulo ?
'base_address_city'. 

Você está tentando instalar o módulo 'l10n_br_base_2' que depende do módulo 'base_address_city'.
Mas este último não está disponível no seu sistema.

![image](https://github.com/OCA/l10n-brazil/assets/69680055/cee3dbd6-2fa7-44e4-b6bc-30fd069b5ade)

**Comment by antoniospneto** [comment]
@RenanBelarmino o seu problema não parece ser da localização já que o módulo **l10n_br_base_2** não faz parte do repositório.

Obs: o módulo **base_address_city** é nativo do odoo, confira se a pasta addons dentro do odoo não mexido por engano..

**Comment by moigamijunior** [comment]
Encontramos uma solução?

**Comment by marcelsavegnago** [comment]
A pasta deste módulo está dentro da pasta addons do core do Odoo ? Deveria estar lá :)

**Comment by moigamijunior** [comment]
Obrigado pela resposta, Marcel! Parece que o Odoo 16 alterou o módulo para `base_address_extended`. Apenas alterei as dependências em `__manifest__.py` e em uma view e foi resolvido. Grato!

**Comment by candidocassio** [comment]
Vi esse comentário no YT:

 para o Odoo 16 o base_address_city se encontra no base_address_extended. Então para que você possa instalar os módulos, terá que substituir as referencias a base_address_city por base_address_extended nos arquivos __manifest__.py (linha 15:  { 'base_address_city,}  --> { 'base_address_extended',} ) e res_city.xml (linha 5: { <field name="inherit_id" ref="base_address_city.view_city_tree" />}  --> { <field name="inherit_id" ref="base_address_extended.view_city_tree" />)}

Porém, depois da alteração, continuo recebendo os mesmo erros. 

Depois somente, fiz a atualização da lista de aplicativos e funcionou !

**Comment by macbellitoaccb** [comment]
> Vi esse comentário no YT:
> 
> para o Odoo 16 o base_address_city se encontra no base_address_extended. Então para que você possa instalar os módulos, terá que substituir as referencias a base_address_city por base_address_extended nos arquivos **manifest**.py (linha 15: { 'base_address_city,} --> { 'base_address_extended',} ) e res_city.xml (linha 5: { } --> { )}
> 
> Porém, depois da alteração, continuo recebendo os mesmo erros.
> 
> Depois somente, fiz a atualização da lista de aplicativos e funcionou !

mas qual arquivo e de qual pasta vc editou o  **manifest**.py? se puder me responder agradeço, estou com o mesmo problema

**Comment by IgorSantRocha** [comment]
Nesse você muda a dependência:
sudo nano odoo-brasil/l10n_br_base_address/__manifest__.py
  `'depends': [
        'account',
        'l10n_br_base',
        # 'base_address_city',
        'base_address_extended',
    ],`  

sudo nano odoo-brasil/l10n_br_base_address/res_city.xml

Aqui você muda a linha 5

`<field name="inherit_id" ref="base_address_extended.view_city_tree" />`

Fiz essas alterações e subiu sem problemas

**Comment by antoniospneto** [comment]
Fechando, pois não se trata de nenhum módulo da localização com problema, para outros assuntos pode ser utilizado a ferramenta de discussões: https://github.com/OCA/l10n-brazil/discussions
