### ISSUE TITLE
[14.0][BUG] l10n_br_nfe: Problema com os campos herdados ao reiniciar o Odoo.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2509]
Módulos afetados: l10n_br_nfe, l10n_br_nfe_spec, spec_driven_model
Versão afetadas: testei só no 14.0

Sempre após reiniciar o Odoo, ao tentar acessar uma fatura dá este erro:
```
psycopg2.errors.UndefinedColumn: column l10n_br_fiscal_document.nfe40_ide does not exist
LINE 1: ...l_document"."nfe40_modFrete" as "nfe40_modFrete", "l10n_br_f...
```

Para resolver eu tenho que sempre rodar um update (-u) no módulo l10n_br_nfe, mesmo que não tenha feito nenhuma alteração no código.
Após o update volta ao normal, sem erros, mas o problema volta ao reiniciar o Odoo.

Ainda estou investigando o problema, mas eu penso que é algo relacionado no spec_driven_model.
@rvalyi se tiver alguma sugestão do que pode ser

**Comment by rvalyi** [comment]
sim é so na 14.0 e tb eu acho que é ligado ao spec_driven_model. Mas eu tb acho que já foi reportado num outro issue. Vou ver depois.
