### ISSUE TITLE
Erro no schema do XML ao enviar NFe 

### ISSUE THREAD

**Issue by igoroliveira-ax4b** [OCA/l10n-brazil#2510]
## Module
l10n_br_nfe

## Describe the bug
Ao enviar a NFe, recebo o seguinte erro referente ao XML.
A linha 27 citada contem a tag `<xNome>NOME DA EMPRESA</xNome>`
![image](https://github.com/OCA/l10n-brazil/assets/101650554/e27e16e4-4158-46b5-85f2-8785ea063bf7)

Ao utilizar o validador de NFe, recebo o seguinte erro:
![image](https://github.com/OCA/l10n-brazil/assets/101650554/4acaa722-de83-4381-8cf6-c8a2c4b83c65)

Porém o erro parece variar a cada nota emitida, pois já recebi erro na tag <transp>, e na tag <idDest>

Atualmente utilizo as libs abaixo nessas versões:
```
erpbrasil.assinatura==1.5.0
erpbrasil.base==2.3.0
erpbrasil.edoc==2.3.1
erpbrasil.edoc.pdf==1.1.0
erpbrasil.transmissao==1.0.0
```

Testei erpbrasil.edoc na versão 2.2.1 e a exibição do erro é diferente:

![image](https://github.com/OCA/l10n-brazil/assets/101650554/29d3287c-1f89-46a3-ba63-dc7d722f86a1)

**Comment by antoniospneto** [comment]
será que não tem algum caractere especial invisível ali na descrição do nome da empresa ? da uma conferida, qualquer coisa apaga tudo que tá escrito no nome da empresa e digita de novo.

**Comment by antoniospneto** [comment]
obs: use a versão mais recente da lib erpbrasil.assinatura vc vai ter que puxar direto de branch master, assim:
`-e git+https://github.com/erpbrasil/erpbrasil.assinatura@master#egg=erpbrasil.assinatura`

**Comment by igoroliveira-ax4b** [comment]
@antoniospneto já cheguei a remover todos os caracteres especiais, porém o erro persiste.
Também instalei a mais recente do erpbrasil.assinatura e o erro ainda insiste na linha 27 que não possui nada que seria um gatilho para erros

**Comment by rvalyi** [comment]
tou no celular não pude fuçar muito, mas vê se isso não seria relacionado as últimas evoluções do esquema da NFe. Olhando essa PR e as mudanças relacionadas na nfelib vc consegue ter uma noção:

https://github.com/OCA/l10n-brazil/pull/2474

EDIT: olhei melhor, eu acho que não seria devido a atualização de esquema não.

**Comment by crsilveira** [comment]
Consulte a chave da sua nota no sefaz, este problema  pode ser a mensagem 104/204 (Erro de duplicidade).
Ontem tive uma NF com este mesmo problema , acompanhando vi que a nota já tinha sido enviada, e apos isso, cada tentativa dá uma msg ...

**Comment by crsilveira** [comment]
no meu caso deu erro keyError : 'file_report_id', este erro quando tenta enviar o Email, ocorrendo isso a nota já foi enviada, só que não foi alterado o status, e dai o usuário tenta enviar novamente , dai vem estes outros erros, pois, ela já consta na base da receita.

**Comment by ATSTI** [comment]
Como simular o erro acima:
   Tenta enviar uma nota de uma pessoa juridica sem IE, e marcada como Contribuinte Icms.
   A primeira mensagem será correta : NF-e sem informação da IE do destinatário (algo assim).
   Se clicar no botão ENVIAR pela segunda vez, sem refazer o xml, a proxima mensagem será :
    -   Rejeição: Falha no Schema XML do lote de NFe 
    
       estes retornos :
          retConsSitNFe : Rejeição: Consumo Indevido
          retConsReciNFe: Rejeição: Falha no Schema XML do lote de NFe

**Comment by antoniospneto** [comment]
@ATSTI essa situação que você está passando está explicada no manual da NF-e, se você ficar tentando enviar muitas vezes a NFE e todas as vezes a nota for rejeitada por erros, chega uma hora que o servidor da sefaz vai ter bloquear por estar consumindo muitos recursos do servidor a toa haha.

Uma dica é utilizar o módulo l10n_br_fiscal_queue que enfileira e coloca o envio da NFE  em segundo plano. ( O módulo ainda tá em desenvolvimento, mas já da pra usar com uns pequenos ajustes) se der algum erro vai ficar registrado no JOB e você pode ver a causa posteriormente.

**Comment by ATSTI** [comment]
...explicada no manual da NF-e ........  isso blz, o que acho q é o correto, e deixar a MSG correta no sistema , pois, o problema original é um, só q se o usuário tenta enviar novamente, o sistema , muda a MSG (não devia, pois, o problema não mudou ) : 

PRIMEIRO ENVIO :

...Rejeição: NF-e sem informação da IE do destinatário</xMotivo></infProt></protNFe></retConsReciNFe></nfeResultMsg></soap:Body></soap:Envelope>

SEGUNDO ENVIO (como dei um tempo, nao deu o consumo indedio):

... encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><nfeResultMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4"><retEnviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>SP_NFE_PL009_V4</verAplic><cStat>103</cStat><xMotivo>Lote recebido com sucesso</xMotivo><cUF>35</cUF><dhRecbto>2023-06-24T10:21:08-03:00</dhRecbto><infRec><nRec>351000175050183</nRec><tMed>1</tMed></infRec></retEnviNFe></nfeResultMsg></soap:Body></soap:Envelope>
...retConsReciNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><verAplic>SP_NFE_PL009_V4</verAplic><nRec>351000175050183</nRec><cStat>225</cStat><xMotivo>Rejeição: Falha no Schema XML do lote de NFe</xMotivo><cUF>35</cUF><dhRecbto>2023-06-24T10:21:26-03:00</dhRecbto></retConsReciNFe></nfeResultMsg></soap:Body></soap:Envelope>

**Comment by antoniospneto** [comment]
@ATSTI 

Veja se não tem algum caracter especial que não é permitido no XML, as vezes tem uns que são invisíveis no lugar do espaço.

**Comment by ATSTI** [comment]
Obrigado pela resposta , mas vc não leu o que eu escrevi .

**Comment by diegosayron** [comment]
@ATSTI embora eu desenvolva para NF-e desde antes de ser lançado, aqui eu sou totalmente cego nesse projeto, e ainda estou engatinhando por aqui... Posso estar falando besteira, mas já tentou pegar o xml e colar em algum site que confronta xml com schema? como o da [Tecnospeed](https://validador.nfe.tecnospeed.com.br/) ou o da própria [Sefaz RS](https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx) (que serve para todas)

Eu também uso o Visual Studio para encontrar erros, confrontando o xml com o schema.

A propósito, como você disse "sem refazer o xml", em um projeto meu, isso acontecia. Era o XML anterior que não era limpo e concatenava com o novo conteúdo. Se for isso, é, realmente, um bug.

Posta o segundo XML aqui. Tem como?
