### ISSUE TITLE
[14.0] Ao Registrar Pagamento em Fatura, esta gerando o recalculo das faturas não fiscais.

### ISSUE THREAD

**Issue by crsilveira** [OCA/l10n-brazil#2515]
Faturas de Clientes, 
Registrar Pagamentos.

**Comment by marcelsavegnago** [comment]
cc @douglascstd

**Comment by felipemotter** [comment]
Consegue dar um exemplo prático?

Att,

**Comment by crsilveira** [comment]
![ksnip_20230606-090210](https://github.com/OCA/l10n-brazil/assets/3135336/ad78e67a-ec9e-4c79-93a8-795f221ff808)
![ksnip_20230606-090245](https://github.com/OCA/l10n-brazil/assets/3135336/0fb7a5a0-7e88-4b7a-881a-17dca2b8f1f8)
aqui : l10n_br_account/models/account_invoice.py  -> def _compute_amount(self)
o estranho é q a base q eu estava vendo isso ontem, hoje não está acontecendo mais isso.

**Comment by rvalyi** [comment]
certeza que seu eu código está e estava atualizado? porque se era código tipo de um mês atrás, pode ter sido corrigido pelo último fix que eu fiz prós registros "dummy".

**Comment by crsilveira** [comment]
commit a2a50ff344f84139b4e18ce4e003fb7133a2b096 (HEAD -> 14.0)
Author: OCA-git-bot <oca-git-bot@odoo-community.org>
Date:   Sat Jun 3 22:21:46 2023 +0000

atualizei ontem, pra ver se resolvia.... , só q o problema continuou, o estranho é hoje não dar problema na base q eu estava ontem ... tive q voltar um backup pra pegar o exemplo acima,....

**Comment by marcelsavegnago** [comment]
Talvez vc tenha que dar uma manutenção nos links entre account.move e account.move.line com os fiscal_document e fiscal_document_line. Provavelmente já deve ter linhas de dummy a mais e afins.

**Comment by crsilveira** [comment]
Nas 2 bases (são copias) praticamente, mesmo número de dummys ,.... tentei refazer tudo q fiz , update all,  update l10n_br_fiscal , l10n_br_account .... mas uma para nos dummys (recalcula tudo) e outra não.... procurando aqui, se conseguir descobrir a diferença, envio aqui.

**Comment by marcelsavegnago** [comment]
Ehh bom dar uma boa olhada nesta relacao.. varios selects para ver se nao tem relacionamento errado.. tive muito e ainda tenho.. varias linhas de documento fiscal sem operacao fiscal (que pode ser pseudo dummy) e por ai vai.

**Comment by rvalyi** [comment]
isso foi solucionado a partir da 14.0 onde não tem mais documentos fiscais "dummy".
