### ISSUE TITLE
[14.0][l10n_br_cnpj_search] consultas de testes estoram as quota

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#2530]
Parece que os testes do l10n_br_cnpj_search ultrapassam as quota de consulta no Serpro, Isso vai atrapalhar a CI pelo jeito:
![2023-06-09_22-31](https://github.com/OCA/l10n-brazil/assets/16926/e85207f4-0060-467c-b7c6-aa88dd6ad9f4)

@mileo @ODBreno talvez voces podem fazer um teste mock ou pseudo mocked talvez como eu fiz pro BCB e IBPT aqui https://github.com/OCA/l10n-brazil/pull/2506 (mas tem que ver para não utrapassar as quotas, mesmo se tiver 10 PR no dia...)

cc @marcelsavegnago @renatonlima

**Comment by ODBreno** [comment]
@rvalyi 
Eu coloquei pra que só testasse uma vez por semana como você fez, mas no dia em específico que ele fosse testar ia continuar dando "too many requests" constantemente, tentei encontrar na documentação da serpro alguma limitação de requisições, mas tudo que falava lá era que não podiam ser feitas ao mesmo tempo. Acabou que aumentei o "time" para pausar mais entre um teste e outro e não deu mais "too many requests" quando eu rodava vários testes seguidos. Entretanto, resolvendo essa issue acabei percebendo outro detalhe que pode gerar problemas no futuro, a api receitaws tem um limite de 3 requisições por minuto, nos testes eu faço 3 consultas, se os testes forem executados mais de uma vez por minuto vai acabar resultando no mesmo problema  de estourar o limite. Confesso que não compreendo o tamanho desse problema para OCA porque não sei qual a chance de 2 testes do mesmo módulo executarem no mesmo minuto.

**Comment by rvalyi** [comment]
@ODBreno @mileo @marcelsavegnago @renatonlima infelizmente o problema ainda existe, acabou de dar erro nesse meu PRhttps://github.com/OCA/l10n-brazil/actions/runs/5300610039/jobs/9594253344?pr=2474
![2023-06-17_20-32](https://github.com/OCA/l10n-brazil/assets/16926/56b2521d-dccc-4890-8257-8b315e8791ea)

**Comment by rvalyi** [comment]
mas assim, seria bom melhorar mas talvez não seja crítico, pois há 2 dias eu mandei rodar de novo e meu teste passou, não ficou travado o dia inteiro me parece. Talvez seja possível detetar o problema e rodar algum skipTest ou coisa do tipo.

**Comment by antoniospneto** [comment]
@rvalyi acho que os mocks agora estão ok certo ? a issue pode ser fechada?

**Comment by rvalyi** [comment]
sim
