### ISSUE TITLE
[14.0][l10n_br_fiscal][IMP] Novas linhas do Regulamento do ICMS somem após serem salvas.

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2534]
Ao criar uma nova linha no Regulamento do ICMS, ela é criada de forma esperada, e aparece na lista após a criação da linha, no entanto, ao salvar o Regulamento do ICMS, esta linha não aparece mais na tela.

Foi verificado que essa linha ainda existe no banco de dados.

Em um teste, criado um novo Regulamento de ICMS, e criado também a linha, o comportamento errado também se apresenta. E para verificar se a linha que não aparece mais no Regulamento, foi realizado uma pesquisa direto no banco, e a linha existe, mas não aparece na tela do Regulamento mais.
![image](https://github.com/OCA/l10n-brazil/assets/20867090/eb8d981d-308e-4dfc-a038-ab211c4ebf14)

## Module
l10n_br_fiscal

## To Reproduce
https://github.com/OCA/l10n-brazil/assets/20867090/3e74d592-8a9d-4cbf-aa05-ddbd3a488506

1. Criar uma nova linha no Regulamento de ICMS
2. Salvar o Regulamento
3. Verificar se a linha recém criada aparece na lista.

@marcelsavegnago @renatonlima

**Comment by marcelsavegnago** [comment]
cc @rvalyi @antoniospneto @felipemotter

**Comment by douglascstd** [comment]
Encontrado o problema, que é a falta de preenchimento do Estado destino.
Sugiro que esse campo de Estado Destino seja obrigatório, pois sem ele o registro não é mais encontrado em nenhum local.

**Comment by rvalyi** [comment]
@douglascstd vc fechou o issue por engano não?

**Comment by douglascstd** [comment]
> @douglascstd vc fechou o issue por engano não?

Fechei pois o erro foi de nao preencher um campo no imposto. 
Mas como sugestão é tornar o campo como obrigatório.

**Comment by rvalyi** [comment]
sim vamos fazer essa alteração, valeu por reportar.
