### ISSUE TITLE
[14.0] Campo incoterm selecionado na SO não popula os campos da fatura e documento fiscal

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2537]
Ao selecionar o campo incoterm numa Sale Order e confirmar a mesma, o campo incoterm da fatura não é preenchido, além disso, caso selecionemos tal campo na fatura, o mesmo não altera os valores do campo "modalidade do frete" no documento fiscal.
## Module

l10n_br_nfe, l10n_br_delivery e l10n_br_delivery_nfe

## Describe the bug
Ao selecionar o campo incoterm numa Sale Order e confirmar a mesma, o campo incoterm da fatura não é preenchido, além disso, caso selecionemos tal campo na fatura, o mesmo não altera os valores do campo "modalidade do frete" no documento fiscal.

## To Reproduce
**Affected versions**:
14.0
1. Crie uma S.O selecionando o método de transporte e selecione o incoterm corretamente e confirme-a
2. Com a S.O confirmada, crie a fatura pelo picking (confira se o campo incoterm foi copiado da SO)
3. Na fatura, verifique se o incoterm é exibido corretamente, e veja se o mesmo aparece nos "detalhes fiscais"
4. Note que mesmo alterando o incoterm, o campo "modalidade do frete" não altera seus valores.

**Expected behavior**
O campo "modalidade do frete" deveria alterar o valor selecionado conforme a incoterm selecionada.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
![image](https://github.com/OCA/l10n-brazil/assets/25938418/6dc61b09-4757-4f34-a043-2515b2f2624c)
![telegram-cloud-photo-size-1-4925100820538698705-y](https://github.com/OCA/l10n-brazil/assets/25938418/0eb9327e-eea7-4989-8642-b2d4916276b0)
![telegram-cloud-photo-size-1-4925100820538698706-y](https://github.com/OCA/l10n-brazil/assets/25938418/ec307a26-aa81-4125-919e-4f9c5dcbdcb1)

ping: @marcelsavegnago , @douglascstd , @antoniospneto , @felipemotter

**Comment by rvalyi** [comment]
@augustodinizl não seria esse o fix https://github.com/OCA/l10n-brazil/pull/2517 ?

cc @antoniospneto se acertar o comentário lá, pode rolar o merge logo...

**Comment by augustodinizl** [comment]
> @augustodinizl não seria esse o fix https://github.com/OCA/l10n-brazil/pull/2517 ?
> 
> cc @antoniospneto se acertar o comentário lá, pode rolar o merge logo...

Exato!!! Obrigado!!!

**Comment by antoniospneto** [comment]
Opa, já vou ajeitar

**Comment by aug1804** [comment]
This issue has to be reopened.
Issue number #2517 deals with Loading the freight modality in the NF-e.
While this issue, number #2537, deals with the Incoterm(1) field selected in the Sales Order that does not populate the fields of the Invoice and fiscal document.
(1) this same problem occurs with the payment_mode_id field (Payment Mode).

Esta issue tem que ser reaberta.
A issue número #2517 trata do Carregamento da modalidade do frete na NF-e.
Enquanto essa issue, número #2537, trata do campo Incoterm(1) selecionado no Pedido de Venda que não popula os campos da Fatura e documento fiscal.
(1) esse mesmo problema ocorre com o campo payment_mode_id (Modo de Pagamento).

**Comment by aug1804** [comment]
![Screenshot from 2023-08-28 19-10-02](https://github.com/OCA/l10n-brazil/assets/56700559/54d0f3f6-679c-4bb7-a014-18c6c0f0393a)

**Comment by aug1804** [comment]
As you can see above, the runboat also crashed.
Sales Order: Incoterm = CIF
Provisional Invoice (print): Incoterm 'in blank'

Como você pode ver no print acima, o 'runboat' também deu pau.
Pedido de Venda: Incoterm = CIF
Nota Fiscal Provisória (print): Incoterm ‘em branco’

**Comment by antoniospneto** [comment]
Olá @aug1804 

Eu consegui reproduzir o problema aqui quanto ao Incoterm.

Mas queria deixar aqui o contexto adicional que o mesmo só acontece quando a fatura é gerada a partir do Picking, quando gerada diretamente do Pedido de Venda o mesmo não acontece, o Incoterm é carregado corretamente.

Quanto ao **Modo de Pagamento** você deve tá falando do módulo **account_payment_sale** o mesmo não vem instalado por padrão na localização, caso instalado ele vai copiar o valor apenas se você criar a fatura diretamente do Pedido de Venda, gerar a fatura a partir do Picking é uma funcionalidade aqui da Localização, por isso o módulo não deve funcionar nessa abordagem, é preciso que alguém implemente esse caso.

**Comment by augustodinizl** [comment]
> This issue has to be reopened. Issue number #2517 deals with Loading the freight modality in the NF-e. While this issue, number #2537, deals with the Incoterm(1) field selected in the Sales Order that does not populate the fields of the Invoice and fiscal document. (1) this same problem occurs with the payment_mode_id field (Payment Mode).
> 
> Esta issue tem que ser reaberta. A issue número #2517 trata do Carregamento da modalidade do frete na NF-e. Enquanto essa issue, número #2537, trata do campo Incoterm(1) selecionado no Pedido de Venda que não popula os campos da Fatura e documento fiscal. (1) esse mesmo problema ocorre com o campo payment_mode_id (Modo de Pagamento).

Respeitosamente discordo, e POR MIM, a issue permanece fechada, caso algum PSC ou contribuidor mais antigo/experiente achar melhor reabrir, fiquem á vontade...
Ao meu ver, a questão apresentada apesar de ser "análoga", não tem a ver com o escopo, e pode ser tratada em issue separada para não interferir na solução apresentada

Ping @rvalyi @antoniospneto @renatonlima @marcelsavegnago @felipemotter

**Comment by aug1804** [comment]
Olá @antoniospneto 

Grato pelos comentários.

O campo 'Modo de Pagamento' ao qual me refiro é o 'payment_mode_id', vide print anexo.
![Screenshot from 2023-08-30 16-59-18 campo](https://github.com/OCA/l10n-brazil/assets/56700559/bdc33359-ff5f-4af2-9749-3bfdaf07995b)

**Comment by aug1804** [comment]
Faturas Provisórias geradas diretamente a partir de Pedidos de Vendas estão populando corretamente os campos 'Incoterm' e 'Modo de Pagemento', conforme print anexo.
![Screenshot from 2023-08-30 16-57-00](https://github.com/OCA/l10n-brazil/assets/56700559/22a66ab7-741a-4d78-a9e7-614502e97a7e)

**Comment by aug1804** [comment]
Porém Faturas Provisórias geradas a partir do Picking NÃO estão populando corretamente os campos 'Incoterm' e 'Modo de Pagemento', conforme meus comentários há 2 dias.

**Comment by aug1804** [comment]
Portanto é razoável que esta issue seja reaberta.

Ou outro instrumento diferente de uma reabertura seja acionado.
