### ISSUE TITLE
Preenchimento de dados fiscais automatico vinculado a Categoria de Produto.

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2538]
NCM padrão para a Categoria de produto. Assim ao selecionar a categoria, a parte fiscal seria preenchida automaticamente com o NCM cadastrado na Categoria. Agilizando o processo de cadastro dos produtos.

**Comment by rvalyi** [comment]
seria legal sim.

**Comment by marcos-mendez** [comment]
Seria legal um modulo a parte, pois não todos usam as categorias no sentido
fiscal delas, alguns usam as categorias no sentido de uso ou comercial dos
produtos. Por exemplo uma Crocs o NCM é de item de borracha, mas é
considerado uma sandália que é outro NCM se for de couro, é importante
manter um módulo a parte só pra isso

Em qui., 15 de jun. de 2023 às 14:42, Raphaël Valyi <
***@***.***> escreveu:

**Comment by rvalyi** [comment]
aí, se tiver um NCM na categoria, ele jogaria no produto. se não tiver não jogaria. E vc poderia alterar ainda. Eu imagino que tem como fazer isso em em menos de 15 linhas e como ainda seria opcional não justificaria módulo extra (módulo de menos de 50 linhas de código efetivo não é muito justificado, basta praticar o ecosistema da OCA para ver).

**Comment by douglascstd** [comment]
Achei uma ótima ideia.

Estava aqui pensando que seja adotado o NCM da categoria, como poderia ser na prática. Poderia pensar em algumas alternativas:
1. Desta forma não precisaria ser obrigatório o preenchimento no form do produto e utilizar o mesmo conceito do preenchimento da conta débito/crédito que segue uma hierarquia pela categoria.
   Mais complicado, pois deverá manipular todos os acessos ao campo do produto, buscar, quando vazio, o campo na categoria.
2- Criar um botão de forçar a aplicação do NCM da categoria em todos os produtos que estejam nela.
   Mais simples, pois não envolveria alteração no comportamento do uso do campo do produto

O mesmo valeria para o Tipo Fiscal... :-)
