### ISSUE TITLE
[14.0] l10n_br_pos, l10n_br_pos_cfe: Warnings

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2548]
Estamos com alguns warnings em cima dos módulos l10n_br_pos e l10n_br_pos_cfe. @mileo consegue dar uma avaliada ?

/oca/l10n-brazil/l10n_br_pos/static/src/js/models.js
  111:21  warning  Method 'initialize' has a complexity of 30. Maximum allowed is 15  complexity
  362:20  warning  The Function constructor is eval                                   no-new-func

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/OrderManagementScreen/ReprintReceiptScreen.js
  15:47  warning  'ReprintReceiptScreen' is already declared in the upper scope  no-shadow

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/PaymentScreen/PaymentScreen.js
  15:40  warning  'PaymentScreen' is already declared in the upper scope  no-shadow

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/models.js
  38:9  warning  Missing JSDoc for parameter 'json'  valid-jsdoc

✖ 5 problems (0 errors, 5 warnings)

/oca/l10n-brazil/l10n_br_pos/static/src/js/Screens/OrderManagementScreen/OrderRow.js
  13:32  warning  'OrderRow' is already declared in the upper scope  no-shadow

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/ReceiptScreen/ReceiptScreen.js
  15:40  warning  'ReceiptScreen' is already declared in the upper scope  no-shadow

✖ 2 problems (0 errors, 2 warnings)

/oca/l10n-brazil/l10n_br_pos/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  19:37  warning  'PaymentScreen' is already declared in the upper scope  no-shadow

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/ChromeWidgets/ProxyStatus.js
  12:29  warning  'ProxyStatus' is already declared in the upper scope     no-shadow
  13:15  warning  'CFeProxyStatus' is already declared in the upper scope  no-shadow

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/ReceiptScreen/SatOrderReceipt.js
  11:30  warning  'OrderReceipt' is already declared in the upper scope  no-shadow

✖ 4 problems (0 errors, 4 warnings)

/oca/l10n-brazil/l10n_br_pos/static/src/js/util.js
    4:5   warning  Function 'validate_cnpj_cpf' has a complexity of 23. Maximum allowed is 15  complexity
   35:20  warning  Expected '===' and instead saw '=='                                         eqeqeq
   39:20  warning  Expected '!==' and instead saw '!='                                         eqeqeq
   49:20  warning  Expected '===' and instead saw '=='                                         eqeqeq
   53:20  warning  Expected '!==' and instead saw '!='                                         eqeqeq
   89:20  warning  Expected '!==' and instead saw '!='                                         eqeqeq
  109:20  warning  Expected '!==' and instead saw '!='                                         eqeqeq

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/devices.js
  22:17  warning  Assignment to function parameter 'status'  no-param-reassign

/oca/l10n-brazil/l10n_br_pos_cfe/static/src/js/fiscal_cfe.js
  62:21  warning  'order' is already defined  no-redeclare

✖ 9 problems (0 errors, 9 warnings)

Desde já agradeço a atenção.

**Comment by lfdivino** [comment]
@marcelsavegnago e @mileo 

Criei um PR para acertar esses warnings de eslint nos módulos. Confiram por favor:

#2561

**Comment by rvalyi** [comment]
foi quase tudo solucionado com https://github.com/OCA/l10n-brazil/pull/2561
