### ISSUE TITLE
Rename "develop" branch as the 7.0 branch?

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#256]
Switching to pt_BR here as it will only concern Portuguese speaking people from the pre-OCA stage of the project.

Pessoal la em 2013 o projeto contava com a metade de contribuidores ativos e o openupgrade era bem mais experimental. Ainda estavamos conversando da OCA mas ainda nao existia estrutura. Alias botamos o projeto no Github 1 anos antes da OCA existir no Github (fomos dos que impulsionaram e ajudaram a mudanca de Launchpad para Github na OCA).

Com isso migramos a branch 6.1 para 7.0. Naquela epoca a localizacao ainda era bem experimental porem ja melhor do que o propŕio codigo do Odoo 7.0... Enfim logo precebemos que varias melhorias eram possiveis, porem a gente nao podia sacanear o pessoal usando a branch 7.0 com mudancas incompativeis. Assim usando a convencao do "gitflow" criamos a branch develop onde foram feitas inumerosas melhorias. Alias foi a primeira branch capaz de transmitir as NFE's pelo pysped direitamente.

Depois da develop, veio Odoo 8.0 e criamos a branch 8.0 e depois a 9.0, padronizando com a OCA.

No futuro esse tipo de problema nao vai acontecer mais pois a partir da 8.0 na OCA estamos usando um sistema stricto de versoes de modulos e assim sera possivel migrar entre as versoes maiores dos modulos usando a lib openupgrade (seremos capaz de exigir que os PR's que quebram o schema venham com script de migracao se for necessario). Atencao isso so nas migracoes dentro de uma serie. So para deixar claro, migrar da 8.0 para a 9.0 sera muito punk e sem garantia da parte da OCA.

Bom, acontece que a gente sabe de muito mais gente que usou a branch develop que naquela epoca nao era estavel mas era bem melhor porem. Na Akretion migramos - meio que na raça - os nossos clientes da 7.0 para a develop e nao temos ninguem que usa a branch 7.0 agora.

Entao o que eu queria saber e se tem gente vivo usando a branch 7.0 ainda e pretendendo atualizar do repo? Se nao for o caso, sugiro que a branch develop seja renomeada 7.0 e que mandamos a 7.0 num outro repo tipo odoo-brazil-team so para fins arqueologicos mesmo.

A ideia e tentar diminuir um pouco a confusao (ja que e complexo com os repos, Odoo/OCA/OCB). Hoje alguem que olha o repo vai se perguntar o que e essa branch "develop" de forma desnecessaria.

Pergunto tambem isso porque e provavel que na Akretion a gente cria os script openupgrade para migrar da branch 'develop' para '8.0', digamos nas camadas mais baixas (provavelmente nao ate o account da nossa parte). Ai renomear a branch iria tb diminuir a confusao.

Quem tiver na develop, se fizer pull acho que nao ia acontecer nada ou talvez iria atualizar a partir da nova 7.0 o que seria entao certo. So zoaria se alguem tiver na 7.0 e der o "pull da morte".

E ai? Qual a opinao de voces?

**Comment by mileo** [comment]
Na minha opinião só deve ser renomeado se for desenvolvido o script de update para o mesmo.

**Comment by rvalyi** [comment]
@renatonlima just made the switch in order to avoid confusing people with such a "develop" branch that is was not compliant to the OCA convention.
The old 7.0 legacy branch from this repo has been replicated both in the odoo-brazil repo:
https://github.com/odoo-brazil/l10n-brazil/tree/7.0-oca
and in our akretion repo:
https://github.com/akretion/l10n-brazil/tree/7.0-oca

@mileo PR of migrations are welcome, but on our side we are note interested in working on it, we migrated our customers from 7.0 to that intermediary develop branch (using hardcore SQL) and then to 8,0 (we will push a few migrations PR about that soon). In the future as more people are working on the project and as we have more customers, we will likely do better for migrations than in the early pre-OCA times...
