### ISSUE TITLE
Versão do erpbrasil.edoc no requirements.txt

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2599]
Ao fazer a atualização via git pull, ocorreu o seguinte erro:

RuntimeError: You need to install the erpbrasil.edoc package to use this legacy webservice layer.

Solução: Tive de desinstalar a versao que estava na 2.2 e instalar a nova q está na 2.4.
Se possível alterem no requirements.

Grato.

**Comment by rvalyi** [comment]
Ah é verdade: no ultimo momento antes de fazer o release de nfelib 2 eu botei um wrapper para os novos recursos de NFCe que a Kmee tinha botado no erpbrasil.edoc https://github.com/akretion/nfelib/blob/master/nfelib/nfe/ws/edoc_legacy.py#L12 e por conta disso precisa da versão 2.4.0 do erpbrasil.edoc mesmo. Valeu por reportar.

**Comment by rvalyi** [comment]
isso deveria resolver https://github.com/OCA/l10n-brazil/pull/2600

**Comment by rvalyi** [comment]
foi resolvido pelos recentes commits
