### ISSUE TITLE
Data e hora de entrada e saída é um campo não obrigatório, portanto deve ser preenchido manualmente ou deixado em branco.

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#264]
Caso a data hora de entrada e saida não seja preenchida durante a emissão. É possível registrar esse horário em sistemas dos sefaz estaduais.

OBS: Pesquisar  + sobre isso.

**Comment by GlauberF** [comment]
Boa Tarde,
A localização Brasileira e seus módulos, exemplo Fiscais já estão funcionando no odoo 9.0?
