### ISSUE TITLE
[14.0][BUG] Erros de concorrencia ao transmitir documento fiscais.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2643]
Ao transmitir uma NF-e  às vezes acontece de falhar, da erro de concorrência no acesso ao banco de dados:

> 2023-08-11 13:56:01,576 1 ERROR devel odoo.sql_db: bad query: UPDATE "res_partner" SET "write_uid"=61,"write_date"=(now() at time zone 'UTC') WHERE id IN (1, 89085)
> ERROR: could not serialize access due to concurrent update
>  
> 2023-08-11 13:56:01,577 1 ERROR devel odoo.sql_db: bad query: UPDATE "res_partner" SET "write_uid"=61,"write_date"=(now() at time zone 'UTC') WHERE id IN (1, 89085)
> ERROR: could not serialize access due to concurrent update

Mesmo que a gente enfileire o envio das NF-e (transmissão para Sefaz) ainda tem o risco disso acontecer, pois o modelo `res_partner` pode estar sendo acessado por outras partes do sistema, pode acontecer com outros modelos também, a ORM desencadeia muitas chamadas ao banco de dados...

Por esse ser um processo bem crítico, perder essas informações dá bastante dor de cabeça para a empresa e para quem está prestando suporte.

Minha sugestão é que para esse processo crítico é deixar de usar qualquer chamada para ORM do Odoo, seja leitura ou gravação, a gente sabe que a ORM facilita bastante o processo, mas ela tende a engorda muito as chamas ao banco de dados, é só ativar os logs que vai ver a imensidão de QUERIES geradas, isso não é legal para um processo crítico como esse.

Fazer com que dentro do método `_eletronic_document_send()` seja utilizada apenas queries SQL bem restritas feito a mão.

@mileo @felipezago@ygcarvalh, vocês que estão implementando a NFC-e acho que o problema com isso vai ser ainda maior pra vocês, não ?

O que acham ? 

cc @rvalyi  @marcelsavegnago @renatonlima @felipemotter

**Comment by mileo** [comment]
Tem que entender o que esta sendo escrito no res_partner, pois não deveria ter nada escrito, vc consegue as queries? 

Qualquer coisa me manda no privado.

**Comment by mileo** [comment]
Explicando melhor deve ter algo que roda antes dessa querie que esta impactando.

**Comment by antoniospneto** [comment]
@mileo a gente pode achar o motivo e minimizar o problema, mas você entende que enquanto a gente tiver usando a ORM a chance de acontecer um erro de concorrência sempre vai ser maior, hoje o problema foi com o res_partner amanhã pode ser outro modelo

**Comment by rvalyi** [comment]
ajudaria por pegar um snapshot de dados menor na transação? Pode ser eu não sei.

Mas ainda assim eu acho que a partir do momento que um query (ORM ou não) vai usar o cursor com snapshot isolation ele pode ter esse problema.

O maior problema na minha opinião é a lentidão da transmissão que aumenta a chance de alguma escritura concorrente acontecer. A lentidão da transmissão ela vem de vários fatores mas o principal é mesmo a transmissão para a fazenda.

@mileo eu vi vários prontos fracos nessa fase de transmissão sincrona pelo erpbrasil.edoc. Vc tem certeza que é preciso 
consultar se a nota já foi enviada antes de tentar transmitir? Será se isso tem que ser o papel da lib de transmissão? Também vi que o Zeep tenta sempre baixar os WSDLs em vez de usar o cache (mas pelo jeito seria possível usar o cache) No final me parece que faz 3x ou 4x mais queries do que deveria, o que aumenta o tempo e a probabilidade de tais problemas. É uma intuição, não verifiquei se isso realmente é o fator principal deste problema.

**Comment by ygcarvalh** [comment]
Nesse sentido que comentou, utilizar apenas queries para lidar com a função de envio não pode comprometer a segurança de alguma forma? E, também, fazer dessa maneira não vai ser uma garantia 100% de que vai minimizar os problemas de concorrência, correto? Seria preciso ter, ainda assim, um planejamento para lidar com as concorrências.

Outro ponto a se considerar é: como optar por essa abordagem vai impactar na forma como lidamos com a manutenção? Consultas SQL's, querendo ou não, precisam de um conhecimento um pouco maior para serem bem implementadas.

cc @mileo @marcelsavegnago @rvalyi @antoniospneto

**Comment by antoniospneto** [comment]
Segue log do profiler para o método `_eletronic_document_send()`

```
2023-08-11 19:21:13,588 1 INFO devel odoo.tools.profiler: 
calls     queries   ms
l10n_br_fiscal.document --------------------- /opt/odoo/auto/addons/l10n_br_nfe/models/document.py, 922

1         0         0.02          @profile
                                  def _eletronic_document_send(self):
1         0         0.54              _logger.info("INICIO DO ENVIO DE NFE")
1         12        85.66             super(NFe, self)._eletronic_document_send()
3         3         9.26              for record in self.filtered(filter_processador_edoc_nfe):
1         0         0.03                  if record.xml_error_message:
                                              return
                              
1         0         0.03                  if record.document_type == MODELO_FISCAL_NFCE:
                                              record.nfe40_infNFeSupl = self.env[
                                                  "l10n_br_fiscal.document.supplement"
                                              ].create(
                                                  {
                                                      "nfe40_qrCode": self.get_nfce_qrcode(),
                                                      "nfe40_urlChave": self.get_nfce_qrcode_url(),
                                                  }
                                              )
                              
1         8         92.79                 processador = record._processador()
2         119       660.84                for edoc in record.serialize():
1         0         0.01                      processo = None
6         0         2418.68                   for p in processador.processar_documento(edoc):
4         0         0.02                          processo = p
4         0         2.42                          _logger.info(processo.retorno.text)
4         0         0.02                          if processo.webservice == "nfeAutorizacaoLote":
2         56        266.06                            record.authorization_event_id._save_event_file(
1         0         0.01                                  processo.envio_xml.decode("utf-8"), "xml"
                                                      )
                              
1         0         0.0                   if processo.resposta.cStat in LOTE_PROCESSADO + ["100"]:
1         118       1731.18                   record.atualiza_status_nfe(processo)
                              
                                          elif processo.resposta.cStat in DENEGADO:
                                              record._change_state(SITUACAO_EDOC_DENEGADA)
                                              record.write(
                                                  {
                                                      "status_code": processo.resposta.cStat,
                                                      "status_name": processo.resposta.xMotivo,
                                                  }
                                              )
                              
                                          elif processo.resposta.cStat in CONTINGENCIA:
                                              record._process_document_in_contingency()
                              
                                          else:
                                              record._change_state(SITUACAO_EDOC_REJEITADA)
                                              record.write(
                                                  {
                                                      "status_code": processo.resposta.cStat,
                                                      "status_name": processo.resposta.xMotivo,
                                                  }
                                              )
1         0         0.63              _logger.info("FIM DO ENVIO DE NFE")

Total:
1         316       5268.2    


```

316 queries e 5,3 segundos para executar, é muita query e a janela de tempo é grande

**Comment by antoniospneto** [comment]
Eu por hora fiz um fork do **erpbrasil.edoc** para utilizar o envio síncrono da NF-e também e não precisar ter o tempo de espera para ler o recibo, dessa forma consegui reduzir o tempo de envio 5s para 2s. acredito que isso já vai ajudar bastante a reduzir a chance dos erro de concorrência 

https://github.com/Engenere/erpbrasil.edoc/commit/c07c78dd47c9f018baef635fab13b1e233408093

Será que seria interessante alterar a lib para deixar essa escolha opcional ?

**Comment by rvalyi** [comment]
sobre o número de queries: como era de se esperar, a grande maioria vem da serializaçao da NFe e nela não tem muita coisa para se fazer para ainda beneficiar do framework de mapping sem ter que mapear de forma manual sem modularidade e com código porco para manter depois. Ainda assim duvido que salvaria 30% dos queries, pois o ORM faz muitas queries mesmo. Uma forma de tirar uns 20% é botar sudo(), mas tb tem seus limites TB em termo de segurança.

Eu acho que a solução é mais enviar de forma asincrona e consultar o status num job depois (ou seja nem como é feito o PR com queue atual). Evitar que o Python Zeep baixasse os WSDLs para cada nota tb. Aí provavelmente fica abaixo do segundo com pouca chance de accesso concorrente acontecer e que ainda seria solucionado com um retry muitas vezes. 5.3 secondos vc teve sorte, eu diria que muitas vezes a fazenda demora mais para retornar o recibo.

Aliás hoje o ORM vai tentar um retry sozinho neste caso eu acho. O que sera que acontece com esse método e a transmissão neste caso?

Por fim deve ser possível botar uns cr.commit() de forma estratégicas logo depois de serializada o XML e antes de transmitir, pois até aqui deve ser idempotente não?

**Comment by antoniospneto** [comment]
Outra coisa que dá pra melhorar é a geração do PDF e o disparo do e-mail que tá sendo desencadeado no método que envia o documento fiscal ao mudar o status da do documento para autorizado, isso até foi uma alteração implementada pela Engenere, porém a gente não tinha noção do impacto.

A geração do PDF e Envio do E-mail pode ser ativada a partir de um Cron. a cada 1 ou 5 min por exemplo.

Pretendo abrir uma PR sugerindo essa melhoria em breve.

**Comment by marcelsavegnago** [comment]
cc @douglascstd @augustodinizl @aug1804

**Comment by mileo** [comment]
> Eu por hora fiz um fork do **erpbrasil.edoc** para utilizar o envio síncrono da NF-e também e não precisar ter o tempo de espera para ler o recibo, dessa forma consegui reduzir o tempo de envio 5s para 2s. acredito que isso já vai ajudar bastante a reduzir a chance dos erro de concorrência
> 
> [Engenere/erpbrasil.edoc@c07c78d](https://github.com/Engenere/erpbrasil.edoc/commit/c07c78dd47c9f018baef635fab13b1e233408093)
> 
> Será que seria interessante alterar a lib para deixar essa escolha opcional ?

1. Nem todo estado tem o serviço síncrono, o ideal seria deixar isso como uma configuração.
2. O pdf e o email com certeza devem ser enviados em um gerados / enviados em um outro momento. O sistema de email do Odoo tem uma funcionalidade de fila que provavelmente não estamos usando.
3. A consulta da nf-e antes do envio é uma forma de garantir que não estamos enviando a mesma nota duas vezes.
4. O for com o loop do processamento pode ser simplificado, o armazenamento dos dados da consulta foi uma forma de garantir que estava tudo funcionando bem. Segue um exemplo: https://github.com/kmee/l10n-brazil/blob/10.0/sped_nfe/models/inherited_sped_documento.py#L571-L680
5. Mesma coisa para o cache com zeep, podemos liga-lo não vejo problema visto que a lib erpbrasil.edoc já esta estável.
6. Referente aos SQLs: Sugiro primeiro tentarmos otimizar o método usando write/update com um dicionário com os dados.
7. O update no res.partner parece ser bug de alguma customização ou módulo com defeito (podendo ser o inclusive os próprios módulos da localização), sugiro um teste só com o módulo l10n_br_nfe instalado para isolar o problema, depois consultar os depends do res.partner / related / store=true. Já passei por esse problema no passado por conta de um erro de um desenvolvedor.

**Comment by rvalyi** [comment]
na vdd eu acho que basta ter uma transação lenta no Odoo para ela ter risco de dar erro se neste mesmo tempo alguém escrever em uma tabela que ela escrever TB. Por isso que quando temos jobs que processam milhares de registros a gente tb da commit a cada alguns registros.

Hoje o envio da NFe é uma transação lenta porque no erpbrasil.edoc se faz o envio e depois, na mesma transação Odoo, se espera para consultar o recibo. Aí vc poderia pensar, basta fazer o envio pelo queue job...

... só que no PR da KMEE que manda pelo queue job é a mesma coisa de enviar a nota e depois ficar pendurado até o recibo ser liberado!

Conceitualmente isso tá errado. O que deveria ser feito neste PR com queue job seria de enviar a NFe na hora e depois pelo job consultar o recibo. Aí sim teria duas transações rápidas suficiente para não ter risco de erro de transação.

A maioria dos nossos clientes aqui são indústrias com relativamente poucas notas por isso este problema não pegou muito com a gente até agora. Mas vcs da KMEE que pretendem trabalhar com varejo com certeza isso vai pegar...

Como eu falei em caso de erro do tipo, o Odoo faz pelo menos um retry. Teria que verificar se esse retry não dá problema com a interação com o site da fazenda. Pode ser que não pelo fato de verificar se a nota já foi enviada. Aí esse retry deve dar conta de alguns erros se mandar sem queue job. Mas para projetos com muitas notas com certeza mandar primeiro e consultar pelo queue job, so que da forma correta será a solução...

**Comment by mileo** [comment]
> 

Sim, o queue job permite melhorias mas não creio que este seja o ponto, pois o usuário deve estar precisando de um feedback instantaneo, ou nao @antoniospneto ?

Os 7 pontos citados acima não dependem do uso do queue job e são melhorias possíveis, que também funcionariam na estrutura do pr #1887 

A melhoria citada acima pelo @rvalyi pode ser uma melhoria que também pode ser feita no #1887

**Comment by antoniospneto** [comment]
@mileo e @rvalyi obrigado por todos os pontos levantados aqui, concordo que tudo que foi comentando aqui pode sim ajudar a aumentar a performance da transmissão, acho essa discussão de grande valor, penso que aos poucos podemos ir implementando cada tópico.

Fui atrás do que estava levando a alteração nos registros  `res.partner` conforme proposto por mileo e encontrei o motivo, eram os campos choice que estavam sendo armazenados no banco de dados sem necessidade, abri uma PR para a correção aqui: #2644
