### ISSUE TITLE
[14.0][BUG]  l10n_br_zip: Erro ao buscar CEP.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2652]
## Module
l10n_br_zip

## Describe the bug
Ao tentar buscar o endereço a partir da pesquisa do CEP no cadastro de uma Parceiro o seguinte erro é apresentado:

> Error in PyCEP-Correios: name 'WebService' is not defined

![Imagem do WhatsApp de 2023-08-16 à(s) 15 37 56](https://github.com/OCA/l10n-brazil/assets/634278/a0178975-893b-44b7-9d50-f3cf7e28ea3a)

## To Reproduce
14.0

1.  Acessar o runboat 
2.  Iniciar o cadastro de um novo parceiro
3. Preencher o CEP
4. Clicar no botão de buscar endereço (lupa)

**Expected behavior**
O endereço deveria ser preenchido automaticamente.

**Additional context**
Será que um backport do que foi feito na v16 resolve ? #2572

**Comment by moigamijunior** [comment]
No meu caso acompanha esse erro no log: `odoo.addons.l10n_br_zip.models.l10n_br_zip: Library PyCEP-Correios not installed !`, mas verifiquei e está instalado. Meu `pip freeze` mostra `pycep-correios==5.2.0`.

**Comment by jonatasartur** [comment]
> Library PyCEP-Correios not installed

Estranhamente também estou recebendo a mensagem `Library PyCEP-Correios not installed` porém está instalado.

**Comment by crsilveira** [comment]
Isto está acontecendo por isso :   A This package has been renamed. Use pip install brazilcep instead.

**Comment by antoniospneto** [comment]
resolvido com o #2716 valeu galera!
