### ISSUE TITLE
Boleto unico para multiplas faturas

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#2658]
Temos um cliente em que tem em sua rotina muitas compras onde várias faturas/documentos fiscais tem um mesmo boleto. 

Situações em que ocorrem: 
1. CTes de um determinado periodo são unificados com uma unica fatura/boleto, 
2. NFSes de um grupo de agências de várias cidades que são cobradas todas em conjunto
3. Manutenção de veículos em que há NFe e NFSe em uma única cobrança.

Exemplo, três vencimentos distintos sendo cobrados em um único boleto
- CTe 1: R$100
- CTe 2: R$250
- CTe 3: R$250
- Boleto referente aos três CTe R$600

A maior reclamação é que não é legível ter os valores quebrados, que diferem com os valores do boleto real, porque pode induzir ao erro ou a confusão. Por isso o financeiro precisaria de uma visão consolidada.

Pensamos em alguns caminhos, mas nenhum deles parecem atender de forma completa:

-------------
**### CRIAR UM MODELO DE AGRUPAMENTO**
Criar um modelo que seja o agrupamento de move.line pagaveis/recebíveis, criando uma view nova que traria uma visão semelhante ao que temos hoje em "Pagamentos e Lista de Vencimentos", porém levando em consideração os valores exatos das obrigações e que pudesse cadastrar informações para pagamento futuro, por exemplo código de barras do boleto. 

Seria possível selecionar os move.lines e criar um registro desse novo modelo.

Vale ressaltar que na maioria das vezes esse novo modelo representaria um unico move.line financeiro, que acredito ser a forma mais normal. Não haveria sentido só ter casos em que há agrupamento, porque meio que substituiria a visão dos "Pagamentos e Lista de Vencimentos" e seria usado para acompanhamento financeiro geral.

Pontos positivos:
- Seria uma camada acima, mantendo o vinculo com os move.lines, não precisando alterar nenhum comportamento nativo do odoo.

Pontos negativos:
- Duas visões com informações muito semelhantes
- Não ajudaria muito no extrato bancário (teria que analisar melhor)

--------
**### USAR CONTAS DE COMPENSAÇÃO**
A ideia seria enviar os valores dos move.line financeiros originais para contas de compensação e logo após consolidar todos em um unico move.line consolidado.

Pontos Positivos:
- Não teríamos mais visões e modelos com pratiamente as mesmas informações.

Pontos Negativos:
- Mais complexidade para a contabilidade no Brasil, pois teríamos que criar um status temporário de pagamento, para que a fatura não fosse considerada paga ao ter os valores 'consolidados' com outros.

Vocês tem algum caso semelhante ou alguma ideia de como isso poderia ser trabalhado? @rvalyi @marcelsavegnago @douglascstd @mileo @renatonlima

**Comment by rvalyi** [comment]
@felipemotter se eu não me engano isso seria resolvido por um refator que eu queria fazer e sobre o qual ja te falei: que um mesmo account.move possa juntar varios documentos fiscais. Na vdd cada account.move.line poderia ter o documento fiscal dele. Geralmente seria o mesmo, o do account.move, mas em algumas situações poderiamos ter um account.move composto.

Eu tinha começado esse refator aqui https://github.com/akretion/l10n-brazil/commit/dec9df0e192f5a6f5c2545cd1cf784e5f13c751a com testes aqui https://github.com/akretion/l10n-brazil/commit/c5fd09e3107ef643c4c67e696823e9c1318913f2

Porem eu acabei largando para dar uma focada no SPED porque é importante não cagar o SPED tb. Semana que vem eu consigo retomar e explicar melhor. Mas eu acho que soluciona. Tb tou querendo fazer esse merge antes https://github.com/OCA/l10n-brazil/pull/2590 (os testes com account.move composto estão por cima desta PR) so que tem umas contas de compensação de imposto cagadas no l10n_br_coa_generic que precisa arrumar antes...

**Comment by felipemotter** [comment]
@rvalyi eu vou estudar a sua ideia!!

**Comment by felipemotter** [comment]
@rvalyi chegou a ter algum avanço com essa ideia? Outra questão que surgiu agora, notas complementares por exemplo de importação por conta e ordem, uma fatura estará relacionada a mais de uma NFe.

**Comment by rvalyi** [comment]
boa noite @felipemotter, não mexi mais, mas agora que eu meio que engatei a questão do SPED, faz partes das minhas maiores prioridades finalizar isso sim. Ou seja eu diria que em questão de 2 semanas eu teria um PR pronto.

**Comment by marcelsavegnago** [comment]
> @felipemotter se eu não me engano isso seria resolvido por um refator que eu queria fazer e sobre o qual ja te falei: que um mesmo account.move possa juntar varios documentos fiscais. Na vdd cada account.move.line poderia ter o documento fiscal dele. Geralmente seria o mesmo, o do account.move, mas em algumas situações poderiamos ter um account.move composto.
> 
> Eu tinha começado esse refator aqui [akretion@dec9df0](https://github.com/akretion/l10n-brazil/commit/dec9df0e192f5a6f5c2545cd1cf784e5f13c751a) com testes aqui [akretion@c5fd09e](https://github.com/akretion/l10n-brazil/commit/c5fd09e3107ef643c4c67e696823e9c1318913f2)
> 
> Porem eu acabei largando para dar uma focada no SPED porque é importante não cagar o SPED tb. Semana que vem eu consigo retomar e explicar melhor. Mas eu acho que soluciona. Tb tou querendo fazer esse merge antes #2590 (os testes com account.move composto estão por cima desta PR) so que tem umas contas de compensação de imposto cagadas no l10n_br_coa_generic que precisa arrumar antes...

@rvalyi sobre este tema acredito que os commits citados já entraram neh ?

**Comment by rvalyi** [comment]
> @rvalyi sobre este tema acredito que os commits citados já entraram neh ?

Sim, eu fiz as mudanças necessárias para isso aqui https://github.com/OCA/l10n-brazil/pull/2761
Nisso eu proponho fechar o issue. Sendo que poderia ser feito ferramentas para ajudar agrupar os documentos fiscais, pois hoje é possível selecionando documentos fiscais para importar num account.move, mas talvez tem como melhorar a usabilidade da coisa.
