### ISSUE TITLE
[14.0] [BUG] Amount total descontando retenção

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#2659]
Hoje o amount_total das faturas está ignorando os valores do mixin e está calculando pelo método nativo.

Pelos meus testes, se ele fosse calculado pelo método da localização, teríamos o valor total como o valor do documento fiscal, ou seja, ele levaria em consideração os valores da retenção também, ou seja, não diminuiria estas do valor total.

O fato é, da forma que está hoje, o valor total está diminuindo os valores das retenções. Na minha opinião, se não este campo, algum outro deveria ter o valor completo.

A foto a seguir eu criei o campo amount document que usa o mesmo método do amount_total da localização.
![image](https://github.com/OCA/l10n-brazil/assets/6812128/7c2e6116-0945-4973-b05e-b5697dadb8e2)

Agora minha dúvida, qual opção seria a correta?
1. Corrigir para que o amount_total seja calculado corretamente como esperado pela localização e seja diferente do nativo?
2. Criar um campo específico para este total e de alguma forma mostrar os dois valores?

@renatonlima @rvalyi

**Comment by antoniospneto** [comment]
No módulo account nativo, é esperado que o `amount_total` seja o valor total do financeiro ou seja, a soma de todos os vencimentos (contas a receber ou apagar) eu acho que pode ser ruim a ideia de sobrescrever o valor do  `amount_total`  para ser o valor do documento ao invés do valor financeiro, pois pode conflitar com outros módulos foram da localização que não esperam por isso, por exemplo os módulo de controle de crédito da OCA, que usa o `amount_total` para analisar o risco.

já no fiscal o `amount_total` é o valor total do documento, que nem sempre vai ser o valor do financeiro, por exemplo uma nota fiscal de remessa, ou no caso de uma nota fiscal de serviço com retenção, o `amount_total` é o valor bruto dos serviços.

Minha proposta é alterar o nome do campo `amount_total` no fiscal para não conflitar com o `amount_total` que já existe na fatura nativa, talvez mudar no fiscal para `fiscal_amout_total` ou `l10n_br_amount_total`  dessa forma a gente consegue exibir esse valor na visão da fatura em conjunto com o `amount_total` nativo, sem que um sobreponha o outro.

**Comment by rvalyi** [comment]
cc @renatonlima vc não tinha comentado comigo sobre esse tipo de problema?

**Comment by antoniospneto** [comment]
Obs: eu acho que a mudança do nome é bom de qualquer forma, pois hoje se quiser ver o valor real do `amount_total`, no caso da NFe, é abrindo o XML e conferir o que tá na tag vNF (Valor da Nota Fiscal)
