### ISSUE TITLE
[14.0][BUG] l10n_br_stock_account: Quantidades erradas na separação de estoque quando é um KIT.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2661]
## Modúlo
l10n_br_stock_account

## Descrição do BUG:

A separação de estoque (Picking) está sendo gerada com as quantidades incorretas ao confirmar um pedido
que o produto é um Kit. ( funcionalidade nativa do módulo de manufatura (MRP)
## Versões afetadas:
Apenas na 14.0
Na 12.0 o mesmo não acontece.

## Etapas para reproduzir o comportamento:
1. Acesse o runboat da versão 14.0 da localização
2. Instale o módulo nativo Manufatura (mrp)
3. Crie um novo produto chamado "kit de teste" informe o product type como "Storable Product"
![image](https://github.com/OCA/l10n-brazil/assets/634278/c96054fd-e82d-4bb3-a4af-6f689492d1b4)
5. Crie uma lista de material (bom) para esse produto, informe que é um kit e informe que ele é composto por 1 Storage Box e 1 Large Desk, assim:
![image](https://github.com/OCA/l10n-brazil/assets/634278/df5da810-7657-4618-971d-8b5bb8c00014)
6. Crie um pedido de venda para 1 unidade deste kit.
7. Confirme o pedido e abra o Picking (Delivery/Separação) gerado
8.  Veja que as quantidades geradas para separação do estoque não está de acordo com o que definimos na lista de material:
![image](https://github.com/OCA/l10n-brazil/assets/634278/7a11debe-ddae-457f-8c9b-d93ed4c4c068)

**Comportamento esperado**
A separação do estoque deveria ser lançado com uma unidade apenas de cada item, conforme descrito na listagem de material do Kit.

**Contexto Adicional**
Eu já identifiquei a parte do código da localização  que está conflitando com o comportamento nativo dos Kits, daqui a pouco vou estar propondo uma pull request.

**Comment by rvalyi** [comment]
Ola @antoniospneto então vale a pena vc olhar tb o que @renatonlima tinha feito para trabalhar com remessas com kits na v12: https://github.com/OCA/l10n-brazil/pull/2460
Apesar que realmente isso ainda não tinha sido testado com a v14 e pode ser que tenha alguma treta para resolver.

**Comment by antoniospneto** [comment]
> Ola @antoniospneto então vale a pena vc olhar tb o que @renatonlima tinha feito para trabalhar com remessas com kits na v12: #2460 Apesar que realmente isso ainda não tinha sido testado com a v14 e pode ser que tenha alguma treta para resolver.

@rvalyi  vou dar uma olhada, não tinha visto não, eu até procurei se tinha algo em aberto, mas acho que usei os termos errados na hora de pesquisar, valeu!

**Comment by antoniospneto** [comment]
@rvalyi eu olhei a #2460 mas ela ainda não resolve essa questão das quantidades dos componentes que ficam duplicadas 
no picking, lá na 12.0 não tem esse problema, é algo que foi mudado na 14.0 que conflita com a localização

**Comment by rvalyi** [comment]
foi solucionado com https://github.com/OCA/l10n-brazil/pull/2662
