### ISSUE TITLE
[14.0] Sessão "outros valores" não sendo considerados no total da fatura, quando ela é preenchida isoladamente

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2666]
Valor de frete não somando ao preencher fatura diretamente

## Module
The name of the module that has a bug.

l10n_br_account ?????

## Describe the bug

Ao tentar preencher uma fatura diretamente, o custo do frete (ou quaisquer campos "outros custos"), os mesmos não são somados para perfazer o total corretamente, e não são considerados nos impostos.

## To Reproduce
**Affected versions**:
14.0

1.  Crie uma fatura
2. Preencha-a corretamente
3. Tente preencher qualquer dos campos "outros custos".
4. Após salvar, notará que os valores não se adicionarão aos totais.

**Expected behavior**
Tais valores poderiam ser preenchidos igual na S.O

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
![image](https://github.com/OCA/l10n-brazil/assets/25938418/ee06ecc3-e003-474d-89fa-01fda59e0ad7)

**Comment by antoniospneto** [comment]
@augustodinizl esse bug ainda acontece? é só quando você preenche os valores pelos totais ?
utilizando essa configuração?
![image](https://github.com/OCA/l10n-brazil/assets/634278/4d13d8f6-91fd-47fa-8ca3-4ce18e6bbba1)

**Comment by corredato** [comment]
@antoniospneto No l10n_br_sale, os campos de frete e etc são declarados lá na SO também, e os inverses funcionam perfeitamente, o caso é replicar esses campos, computes e etc no account move e account move line, já que eles estão propriamente declarados apenas nos mixins do fiscal, tô tentando fazer isso, mas tá meio buxa...

**Comment by corredato** [comment]
@antoniospneto @mileo @rvalyi @mbcosta @renatonlima @marcelsavegnago 

Alguém dá um no stale aqui pq não pode continuar desse jeito, sabe-se lá quanto tempo isso aqui não tá funcionando direito.

Atenção:

> l10n_br_fiscal/models/document_mixin_methods.py:121

> l10n_br_fiscal/models/document_mixin_methods.py:171

> l10n_br_fiscal/models/document_mixin_methods.py:221

Antes de mais nada, quando alguém fizer algo parecido com isso, dá uma comentada explicando o que tá acontecendo, pq não é intuitivo

![image](https://github.com/user-attachments/assets/f5616ce9-1c75-41b8-90c7-e555b16565b7)

O sale herda os mixins do fiscal e tem os mesmos campos declarados com seus respectivos inverses, e tá funcionando quase 100%

### Caso de uso no sale passando no bloco if dos inverses:

### 1. Ao adicionar um produto e o frete:

![image](https://github.com/user-attachments/assets/5bbfc374-7068-4c07-81f4-08d935472b06)
![image](https://github.com/user-attachments/assets/a50cb361-92f0-432e-a839-a1cf1da64e3b)

### 2. Ao adicionar outro produto e manter o frete anterior:

![image](https://github.com/user-attachments/assets/e249378d-49f1-4d76-8bb4-98ee5c73b05b)
![image](https://github.com/user-attachments/assets/6933486a-28bf-4416-93df-ae8e4de0519e)

Seria certo o método do mixin ser chamado novamente e ocorrer a distribuição proporcional, mas não acontece.

Não vou falar mais do sale pq de certa forma ele tá funcionando de um jeito aceitável, por mais que possa melhorar, agora no account o buraco é bem mais embaixo.

### Caso de uso no account move passando no bloco if dos inverses:

### 1. Adicionar um produto e o frete:

![image](https://github.com/user-attachments/assets/61995aed-b47b-4fc3-87a9-d5577104507d)
![image](https://github.com/user-attachments/assets/db717929-a36f-463b-84b1-1701c276abbe)

O valor do frete entra na linha mas não é inserido no total da fatura;
Acredito que esses campos não poderiam ser editáveis.


### 2. Alterar o valor do frete na linhas altera o valor total da fatura e o campo de frete na fatura permanece o mesmo de antes

![image](https://github.com/user-attachments/assets/559a26c0-126b-4a46-9a7b-15c6464137c2)
![image](https://github.com/user-attachments/assets/2b155e67-ee4f-4aed-9efe-3e209a6390cd)

### 3. Adicionar outro produto e alterar o frete da fatura já faz as coisas começarem a ficar bizarras

![image](https://github.com/user-attachments/assets/57a622d5-d8c2-4f27-8a31-73f33549b23c)
![image](https://github.com/user-attachments/assets/cef80941-a14a-4c0f-b0b4-a31a3159d8c8)
![image](https://github.com/user-attachments/assets/11e28bd7-2b68-4c2b-b810-f8cca6c2bd11)

O inverse é chamado e ele faz a distribuição proporcional, mas continua utilizando o valor antigo adicionado manualmente na linha
### 
4. Pra completar, se você altera a quantidade de um produto, eu já nem sei mais que conta que tá acontecendo aqui.

![image](https://github.com/user-attachments/assets/946d8c1f-e214-45f5-a5f8-fe82fc7c36ca)

Claro, esse problema não é só no frete, também ocorre com o seguro e outros valores. O mais preocupante é que dependendo de como o usuário vai operar essa parte do fiscal, os valores ficam completamente divergentes da nota.

Tem diversos mais testes pra fazer, mas acho que dá pra parar por aqui. Só é chato algo tão quebrado ter passado no módulo mais importante da nossa localização, não sei se os casos não foram testados ou se foram e alguém rezou pra ninguém perceber.

Merece uma atenção especial.

**Comment by antoniospneto** [comment]
@corredato, obrigado por adicionar mais informações à issue. Esses detalhes certamente ajudam muito. Os PSCs já estão cientes do problema, mas precisamos aguardar a disponibilidade de alguém que possa focar nesta questão. Entendo que se trata de um problema sério e prioritário, mas precisamos balancear as várias demandas atuais da localização.

Vale lembrar que cada PSC tem suas próprias prioridades e precisamos respeitar o tempo e o planejamento de cada um. De qualquer forma, fica aberto o convite para que qualquer pessoa interessada apresente uma proposta de melhoria que possa acelerar a solução.

**Comment by rvalyi** [comment]
alem disso vale a pena dar uma pensada sobre que empresa ajudou (ou não...) a fazer o que (tipo para migrar para a v13 ou a v14) e se lembrar que pressionar para aumentar o scope, como pressionar para fazer MDfe, CTe, SPED, modulos de ecommerce etc certamente tira/tirou o foco dessas coisas mais prioritares...

Outra coisa eu acho que ninguém reza para ninguém descobrir tal ou tal bug, se tem gente que faz propaganda para fingir que o projeto ta num patamar que ele não esta ainda, dificilmente se trata de quem fez ou mantem esses módulos... Muito pelo contrário eu por exemplo sou um dos que sempre fala que o desafio de botar qualquer projeto Odoo para rodar no Brasil ainda é super difícil, que as mudanças na v13/v14 criaram desafios por anos etc...

Mas valeu pelos detalhes no bug report. Eu tb tinha começado a melhorar essas coisas... Mas infelizmente o ano passado eu tive que mudar o foco por para impedir que fosse cagado a importação de NFe ou o SPED por exemplo né... Porque bom depois que caga as coisas e ainda mais nos módulos existentes, a energia para "descagar" é 10x e acontece que tem certas pessoas que costumam cagar e andar e ainda fazem essa propaganda para fingir que as coisas não são como são, o que pertube as expectativas dos potenciais clientes e dificulta ainda mais qualquer investimento para resolver o que precisa resolver...

**Comment by mileo** [comment]
Pessoal venho acompanhando o @corredato diariamente na resolução do problema e endereçando uma solução. Assim que tivermos alguma novidade informo vocês / será aberto um PR.

**Comment by marcelsavegnago** [comment]
> Tem diversos mais testes pra fazer, mas acho que dá pra parar por aqui. Só é chato algo tão quebrado ter passado no módulo mais importante da nossa localização, não sei se os casos não foram testados ou se foram e alguém rezou pra ninguém perceber.

Grande @corredato. Realmente, é frustrante. Uma atividade importante, mas que poucos na comunidade têm feito, são as revisões funcionais. Por isso, te convido a acompanhar o projeto (caso não esteja fazendo isso diariamente ou semanalmente) e a colaborar com revisões e testes como os que fez. Isso vai ajudar muito! Normalmente, focamos em manter mais de 87%(não lembro a meta atual mas é por ai) de cobertura de testes, mas, mesmo chegando a 100%, ainda não cobriria todas as situações. Temos trabalhado na implementação de testes voltados para casos de uso específicos também... mas isso leva tempo. :D

**Comment by marcelsavegnago** [comment]
Só para registrar, a localização na versão 14 passou por uma grande revisão e aprimoramento, o que atrasou o início da migração para a versão 16.0. Agora, com mais apoio da comunidade e verba para P&D (de clientes), conseguiremos resolver muitas pendências que possam ter ficado na 14.0.

O desafio na versão 16.0 será intensificar os testes de geração de faturas, validar os lançamentos contábeis e testar ao máximo... a contabilidade rodando bonitinho, já era.. o resto fica fácil.

**Comment by rvalyi** [comment]
resolvido em #3529
