### ISSUE TITLE
Error in requirements.txt

### ISSUE THREAD

**Issue by falexandresilva** [OCA/l10n-brazil#2688]
## Module
Requirements.txt 

## Describe the bug
there is a duplication of lines. Specifically:

erpbrasil.edoc 
erpbrasil.edoc>=2.5.2
erpbrasil.transmissao
erpbrasil.transmissao>=1.1.0

## To Reproduce
**Affected versions**: 14.0

**Comment by marcelsavegnago** [comment]
Este problema está relacionado com o manifesto dos módulos. Como tem modulos que não estão especificando a versão, na hora de gerar o requirements.txt o mesmo é gerado com a lib duplicada.

Se tiver alguem interessado em contribuir, gera uma PR para um dos módulos como por exemplo este do ginfes adicionando a versão da lib que deu duplicado. Basicamente é deixar igual está no l10n_br_fiscal_dfe.

![image](https://github.com/OCA/l10n-brazil/assets/3595132/b78c33be-51e9-49c7-a67e-8d1f4f4b5055)

**Comment by marcelsavegnago** [comment]
![image](https://github.com/OCA/l10n-brazil/assets/3595132/434cd818-f1d1-481c-8446-e864a8181437)

**Comment by marcelsavegnago** [comment]
@felipezago pode tratar este caso ?
