### ISSUE TITLE
[14.0][BUG][Purchase] Ao faturar um Pedido de Compra de serviço, não aparece Smart Button para Fatura

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2708]
Ao faturar um Pedido de Compra de serviço, (selecionado na conf geral de faturamento pelo Picking). O Smart Button de faturas emitidas não aparece no pedido...
Mas como é um serviço, nunca teríamos um Picking para rastrear 

## Module
purchase (purchase.order)

## Describe the bug
![image](https://github.com/OCA/l10n-brazil/assets/20867090/2ef14304-b92a-49eb-9baa-ae9ed7088d8f)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/79e690e8-4e77-4905-ab71-5a4562fe51e6)

Se selecionado o modo de política de faturamento para pedido de compra:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/47b889d0-7abe-463a-b550-c45995a718a0)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/35da0cd8-b90d-4e53-896a-65e1527499c1)

## To Reproduce
**Affected versions**: 14.0
1. Configurar política de faturamento (Empresa): Stock Picking
2. Criar pedido de compra: Produto = Serviço
3. Criar Fatura pelo Pedido de Compra (pode ser necessário indicar a quantidade recebida)
4. Confirmar Fatura
5. Retornar ao pedido de compra. Não aparece o Botão Inteligente (smart button)

**Comment by mbcosta** [comment]
value @douglascstd procurei resolver o problema no PR https://github.com/OCA/l10n-brazil/pull/2711 , realmente esse botão deve sempre aparecer o que precisa ser verificado em que condições deve ou não parecer é o "Criar Conta". Sobre isso:
"3 , . Criar Fatura pelo Pedido de Compra (pode ser necessário indicar a quantidade recebida)"

Quando é um Serviço é preciso definir no Produto
![image](https://github.com/OCA/l10n-brazil/assets/6341149/01c9b44c-8ca2-4df3-88b9-bae3a40f8df0)

**Comment by douglascstd** [comment]
A PR #2711 Deverá resolver esse problema.
