### ISSUE TITLE
Como adicionar São Bernardo no NFS-e Ginfes?

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2726]
Verifiquei que é necessário algumas alterações para incluir a cidade de SBC - SP no NFS-e, Ginfes.
A minha dúvida seria qual seria as estruturas de pastas para se fazer as adequações, também preciso incluir campos na impressão, hoje empresas que não são MEI's ainda precisam emitir pelo site da prefeitura.

**Comment by marcelsavegnago** [comment]
Se de fato for GINFES, precisaria apenas submeter uma PR incluindo o codigo ibge da cidade e o provedor ginfes na frente igual a referencia abaixo. Já as configurações de URL e logo da cidade vc configura no cadastro da empresa.

https://github.com/erpbrasil/erpbrasil.edoc/blob/914bb8bff8199d5be38e85ccb1265d5aed6f67ea/src/erpbrasil/edoc/provedores/cidades.py#L16
