### ISSUE TITLE
Documentação da Localização.

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2727]
Gostaria de ajudar com a documentação da Localização, se alguém puder dar um suporte eu poderia descrever cada módulo e suas configurações e requerimentos de funcionamento, isso facilitaria os iniciantes e ajudaria também na documentação das alterações.

**Comment by marcelsavegnago** [comment]
@rodmad85 sugiro começar pela revisão/melhoria dos READMEs de cada módulo. Para isso vc pode submeter uma pull request alterando arquivos como estes:

https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_crm/readme/DESCRIPTION.rst
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_crm/readme/USAGE.rst
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_crm/readme/INSTALL.rst

Obs. Quando for submeter a PR, sugiro que faça por módulo para que possamos discutir separadamente.

Obs2. não precisa se preocupar com o arquivo README.rst já que ele é gerado automaticamente durante o merge.

**Comment by rodmad85** [comment]
Entendi, só não sei se estou autorizado a incluir essas alterações no repositório. Vou me atualizar na questão de uso do Github. Iniciarei os textos separadamente e quando estiver algo pronto, retorno aqui para darmos seguimento.

**Comment by marcelsavegnago** [comment]
Vc faz o fork do projeto, cria uma branch nova no teu fork e faz uma pull request para o repositorio da localização

**Comment by marcelsavegnago** [comment]
Assina a CLA individual

https://odoo-community.org/about/cla
