### ISSUE TITLE
Erro ao pesquisar CNPJ, não retorna a cidade.

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2741]
Ao pesquisar o CNPJ o campo cidade não é preenchido.

**Comment by rpsjr** [comment]
aqui o campo cidade foi preenchido ao pesquisar um CNPJ, você testou no runboat?

**Comment by antoniospneto** [comment]
@rodmad85 não consegui reproduzir o problema aqui, todos os cnpjs que pesquisei retornou a cidade.

**Comment by rodmad85** [comment]
Problema foi resolvido. Desculpe a demora.

Em qui., 29 de fev. de 2024, 21:59, Antônio Neto ***@***.***>
escreveu:
