### ISSUE TITLE
Erro ao importar XML (NFe)

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2754]
Ocorre o seguinte erro ao importar a NFe.

The operation cannot be completed:
- Criar/atualizar: um campo obrigatório não está definido.
- Excluir: outro modelo requer que o registro seja excluído. Se possível, arquive-o em vez disso.

Modelo: Supplier Pricelist (product.supplierinfo), Campo: Vendor (name),

Outro erro aconteceu ao selecionar outro XML:

  File "/home/odoo/odoo14/core/l10n-brazil/l10n_br_nfe/wizards/import_document.py", line 189, in _get_taxes_from_xml_product
    ipi_trib = product.imposto.IPI.IPITrib
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/odoo14/core/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo14/core/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'IPITrib'

**Comment by mileo** [comment]
@rodmad85 isso foi com a recém mergeada funcionalidade de importação de XML? 

@hirokibastos @ygcarvalh @luismalta @DiegoParadeda

**Comment by rodmad85** [comment]
Sim.

**Comment by mileo** [comment]
Pode me enviar no telegram o XML que vc esta tentando importar? []s

**Comment by rodmad85** [comment]
> Pode me enviar no telegram o XML que vc esta tentando importar? []s

Te encaminhei no dia 30/10

**Comment by hirokibastos** [comment]
Fix criado em #2790
