### ISSUE TITLE
Utilização de Documentos importados por XML.

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2780]
Gostaria de saber aos responsáveis pelo modulo de importação XML e DFE se há algo em andamento para o tratamento e utilização dos documentos importados por XML.

Vincular documento importado com pedido de compra.
Gerar fatura de fornecedor através de documento importado e o mesmo seria vinculado ao pedido de compra.

O mesmo processo para vendas.

**Comment by antoniospneto** [comment]
https://github.com/OCA/l10n-brazil/pull/2781

**Comment by marcelsavegnago** [comment]
@rodmad85 Se possivel, faça testes funcionais e revise a PR por favor. Isto já seria uma forma de colaborar.

**Comment by rodmad85** [comment]
Irei verificar essa semana.

Em qui., 29 de fev. de 2024, 08:49, Marcel Savegnago <
***@***.***> escreveu:
