### ISSUE TITLE
[14.0][15.0][16.0] git checkout on windows "" error: invalid path 'l10n_br_base/migrations/14.0.2.0.0/post-migration.py ' ""

### ISSUE THREAD

**Issue by rpinset** [OCA/l10n-brazil#2784]
## Module
l10n_br_base

## Describe the bug
When I git checkout on windows (for Docker environment) "" error: invalid path 'l10n_br_base/migrations/14.0.2.0.0/post-migration.py ' "" because file has got a space after ".py"
https://github.com/OCA/l10n-brazil/blob/15.0/l10n_br_base/migrations/14.0.2.0.0/post-migration.py%20

## To Reproduce
**Affected versions**: 14.0 15.0 16.0

1. On windows
2. Git clone this repo
3. git checkout 14.0

**Comment by antoniospneto** [comment]
Opsss, here's the correction: #2785

"Thank you for reporting!"

**Comment by antoniospneto** [comment]
@romaric-pl 

Here's a suggestion: Installing Odoo on Windows is not extensively tested. I recommend opting for a Linux distribution, which is more widely supported in the community. You'll likely encounter fewer difficulties, and if you prefer to stick with Windows, consider using WSL (Windows Subsystem for Linux).

**Comment by rpinset** [comment]
a small mistake can happen to the best


the anomaly is also present in 15.0 and 16.0 @antoniospneto
