### ISSUE TITLE
Emissão NFe pessoa física retorna sempre 302 Uso Denegado: Irregularidade fiscal do emitente 

### ISSUE THREAD

**Issue by converge** [OCA/l10n-brazil#28]
Problema: não faz emissão de NFe para pessoa física, ao tentar emitir a NFe o retorno é:

302 Uso Denegado: Irregularidade fiscal do emitente 

Passos para gerar o bug:
1. cadastrar o cliente como pessoa física
2. criar uma ordem de venda
3. exportar a NFe

OpenERP 6.1

**Comment by rvalyi** [comment]
invalido: https://groups.google.com/d/msg/openerp-brasil/tr8s9ZyFjpY/Ls0d85WCI9YJ
