### ISSUE TITLE
[14.0][l10n_br_purchase] Pedido de compra confirmado permite a troca do produto da linha do pedido via form.

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2811]
Módulo
======
l10n_br_purchase

Descreva o Bug
==============
Na localização brasileira, quando o pedido de compra está confirmado, o sistema permite trocar o produto da linha do pedido.

Para Reproduzir
===============
Para reproduzir, eu recomendo teste em um ambiente com apenas o core do Odoo e um teste com a localização brasileira.

Passos para reproduzir o comportamento:
1. Crie um novo pedido de compra (com o produto Storage Box)
2. Confirme o Pedido de Compra
3. Volte no pedido, 
4. Clique em editar 
5. Tente alterar o produto e salvar o pedido de compra

Observe que apenas com o core não é possível fazer a troca do produto. Já com a localização brasileira, tendo a edição da linha em via form e não via tree, é possível fazer a troca do produto.

Comportamento Esperado
======================
O comportamento esperado é que o sistema permita apenas a edição da descrição do produto e campos como quantidade e o preço unitário, e que certos campos não possam ser editados.

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/2813
