### ISSUE TITLE
[14.0][BUG] l10n_br_fiscal: não é possivel inserir seções nos pedidos de venda.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2863]
Apenas para deixar registrado, atualmente na versão 14.0 não está sendo possivel adicionar seções nos Pedidos de Venda.
Pois o sistema está obrigando o preenchimento da operação fiscal na linha.
![image](https://github.com/OCA/l10n-brazil/assets/634278/c42225a3-8984-4221-9ff1-7e8e1e29db38)

**Comment by douglascstd** [comment]
Olá Neto, tudo bem? acredito que essa PR #2862 deva resolver esse problema. Que hoje é obrigatório ter linha de operação fiscal em todas as linhas, inclusive a linha de  secção ou comentário...

**Comment by mbcosta** [comment]
Valeu @antoniospneto por reportar o problema, @douglascstd acredito que o PR https://github.com/OCA/l10n-brazil/pull/2866 deve resolver o problema, inclui o campo product_id para definir se o campo é requerido ou não

**Comment by antoniospneto** [comment]
Obrigado @mbcosta, isso vai ajudar, mas eu acho que ainda vai ter um outro problema, no processo de "Criar Fatura" mas logo a gente abre um PR com a correção.

**Comment by antoniospneto** [comment]
Apenas para atualizar a issue, o problema continua persistindo mesmo após o merge da PR #2866. Em breve, a Engenere pretende abrir uma nova PR com a correção.
![image](https://github.com/OCA/l10n-brazil/assets/634278/25ec092a-4954-4a63-a415-1aa2d1e809ce)

**Comment by antoniospneto** [comment]
Resolvido com o #2907
