### ISSUE TITLE
[l10N_BR_ACCOUNT][BUG] Uso da função "Lançar Entradas" para faturas em rascunho impossibilita emissão de Documento Fiscal

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#2873]
Ao tentar acionar a postagem das faturas em lote, pelo botão ação, as faturas que necessitam de Documento Fiscal ficam em um status que não podem ser continuados.

## Module
l10N_BR_ACCOUNT

## Como reproduzir:
Criar um pedido de venda com 1 produto.
	Selecionar Tipo de Documento (SE)
	Operação: Venda
	Selecionar produto ([ODOO_DEV] Customized Odoo Development)
	Adicionar outros dados
Confirmar Pedido
Criar Fatura (será criada em modo rascunho)
Acessar lista de Faturas
Marcar a linha da fatura criada (pelo pedido de venda)
Acionar: Ação >> Lançar Entradas
Observe o botão "Detalhes Fiscais"
O Documento ainda permanece "em digitação", enquanto a fatura está Lançada.

Passo a Passo do ocorrido:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/ce637a2a-0e56-49b5-a6a1-958038dce2e6)

![image](https://github.com/OCA/l10n-brazil/assets/20867090/a9e03e82-53d7-480a-857e-d48a2834e20d)

![image](https://github.com/OCA/l10n-brazil/assets/20867090/1c2d15dd-9534-4689-9027-a166020c933c)

![image](https://github.com/OCA/l10n-brazil/assets/20867090/fd6e8ada-9e81-4e9d-ab7a-834d5ceb08b7)

## Se usar a mesma fatura, e retornar para provisório e acionar o botão "Confirm"
![image](https://github.com/OCA/l10n-brazil/assets/20867090/cc8062d9-94ad-4f3f-b0f4-8e06ab8f6e05)

Provavelmente a ação (Ação>>Lancar Entradas) deve omitir algum passo que o botão "Confirm" executa.

**Comment by antoniospneto** [comment]
A função que é chamado no action é o `_post()` enquanto no botão é o `action_post()`

A localização brasileira acaba que extende as funcionalidade diretamente no `action_post`, penso que o correto é movermos essa logica para o `_post`

![image](https://github.com/OCA/l10n-brazil/assets/634278/b19a4ef2-4b72-4361-8495-19b3649c3070)

acho que é tranquilo fazer ess alteração pois nativamente o `action_post` é apenas uma abstração do `_post`:
![image](https://github.com/OCA/l10n-brazil/assets/634278/66481196-30fc-41e7-bf3e-6a04b6627302)

**Comment by antoniospneto** [comment]
@douglascstd 
Se puder conferir se agora com o merge do #2888 o problema foi resolvido.
