### ISSUE TITLE
[14.0][BUG][l10n_br_account] Impossibilidade de inserir impostos em uma fatura gerada por uma SO que não tem operação declarada. 

### ISSUE THREAD

**Issue by augustodinizl** [OCA/l10n-brazil#2877]
Ao tentar editar uma fatura criada por uma SO  de serviço onde a 
![SCR-20240117-mwcu](https://github.com/OCA/l10n-brazil/assets/25938418/3e495ad4-1e9c-4f96-9c6f-14eb6566fe87)

operação fiscal não foi preenchida, a mesma dá o seguinte erro:
![SCR-20240117-mxfl](https://github.com/OCA/l10n-brazil/assets/25938418/9a568f29-d6ee-4681-a7ff-07238bbc2709)

## Module
The name of the module that has a bug.
l10n_br_account
## Describe the bug

Com a mudança efetuada pela PR #2743 , o campo de operação deixa de ser obrigatório na SO, causando os seguinte erro ao tentarmos inserir as informações fiscais diretamente na fatura gerada após a confirmação da SO.
![SCR-20240117-mxfl](https://github.com/OCA/l10n-brazil/assets/25938418/9a568f29-d6ee-4681-a7ff-07238bbc2709)

## To Reproduce
**Affected versions**:
14.0

1.Crie uma SO sem selecionar a operação
2.Insira um item do tipo serviço
3.Crie a fatura
4.Tente preencher na fatura os dados para a emissão de uma nfs-e
5. Não será possível salvar a mesma

**Expected behavior**
Como não há movimentação de estoque, creio que seja necessário algum ajuste no código que retorna tal erro.
**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

Ping: @marcelsavegnago, @douglascstd, @rvalyi

**Comment by mbcosta** [comment]
Valeu @augustodinizl por reportar, é importante entender o caso de uso que você está testando, algumas perguntas:

Por que você está criando um Pedido de Vendas sem a Operação Fiscal se você pretende que a Fatura gere um Documento Fiscal? Tem algum motivo especifico?

Porque a implementação foi pensada para quando você criar um Pedido de Vendas sem a Operação Fiscal fica sub entendido que a Fatura/Invoice não deve gerar Documento Fiscal, é o caso de uma Fatura/Invoice Internacional o padrão original do modulo account, quando tem a Operação Fiscal é o caso que vai gerar o Documento Fiscal então hoje a decisão se vai gerar ou não o Documento Fiscal precisa ser feita já na criação ou antes de Confirmar o Pedido de Vendas, porque no código os métodos que carregam os Dados Fiscais do Brasil são feitos baseados nessa informação aqui https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_sale/models/sale_order.py#L185 veja que isso está depois da verificação se tem a Operação Fiscal.

Por enquanto até onde vi esse comportamento é o ideal porque não deveria existir o caso onde o Pedido de Vendas não tem a Operação Fiscal e portanto não mostra os campos Fiscais do Brasil mas a Fatura criada tem os Dados Fiscais e gera o Documento Fiscal, mas dependendo da justificativa do seu caso de uso podemos considerar ser necessário alterar o codigo para atender.

**Comment by augustodinizl** [comment]
Grande @mbcosta , obrigado pela explicação, o caso que presenciei, é na venda, onde os vendedores nem se preocupam com a classificação fiscal ou impostos pois a margem de lucro praticada pela empresa já prevê o recolhimento de tais impostos, e a SO é encaminhada para outro departamento para os ajustes fiscais da nf-e, onde tais ajustes seriam feitos na fatura para a geração da nf-e.

Por isso penso que podemos usar alguma variável (ou um conjunto de variáveis) tipo o país do parceiro/cliente + alguma outra variável, assim, poderíamos ter os impostos declarados na fatura. ao invés de somente usarmos o campo operação na SO para determinar se na fatura serão ou não declarados os impostos

**Comment by mbcosta** [comment]
@augustodinizl acabei revendo o seu issue recentemente acredito que faltou uma resposta mais clara, segue:

O recomendado é que a Operação Fiscal seja informada já no Pedido de Vendas porque como todos os objetos herdam o Mix Fiscal, incluindo a Fatura/account.move, quando o Usuário informa a OP Fiscal o "motor fiscal" carrega todos os dados necessários em todos os objetos, portando a parametrização ideal é a Empresa é o responsável, ou responsáveis, pelo Fiscal configurarem as Operações usadas pela Empresa porque assim quando um Vendedor cadastra um Pedido de Vendas ele simplesmente informa a OP Fiscal e o mapeamento já é feito mesmo que seja parcial e precise se corrigido na Fatura, já que tendo um "motor fiscal" no programa é improdutivo e repetitivo ( porque existe muita chance de casos fiscais iguais ) ficar preenchendo todos os Dados Fiscais, Impostos e etc na "mão" todas as vezes ao invés de usar o "moto fiscal".
