### ISSUE TITLE
Impressão de NFCe em branco no POS

### ISSUE THREAD

**Issue by guilhermeats** [OCA/l10n-brazil#2893]
Bom dia, estou emitindo a NFCe pelo Ponto de Venda em um cliente e ao finalizar ela é emitida perfeitamente:
![image](https://github.com/OCA/l10n-brazil/assets/157712313/5096cc72-ddf4-453b-aad9-1cb12cc0bf1f)

No entanto quando clico no botão imprimir recibo, a tela vem toda em branco, ja alterei as configurações de layout mas sigo com mesmo problema

![image](https://github.com/OCA/l10n-brazil/assets/157712313/4b5bbc6f-5ab7-40d1-97b5-a04e25a9b942)

Alguem ja passou por algo parecido?

Obrigado

**Comment by mbcosta** [comment]
@guilhermeats veja se aparece algo no LOG do programa ao tentar Imprimir, não conheço de perto a implementação do PoS, mas é importante saber que foi criado um PR recentemente que pretende fazer uma grande refatoração do modulo principal l10n_br_pos https://github.com/OCA/l10n-brazil/pull/2890 então dependendo do seu nível de conhecimento, disponibilidade e cronograma do seu projeto talvez seja bom você considerar participar dessa refatoração e assim ter um contato direto com os mantedores do modulo
