### ISSUE TITLE
[14.0][BUG] Relatorio Movimentos de Estoque: Erro ao tentar acessar um movimento de estoque

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#2900]
![image](https://github.com/OCA/l10n-brazil/assets/3595132/b09e41e1-b867-40e1-a047-d63529ef7b15)

**Comment by mbcosta** [comment]
@marcelsavegnago com o merge do PR https://github.com/OCA/l10n-brazil/pull/2947 acredito que o problema foi resolvido, certo? Apenas para confirmar e ver de encerrar esse issue

**Comment by marcelsavegnago** [comment]
Perfeito, resolvido. Parabens pelo trabalho
