### ISSUE TITLE
14.0 ISSUE ao instalar as dependências da wiki

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#2918]
root@odoo .../oca/l10n-brazil# apt-get update \
        && apt-get install -y --no-install-recommends \
            locales \
            ca-certificates \
            nano \
            wget \
            git \
            mercurial \
            screen \
            htop \
            curl \
            openssh-client \
            node-less \
            node-clean-css \
            tig \
            binutils \
            build-essential \
            bzr \
            ca-certificates \
            cpp \
            cups \
            gcc \
            dpkg-dev \
            fontconfig \
            fontconfig-config \
            gir1.2-glib-2.0 \
            git \
            git-core \
            git-man \
            tar \
            zip \
            gzip \
            zlib1g \
            sudo \
            virtualenv \
        && cp -r wkhtmltox/share/man/man1 /usr/local/share/man/ltox.tar.xz' | sha1sum -c - \download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
Hit:1 http://security.debian.org bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                                              
Ign:3 http://archive.turnkeylinux.org/debian bullseye-security InRelease                           
Ign:4 http://archive.turnkeylinux.org/debian bullseye InRelease
Hit:5 http://archive.turnkeylinux.org/debian bullseye-security Release
Hit:7 http://archive.turnkeylinux.org/debian bullseye Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
Note, selecting 'expect' instead of 'expect-dev'
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
Note, selecting 'postgresql-client-13' for glob 'postgresql-client*'
Note, selecting 'postgresql-client-common' for glob 'postgresql-client*'
Note, selecting 'postgresql-client' for glob 'postgresql-client*'
Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package cython is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libpython-dbg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libpython2-dbg

E: Package 'libpng12-dev' has no installation candidate
E: Package 'cython' has no installation candidate
E: Unable to locate package gfortran-5
E: Unable to locate package libgfortran-5-dev
E: Package 'libpython-dbg' has no installation candidate
E: Unable to locate package libpython3.5-dbg
E: Couldn't find any package by glob 'libpython3.5-dbg'
E: Couldn't find any package by regex 'libpython3.5-dbg'

**Comment by antoniospneto** [comment]
Poucas a informações para entender o problema, o wiki pode estar desatualizado também.
Se ainda estiver enfrentando problemas, favor reabrir a issue com mais detalhes.
