### ISSUE TITLE
l10n_br_account_payment_brcobranca: Limitação no Registro de Tarifas 

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2919]
Atualmente, o módulo `l10n_br_account_payment_brcobranca ` apresenta uma limitação: o lançamento das tarifas não ocorre quando o evento não é classificado como "liquidação".

Por exemplo, em situações em que bancos cobram tarifas pela confirmação de registro do boleto, pela alteração de vencimento, ou para protestar, entre outras, essas tarifas não são registradas pelo sistema Odoo. O lançamento dessas despesas acontece apenas nos casos em que ocorre efetivamente a liquidação do boleto.

**Comment by mbcosta** [comment]
@antoniospneto valeu, é importante destacar que os CNABs não são iguais entre si, o que existe para um caso pode não existir para outro, então é importante saber:

 Se você tem esse caso, qual o Banco e CNAB ocorrem? Se sim tem como disponibilizar dados de exemplo, nesse casos são os arquivos de retorno alterados com dados anônimos, apenas para poder testar o processo e inclui-los como dados de demonstração, 

Olhando nos Códigos de Retorno dos Bancos que existem hoje é possível ver, que em alguns Bancos CNAB tem um código que parece ser referente a Tarifa, mas é importante ver um arquivo de exemplo para saber quais os campos que estão sendo preenchidos para identificar se a alteração precisa ser feita somente na Localização ou no BRcobranca

AILOS 240, parece ter apenas um Código referente a Débito de Tarifas/Custas
![image](https://github.com/OCA/l10n-brazil/assets/6341149/eaaf044a-63f5-433c-a969-bac739202832)


Bradesco 400, parece ter apenas um Código referente a Débito de Tarifas/Custas
![image](https://github.com/OCA/l10n-brazil/assets/6341149/4fd2e35e-fa5a-4355-a968-3132f4f275bd)

Bradesco 240, parece ter apenas um Código referente a Débito de Tarifas/Custas
![image](https://github.com/OCA/l10n-brazil/assets/6341149/5a313dc5-fab7-4377-9faf-ab541ddb7aba)

Banco do Brasil 400, apenas códigos referentes a Despesa de Protesto e Custas Antecipadas

![image](https://github.com/OCA/l10n-brazil/assets/6341149/2c9fcaf9-c1d1-467f-aa6d-764b051a3dc0)

Banco Itau 400, possui diversos códigos

![image](https://github.com/OCA/l10n-brazil/assets/6341149/9baae21f-43e0-44ac-a478-9215be358323)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/511e0e6c-4fdd-4aa2-87e6-da5712bac70a)

Banco Itau 240 diversos Códigos

![image](https://github.com/OCA/l10n-brazil/assets/6341149/ae119842-b943-4ae0-af38-17de576700e3)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/76960319-8142-4057-8e4b-9c6d0e4edc68)

![image](https://github.com/OCA/l10n-brazil/assets/6341149/44fa02a6-04dd-46b5-b9c7-f7f273a315d2)

Banco Santander 400, apenas um código para Custas de Cartório

![image](https://github.com/OCA/l10n-brazil/assets/6341149/7033f0ce-4617-4ca6-bf80-c606c8d87629)

Banco Santader 240 apenas um código para Débito para Tarifa/Custas

![image](https://github.com/OCA/l10n-brazil/assets/6341149/13a3b452-e968-47cf-a85f-e4ef465dbb80)


Sicredi 240, apenas um código para Débito para Tarifa/Custas

![image](https://github.com/OCA/l10n-brazil/assets/6341149/74f90feb-0f6d-42e5-8a7c-f4adaa468e37)

Unicred 400, nenhum código relacionado

![image](https://github.com/OCA/l10n-brazil/assets/6341149/871fa5ee-a3de-4fd0-b32d-5d8ed93ee769)

Caixa Economica Federal 240, apenas um código para Débito para Tarifa/Custas

![image](https://github.com/OCA/l10n-brazil/assets/6341149/a47460c6-2306-440c-a3cc-58a92fa73205)


No seu caso o Código de Retorno identifica a operação?

O que mais aparece é o 28 - Debito de Tarifas/Custas mas não é um padrão, o Itau tem vários códigos e o Unicred nenhum, o Santander no 240 tem esse 28 mas no 400 não e o que tem é Custas de Protesto, a partir disso é possível dizer que o campo precisa permitir associar um ou mais códigos, tem outras questões que talvez o seu caso podem esclarecer

* Esses campos devem estar todos juntos em um único campo ou devem ser separados em grupos ex.: Códigos de Tarifas,  Protesto, Outros Custos, etc? Acredito que devem estar em separado

* No Lançamento Contábil hoje existe o campo para a Conta de Tarifa, que acredito que atenderia esse caso ou deveria existir outra? Deve ter uma Conta "Despesas de Protesto"? Teria mais outras contas?

*  Ao fazer esse lançamento ele deve sempre estar associado a Fatura/account.move relacionada ou em algum caso deve estar em separado?

**Comment by antoniospneto** [comment]
Fala @mbcosta 

Pelo que percebi essa issue pode acontecer com qualquer banco que cobre tarifa em ocorrencias que não são do tipo liquidação. Mas os que posso dizer com certeza são, Banco do Brasil, Ailos e Itaú, essas são as implementações que temos ativo. 

Mas a cobrança dessas tarifas não se limitam a ocorrencias que tem explicito em seu nome escrito "Tarifa" pelo que pude perceber qualquer ocorrencia é passivel de taxa/tarifa, isso depende do que o cliente tem contratado/acordado com o seu banco.

Por exemplo, um dos nosso casos de uso é um cliente que o Banco do Brasil cobra tarifa na emissão do boleto, não cobra na liquidação, a cada ocorrencia de código **02 ("Confirmaçaõ de Entrada de Boleto")** é cobrado uma tarifa.

A Engenere está trabalhando na solução destes casos em breve iremos propor uma PR, vamos incluir testes unitários para simular cada situação desta.
