### ISSUE TITLE
[14.0][BUG] Erro de cálculo de valor de impostos no faturamento

### ISSUE THREAD

**Issue by DiegoParadeda** [OCA/l10n-brazil#2924]
## Module
l10n_br_account ?

## Describe the bug
O bug acontece ao faturar uma entrega que tenha os impostos IPI e ICMS simultaneamente e faz com que o valor do lançamento (journal item) do ICMS fique maior do que deveria ser.

O valor errado segue a seguinte fórmula: "ICMS errado = ICMS certo * (1 + IPI %)".

Caso a linha da fatura seja recriada na mão, o erro é corrigido.

## To Reproduce
**Affected versions**: 14.0

1. Selecione "empresa lucro presumido"
2. Crie uma venda para o cliente KMEE e o produto [1094] GRANOLA TRADICIONAL 800G -> **ambos primeiros registros da lista**
3. Insira uma operation line Venda ou Revenda
4. Selecione manualmente ICMS 10% e IPI 30% (os outros impostos deixe default)
5. Coloque o Unit Price: R$100 e verifique o valor dos impostos (aqui obtive ICMS R$10 e IPI R$ 30)
6. Salve e confirme a venda
7. Entregue o produto e crie a fatura (tudo default)
8. Na segunda aba da fatura (Journal Items) veja que o valor do lançamento do ICMS fica R$13 (e não R$10 como foi calculado na SO)
9. opcional: Recrie a linha da fatura (na primeira aba) e insira o mesmo produto, price unit e operation line. Salve e veja que o novo valor do lançamento do ICMS é R$10.

**Expected behavior**
O comportamento esperado é que a fatura criada a partir da entrega já venha com o valor da linha do lançamento do diário do ICMS igual ao valor calculado na SO para o ICMS.

**Additional context**
Quando a linha tem substituição tributária, o valor do ICMS ST também fica diferente do esperado, e nesse caso o valor da soma dos pagamentos fica diferente do total da nota (e trava a emissão de DANFE).

**Imagens do runboat**
![image](https://github.com/OCA/l10n-brazil/assets/12245538/f2abcfb0-630b-4cf1-8378-a68fbe1cc21b)
![image](https://github.com/OCA/l10n-brazil/assets/12245538/38b931d6-99b9-4a79-a32c-95eacbfabe16)

**Comment by antoniospneto** [comment]
@DiegoParadeda você está criando a fatura pelo picking (separação de estoque) ou pelo pedido de venda? 
Pois criando diretamente pelo botão do pedido o bug não acontece, os valores ficam certinho, veja:
![image](https://github.com/OCA/l10n-brazil/assets/634278/2175674d-6cda-4c22-a5ae-035cf343724e)

**Comment by DiegoParadeda** [comment]
> @DiegoParadeda você está criando a fatura pelo picking (separação de estoque) ou pelo pedido de venda? Pois criando diretamente pelo botão do pedido o bug não acontece, os valores ficam certinho, veja: ![image](https://private-user-images.githubusercontent.com/634278/307434270-2175674d-6cda-4c22-a5ae-035cf343724e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTg2NzksIm5iZiI6MTcwODcxODM3OSwicGF0aCI6Ii82MzQyNzgvMzA3NDM0MjcwLTIxNzU2NzRkLTZjZGEtNGMyMi1hNWFlLTAzNWNmMzQzNzI0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxOTU5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTVlNDEwYTllOTkwOWRlNDk0OWRjMDBlMzhkZTVhZTQ0ZjA0ZDIwYmVmMjAyMjQwNzE2YjlhN2U5YTQ2YTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6OuKmRI2dwVT_VxVuXL0kTB3OypGpTk_rQjzuxOiHsI)

Pela separação de estoque

**Comment by antoniospneto** [comment]
@DiegoParadeda algo que eu acho que vale à pena investigar, pro ICMS ter sido 13,00 é pq o sistema somou o ipi na base, isso acontece quando é uma venda diretamente a **um consumidor final**, talvez o método que cria a fatura no picking não tá puxando essa informação corretamente, não no momento que precisa.

**Comment by mbcosta** [comment]
@DiegoParadeda @antoniospneto , como o Antonio apontou o problema era o 'Consumidor Final' estava indo 'Sim' isso era causado devido a simulação do onchange https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_stock_account/wizards/stock_invoice_onshipping.py#L153 que trazia o valor default do ind_final, eu busquei resolver o problema no PR https://github.com/OCA/l10n-brazil/pull/2941 agradeço se puderem revisar e verificar se o problema foi corrigido

**Comment by DiegoParadeda** [comment]
@mbcosta acho que o #2941 acabou passando outro erro no cálculo dos impostos na fatura.

Quando eu testei a primeira solução proposta no PR parecia tudo ok, mas vi que teve alterações com force-push depois do teste que rodei.

Testando numa base recente aqui o ICMS parou de aparecer na fatura gerada a partir do picking. A simulação que rodei é exatamente a mesma descrita nessa issue.
![image](https://github.com/OCA/l10n-brazil/assets/12245538/d3c6895d-d4e9-4d7c-be8a-93489c61a08c)

**Comment by DiegoParadeda** [comment]
Corrigido em #2990, obrigado @mbcosta
