### ISSUE TITLE
[14.0] l10n_br_stock_account: erro ao tentar visualizar o movimento de estoque, pelo menu.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#2946]
Erro ao tentar abrir um movimento de estoque (stock.move) a partir do menu Iventory->Reportin->Stock Moves

![image](https://github.com/OCA/l10n-brazil/assets/634278/51f3dc8c-fff8-4a6d-8b91-a31803356d52)

Ao entrar no menu a listagem dos movimentos é exibida, porém ao tentar abrir algum movimento é exibido o seguinte erro:

![image](https://github.com/OCA/l10n-brazil/assets/634278/bb02efe6-76b6-4a00-89ea-8e4d37b5d88e)

Pelo que percebi o formulário só abre quando é aberto a partir da visualização da separação de estoque (stock.picking)

![image](https://github.com/OCA/l10n-brazil/assets/634278/a1fe0e76-5cce-413b-990f-a4e1d31017e6)

O erro está no uso do atributo "parent" nesse formulario:
https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_stock_account/views/stock_account_view.xml
No caso quando não tem um objeto pai na vizualização, o "parent" não existe.

Ainda não estudei a fundo, mas o que eu acho que poderia ser feito:

Opção 1)  limitar o uso dessa visualização para abrir somente quando é a partir de um `stock.picking`
no caso não pode ser visualização padrão.

Opção 2) verificar se é possivel substituir o acesso ao `stock.picking` no `stock.move` sem usar o "parent"

**Comment by mbcosta** [comment]
@antoniospneto com o merge do PR https://github.com/OCA/l10n-brazil/pull/2947 acredito que o problema foi resolvido, certo? Apenas para confirmar e ver de encerrar esse issue

**Comment by antoniospneto** [comment]
Resolve sim, valeu @mbcosta!
