### ISSUE TITLE
Emissão de NF's não vinculadas às Faturas (Industrialização, Remessa p Conserto etc.)

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#2956]
Gostaria de sugerir a opção de emissão de NFe direto do módulo Fiscal sem estar vinculado à uma Fatura, todas aquelas NF's que não irão gerar receita. Remessa de Industrialização, Remessa p Conserto etc. Pelo que vi a seleção da empresa fica desativada quando há o módulo de l10n_br_account_nfe instalado.

Uma alternativa para o uso direto pelo modulo Fiscal de outras NF's seria a seleção/criação de uma fatura (Vendas/Compras) direto pelo módulo fiscal. Abriria um wizard com as opções antes de carregar a tela de criação da NF.

Exemplo NF de Vendas: Ao clicar em Novo Documento no painel Vendas, iria abrir um Wizard com as opções de Criar Novo, Importar de Fatura ou Importar direto de Pedido de Venda (O que eliminaria a necessidade do Criar Fatura em Vendas).

A mesma lógica para NF relacionadas a Compras: Wizard com opções de devolução de NF de compra importando os dados da NF recebida.

Com isso conseguiria separar setores de empresas que Não querem acesso ao financeiro do Fiscal.

Ainda estou em processo de aprendizagem, mas assim que conseguir ter competencia, irei auxiliar nas melhorias aqui na OCA.

**Comment by antoniospneto** [comment]
Também acho interessante a criação de uma nota fiscal sem vinculo com uma fatura do Odoo.
Acho que já teve algumas conversas sobre o assunto por aqui ou no grupo do telegram.
Apesar de não estar relacionado a fatura seria importante estar relacionado ao picking (separação do estoque)
Apesar de não haver movimentação de receitas nessas operações há movimentação de estoque.

**Comment by rvalyi** [comment]
isso tb seria ligado ao assunto desse PR (que é o mais critico que falta para importar NFe's): https://github.com/OCA/l10n-brazil/pull/2761 pois para ter vários documentos fiscais ligados a um mesmo account.move também teria que ter um menu para acessar a esses documentos fiscais sem ser pelo account.move. Hoje é principalmente uma questão de menu que falta para ter isso.
cc @renatonlima

**Comment by antoniospneto** [comment]
@rvalyi 

uma outra vangatem de ter a visão separada/dedicada é que vai ser possivel visualizar os anexos, tracking, mensagens e e-mail que estão diretamente associados ao objeto documento fiscal, hoje isso acaba ficando escondido por causa da visão do account.move que fica por cima

**Comment by rvalyi** [comment]
> @rvalyi
> 
> uma outra vangatem de ter a visão separada/dedicada é que vai ser possivel visualizar os anexos, tracking, mensagens e e-mail que estão diretamente associados ao objeto documento fiscal, hoje isso acaba ficando escondido por causa da visão do account.move que fica por cima

Então em algum momento da v12 eu tirei a herança do mail.thread do l10n_br_fiscal.document com a justificativa que a gente ja tinha pelo então account.invoice e que isso tinha um custo grande em termo de performance. Mas vimos com o @renatonlima que vamos sim ter que trazer essa herança de novo exatamente para isso (alias o Renato trabalhou um pouco sobre esses "logs"). Agora que a v14+ ficou bem mais rapida do que a v12 e que não temos mais os documentos "dummy", não deveria ser tanto problema em questão de performance.

**Comment by rvalyi** [comment]
> Gostaria de sugerir a opção de emissão de NFe direto do módulo Fiscal sem estar vinculado à uma Fatura, todas aquelas NF's que não irão gerar receita. Remessa de Industrialização, Remessa p Conserto etc. Pelo que vi a seleção da empresa fica desativada quando há o módulo de l10n_br_account_nfe instalado.

@rodmad85 @antoniospneto tou vendo a ideia de poder ter um menu para documentos fiscais não ligados a um account.move para atender o que o @antoniospneto levantou e o que eu falei sobre account.move compostos.

Porem @rodmad85 quando vc fala de "Remessa de Industrialização, Remessa p Conserto etc" isso tudo a gente faz certinho emitindo uma NFe pelo picking (com os modulos logados a l10n_br_stock_account) e **com uma operação fiscal que não gera financeiro**. Ai temos um account.move sim, mas isso ta certo porque essas notas apesar de não gerar financeiro elas geram contabilização e essa contabilização (por exemplo dos impostos) a localização faz certinho já!
inclusive se vc se interessar pelo assunto, pode ver que a gente tb pode contabilizar os lançamentos de CMV pelo Odoo. Esquece as mensagem da pessoa parasita, mas vc pode ler https://github.com/OCA/l10n-brazil/pull/1561 a respeito dessas coisas.

**Comment by rodmad85** [comment]
Obrigado pelas informações. Vou estudar mais a respeito. No caso da
sugestão de melhoria seria para facilitar o uso no dia a dia.

Em sáb., 16 de mar. de 2024, 18:05, Raphaël Valyi ***@***.***>
escreveu:

**Comment by DiegoParadeda** [comment]
@rodmad85 é possível criar uma fatura e emitir uma nota fiscal sem gerar movimentos financeiros e sem ter que pagar a fatura (pois o valor é zero), verifique o campo finance_move da cfop.

As Nfes das remessas que você comentou carregam valor fiscal e impostos calculados (mesmo não tendo pagamento). Não acho que criar uma nfe sem uma fatura vai te ajudar, considerando que é a fatura que calcula esses valores fiscais e de impostos que precisam estar na nfe.

**Comment by antoniospneto** [comment]
> possível criar uma fatura e emitir uma nota fiscal sem gerar movimentos financeiros e sem ter que

@DiegoParadeda sim hoje o sistema permite criar faturas sem valor financeiro, mas eu ainda sou da opnião que nesses casos seria melhor nem gerar a fatura, para não poluir a listagem de faturamento com essas faturas "dummy"

**Comment by marcelsavegnago** [comment]
@rodmad85 nós já criamos as faturas inclusive via picking para permitir a baixa do estoque a emissão dos documentos.. inclusive permitindo também até a emissão de retorno. Porém, como comentado pelo @DiegoParadeda precisa configurar o CFOP para não gerar financeiro.

**Comment by rvalyi** [comment]
ai pessoal vou fechar o issue então. Podem re-abrir caso acham necessário.
