### ISSUE TITLE
Runbot build does not install l10n-brazil modules

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/l10n-brazil#296]
The runbot is not installing the modules like other projects in OCA,
check this link http://3145067-295-826933.runbot1.odoo-community.org/web?db=3145067-295-826933-all

Any hint where could be the problem?

**Comment by mileo** [comment]
up plz!

**Comment by mileo** [comment]
up again @rvalyi @renatonlima

**Comment by rvalyi** [comment]
@mileo yep I agree this is important. I tried to investigate but found nothing yet. Will see that with our OCA collaborators. BTW we will soon discuss extending the project OCA scope and PSC too, just fixing urging stuff internally first.

**Comment by mileo** [comment]
@renatonlima Acredito que o erro do runbot seja pq o repo reporting-engine apesar de estarem no arquivo OCA  DEPENDENCIES eles não estão disponíveis.

Att

**Comment by rvalyi** [comment]
@mileo acabei de dar uma olhada e chego a mesma conclusao. Realmente os modulos nao parecem estar no addons-path. Eu nao faco idea de porque as outras dependencias estao la e nao essa.

**Comment by mileo** [comment]
Na configuração do buildout (no backend) não tem uma opção de vc colocar as dependencias?
