### ISSUE TITLE
l10n_br_fiscal/l10n_br_fiscal.cfop.csv  Definir CFOP 5124 finance_move como 1

### ISSUE THREAD

**Issue by rodmad85** [OCA/l10n-brazil#3004]
Favor definir  no l10n_br_fiscal/l10n_br_fiscal.cfop.csv , o CFOP 5124 (Industrialização), como habilitado para movimento financeiro como padrão.

Grato.

**Comment by marcelsavegnago** [comment]
1. Vá até o repositório https://github.com/OCA/l10n-brazil e faça um fork (via interface do github)

2. Clone o repositório da OCA (Open Source Community Association) com a versão 14.0 do módulo de localização brasileira para a pasta de sua escolha:
```
git clone -b 14.0 https://github.com/oca/l10n-brazil ./pastaquevcquiser
```

3. Navegue até a pasta recém-clonada:
```
cd pastaquevcquiser
```

4. Adicione um novo repositório remoto (seu fork do repositório l10n-brazil) para onde você enviará suas alterações:
```
git remote add rodrigoxyz https://github.com/rodrigoasdasdasdasd/l10n-brazil
```

5. Abra o arquivo CSV `l10n_br_fiscal.cfop.csv` para edição, onde você modificará o valor na coluna `finance_move`:
```
nano ./l10n_br_fiscal/l10n_br_fiscal.cfop.csv
```

6. Faça as edições necessárias no arquivo, alterando o valor da coluna `finance_move`, e depois salve as alterações.

7. Adicione o arquivo editado ao git para prepará-lo para o commit:
```
git add ./l10n_br_fiscal/l10n_br_fiscal.cfop.csv
```

8. Faça um commit das suas alterações, adicionando uma mensagem descritiva:
```
git commit -m "[FIX] l10n_br_fiscal: Definir finance_move como verdadeiro para o CFOP X (descrição opcional)"
```

9. Envie suas alterações para o seu fork remoto:
```
git push rodrigoxyz
```

10. Após executar essas etapas, um link será gerado, permitindo que você abra uma solicitação de pull request no repositório oficial da OCA. Você pode clicar no link ou copiá-lo e colá-lo em seu navegador para iniciar o processo de pull request.


Obs. Talvez vc precise instalar o pre-commit na sua maquina.. 
```
pip install pre-commit
```

**Comment by antoniospneto** [comment]
resolvido no https://github.com/OCA/l10n-brazil/pull/3036
