### ISSUE TITLE
[16.0] l10n_br_fiscal BUG na tela da empresa

### ISSUE THREAD

**Issue by marcos-mendez** [OCA/l10n-brazil#3014]
Pessoal comecei a testar algumas coisinhas da 16 com o l10n_br_fiscal

Vim registrar que lá embaixo a tela impostos avançados aparece toda comprimida pro lado esquerdo do monitor

![image](https://github.com/OCA/l10n-brazil/assets/38361760/2b5e5d5b-3e24-4a29-83e5-c274a627c29a)

Eu não sei se vocês estão trabalhando nisso, mas pelas dúvidas só para deixar registrado. Se for necessário fechar e puderem passar a PR que corrige isto agradeço

**Comment by rvalyi** [comment]
resolvido em #3468
