### ISSUE TITLE
RUNBOT ins't install any module in db=all

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#302]
http://3146177-8-0-6382a9.runbot1.odoo-community.org/web?db=3146177-8-0-6382a9-all#view_type=kanban&model=ir.module.module&menu_id=53&action=37

**Comment by mileo** [comment]
File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3146182-299-65c5ef/openerp/tools/convert.py", line 962, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_br_account failed: file l10n_br_account/demo/account.account.csv could not be processed:
**Line 180 : CPU time limit exceeded.**

**Comment by danimaribeiro** [comment]
I made this same question here: #296 

But not all the builds show the cpu limit problem, check this one:
https://runbot.odoo-community.org/runbot/build/3146172
No errors in the log, but no modules get installed.

**Comment by mileo** [comment]
@danimaribeiro Sorry. We continue on #296
