### ISSUE TITLE
[14.0] [l10n_br_cnab_structure][l10n_br_account_payment_order] Data para pagamento não está sendo respeitada na Ordem e no arquivo CNAB

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#3028]
Ao criar uma Payment Order, é possível selecionar o formato de compensação:
- imediatamente
- na data de vencimento
- uma data fixa

Mesmo selecionando qualquer uma das informações, ele não respeita essa informação, ele sempre vai adotar como data da emissão do payment order, ou seja, "imediatamente"

O problema está na formação das linhas do Payment Order e na criação do Arquivo CNAB

## Module
l10n_br_cnab_structure
l10n_br_account_payment_order

## To Reproduce
TESTE REALIZADO NA OCA:
Criado uma fatura de fornecedor
![image](https://github.com/OCA/l10n-brazil/assets/20867090/1cde548a-b720-4135-8c9c-fdcf45aa526f)

A data que deveria estar na geração da linha é a dat de vencimento, mas ele adotou a data de hoje:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/fbf993da-725d-447e-9bd1-6e1f0cc6c567)

A montagem do CNAB, foi montado com a data de hoje, que também a data da linha:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/29b91ebc-dc2b-42af-bc04-7f24a7114c48)

O Campo para formação do CNAB:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/9e68b438-6c71-407e-a7c2-1b373d216ca0)
![image](https://github.com/OCA/l10n-brazil/assets/20867090/3d756139-4cc6-495a-b96f-f56a9586cd84)

Teste realizado alterando **MANUALMENTE** a data da linha:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/695c2cb2-9bfa-43cd-97de-9219e313f898)

Mesmo assim não é assumido a data da linha:
![image](https://github.com/OCA/l10n-brazil/assets/20867090/9a5497e7-7829-4d33-8ac0-b4d56d722c03)

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by marcelsavegnago** [comment]
resolvido com a PR #3033
