### ISSUE TITLE
[14.0] Valores price_unit, price_total e price_subtotal das linhas de impostos e de pagar/receber

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#3034]
Veja aqui como ficam os campos price_unit, price_total, price_subtotal em uma instancia Odoo sem localização:

![image](https://github.com/OCA/l10n-brazil/assets/3595132/e6c481ba-fbc3-45aa-ac09-293e4d6cfcfd)

e aqui com a localização:

![image](https://github.com/OCA/l10n-brazil/assets/3595132/867a59ca-c05f-452e-a32a-68c73cbb685e)

_Originally posted by @marcelsavegnago in https://github.com/OCA/l10n-brazil/issues/3030#issuecomment-2073302139_
            
Obs. Estou investigando mas ainda não percebi se isso é proposital ou se tem alguma condição especifica forçando o valor 0.

**Comment by felipemotter** [comment]
Isso acontece sempre ou tem alguma condição para acontecer?

**Comment by marcelsavegnago** [comment]
Do jeito que está o codigo hoje, acontece sempre.

**Comment by antoniospneto** [comment]
Resolvido no #3037 certo?
