### ISSUE TITLE
[14.0][BUG]l10n_br_account: ao cancelar uma nfe, não está cancelando a fatura

### ISSUE THREAD

**Issue by felipemotter** [OCA/l10n-brazil#3071]
Caso uma nfe seja cancelada pela visão do documento fiscal (state_edoc cancelado), não há mudança alguma na fatura, que permanece confirmada. Caso o usuário tente voltar a fatura para provisória/rascunho, ele é impedido porque o state_edoc é cancelado, logo não pode cancelar a fatura manualmente tbm.

**Comment by rvalyi** [comment]
@felipemotter não seria um duplicate desse issue https://github.com/OCA/l10n-brazil/issues/2998
?

**Comment by rvalyi** [comment]
a gente poderia considerar usar esse módulo talvez:
https://github.com/OCA/account-invoicing/tree/16.0/account_move_substate
teria que ver se aumenta muito o código para pouco benefício, se for o caso talvez num módulo extra com uma solução mais simples sem nova dependência...

**Comment by antoniospneto** [comment]
> @felipemotter não seria um duplicate desse issue #2998 ?

@rvalyi 

O #2998 parece ser outro assunto destinto, o "denegado" que o @mileo  fala lá é quando a sefaz nega o pedido de autorização de uso da NFe e também não permite que faça mais correção, isso acontece quando o contribuinte tem alguma irrugalidade fiscal. A nota fiscal fica salva no servidor da sefaz, mas com o status “Denegada a Autorização de Uso”. Para esse caso eu tbm acho interessante o módulo `account_move_substate` mas para a issue do @felipemotter não se aplica.

O que o Felipe comentou é uma pequena regressão que houve após a PR do composite,  que ao efetuar o cancelamento de uma NF-e (solicitado pelo contribuinte) o documento fiscal é cancelado mas a fatura (account_move) continua como postada, não é mais cancelado automaticamente igual antes.

Mas o Felipe já está trabalhando na proposta para correção e logo abre uma PR.

**Comment by marcelsavegnago** [comment]
@douglascstd será que não foi o caso que tivemos com o cliente X.

**Comment by douglascstd** [comment]
Exato.. esse problema ja apareceu. Mas foi um caso que nao conseguimos reproduzir.
Pois quando cancela o documento fiscal ele cancela tambem a fatura.

Mas parece que o local do cancelamento indicado é no wizard de obtenção de status

**Comment by rvalyi** [comment]
fixed by #3090
