### ISSUE TITLE
Como ativar os relatorio de BALANCETE no odoo 14?

### ISSUE THREAD

**Issue by gilsonlima10** [OCA/l10n-brazil#3082]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by marcelsavegnago** [comment]
@gilsonlima10 pode colocar uma descrição na sua issue?

Pelo titulo eu entendi que o que você está procurando possa ser isso:
https://github.com/OCA/account-financial-reporting/tree/14.0/account_financial_report

**Comment by antoniospneto** [comment]
@gilsonlima10 para perguntas gerais desse tipo favor usar o fórum: https://github.com/OCA/l10n-brazil/discussions
@marcelsavegnago acho que dá de mover pra lá não ?
