### ISSUE TITLE
Perda de permissões após o update do l10n_br_nfe_spec

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#3131]
Após atualizar o módulo l10n_br_nfe_spec, responsável pela estrutura de dados da NF-e, por algum motivo está deletando as regras de acesso aos modelos como, por exemplo, o modelo nfe.40.vol.

versão 14.0

@rvalyi @marcelsavegnago @antoniospneto

**Comment by antoniospneto** [comment]
É o mesmo que https://github.com/OCA/l10n-brazil/issues/2349

**Comment by marcelsavegnago** [comment]
No meu caso faz tempo que não vejo acontecer este problema novamente. Mas como comentado na issue #2349, solução de contorno está em atualizar o l10n_br_nfe.

**Comment by rvalyi** [comment]
@mileo pode testar se esse PR resolve https://github.com/OCA/l10n-brazil/pull/2725 ?

**Comment by rvalyi** [comment]
resolvido por https://github.com/OCA/l10n-brazil/pull/3215
