### ISSUE TITLE
Tradução da descrição dos módulos brasileiros

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/l10n-brazil#32]
Traduzir a descrição dos módulos brasileiros, para ficar mais fácil na instalação saber o que significa cada módulo.

![traduzir descricao modulos](https://f.cloud.github.com/assets/854781/1966008/02692fa4-82c2-11e3-9719-d8da297d9b07.PNG)

**Comment by renatonlima** [comment]
Este recurso foi implementado pelo pull request #39
