### ISSUE TITLE
[16.0 ][l10n_br_account] TODO: adaptar PR 3037 price_total and price_subtotal values

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#3252]
Os commits do PR #3037 (price_total and price_subtotal values) foram portados dentro da migracao do l10n_br_account para a v16 #2865

Porem or PR #3037 impactou metodos que nao existem mais na v16 ou nao foram devidamente migrados e as mudanças esperadas nos valores dos testes foram revertidas dentro de um commit explicito no fim do PR ate que isso seja corrigido.

Deixo aqui como TODO para a gente nao esquecer, pois talvez a gente acaba fazendo o merge do modulo mesmo que deixando isso para resolver depois ainda.

cc @renatonlima  @marcelsavegnago @antoniospneto

**Comment by mileo** [comment]
Tem tb esse: https://github.com/OCA/l10n-brazil/pull/3135

**Comment by rvalyi** [comment]
fechando porque eu resolvi isso na migraçao https://github.com/OCA/l10n-brazil/pull/2865 os testes estao passando.

@mileo seu caso do #3135 eh diferente pos era apenas um PR normal para portar e agora ja fizemos o port dele para as v15 e v16 inclusive.
