### ISSUE TITLE
Cancelar a fatura quando uma EDOC é denegado

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#3262]

**Comment by antoniospneto** [comment]
Não é o mesmo que https://github.com/OCA/l10n-brazil/issues/2998?

**Comment by antoniospneto** [comment]
Essa sua pr tem relação com a issue? https://github.com/OCA/l10n-brazil/pull/3130

**Comment by mileo** [comment]
> Não é o mesmo que #2998?

Sim é o mesmo.

**Comment by mileo** [comment]
> Essa sua pr tem relação com a issue? #3130

Não tem relação.
