### ISSUE TITLE
Forward port from 14.0 to 15.0/16.0

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#3285]
Forward port from 14.0 to 15.0/16.0

15.0 

- [x] #3278 l10n_br_contract
- [x] #3278 l10n_br_repair
- [X] #3278 l10n_br_sale:
     Port -> https://github.com/OCA/l10n-brazil/pull/3283
- [x] #3278 l10n_br_stock_account

16.0

- [x] #3278 l10n_br_contract
- [x] #3278 l10n_br_repair
- [x] #3278 l10n_br_sale
- [x] #3278 l10n_br_stock_account

**Comment by antoniospneto** [comment]
@marcelsavegnago eu fechei a issue pq tava tudo com merge os itens, mas a ideia aqui é deixar aberto?

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago eu fechei a issue pq tava tudo com merge os itens, mas a ideia aqui é deixar aberto?

Acho que pode fechar.. se precisar abre outra..
