### ISSUE TITLE
[BUG][14.0] Calculo de Operação e Linha de Operação Fiscal em Fatura geradas pela Separação (Picking)

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#3295]
Na criação de uma fatura por um picking cujo a operação esteja vinculada a uma Operação Fiscal, deveria utilizar essa informação para preencher e calcular as informações da Fatura criada.

Aparentemente o calculo da fatura está desconsiderando a Operação, e não está fazendo o calculo para encontrar a linha da operação fiscal, em cada uma das linhas da fatura gerada a partir do picking.

A sequencia realizada no runboat:
Criação de Operação, já vinculando a uma operação fiscal:
![image](https://github.com/user-attachments/assets/9da35929-f340-428d-b0d0-264fc7926b1d)

Acessando a operação pelo painel:
![image](https://github.com/user-attachments/assets/8f27caa9-9760-4195-bff9-46cfec621b2e)

Criado um movimento manualmente:
![image](https://github.com/user-attachments/assets/ad69b27e-9816-44aa-9fb3-fe21b401774a)

A fatura gerada pelo movimento, ele preenche o campo de Operação da Fatura, mas na linha não é calculado usando essas informações:

**Comment by mbcosta** [comment]
@douglascstd acredito que o PR https://github.com/OCA/l10n-brazil/pull/3497 deve resolver o problema
