### ISSUE TITLE
[14.0][l10n_br_fiscal][BUG] Não é possível ter a quantidade fiscal diferente da quantidade comercial no documento fiscal

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#3304]
Ao realizar uma fatura, utilizando a quantidade fiscal (pelo fator do produto) e a unidade pelo NCM, ao criar o documento fiscal, a quantidade fiscal é ignorada e é mantido sempre os 2 campos com o mesmo conteúdo.

Ao tentar forçar o valor em qualquer um dos 2 campos, esse novo valor é assumido nos dois campos, seja pela interface ou pelo terminal:
![image](https://github.com/user-attachments/assets/6e248b3a-6c2a-4948-818c-6db871447de5)
![image](https://github.com/user-attachments/assets/d1a90d01-0665-4f57-a52e-fbb988ece7bc)

O efeito deste problema é refletido no XML:
![image](https://github.com/user-attachments/assets/5a88b369-24c6-46f1-a455-3821db35b4a8)
Causando um desvio de valores no Total do Documento Fiscal.
![image](https://github.com/user-attachments/assets/d1a90d01-0665-4f57-a52e-fbb988ece7bc)

Não sei dizer se tem relação com o problema, encontrei essa parte do código, que menciona uma relação entre dos dois campos:
https://github.com/OCA/l10n-brazil/blob/7f80f222d69731cf567b11a5189b84321ad745c0/l10n_br_account/models/fiscal_document_line.py#L30

**Comment by antoniospneto** [comment]
Resolvido no #3307
