### ISSUE TITLE
[16.0] l10n_br_base: espaçamento desnecessário nos campos do endereço.

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#3331]
Na visualização dos campos do endereço, por exemplo no contato ou no lead do crm, os campos estão ficando com espaçamento extra sem necessidade (padding)
![image](https://github.com/user-attachments/assets/4cd6dd07-785b-4cf5-94a2-1619f1678b94)

Detalhes técnicos:

Esse bug vem da funcionalidade nativa do Odoo em substituir os campos dos endereço na visão dinamicamente, conforme definido na configuração da empresa.

Isso aconte porque tá sendo injetando a tag `<Form>` sem necessidade, o odoo deveria injetar apenas a conteudo de `<div class="o_address_format">` aqui https://github.com/OCA/l10n-brazil/blob/cd10954f096d37d79218b55d0c472c7c1ee1aa4b/l10n_br_base/views/res_partner_address_view.xml#L10C17-L10C47

É preciso verificar se é possivel resolver com CSS conforme sugerido pelo @rvalyi 
ou se terá que fazer overrides nos métodos nativos do Odoo..

Isso acontece apenas na 16.0, na 14.0 está ok.

**Comment by CristianoMafraJunior** [comment]
Corrigido na PR #3477 @antoniospneto se conseguir fechar

**Comment by mileo** [comment]
> Corrigido na PR #3477 @antoniospneto se conseguir fechar

Para fechar uma pull request (PR) automaticamente no GitHub usando commits, você pode incluir palavras-chave específicas na mensagem do commit ou na descrição do pull request. Essas palavras informam ao GitHub que a PR ou uma issue associada deve ser fechada assim que o código for mergeado no branch de destino (geralmente `main` ou `master`). 

Aqui estão os passos:

1. **Escolha uma Palavra-Chave**: As palavras-chave que acionam o fechamento automático incluem:
   - `close`
   - `closes`
   - `closed`
   - `fix`
   - `fixes`
   - `fixed`
   - `resolve`
   - `resolves`
   - `resolved`

2. **Referencie o Número da PR ou Issue**: Após a palavra-chave, inclua `#` seguido do número da PR ou issue que deseja fechar. Por exemplo: `closes #123`.

3. **Escreva a Mensagem do Commit**: A mensagem de commit ou descrição da PR deve conter a palavra-chave e o número da PR ou issue. Exemplo de commit para fechar a PR ou issue número 123:
   
   ```plaintext
   git commit -m "fixes #123"
   ```

4. **Suba o Commit e Abra o PR**: Quando esse commit for mergeado no branch principal, a PR ou issue associada será automaticamente fechada.

### Exemplo Completo:
1. Faça as alterações necessárias no código.
2. Use o comando para adicionar e fazer commit das mudanças:
   
   ```bash
   git add .
   git commit -m "closes #123"
   ```

3. Suba as mudanças para o repositório remoto:

   ```bash
   git push origin sua-branch
   ```

Ao fazer o merge da sua branch para a principal, a PR ou issue será automaticamente fechada pelo GitHub com base na mensagem do commit.
