### ISSUE TITLE
Quotes generates a python error on Additional Information of the Invoice

### ISSUE THREAD

**Issue by wagnerpereirasp** [OCA/l10n-brazil#336]
We've had a case that users started using double quotes at the Additional Information on sales.order which was being copied to account.invoice.

When attempting to Confirm the Invoice it generates error:

 File "/opt/odoo/parts/l10n_br/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 101, in _serializer
    self._additional_information(invoice)
  File "/opt/odoo/parts/l10n_br/l10n-brazil/l10n_br_account_product/sped/nfe/document.py", line 600, in _additional_information
    self.nfe.infNFe.infAdic.infCpl.valor = invoice.comment or ''
  File "/opt/odoo/src/PySPED/pysped/xml_sped/base.py", line 270, in set_valor
    raise ErroCaracterInvalido(self.codigo, self.nome, self.propriedade, novo_valor, c)
ValueError: "" while evaluating
u'nfe_export()'

Workaround: Remove the double quotes manually and instruct users not to use them at all.

**Comment by danimaribeiro** [comment]
Do you know if double quotes is valid in the xml for the NFe?

**Comment by mileo** [comment]
Acontece muito quando o pessoal copia e cola instruções, aconteceu uma vez tb com aquele travessão grande do MS Word.

**Comment by wagnerpereirasp** [comment]
Seria interessante fazer um parser no campo para não dar mais erro. Eu não gosto desses erros python aparecendo para os usuários. Da impressão de produto inacabado.Em 21 de jun de 2016 8:08 PM, Luis Felipe Miléo notifications@github.com escreveu:Acontece muito quando o pessoal copia e cola instruções, aconteceu uma vez tb com aquele travessão grande do MS Word.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wagnerpereirasp** [comment]
I'm looking on the Manual_de_Orientacao_Contribuinte_v_5.00.pdf and the information about this field I found is: 

In section 3.2. Padrão de Documento XML I found a mention to: 
A especificação do documento XML adotada é a recomendação W3C para XML 1.0, disponível em www.w3.org/TR/REC-xml e a codificação dos caracteres será em UTF-8, assim todos os documentos XML serão iniciados com a seguinte declaração: 

Additional relevant information about the field "Informações Complementares" never mentioned any character restrictions. See below: 

7.1.6 Informações Complementares Deverá conter todas as Informações Adicionais da NF-e incluídas nas TAGs e , ficando facultada a impressão das informações adicionais contidas nas TAGs . Na hipótese de insuficiência de espaço no quadro de “informações complementares”, a impressão destas deverá ser continuada no verso ou na folha seguinte, neste mesmo quadro ou no quadro “Dados dos Produtos/Serviços”. 

7.7.8 Conteúdo do Campo Informações Complementares Deverá ter tamanho mínimo de seis (6) pontos, ou 17 CPP. 

400 Z02 infAdFisco Informações Adicionais de Interesse do Fisco E Z01 C 0-1 1-2000 (v2.0) 
401 Z03 infCpl Informações Complementares de interesse do Contribuinte E Z01 C 0-1 1-5000 

I did went thru all the W3C documentation but I think there should be no problems as long is the characters are UTF-8 encoded, however I strongly suggest a validation. 

I hope this helps. 
Wagner Pereira 

De: "Wagner Pereira" wagner.pereira@kmee.com.br 
Para: "OCA/l10n-brazil" reply@reply.github.com 
Enviadas: Terça-feira, 21 de junho de 2016 21:03:44 
Assunto: Re: [OCA/l10n-brazil] Quotes generates a python error on Additional Information of the Invoice (#336) 

Seria interessante fazer um parser no campo para não dar mais erro. Eu não gosto desses erros python aparecendo para os usuários. Da impressão de produto inacabado. 
Em 21 de jun de 2016 8:08 PM, Luis Felipe Miléo notifications@github.com escreveu: 

Acontece muito quando o pessoal copia e cola instruções, aconteceu uma vez tb com aquele travessão grande do MS Word.
