### ISSUE TITLE
Calculo imposto IBPT no POS NFC-e

### ISSUE THREAD

**Issue by kcarriello** [OCA/l10n-brazil#3407]
Estava analisando a implementação do calculo do imposto via tabela do IBPT na emissão da NFC-e no POS, alguém já tem algo iniciado neste sentido?

**Comment by antoniospneto** [comment]
O módulo fiscal já tem uma funcionalidade para carregar as estimativas de impostos, via integração por API do IBPT.
Você precisa criar o token em https://deolhonoimposto.ibpt.org.br/ e informar na configuração do Odoo.
Na NF-e eu sei que isso tá funcionando muito bem, na NFC-e teria que verificar se está faltando algo.

cc @mileo

**Comment by mileo** [comment]
Pelo que me lembro esta sim: https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_pos/static/src/js/models.js#L277C45-L277C60

**Comment by kcarriello** [comment]
Alguma dica de como incluir estes dados na impressao da NFCe, como importo isso no XML do recibo em l10n_brasil_pos_nfce?

**Comment by mileo** [comment]
Coloque uma mensagem fiscal na linha da operação. Ou na operação.

**Comment by kcarriello** [comment]
Você diz aqui? Algo que tenho que fazer também na edição do XML? 
<img width="970" alt="Screenshot 2024-10-30 at 9 43 32 AM" src="https://github.com/user-attachments/assets/820071fb-1229-4ccc-8b94-e3a33045a17d">

**Comment by kcarriello** [comment]
<img width="1266" alt="Screenshot 2024-10-30 at 9 48 25 AM" src="https://github.com/user-attachments/assets/5d55b11d-875c-4ec1-aae0-5c58004a3f5d">

**Comment by kcarriello** [comment]
Eu olhei os xml que geram o recibo dentro de ReceiptScreen, não encontrei tag que remetam a informação de impostos estimados. Mas estou com entendimento errado? Alguma dica em como implementar isso no xml e no js do módulo para ter isso impresso no recibo nfce do POS?

**Comment by kcarriello** [comment]
Quando coloco comentário na nfce do PoS obtenho um erro por order.orderline[0] não existe na abertura do PDV. Eu alterei o js para validar a existência do ordeline porém mesmo após isso os impostos aparecem zerados no resultado do json da venda. Tem certeza que isso foi implementado?
