### ISSUE TITLE
l10n_br_account_payment_order/migrations/14.0.7.0.0/post-migration.py

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#3408]
```
  File "/opt/odoo/auto/addons/l10n_br_account_payment_order/migrations/14.0.7.0.0/post-migration.py", line 173, in migrate
    update_payment_mode_inbound(env)
  File "/opt/odoo/auto/addons/l10n_br_account_payment_order/migrations/14.0.7.0.0/post-migration.py", line 39, in update_payment_mode_inbound
    cnab_config.sending_code_id = payment_mode.sending_code_id
AttributeError: 'account.payment.mode' object has no attribute 'sending_code_id'
Error: 'account.payment.mode' object has no attribute 'sending_code_id'
```

**Comment by antoniospneto** [comment]
@mileo tbm peguei o erro aqui, os scripts de migração das ultimas refatorações CNAB não ficaram bom, estou refazendo eles aqui para usar SQL ao invés de ORM

**Comment by antoniospneto** [comment]
ainda to trabalhando, mas segue pr: https://github.com/OCA/l10n-brazil/pull/3409

**Comment by mbcosta** [comment]
@mileo esse erro deve estar acontecendo porque acredito que vocês está atualizando um Banco de Dados da versão 14.0.6.0.0 diretamente para a versão 14.0.9.0.0, para migrar esses dados era preciso rodar a atualizações passo a passo conforme os PRs foram sendo aprovados a cada nova versão deveria rodar um update:

$ odoo -d NOME_DO_BANCO -u l10n_br_account_payment_order --workers 0 --stop-after-init

* https://github.com/OCA/l10n-brazil/pull/3365

![image](https://github.com/user-attachments/assets/fd6bb915-a4d0-409d-a4d2-253d0b3b9eaf)

Para contornar o problema o que pode ser feito é voltar os campos removidos aqui https://github.com/OCA/l10n-brazil/pull/3365/commits/68a9318e72340a178375ada8118e16f40a407218 e aqui https://github.com/OCA/l10n-brazil/pull/3365/commits/2bc5db9a5b3a04f68b384f98fac2a0163e957bf8  e colocar no manifest a versão 14.0.8.0.0 comentar ou renomear o arquivo https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_account_payment_order/migrations/14.0.9.0.0/pre-migration.py rodar 

$ odoo -d NOME_DO_BANCO -u l10n_br_account_payment_order --workers 0 --stop-after-init

Com isso vai rodar os scripts de migração até a versão 14.0.8.0.0 e não deve gerar nenhum erro, em seguida já deverá ser possível atualizar para a versão 14.0.9.0.0 

$ odoo -d NOME_DO_BANCO -u l10n_br_account_payment_order --workers 0 --stop-after-init

Onde os campos obsoletos deverão ser apagados sem erros e com isso a atualização estará concluida.

Poderia ter deixado esses campos para evitar erro e considerei mante-los até a mudança de versão v15 ou v16 mas como a migração havia sido feita esses campos precisariam ser mantidos até a v17, acreditei que estava clara a explicação sobre a cada PR ser necessário atualizar o Banco de Dados, até por isso foram feitos PRs em separado.

**Comment by rvalyi** [comment]
Resolvido aqui https://github.com/OCA/l10n-brazil/pull/3409
