### ISSUE TITLE
problemas de emissao de NFCe apos update para ultima versao 14 do repositorio

### ISSUE THREAD

**Issue by kcarriello** [OCA/l10n-brazil#3419]
Eu estava rodando os modulos da base 14.0.3.13.0, fiz um upgrade para os ultimos modulos da versao 14 disponiveis no git, apos este upgrade a emissao de NFCe do POS nao funciona, ao confirmar a venda o recido impresso é o recibo padrao ODOO e nao a NFCe, e a nota tmbem nao aparece no modulo fiscal para ser transmitida, tentei criar uma NFCe na mao a partir de uma venda fora do POS e recebo a mensagem de erro abaixo. Todas as dependencias python foram atulizadas conforme o novo requirements.txt que veio junto com a atualizacao, antes da atulizacao tudo estava funcionando, eu atualizei para poder ter a informacao de valores estimados de impostos na NFCe. Alguma ideia da causa? Algo que mudou na config do POS para ele emitir NFCe?

AO VALIDAR UMA COMPRA NO POS O LOG REGISTRA A SEGUINTE INFO, MAS NAO EMITE NOTA:

2024-10-06 02:11:02,602 470476 INFO atiboo werkzeug: 10.0.1.128 - - [06/Oct/2024 02:11:02] "POST /web/dataset/call_kw/pos.config/update_nfce_serie_number HTTP/1.1" 200 - 2 0.002 0.010

Não acho que o erro abaixo  esteja relacionado a emissoa da nota via POS, mas ele ocorre ao tentar gerar uma nfce na mao fora do modulo POS.

Exception The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/opt/odoo/atiboo/odoo/http.py", line 652, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/opt/odoo/atiboo/odoo/http.py", line 317, in _handle_exception raise exception.with_traceback(None) from new_cause TypeError: __init__() got an unexpected keyword argument 'envio_sincrono'

**Comment by rvalyi** [comment]
parece que a sua lib erpbrasil.edoc não esta atualizada. Pois olha essa mudança que houve: https://github.com/erpbrasil/erpbrasil.edoc/pull/74/files

Esse PR entrou em Maio, mas pelo jeito sua lib erpbrasil.edoc ta mais antiga ainda... Com `pip show erpbrasil.edoc` vc consegue conferir a versão. O ideal é atualizar para a versão 2.10.0 mesmo.

Vou fechar o issue, caso pode re-abrir se isso não resolveu.

**Comment by kcarriello** [comment]
obrigado pela pronta resposta, outra mudanca que reparei é que não consegui mais achar uma opção de sempre gerar fatura ao validar uma compra no POS, agora sempre tenho que selecionar FATURA para ele poder emitir a NFCe, é isso mesmo?

**Comment by rvalyi** [comment]
> obrigado pela pronta resposta, outra mudanca que reparei é que não consegui mais achar uma opção de sempre gerar fatura ao validar uma compra no POS, agora sempre tenho que selecionar FATURA para ele poder emitir a NFCe, é isso mesmo?

Essa nao sei responder. @mileo @DiegoParadeda podem responder?
