### ISSUE TITLE
[14.0][l10n_br_fiscal][BUG] Campo ind_final não está sendo computado nas SOs

### ISSUE THREAD

**Issue by DiegoParadeda** [OCA/l10n-brazil#3449]
**Problema**:

- **Na criação**: O campo está sendo preenchido com o valor "True" e não está sendo recalculado ao selecionar o parceiro.
- **Ao alterar o parceiro já definido**: O cálculo automático (compute) funciona normalmente.
- **Na edição**: O cálculo automático (compute) também funciona conforme esperado.

![image](https://github.com/user-attachments/assets/7dd3baa6-adfb-4495-aac3-43096fb0d5e8)
![image](https://github.com/user-attachments/assets/06602e0f-b809-40c0-be98-b1792a5dec31)

**Comment by mbcosta** [comment]
@DiegoParadeda procurei resolver o problema no PR https://github.com/OCA/l10n-brazil/pull/3512

**Comment by rvalyi** [comment]
Resolvido com #3512
