### ISSUE TITLE
[14.0] Tradução incorreta em l10n_br_pos

### ISSUE THREAD

**Issue by kcarriello** [OCA/l10n-brazil#3475]
Na configuração do modulo l10n_br_pos a tradução abaixo está incorreta. Ela deveria ser: Operação Fiscal de Venda no POS. Não consigo entender o que tem de reembolso nesta configuração para ter este termo.

#. module: l10n_br_pos
#: model:ir.model.fields,field_description:l10n_br_pos.field_pos_config__out_pos_fiscal_operation_id
#, fuzzy
msgid "Default Sales Operation"
msgstr "Operações Fiscais de Reembolso do POS"

**Comment by antoniospneto** [comment]
Olá @kcarriello 

A tradução é gerenciada por uma ferramenta externa OCA Weblate: 
https://translation.odoo-community.org/projects/l10n-brazil-14-0/
![image](https://github.com/user-attachments/assets/00d240ce-78c7-4958-98b1-71a95360526c)


Qualquer um pode participar da tradução, só precisa solicitar o acesso.

**Comment by antoniospneto** [comment]
Atualizei o termo no weblate conforme você sugeriu ok

**Comment by kcarriello** [comment]
obrigado!
