### ISSUE TITLE
[14.0][BUG] Não é possível Criar Documento Fiscal quando a Fatura é criada por um Picking

### ISSUE THREAD

**Issue by douglascstd** [OCA/l10n-brazil#3478]
Em alguma das últimas atualizações causou a impossiblidade de criar documento fiscal.

Não encontrei nenhuma alternativa que fosse possível a emissão, mesmo com os erros apresentados.

### Como Reproduzir:
Criar uma Operação de Transferência
  Incluir uma Operação Fiscal: Remessa para Industrialização
Operações >> Transferência >> Nova
  Inserir:
    Tipo de Operação: Criada no passo anterior
    Produto: Led
  Validar
  Marcar para Faturar
  Criar Fatura
Na Fatura
  Editar linha da fatura
    Inserir Operação e Linha de Operação (deveria ter vindo do picking, mas esse é outro problema)
 Salvar
  Observar que a Operação e linha e Operação não ficarão no registro
Acessar o botão: Detalhes Fiscais
  Observar que não é apresentado a visão do documento fiscal, no entanto é possível ver no menu Fiscal.

### Evidências
Não é persistido os campos de Operação e Linha de Operação:
![image](https://github.com/user-attachments/assets/e6e6d888-22eb-45ae-a862-29a54df56606)

Visualização do Documento Fiscal:
![image](https://github.com/user-attachments/assets/0d5d478d-9384-43e3-9353-986d7e0fd4c3)

Na visão do Documento Fiscal, no app "Fiscal":
![image](https://github.com/user-attachments/assets/720ac93c-d26b-4354-998f-53be281b45fb)

**Comment by kaynnan** [comment]
Após a realização de alguns testes, constatei que o problema na atribuição da Operação Fiscal manifestou-se após a aplicação do commit [[FIX] l10n_br_stock_account: Get Default OP Fiscal](https://github.com/OCA/l10n-brazil/pull/3327/commits/328ca7f38a39e604df4be508755ea8db2f223a70). No ambiente local, reverti as modificações introduzidas por esse commit para a versão anterior, o que restaurou a funcionalidade de atribuição da Operação Fiscal.

**Comment by douglascstd** [comment]
@mbcosta tudo bem? vc pode dá uma olhada se faz sentido esse erro?? e avaliar se o Fix que o @kaynnan mencionou pode ter causado esse problema...

**Comment by douglascstd** [comment]
@mbcosta Boa tarde, vc pode dar uma olhada?

**Comment by mbcosta** [comment]
@douglascstd acredito que o problema acontece porque a Fatura estava sendo criada sem a Operação Fiscal e nesse caso o programa não cria o Documento Fiscal e aí surge esse problema que precisa ser avaliado que é 

**A partir de uma Fatura gerada de um objeto Sem Operação Fiscal deve ser possível Associar/Criar um Documento Fiscal?**

Algo que também foi reportado no issue [[14.0][BUG][l10n_br_account] Impossibilidade de inserir impostos em uma fatura gerada por uma SO que não tem operação declarada.](https://github.com/OCA/l10n-brazil/issues/2877), como no caso de uso que você descreveu você informa a Operação então esse não seria o seu caso.

O problema ocorre porque você estava informando que o Picking deveria ser Faturado depois de incluir as Linhas e o programa não estava incluindo nas Linhas a Operação Fiscal e a Linha de Operação Fiscal, dessa forma o programa também não mostra os Dados Fiscais antes  

**O caso de uso que você descreveu:**
Criar uma Operação de Transferência
Incluir uma Operação Fiscal: Remessa para Industrialização
Operações >> Transferência >> Nova
Inserir:
Tipo de Operação: Criada no passo anterior
Produto: Led
Validar
**Marcar para Faturar**

**Como era esperado pelo código:**
Criar uma Operação de Transferência
Incluir uma Operação Fiscal: Remessa para Industrialização
Operações >> Transferência >> Nova
Inserir:
**Endereço de entrega**  - para poder mapear a Operação Fiscal
Tipo de Operação: Criada no passo anterior
**Marcar para Faturar** - assim será mostrado os Dados Fiscais
Produto: Led
Validar

![image](https://github.com/user-attachments/assets/95c7e840-e0b9-4137-a23b-395ef91a2c9a)

![image](https://github.com/user-attachments/assets/59262409-b50a-42c4-b131-4cf6f8f0ffbe)

Apesar de você ter escrito

"Inserir Operação e Linha de Operação (deveria ter vindo do picking, mas esse é outro problema)"

O problema era justamente esse que é o issue [[BUG][14.0] Calculo de Operação e Linha de Operação Fiscal em Fatura geradas pela Separação (Picking)](https://github.com/OCA/l10n-brazil/issues/3295) então hoje ao criar uma Fatura que tem um **Documento Fiscal** tanto a partir do Pedido de Vendas, Compras ou Picking é preciso informar a Operação Fiscal para evitar o erro da Fatura Sem Documento Fiscal.

O PR que o @kaynnan reverteu foi necessário para resolver o caso **Pedido de Vendas Sem Operação Fiscal gerando a Fatura a partir do Picking**, essa Fatura não dever ter o Documento Fiscal, o teste que ocorria erro está no l10n_br_sale_stock https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_sale_stock/tests/test_sale_stock.py#L487

![image](https://github.com/user-attachments/assets/57fa0d3f-ac9d-4e7d-8b38-f7960ca0c267)


O projeto da Localização está buscando manter compatibilidade tanto com os casos de uso onde uma empresa do Brasil gera Faturas Com ou Sem Documento Fiscais, por alguma questão de processo, quanto nos casos onde empresas multi-nacionais usam o mesmo Banco de Dados e por isso podem ter multi-localizações instaladas e nesse caso você vai ter tanto as Faturas Com documento Fiscal para o Brasil quanto as Faturas Sem o Documento fiscal para os casos fora do Brasil, antes desses PRs o programa acabava sempre criando as Faturas Com Documentos Fiscais por isso esse tipo de erro não era visto.

Bom, procurei resolver o problema no PR  https://github.com/OCA/l10n-brazil/pull/3497 deve atender esse caso que você descreveu, onde o **Marcar para Faturar** e feito por último, por favor veja se resolve o seu caso de uso.

Aproveitando que você parece estar usando e testando a **criação da Fatura a partir do Picking** eu tenho um PR importante onde estou melhorando o caso de criação da Fatura a partir do Picking que tem relação com o Pedido de Vendas, hoje o que temos na localização não permite o uso com **Pagamentos Adiantados, Linhas de Seção, Notas, e outros campos** que quando são criados a partir do Pedido de Vendas são copiados para a Fatura mas não quando são criados a partir do Picking, além da necessidade de criar "glue modules" para todos os casos onde um determinado módulo adiciona uma nova informação no Pedido de Vendas e na Fatura criada, um exemplo é o módulo de Comissões, mas podem existir N módulos, por isso peço ajuda na revisão do PR https://github.com/OCA/l10n-brazil/pull/2955

**Comment by rvalyi** [comment]
Resolvido em #3497, re-abrir se eu estiver equivocado.

**Comment by douglascstd** [comment]
Concluído sim..
