### ISSUE TITLE
[14.0][l10n_br_pos] nfce printing

### ISSUE THREAD

**Issue by DiegoParadeda** [OCA/l10n-brazil#3494]
## Print receipt broken for NFCe

Note that HTML is being correctly generated:
![image](https://github.com/user-attachments/assets/f946fcbe-9357-47e9-9e3f-5a37aebde660)

But, when printing, the page is empty:
![image](https://github.com/user-attachments/assets/27a329c2-e60a-4678-8628-822985d9d24b)

**Comment by DiegoParadeda** [comment]
This is how the receipt should look like:
![image](https://github.com/user-attachments/assets/b1a7bb86-8589-42de-a1ef-d8e552158957)

Opening PR soon...

**Comment by rvalyi** [comment]
Quando vc cria um PR logo para solucionar algo, a prática na OCA é de fazer tudo no próprio PR, assim tudo é feito num único lugar e evita dispersar a informação/noise. Issue só serve se vc não tá trabalhando no assunto mesmo...
