### ISSUE TITLE
Problema de Sobreposição de Dados de Demonstração

### ISSUE THREAD

**Issue by antoniospneto** [OCA/l10n-brazil#3538]
Estamos enfrentando um problema de sobreposição de dados na localização do Odoo, especificamente relacionados ao registro da empresa padrão de demonstração (`base.main_company`). A seguir, detalhamos como as informações da empresa são alteradas conforme a instalação de diferentes módulos.

### Evolução da Configuração da Empresa

| Passo | Módulos Instalados                        | Nome da Empresa                  | Moeda |
|-------|-------------------------------------------|----------------------------------|-------|
| 1     | `base`                                    | My Company                       | EUR   |
| 2     | `base`, `l10n_br_base`                    | Sua Empresa                      | BRL   |
| 3     | `base`, `l10n_br_base`, `stock`           | My Company (San Francisco)       | BRL   |
| 4     | `base`, `l10n_br_base`, `stock`, `account` | My Company (San Francisco)      | USD   |

### Impacto

- **Confusão nos Dados de Demonstração**: A localização implementa diversas alterações ao tratar a empresa como brasileira, tornando os dados de demonstração confusos.
- **Dificuldade nos Testes Unitários**: A validação dos testes torna-se complicada, pois a configuração da empresa pode variar conforme a ordem de instalação dos módulos, afetando os resultados. A mudança da moeda de BRL para USD, por exemplo, altera significativamente os valores nos lançamentos contábeis.

### Sugestões

- **Manter a Empresa Padrão Inalterada**: Evitar sobrescrever o registro da empresa padrão (`base.main_company`) e preservar suas configurações originais.

- **Utilizar Empresas Alternativas da Localização**: Empregar outras empresas disponíveis na localização, como Empresa de Lucro Presumido e Empresa de Simples Nacional.

- **Evitar Uso de Dados de Demonstração nos Testes**: Não utilizar dados de demonstração nos testes unitários para garantir a consistência dos resultados, independentemente da ordem de instalação dos módulos.

### Anexos

 ![Registro Nativo](https://github.com/user-attachments/assets/6d4e6ee1-7d08-43b3-854a-bef7d0acd005)
 ![Após l10n_br_base](https://github.com/user-attachments/assets/65ff775a-d3bc-438b-9299-1c454cdeff51)
 ![Após módulo stock](https://github.com/user-attachments/assets/39f56e99-56d3-492a-b825-1c2f0d192162)
 ![Após módulo account](https://github.com/user-attachments/assets/fa4c02fd-88c8-4b63-953b-8ff8661f2f6f)

**Comment by antoniospneto** [comment]
Depois que instala o plano de contas brasileiro a moeda volta a ficar BRL, o mais chato é quanto tá executando os testes localmente que se não cuidar a moeda fica USD e os testes quebram.

Qualto ao nome talvez dá pra sobrescrever no módulo l10n_br_sale_stock o nome pra "Sua Empresa" de volta ai já fica OK tbm.

**Comment by rvalyi** [comment]
As mudancas no base.main_company, a gente poderia faze-las apenas no módulo l10n_br_setup_tests para fins de demonstrações (runboat por examplo), uma vez que todo restante ja foi instalado. Mas sim de uma forma geral, nao foi legal mudar essas configurações do base.main_company nos outros modulos da localização.

**Comment by rvalyi** [comment]
resolvido por #3545
