### ISSUE TITLE
Transferências Reversas com Faturamento - Lista de Problemas

### ISSUE THREAD

**Issue by wagnerpereirasp** [OCA/l10n-brazil#356]
- [ ] NF de Devolução não referencia o documento fiscal original que está sendo devolvido.
- [x] A NF de Devolução é criada com Finalidade de Emissão = Normal quando deveria ser Devolução de Mercadoria. PR #346 
- [ ] O processo de Confirmar poderia validar ser os valores e impostos de devolução estão iguais aos da NF original (ou soma das NFs se for mais de uma).
- [ ] Uma NF cancelada também deveria cancelar o pedido de venda original, hoje o pedido de venda original se mantém como Concluído.

**Comment by renatonlima** [comment]
@wagnerpereirasp 

O item 2 já foi implementado neste PR https://github.com/OCA/l10n-brazil/pull/346, sobre os outros itens:
1. É importante e automatiza já informar a nota de origem nas referenciadas. (alguém esta trabalhando nisso?)
2. Quando é criada uma devolução é utilizados os mesmos impostos e só usado as contas contábeis de devolução.
3. Como estamos falando sobre NF-es de devolução, eu vou pensar nos dois casos 1. Se a nota fiscal é devolvida, ai o fluxo esta correto porque a nota fiscal vai continuar aberta e vai ser feita outra de devolução. 2. Se a nota fiscal é cancelada na SEFAZ deveria ser cancelado o pedido de venda, mas isso vai depender do picking porque se tiver um picking concluído deveria ser feito uma operação reversa para o material voltar no estoque.

**Comment by wagnerpereirasp** [comment]
@renatonlima 

Bom dia Renato,

Legal saber que o item 2 já está em um PR, vou pedir para o Luis revisá-lo.

Quanto a Item 1 nós vamos trabalhar nisso e teremos isso pronto em 1 ou 2 meses dentro de nossa prioridade, se alguém precisar disso antes avisa que tentamos antecipar.

Já o Item 3 é mais filosófico e precisa incluir Invoice, Picking e Sale ao mesmo tempo, eu pensei muito nisso e tenho uma sugestão:

a) Todos os 3 registros precisam ser relacionados sempre, porém podem haver casos que uma Fatura é emitida sem uma venda relacionada, um ajuste por exemplo

b) Quando há relacionamento entre os 3 itens a dinâmica deveria ser a seguinte:

1o. Passo, usuário registra um pedido de venda, confirma e faz os passos necessários para que o pedido chega a etapa de Aguardando Entrega.
2o. Passo, o Picking não deveria permitir alterar dados que foram herdados da Venda, principalmente Categoria e Posição Fiscal, se isso precisasse ser alterado a mudança deveria ser feita no Pedido de Venda (que deveria ser Cancelado, Reaberto e Reprocessado).
3o. Passo, o Picking é Transferido e gera-se a Fatura (hoje para criar a Fatura é preciso clicar no Botão Criar Fatura após a transferência do Picking, eu sugiro que isso seja automático para pickings que devem ser faturados)
4o. Passo a Fatura é Confirmada e Transmitida

Para o Cancelamento nós podemos ter vários tipos de cancelamentos:

1o. A Fatura contém algum erro e precisa ser reemitida com menos de 24 horas, isso não influencia nem na venda nem no transporte pois o produto ainda precisa ser enviado ao cliente.
- Para esse caso basta clicar em Cancelar Fatura, justificar junto a SEFAZ, e isso deveria fazer o Picking voltar para Aberto e o Pedido de Venda para Aguardando Entrega, devendo assim a correção ser feita no Pedido de Venda se for o caso.

2o. A Fatura contém algum erro e precisa ser reemitida após 24 horas, obrigando-nos a gerar uma Fatura de Devolução.
- Para este caso eu sugiro que o botão Cancelar Fatura automatize esse passo, ele precisaria contar o prazo de 24 horas (que também deveria ser configurável na configuração da empresa, já pensando que algum dia esse prazo possa ser diferente) e decidir pela criação da Fatura de Devolução, esta fatura deveria ser criada automaticamente já com a Posição Fiscal de Devolução configurada na Categoria Fiscal e as Regras de Posição Fiscal executadas, todos os dados do cancelamento serem incluídos automaticamente permitindo ao operador apenas a Confirmação e Transmissão da Fatura. Isso não termina o processo pois o picking e o sale originais também precisam voltar para a situação abertos.

3o. Não há nenhum problema na fatura porém ainda assim o cliente deseja devolver o produto por qualquer motivo que seja, porém se o cliente deseja receber o produto de novo (que seja uma troca por exemplo), isso poderia ser feito por uma Transferência Reversa do Picking, que eu acredito que um nome melhor seria "Cancelar Transferência".
- Neste caso o operador encontra o Picking e executa a Transferência Reversa, como o Picking original foi Faturado, o Picking de Transferência Reversa também precisa ser faturado e a Categoria Fiscal e Posição Fiscal precisam ser as mesmas da Devolução da Categoria Reversa, ao operador basta Executar a Transferência Reversa e a Fatura de Devolução já é criada, nos moldes do passo 2, e o pedido de venda volta para a situação de Aguardando Entrega.

4o. A Venda será cancelada, o cliente não deseja mais o produto e quer restituição de qualquer valor pago anteriormente.
- Neste caso o operador deve cancelar o Pedido de Venda, o que imediatamente gera uma Fatura de Devolução e um Picking de Transferência Reversa, veja que neste caso o Picking de Transferência Reversa precisa continuar em aberto até o produto retornar ao Estoque, porém a Fatura de Devolução precisa ser emitida imediatamente, para permitir o transporte de retorno do produto.

O que acha Renato ?

**Comment by wagnerpereirasp** [comment]
@renatonlima 

Acabei de ver um outro caso que também precisamos cobrir, é quando uma NF-e é Denegada na SEFAZ, isso pode ocorrer por problemas de cadastro do cliente e a NF-e fica documentada e não pode ser mais cancelada, quando isso ocorre tanto o Picking quanto o Sale precisam ser reabertos (hoje não está fazendo isso).

**Comment by mileo** [comment]
@renatonlima @wagnerpereirasp o Daniel esta melhorando alguns detalhes dessa funcionalidade.
1. NF de Devolução não referencia o documento fiscal original que está sendo devolvido:
   1.1 Inclusão do modulo https://github.com/OCA/stock-logistics-workflow/tree/9.0/stock_picking_invoice_link nas dependências do l10n_br_stock_account
   1.2 Criação de modulo similar no repositório https://github.com/OCA/pos para linkar o picking com o pos.
   1.3 Criação de campo chave de acessso em stock.picking ( computed );

> for record in self:
>     record.chave_acesso = record.invoice_id.chave_acesso
> 
> for record in self:
>     record.chave_acesso = record.invoice_id and record.invoice_id.chave_acesso or record.pos_order_id and record.por_order_id.chave_acesso or ''

1.4 Incluir campo chave de acesso na pesquisa;
1.5 Sobrecrita do metodo chamado no item 1.3 em l10n_br_pos para verificar se o mesmo tem um pos_order_id definido assim calculando a chave de acesso do picking do pos.
1.6 Criação do campo tipo da operação na categoria fiscal;
1.7 Alteração do wizard de faturamento do picking para trazer como default o campo documento referenciado caso a operação seja de devolução, permitindo tb o usuário selecionar a fatura quando não localizada. Este campo deve ser do tipo refence.

> refence_doc = fields.reference(compute='_compute_reference....')
> 
> def _compute_reference_...()
>     return  = (model, id)

1.8 Verificar se o documento referenciado esta no contexto, no metodo _prepare_invoice_vals preenchendo o mesmo;

> def _prepare_invoice_vals(...)
> super....
> if self._context.get('refence_doc', False):
>      result['l10n_br_related_document'] = {6,0, (...)}
