### ISSUE TITLE
Posição fiscal

### ISSUE THREAD

**Issue by lucasrabelo** [OCA/l10n-brazil#362]
Olá, 
gostaria de relatar a seguinte situação:
Ao tentar criar um novo pedido de venda, as opções de posição fiscal se apagam 
![captura de tela de 2016-08-03 09-45-45](https://cloud.githubusercontent.com/assets/5579942/17365957/1dd1eab2-595f-11e6-8eaf-150580959cfd.png)

**Comment by renatonlima** [comment]
Você deve configurar as regras de posição fiscal, caso não tenha uma regra, a localização não deixa colocar uma posição fiscal

**Comment by vafonso** [comment]
Boa tarde
Estou enfrentando problema similar ao fazer a cotação da ordem de compra ou pedido de vendas
Situação:
- Cadastrado as posições fiscais para Venda de Produtos e Revenda de Mercadoria (Idem para as compras)
- Cadastrado as regras de posições fiscais para os casos acima
- Cadastrado impostos na empresa (PIS 0,65, COFINS 3%, ICMS Interno)
- Cadastrado impostos na classificação fiscal (Venda - IPI 10%, Compra - IPI, ICMS interno, PIS, COFINS)
- A posição fiscal de compra deve trocar os impostos genéricos pelos que a empresa possa recuperar
- A posição fiscal de venda deve trocar o ICMS genérico para o ICMS correto

**CASO VENDAS**
- Ao cadastrar o pedido de venda, a posição fiscal é puxada automaticamente (A linha de prioridade menor no cadastro da regra). No meu caso, é puxado a categoria de venda.
- Ao alterar para categoria para Revenda, os impostos não são modificados conforme mapeamento feito na posição fiscal
- Também não funciona se quiser modificar manualmente a posição fiscal para, por exemplo, venda fora do estado, que contem outro mapeamento para o ICMS

**CASO COMPRAS**
- Ao cadastrar a ordem de compra, os impostos são copiados exatamente iguais aos cadastrados na classificação fiscal, porem sem o mapeamento feito na posição fiscal (Lembrando que a posição fiscal está sendo puxada para a linha, isto é, ela não está em branco)
- Caso seja fixado a posição fiscal no cadastro do fornecedor, as trocas pelo mapeamento são efetuadas.

Me parece que, ao trocar o produto, todos os campos são atualizados automaticamente, contudo, se modificar somente a categoria fiscal ou a posição fiscal, nenhum campo é atualizado

Ats

**Comment by vafonso** [comment]
Bom dia
Fiz mais alguns testes e pude verificar que ao gerar uma fatura de compras para industrialização, a qual possui categoria fiscal de "Compras para Industrialização" mas diversas posições fiscais (Exemplo: compra dentro do estado, compra fora estado ICMS 7% etc), o Odoo não deixa efetuar a troca dessas posições, ficando fixa a 1 da regra da posição fiscal.
Tenho uma base mais antiga com repositório da Trust, e com as mesmas configurações funciona perfeitamente.
Tentei ver algo no código para auxiliar porem estou longe de entender por completo. Contudo pude verificar que o repositório da OCA está referenciando uma outra API
Alguém podeira auxiliar?

Obrigado

**Comment by mbcosta** [comment]
@vafonso conforme falado no outro issue https://github.com/OCA/l10n-brazil/issues/405 as correções já foram integradas na branch 8.0, por isso vou pedir aos PSCs para encerrarem esse issue, caso ainda tenha algum problema por favor nos avise

cc @renatonlima @rvalyi
