### ISSUE TITLE
Fim do Emissor Gratuito

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#368]
Bom dia,

Pessoal o emissor gratuito de NF-E tem data definida. O Sefaz de SP deixará de atualizar o aplicativo em  1 de Janeiro de 2017.

De forma que precisamos abrir uma discussão sobre isso. De antemão levanto alguns pontos:
- [ ] Emissão em contingência.
- [ ] Flexibilidade para preencher o documento eletrônico sem o mapeamento fiscal

**Comment by rvalyi** [comment]
@mileo a partir da v8 o @renatonlima trabalhou bastante nessa questao de "Flexibilidade para preencher o documento eletrônico sem o mapeamento fiscal". Sera se vc poderia explicitar melhor o que vc acha que ainda falta melhorar nisso?

**Comment by mileo** [comment]
Acredito que devemos fazer um hangout sobre isso. O @renatonlima comentou a pouco o contrário.... https://github.com/OCA/l10n-brazil/issues/362

**Comment by renatonlima** [comment]
@mileo 

Eu acredito que o lugar mais apropriado para este issue seria em https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/issues Existe algumas funções que existe no emissor gratuito que deveria ser implementado nos módulos de NFe.

Sobre a flexibilidade eu estou trabalhando no https://github.com/OCA/l10n-brazil/pull/363 para flexibilizar a criação do documento fiscal, assim como a visualização de alguns campos que hoje não existe na visão atual, como por exemplo os totais dos impostos.

Sobre flexibilizar a edição sem mapeamento de regra fiscal, poderia ser um parâmetro ou um grupo de segurança para permitir isso, pois com isso poderíamos restringir que usuários que não tenha conhecimento fiscal só consiga fazer o que esta parametrizado, mas um especialista poderia preencher manualmente.

**Comment by renatonlima** [comment]
Nos poderíamos fazer um hangout com algumas pessoa da comunidade para discutir sobre estes pontos.

**Comment by renatonlima** [comment]
#402
