### ISSUE TITLE
Validação das faturas de forma dinâmica

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#371]
É muito importante aprimorarmos de forma facilitada as regras de validação das faturas. Portanto sugiro a criação de funcionalidade similar ao modulo https://github.com/OCA/sale-workflow/tree/8.0/sale_exceptions para validar a aprovação das faturas.

Extrair regras do modulo https://github.com/OCA/l10n-brazil/blob/9.0/l10n_br_account_product/sped/nfe/validator/txt.py#L44 e coloca-las em dados xml.

**Comment by mileo** [comment]
OBS: Seria bacana criar um modulo e envia-lo ao repo: https://github.com/OCA/account-invoicing

**Comment by danimaribeiro** [comment]
https://github.com/Trust-Code/trust-addons/tree/8.0/trust_invoice_validation
Que é baseada em um módulo de validação do pedido da akretion.

**Comment by danimaribeiro** [comment]
https://github.com/OCA/sale-workflow/tree/9.0/sale_exception

**Comment by mileo** [comment]
Pode mandar ele pra OCA?

**Comment by mileo** [comment]
https://github.com/OCA/account-invoicing de forma mais genérica?

**Comment by rvalyi** [comment]
@mileo @danimaribeiro sou quem iniciou esse modulo sale_exception na Akretion uns 4 anos atras... Recentemente o @renatonlima trabalhou exactamente nisso e eu acho que ele vai subir um modulo desse na OCA em breve. @renatonlima deixo vc comentar...

**Comment by renatonlima** [comment]
@mileo 

Na semana passada quando estava trabalhando no PR para separar as visões da Fatura e NFe eu pensei nisso e criei o módulo invoice_exception na semana passada, eu subi neste PR https://github.com/OCA/account-invoicing/pull/173

A minha ideia é primeiro fazer um módulo genérico no nível da OCA, e depois utiliza-lo na localização nos módulos l10n_br_account_product e l10n_br_account_service para:
- Substituir a rotina de validação em TXT;
- Poder definir exceções por tipo de documentos fiscais (NF-e, NFC-e, NFS-e e etc.);
- Integrar com a validação da NFe (schemas xsd da NF-e)

@danimaribeiro 

Eu analisei o seu módulo, em comparação com o sale_exception existem algumas features não implementadas, e existe algumas dependências com a localização e alguns métodos, você pode dar uma olhada no PR acima e fique a vontade para propor melhorias.

Para finalizar este PR eu quero implementar na regra de exceções o campo de tipo de fatura (customer invoice, supplier invoice) para poder criar exceções tanto na fatura de clientes quanto de fornecedores.

**Comment by mileo** [comment]
Bacana.. @renatonlima era exatamente oq eu esta imaginando.  A questão do XSD ficaria top.

**Comment by mileo** [comment]
Vou revisar seu PR, no sale_exceptions personalizamos um modulo para ter tipo de exceções e categorizar as validações, vou ver se consigo adaptar com oq vc fez na fatura para contemplar a questão do tipo da fatura.
