### ISSUE TITLE
Utilização dos módulos de locais do repositório partner-contact

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#372]
https://github.com/OCA/partner-contact/tree/8.0/base_location
https://github.com/OCA/partner-contact/tree/8.0/base_location_nuts

**Comment by rvalyi** [comment]
Eh esse eu ja tinha feito um issue na epoca do Launchpad, accredito que podemos ter um proveito sim, porem nao parece trivial, ja cheguei a conversar bastante com o Pedro para poder nos atender na epoca, so nao me lembro muito. Agora eu acho que so vai valer a pena se quem contribuir esse refator encarar a migracao dos dados tb... Talvez e bastante trabalho para pouco ganho, temos que re-avaliar...

**Comment by mileo** [comment]
Só vejo vantagem se for feito em conjunto com esta funcionadalide: https://github.com/OCA/l10n-brazil/issues/373

Definições de imposto por região. Infelizmente no Brasil existem diferentes icms dentro de uma mesma cidade.
