### ISSUE TITLE
Remover a rotina de exportação em TXT

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#380]
Com a descontinuação do programa emissor de NFe não tem mais utilidade esta função, que pode ser subsistida pela exportação em XML. O emissor aceita a importação de XML validados e assinados.

**Comment by renatonlima** [comment]
#381

**Comment by mbcosta** [comment]
olá @renatonlima @rvalyi @mileo , isso foi removido na 10.
