### ISSUE TITLE
Correção dos lançamentos contábeis da localização

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#382]
Ao analisar o PR https://github.com/OCA/l10n-brazil/pull/274 verificamos que a localização tem alguns problema nos lançamentos contábeis.

Então iniciamos um levantamento dos tipos de lançamentos no arquivo: 
https://docs.google.com/document/d/1lms-pOdbbBL5JU3c0g50gcjciEWf_ZGPWgZFySpJUBk/edit?usp=sharing

@rvalyi @renatonlima @danimaribeiro @carlosmaguda @mstuttgart @wagnerpereirasp @leticiadnsouza

Abro a discussão para avaliarmos uma solução sobre o item.

Abraços

**Comment by ghost** [comment]
Vou abrir o PR com as mudanças.

**Comment by rvalyi** [comment]
@mileo uma coisa que seria interessante seria accrescentar testes, principalmente onde tiver erros.
