### ISSUE TITLE
Nota fiscal de servico: merge do modulo base_nfse

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#392]
Ao nivel da OCA, podemos melhorar as abstracoes para a emissao das notas fiscais de servico. Especialmente podemos integrar o trabalho do @danimaribeiro no modulo base_nfse que esta hoje proposto no merge no repo odoo-brazil/odoo-brazil-eletronic-documents:
https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/pull/105

Esse nodulo base_nfse nao e muito complexo e nao tem nehnuma dependencia problematica (ao contrario dos modulos que dependem do pysped la) entao realmente e possivel integrar esse modulo nesse repo da OCA.

A ideia porem e de deixar os templates de mapping das notas dos municipios em repos satelites (pode ser um so) onde a burocracia e menor e para deixar o projeto OCA bem struturado por camadas.

Precisamos entender exactemente porque o base_nfse depende do modulo l10_br_account_product e se poderiamos refatorar umas coisas no l10_br_account para nao ter esse dependencia. Caso matar essa dependencia, poderiamos considerar de fazer um merge do modulo base_nfse dentro do modulo l10n_br_account_service ja que nao teria justificativa do l10n_br_account_service existir sem essas funcionalidades.

Antes de proceder com esse merge, temos porem que finalizar esse outro do @renatonlima que estrutura as visoes e menus de documentos fiscais de forma muito mais conveniente para extender alem: https://github.com/OCA/l10n-brazil/pull/363 O Renato deve estar terminando isso ja ja...

**Comment by mileo** [comment]
Tem que tomar um pouco de cuidado com a NFS-E do DF, pois ela usa o webservice da NF-E.

**Comment by rvalyi** [comment]
Tambem so avisando que isso nao vai ser uma prioridade grande aqui na Akretion entao @mileo ou @danimar se voces querem assumir essa tarefa, podem ficar a vontade de propor o PR (acho que teria que extrair o base_nfse do outro repo preservando o historico, fazendo um rebase nesse repo e talvez depois entao comecar um merge com os arquivos do l10n_br_account_service caso seja pertinente).

**Comment by mileo** [comment]
Te dizer que estou de saco cheio de emitir nfs-e na mão. Devo ver isso em breve.

**Comment by danimaribeiro** [comment]
Estou no momento implementando a NFSe de São Paulo e estou aproveitando o momento para fazer um refactor desse nfse_base e dos outros módulos.
Estou jogando a parte de gerar para uma bilbioteca externa.

A paulistana por exemplo ficou com um código bem enxuto e fácil de dar manutenção.
https://github.com/danimaribeiro/PyTrustNFe/blob/master/pytrustnfe/nfse/paulistana/__init__.py
Porém falta alguns testes ainda.

Vou precisar mais umas três semanas para finalizar ainda.

**Comment by rvalyi** [comment]
@danimaribeiro sem problema, valeu pelo trabalho!
