### ISSUE TITLE
opcao de emissao das NFe's de forma asincrona com connector; transmissao por lotes

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#393]
De uma forma geral nao queremos depender do framework OCA/connector para nao complexificar demais o projeto (a localisacao ja e o projeto mais complexo da OCA, o OCA/connector nao esta longe atras).

Porem, algumas empresas precisam emitir muitas NFe's e com um control melhor do que temos hoje. Nesse caso, usar o OCA/connector iria melhorar a situacao.

A ideia seria de fazer alguns leves refatores ao nivel do modulo l10n_br_account_product e dos modulos do repo odoo-brazil/odoo-brazil-eletronic-documents e criar um modulo aditional e opcional que iria transmitir atraves do connector. A ideia e que se esse modulo for instaldo, a emissao asincrona ja existente do l10n_br_account_product iria acontecer dentro de um job e usando o sistema de reporting do connector. Na Akretion e possivel que temos um cliente que iria financiar essa melhoria, na v8 ainda (ele pensa mandar tipo 10 000 notas fiscais por mes). Como trabalhei bastante com connector, eu iria trabalhar nesse refator.

**Comment by mileo** [comment]
@rvalyi 10 mil notas são 450 notas dia,  aproximadamente 1 nota por minuto se for contar o horário comercial.

Temos um cliente que emite 200 notas dia sem problemas com a implementação atual. Brevemente explivo que existem algumas questões importantes que devem ser discutidas nessa implementação:
- A arquitetura atual do nfe não permite o envio em lote;
- Ao confirmar as faturas provisórias é executado o workflow da invoice, de forma que cada um dos itens é chamado individualmente. 

Se vc pretente enviar um lote de com várias nf-es dentro vamos precisar rever algumas coisas.

abs

**Comment by rvalyi** [comment]
Sim a ideia e a gestao por lote mesmo. Legal saber que ja estao conseguindo mandar 200 por dia nesse cliente...

**Comment by mileo** [comment]
O Pysped e o Odoo aguentam uma porrada boa! Coisa de dois faturistas com várias abas abertas transmitindo nf-e e em um dia só uma dar problema e precisar consultar o status.

Mas com o connector ficaria muito melhor. Mas antes de chegar nele tem vários outros pontos a serem resolvidos.

Quando uma nf-e é perdida no meio do caminho vc precisa conseguir buscar o xml dela.

Este método faz isso: https://github.com/kmee/odoo-brazil-eletronic-documents/blob/8.0/nfe/models/account_invoice.py#L336

Alias preciso mandar ele para a odoo-brazil. Enfim vale um hangout para tratarmos das coisas a serem melhoradas.

**Comment by rvalyi** [comment]
Sim, identificamos esse tipo de problema, pegamos tb. Alias, botei esse ponto nao e uma critica ao pysped que seja claro. O Pysped tem outros problemas como a qualidade do codigo dele ou a futura manutencao, mas com certeza as limitacoes na ergonomia da transmissao nao vem do pysped. Aqui a gente so ta correndo para encerrar o PR da separacao das visoes que ta ficando show de bola e iremos fazer um hangout sim.

**Comment by mileo** [comment]
#854 Closes this issue.
