### ISSUE TITLE
Criação de Parceiro a partir do Ponto de Venda (POS) - Dados obrigatórios não são populados

### ISSUE THREAD

**Issue by wagnerpereirasp** [OCA/l10n-brazil#398]
Bom dia, estamos trabalhando com o Ponto de Venda do Odoo, e quando criamos um parceiro a partir do  POS este parceiro não tem os campos obrigatórios da localização brasileira definidos por padrão.

O campo em especial é o Tipo Fiscal do Parceiro, minha sugestão é:

[ ] Cliente é uma Pessoa Física (com CPF), Tipo Fiscal do Parceiro é automaticamente definido como Não Contribuinte.
[ ] Cliente é uma Pessoal Jurídica (com CNPJ), Tipo Fiscal do Parceiro é deixado em branco para ser definido posteriormente.

Wagner Pereira

**Comment by renatonlima** [comment]
Olá Wagner,

Isso já funciona https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account/models/res_partner.py#L299 Eu não me lembro qual visão de parceiro o POS funciona, mas na visão do modulo base o valor padão funciona de acordo com o flag is_company,  você pode verificar se o campo is_company e company_id estão na visão do cadastro de parceiro que esta sendo usada pelo POS?

**Comment by wagnerpereirasp** [comment]
Obrigado Renato, é possivel que estejamos usando um commit anterior, vou investigar.
