### ISSUE TITLE
Módulos de recursos humanos

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#401]
portar e propor merge dos modulos https://github.com/OCA/l10n-brazil/pull/91
A partir da v8 e razoavel aceitar esses modulos na OCA. Realmente nao sei se vamos ter revisores suficentes para acertar o l10n_br_payroll mas pelo menos e muito razoavel aceitar o l10n_br_hr,
cc @mileo

**Comment by mileo** [comment]
Raphael Bom dia!
Estaremos trabalhando nesses módulos nos próximos dias. Já realizamos parte da migração mas falta finalizar e colocar testes.
Abraços

**Comment by rvalyi** [comment]
legal saber. Seria bom mandar separadamente, primeiro o l10n_br_hr que eu acho que seria rapido de aceitar. O Payroll pode demorar mais...
