### ISSUE TITLE
Erro de singleton na tela de Empresas ao utilizar base com dados demo

### ISSUE THREAD

**Issue by mstuttgart** [OCA/l10n-brazil#403]
Encontrei o seguinte erro ao criar uma base com dados demo e instalar a localização da OCA.

![captura de tela de 2016-09-14 17-54-13](https://cloud.githubusercontent.com/assets/8174740/18529781/ed8e07f2-7aa4-11e6-89c4-8f4332d1e854.png)

Para reproduzir o erro:

Localização da OCA
- Branch 8.0 
- Ultimo commit: 679726fcecc619f5fade1ae7d19e668f84c68fab

Para reproduzir o erro basta criar uma base com dados de demonstração e em seguida, instalar os módulos da localização (utilizar o filtro `l10n_br` na barra de pesquisa e instalar todos os módulos instaláveis).

Após a instalação dos módulos e ir para a tela de empresas (Configurações -> Empresas) para reproduzir o erro.

**Comment by rvalyi** [comment]
good catch, fixed by https://github.com/OCA/l10n-brazil/pull/404
