### ISSUE TITLE
Erro na Posição Fiscal / Regra de Posição Fiscal

### ISSUE THREAD

**Issue by vafonso** [OCA/l10n-brazil#405]
Bom dia a todos!!

Acabo de baixar e montar uma máquina para testes do repositório da OCA, fiz as seguintes configurações:

**Cadastro dos impostos na empresa**
![image](https://cloud.githubusercontent.com/assets/15039028/18547725/410f6102-7b1b-11e6-88c1-3965c894a370.png)

**Cadastro dos impostos na classificação fiscal do item**
![image](https://cloud.githubusercontent.com/assets/15039028/18547735/57dacbec-7b1b-11e6-92e8-85fb8b41f9c7.png)

**A propósito, alguém sabe dizer pra onde foi o botão de "Atualizar todos os produtos"???? Como é feito a atualização dos impostos em todos os produtos com a mesma NCM nessa versão?**

**Cadastro da posição fiscal**
![image](https://cloud.githubusercontent.com/assets/15039028/18547619/b59adac0-7b1a-11e6-8139-9be84807cfbe.png)

**Cadastro da Regra de posição fiscal**
![image](https://cloud.githubusercontent.com/assets/15039028/18547629/c3afb180-7b1a-11e6-8b28-6f8310786046.png)

E encontrei o seguinte problema:

**Criação do Pedido de Compras**
Ao criar o pedido de compras e selecionar o cliente, a posição fiscal é escolhida corretamente
![image](https://cloud.githubusercontent.com/assets/15039028/18547640/cc4d0216-7b1a-11e6-8fa9-6a4da4f849e7.png)

Contudo, caso tente-se manualmente alterar a posição fiscal para outra, esta se apaga e ao tentar novamente recolocar a posição fiscal original, o Odoo não aceita mais.
![image](https://cloud.githubusercontent.com/assets/15039028/18547642/d53e461e-7b1a-11e6-8ba6-ace5557b28b5.png)

Ao inserir as linhas do pedido de compra, a posição fiscal é novamente inserida automaticamente, contudo, o mapeamento dos impostos não é efetuado.
![image](https://cloud.githubusercontent.com/assets/15039028/18547645/db916f50-7b1a-11e6-9703-806d0d5ee000.png)

Ao tentar reinserir manualmente a Categoria Fiscal e a Posição Fiscal (Exemplo pegar outra para simples remessa ou outra), todos os impostos são deletados e não voltam mais a aparecer.
Isso está acontecendo para os pedidos de vendas, compras e geração das faturas de fornecedor e cliente

Nas outras máquinas de testes, esse erro não acontecia e era possível escolher as posições fiscais que tinham a mesma regra mas sequencias de posição diferentes.

Tentei observar o código, contudo há muitas diferenças acredito devido à nova API e eu não consegui acompanhar.
Peço auxilio para verificar se as configurações feitas estão equivocadas ou há algum problema no código
Abraços a todos

Vinicius

**Comment by vafonso** [comment]
Bom dia
Hoje montei uma nova máquina virtual somente com os repositórios descritos em https://github.com/OCA/l10n-brazil/wiki/Instala%C3%A7%C3%A3o-Odoo-v8-em-Ubuntu-Server-14.04-LTS (Isto é sem módulos adicionais ou customizados). E infelizmente o problema ainda persiste.
Alguém mais está tendo esse problema? Poderia, por favor, explicar como fez para solucionar?

Obrigado
Vinicius

**Comment by danimaribeiro** [comment]
Acredito que este bug/feature sempre existiu.

**Comment by vafonso** [comment]
Boa tarde Danimar
Estive verificando um pouco e:
**\- Pedido de vendas está funcionando parcialmente** > É possível trocar a categoria fiscal e selecionar a posição fiscal no cabeçalho do pedido. Ao inserir a linha com o item, esta "puxa" a categoria e posição fiscal do cabeçalho e faz o mapeamento correto dos impostos. Contudo, caso troque a posição e categoria fiscal na linha, os impostos não são mapeados. Para conseguir colocar diferentes CFOPs nas linhas do pedido, deve-se primeiro colocar no cabeçalho e depois inserir a linha: trocar o cabeçalho para nova posição fiscal e inserir a outra linha. Assim, aparentemente, está funcionando
**\- Notas fiscais diretamente na contabilidade** > Estas estão funcionando perfeitamente. Pode-se colocar uma categoria fiscal e posição fiscal qualquer no cabeçalho da NF e na linha, pode-se trocar como desejar. Todos os impostos são mapeados corretamente
**\- Ordem de Compra não funciona** > Nesse caso, há problema na seleção da posição fiscal, caso seja alterada a categoria fiscal, a posição fiscal é apagada e não é possível inserir outra. Assim, os mapeamentos dos impostos nas linhas não são efetuados.

Portanto, eu observei o código do pedido de vendas e fiz as seguintes alterações para teste no módulo de compras e aparentemente este agora está funcionando parcialmente como é o pedido de vendas.
Por favor, se possível, verifique se está correto para podermos sugerir um pull request
**/opt/odoo/localizacao/l10n-brazil/l10n_br_purchase/models/purchase.py**

**Antigo**

```
    @api.model
    def _fiscal_position_map(self, result, **kwargs):
        """Método para chamar a definição de regras fiscais"""
        ctx = dict(self._context)
        kwargs['fiscal_category_id'] = ctx.get('fiscal_category_id')

        ctx.update({'use_domain': ('use_purchase', '=', True)})
        return self.env[
            'account.fiscal.position.rule'].with_context(
                ctx).apply_fiscal_mapping(result, **kwargs)

```

**Novo**

```
    @api.model
    def _fiscal_position_map(self, result, **kwargs):
        ctx = dict(self.env.context)
        if not kwargs.get('fiscal_category_id'):
            kwargs['fiscal_category_id'] = ctx.get('fiscal_category_id')
        ctx.update({
            'use_domain': ('use_purchase', '=', True),
            'fiscal_category_id': ctx.get('fiscal_category_id')})
        return self.env['account.fiscal.position.rule'].with_context(
            ctx).apply_fiscal_mapping(result, **kwargs)

```

**Antigo**

```
    @api.onchange('fiscal_category_id', 'fiscal_position')
    def onchange_fiscal(self):

        result = {'value': {'fiscal_position': False}}

        if self.partner_id and self.company_id:
            kwargs = {
                'company_id': self.company_id.id,
                'partner_id': self.partner_id.id,
                'partner_invoice_id': self.partner_id.id,
                'fiscal_category_id': self.fiscal_category_id.id,
                'partner_shipping_id': self.dest_address_id.id,
            }
            result = self._fiscal_position_map(result, **kwargs)

        self.fiscal_position = result['value'].get('fiscal_position')
```

**Novo**

```
   @api.onchange('fiscal_category_id')
    def onchange_fiscal(self):
        """Método chamado ao mudar a categoria fiscal
        para refinir a posição fiscal de acordo com as
        regras de posição fiscal"""
        if self.company_id and self.partner_id and self.fiscal_category_id:
            result = {'value': {'fiscal_position': False}}
            kwargs = {
                'partner_id': self.partner_id.id,
                'partner_invoice_id': self.partner_id.id,
                'fiscal_category_id': self.fiscal_category_id.id,
                'company_id': self.company_id.id,
                'context': self.env.context
            }
            result = self.env[
                'account.fiscal.position.rule'].apply_fiscal_mapping(
                    result, **kwargs)
            self.fiscal_position = result['value'].get('fiscal_position')
```

Obrigado
Vinicius

**Comment by mbcosta** [comment]
Ola @vafonso eu analisei e corrigi os problemas nos seguintes PRs:
- Vendas https://github.com/OCA/l10n-brazil/pull/410
- Notas Fiscais, apesar de você ter relatado que não existia problemas eu encontrei um erro que depende da forma de como é configurada a Posição Fiscal https://github.com/OCA/l10n-brazil/pull/409 
- Compras https://github.com/OCA/l10n-brazil/pull/411

Obrigado pelos testes e por ter reportado os erros, também agradeço se você puder fazer a revisão desses PRs, isso pode agilizar o processo de aprovação dessas correções

**Comment by mbcosta** [comment]
@vafonso as correções foram integradas na branch 8.0, por isso vou pedir para os PSCs encerrarem esse issue , caso ainda encontre algum problemas por favor nos avise 
cc @renatonlima @rvalyi
