### ISSUE TITLE
Integrações que faltam da KMEE->OCA, antes de iniciarmos a versão 9/10

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#424]
- [x] 1. Reserva do numero da nota fiscal para o casos de uso: A nota fiscal foi transmitida e rejeitada, ao voltar a nf para provisório e transmitir novamente ao mesmo número é mantido; https://github.com/OCA/l10n-brazil/pull/430
- [x] 2. Reserva do numero da nota fiscal para o casos de uso: Permite a reserva do numero da fatura, ao faturar baseado na entrega. Para tanto ao criar ao confirmar o picking o numero da fatura já é reservado e salvo no picking, permitindo a impressão de etiquetas com número da nf-e no momento da separação. https://github.com/OCA/l10n-brazil/pull/430
- [x] 3. Melhorias nas pesquisas pesquisa por CNPJ/IE/Razão social no picking https://github.com/OCA/l10n-brazil/pull/429
- [x] 4. Recursos Humanos: l10n_br_hr https://github.com/OCA/l10n-brazil/pull/425
- [ ] 5. Recursos Humanos: l10n_br_hr_contract
- [ ] 6. Recursos Humanos: l10n_br_hr_payroll
- [ ] 7. Recursos Humanos: l10n_br_hr_payroll_account 
- [ ] 8. Recursos Humanos: l10n_br_timesheet_invoice https://github.com/OCA/l10n-brazil/pull/246
- [x] 9. Baixa bonificação: https://github.com/OCA/l10n-brazil/pull/337
- [x] 10. Bug, categoria fiscal e posição fiscal não copiadas para o picking: https://github.com/OCA/l10n-brazil/pull/341 @lfdivino 
- [ ] 11. Testes em python para o modulo l10n_br_sale_stock: https://github.com/OCA/l10n-brazil/pull/342 @lfdivino 
- [ ] 12. Bug: Data das faturas: https://github.com/OCA/l10n-brazil/pull/203
- [x] 13. Revisar o PR: https://github.com/OCA/l10n-brazil/pull/272
- [x] 14. Corrigir o PR: https://github.com/OCA/account-fiscal-rule/pull/50
- [ ] 15. Verificar se isto já não foi corrigido: https://github.com/OCA/l10n-brazil/pull/277
- [x] 16. GNRE: Rebase https://github.com/OCA/l10n-brazil/pull/286
- [ ] 17. l10n_br_pos: https://github.com/OCA/l10n-brazil/pull/308
- [ ] 18. md5sum p/ nome da categoria fiscal @renatonlima, estou aguardando o comando no shell: https://github.com/OCA/l10n-brazil/pull/384
- [ ] 19. Correção do campo origem na posição fiscal
- [x] 20. Dados da FCI no Danfe https://github.com/OCA/l10n-brazil/pull/428
- [ ] 21. Correção dos lançamentos contábeis da fatura https://github.com/OCA/l10n-brazil/pull/432
- [ ] 22. Correções referentes ao Frete https://github.com/kmee/l10n-brazil/commit/acdd1cf1453f5ad635f4923587e8db457a917e0f e outros commits

**Comment by mileo** [comment]
@sadamo @lfdivino @wagnerpereirasp

**Comment by rvalyi** [comment]
@mileo, nao acho interessante tentar integrar tudo isso antes de fazer as migracoes de 9 ou 10 ou digamos que e um pouco tarde para de repente querer incluir tudo isso antes de migrar. Tem alguns desses items que se vc refizer o PR na 9 ou na 10 depois vai dar na mesma (por examplo a integracao do modulo l10n_br_hr_payroll que nao existe hoje no repo). A unica diferenca e que nao ira atrasar a migracao. Portanto, acho interessante voces focar nos items dessa lista que tem impact nos modulos ja existente, de forma strutual e principalmente se a mudanca e importante e precisa de varios commits. Fora isso, outros PR em paralelo na 9 ou 10 e cherry-pick deveria resolver sem atrasar demais. Realmente os PR's de IBT, NT e separacao das visoes fazem muita diferenca na migracao do existente, so por isso pretendemos inclui-los antes de migrar.

**Comment by mileo** [comment]
Tem vários bugs na lista é muito importante inclui-los antes de fechar a versão v8. Mas concordo contigo que nem todos eles são essenciais.

Veremos oq que podemos fazer até sexta-feira.

Na minha opinião a alteração das visões impacta muito o fluxo dos usuários da versão 8. E deveria ser feita somente na v9. 

Mas como vcs precisam do merge para um de seus clientes, vamos **digerir** a alteração e seria ótimo que vocês analisassem as alterações que fizemos, pois os PRs estão abertos antes desses.

**Comment by mileo** [comment]
Completo, visto que vai demorar uns dias para fecharmos a versão v10. E mais ainda a migração dos clientes vai ser muito mais facil se estas mudanças estejam integradas na v8.

**Comment by rvalyi** [comment]
@mileo pode mandar os PR's. Alias sao poucos PR's que voces mandaram na 8 onde nao demos retorno. Agora isso tb nao depende apenas da gente, quanto mais gente revisar melhor as chances de incluir os PR's, espero que vc pude deixar isso bem claro para os potentiais contribuidores na PyCon...

**Comment by mileo** [comment]
@danimaribeiro vc pode fazer a mesma coisa referente as suas mudanças? Vai conseguir vir para reunião na segunda?

**Comment by rvalyi** [comment]
Para mim, de accordo com os criterios que eu listei, de importante e urgente ou facil nessa lista tem:

[ ]  3. Melhorias nas pesquisas pesquisa por CNPJ/IE/Razão social no picking
[ ]  8. Baixa bonificação: #337 (apesar que talvez iria mudar muito nas v9/10 de forma que nao seja pertinente atrasar a migracao por causa desse PR.)
[ ]  11. Bug: Data das faturas: #203
[ ]  15. GNRE: Rebase #286
[ ]  18. Correção do campo origem na posição fiscal
[ ]  19. Dados da FCI no Danfe #428
[ ]  20. Correção dos lançamentos contábeis da fatura

1 e 2 sao legais tb, mas tb se nao tiver ja pronto da para fazer um cherry pick na 8.0 e 9.0/10.0.

agora realmente a addicao de modulos como de RH ou POS e muito bem vinda mas tem que ser feita em paralelo como em todos projetos da OCA e nao ficar atrasando a migracao do que ja pode ser migrado.

**Comment by mileo** [comment]
Pessoal, verifiquei que nosso código referente ao frete esta bem diferente. Lembro que no passado refatorei colocando o código no button reset taxes, mas deu alguns bugs e ai eu voltei para o motor de impostos.

Acho q tenho uns testes em yml aqui referentes ao frete que não estão integrados, mas acredito que eles não sejam capazes de simular o erro. Poderiam realizar testes manuais

**Comment by mileo** [comment]
ping @danimaribeiro @Mackilem

**Comment by sadamo** [comment]
@mileo 
Era esse o bug que estava dando?
https://github.com/OCA/l10n-brazil/pull/459

**Comment by sadamo** [comment]
@mileo 
Era esse o bug que estava dando no frete?
https://github.com/OCA/l10n-brazil/pull/459
