### ISSUE TITLE
Alteração do campo cnpj do contator para um campo relacionar com res.partner do tipo supplier

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#426]
@leorochael

**Comment by renatonlima** [comment]
@mileo @leorochael

Seria legal o campo também não ser obrigatório, porque a obrigatoriedade deste campo depende da legislação de cada estado, então tem estados que é obrigatório e outros não (só para complicar nossa vida). Se eu não me engano a validação da NFe faz consistência disso.
