### ISSUE TITLE
Erro no label do ibtp_update_days

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#427]
https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account/models/res_company.py#L45

found by @leorochael

**Comment by renatonlima** [comment]
Maybe this should be resolved before it is closed. This problem is very simple to solve and still exists in v10.0 https://github.com/OCA/l10n-brazil/blob/10.0/l10n_br_account/models/res_company.py#L69 (In version 12.0 I already solved)

**Comment by hendrixcosta** [comment]
@renatonlima 
Onde eu acho esse label na v12?
na branch 12.0 não foi migrado ainda. Nesse PR https://github.com/akretion/l10n-brazil/blob/12.0-mig-l10n_br_account_product/l10n_br_account/models/res_company.py#L68 também não esta...
Ou diz o label que tem que ser e eu commito aqui se precisar.
