### ISSUE TITLE
Modulo de estrutura de dados de Boleto e CNAB

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#434]
Ola,

CNAB's e Boletos involvem parsing e serializacao/impressao. Tem varias bibliotecas fazendo isso, algumas mantidas, algumas em Python 2.x, outras nao. Enfim, e um pouco o mesmo tipo de problema do que a serializacao/transmissao das NFe's. Na falta de biblioteca totalmente maduras e bem mantida em Python, planejamos adotar a mesma estrategia de estar agnostico no core l10n-brazil e deixar repos satelites para as diversas technologias de parsing/serializacao no objetivo de favorescer solucoes sempre melhores. A medida que esses repos satelites amadurescem eles poderiam ser incluidos na OCA aos poucos na medida que isso nao tira o foco da OCA de acertar o core primeiro.

Mas mesmo assim e interessante teremos um denominador comum no l10n-brazil quando se trata da estrutura de dados persistente de CNAB's e Boletos.

A medida que o projeto amaduresce e que podemos aumentar o scope da OCA, seria interessante considerar a inclusao nesse repo das abstracoes basicas, e talvez fazer a inclusao dos modulos:
- https://github.com/odoo-brazil/odoo-brazil-banking/tree/8.0/l10n_br_account_payment_boleto
- e https://github.com/odoo-brazil/odoo-brazil-banking/tree/8.0/l10n_br_account_banking_payment_cnab

Isso pode ser feito em paralelo da migracao e pode nao ser pertinente a inclusao na branch 8.0 OCA se tiver que mudar demais nas branches 9 ou 10 (eu acho que isso muda muito a partir da 9.0).

cc @renatonlima @mileo

**Comment by mileo** [comment]
Acho isso super interessante, inclusive na PyCon conheci o criador da cnab240 e me liberou o acesso e acabei incluindo o @danimaribeiro e o @renatonlima como commiters(PSC ^^). 

O @danimaribeiro estava citando que o cnab 240 foi recentemente determinado como o layout padrão da febraban e o boleto registrado já tem seu fim declarado para final deste ano!

Então ao meu ver vale a pena colocar esses módulos no core.

**Comment by rvalyi** [comment]
e bom essa lib cnab240 e um outro tipo de pysped ainda... Mas se podemos ja incluir a estrutura de dados seria um bom primeiro passo.

**Comment by mileo** [comment]
Discordo, ela não tem nenhuma dependência e pode ser instalada com pip (apesar de desatualizada)

Da mesma forma que o os scripts da OCA, instalam pacotes do git via pip, tb podemos fazer isso. (https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L12)

**Comment by rvalyi** [comment]
@mileo, sim mas a manutencao dele nao ta das melhores tb, se vc comparar com solucoes vivas como
- https://github.com/kivanio/brcobranca/pulls?utf8=%E2%9C%93&q=
- https://github.com/kivanio/brcobranca/graphs/contributors

Mas enfim, podera ser incluido sim na OCA, num repo especifico (tipo esse do banking) a medida que a gente tem tranquilidade nas partes mais centrais.,.. Me lembro tb muito bem de 2 anos atras de um papo de gente falando que o pysped era o pico das galaxias e que hoje ta ate fazendo uma outra lib de tanto que a gente tava certo em alertar que nao era aquilo tudo nao...

Ou seja a gente prefere hoje que um cara que contribue na OCA ajuda tipo a migrar na 10 ou consolidar a NFe do que gastar tempo batendo a cabeca em re-transcodar algum mapping que ja existe e bem mantido em outro lugar; na medida do possivel claro.

**Comment by mileo** [comment]
O Pysped é bom, não é excelente..... Hoje sabemos dar manutenção nele. E devem ter uns quase 10 mil notas emitidas com ele com Odoo. 

Não vejo o pq não integrá-lo ao Odoo, a medida que forem surgindo soluções melhores feitas por nós ou por outros, alteramos a estrutura, fazemos que seja possível integrações com outras libs.

Mas até lá precisamos fomentar a entrada de outros interessados, com ferramentas uteis e não com entraves.

Br cobrança é feito em ruby e infelizmente não é minha área, mas fique a vontade de integrá-lo e usar o factory que eu fiz para o boleto, vai ser um prazer revisar sua contribuição.

**Comment by danimaribeiro** [comment]
O cnab240 é uma lib bem escrita e de fácil manutenção e adição de novas carteiras.

A minha opinião é de se utilizar e já deixar a exportação para cnab de alguns dos principais bancos prontos dentro da localização, no formato 240 que é o que a febraban recomenda.

Fica mais fácil de dar manutenção se os esforços forem concentrados na localização do que em repositórios separados.

**Comment by rvalyi** [comment]
@danimaribeiro mais ou menos: tipo hoje tem alguns modulos funcionais na 9 e ate na 10 mas nao fizemos a branch oficialmente porque tudo ta junto, vai ter que revisar os PR's de POS 2 vezes porque serao integrados depois do re-fork da v9/v10... Alem do mais tem questoes de lideranca de projetos: pode ser que seja vc que tenha mais competencia para administrar o repo de NFSe mas que seja o renato que tenha mais legitimidade para o repo do core onde vc fez poucas contribs (e sendo que nem sempre concordamos para tudo e que em ultimo caso o principal autor de um repo tem que decidir, assim como se faz em qualquer projeto open source), esse tipo de coisa.

A tendencia realmente e de ter um repo por modulo, trabalhamos bastante nisso na OCA, com essa coisa de empacotamento com pip por examplo. Agora como primeira aproximacao vamos ter ALGUNS repos, sendo que alguns vao competir ate que o melhor ganha claramente ou de forma que um integrador fica livre de escolher. Por exemplo durante 2016 vamos exportar com pysped. Mas graca a essa arquitetura modular que desenhamos, talvez durante 2017 a gente faz a transicao para uma outra lib, quem sabe talvez aquela que vc ta fazendo.

Novamente, nao estamos contra usar o pyCNAB na OCA em um certo prazo. Porem, se vc olhar, hoje a comunidade nao da conta do core. a 9.0 saiu ha mais de 18 meses e tem varios PR's que nao receberam review suficente, tem varios engarafamentos so na base de codigo que tem hoje,. Porem mesmo assim ja um dos 3 maiores repos da OCA, com certeza o maior projeto da OCA se a gente leva em consideracao a quantidade de codigo ainda nao integrado na OCA... Entao vamos com calma e conforme a gente anda bem nas coisas centrais vamos extender na OCA com certeza, essa e a logica.

**Comment by rvalyi** [comment]
@mileo essas questoes da linguagem tem que relativisar. Libreoffice nao e escrito em Python mas Aeroo ou py3o usam. wkhtmltopdf nao e escrito em Python mais usamos. Na Franca o povo usa varias ferramentas para as obrigacoes tipo SPED que nao estao escritas em Python. A partir do momento que tem uma lib madura numa linguagem (que nao seja PHP num fode), da para considerar, ou pelo menos deixar quem quer ser preguicoso usar.

Nao vou te obrigar a usar uma lib em Ruby na Kmee, mas tb faco questao que vc nao me obriga dilapidar recursos da OCA para manter com 3 gatos pingados uma lib que ja e madura numa linguagem que dominamos. Enfim a palavra chave e permitir liberdade apenas. Do restante o processo de construcao da OCA e iterativo, assim como o proprio core da Odoo. Os primeiros connectores Magento eram zoados, hoje o framework connector e top... A localizacao da 7 ainda era ruizinha, mas talvez o core seja top na 10. Vai ser a mesma coisa com essas lib. Boleto e CNAB passando para v9 tem muita coisa para rever, ate porque o proprio core do Odoo amadureceu muito nessa gestao dos pagamentos. Ate por isso nao tem agonia de integrar isso ja ja na 8,0... Entao logo veremos mas vamos comecar com o repo da transmissao de NFe que isso e bem mais urgente melhorar a qualidade.

**Comment by mileo** [comment]
Bacana que vc concorda. Tb acho que a prioridade é a NF-e e NFS-e. A lib do cnab é bem simples de manter, tem jsons para vários bancos.

Poderia ser mais pythonica, mas como o próprio autor disse, foi "meu primeiro modulo python". Podemos refatorá-la, o importante é que os jsons já estão validados e testados em produção faz muito tempo por muitas empresas, com é o caso do pysped.

E vamos seguindo.

**Comment by renatonlima** [comment]
Olá @mileo 

No caso o Pycnab é bem diferente mesmo do pysped, o pycnab veio de pessoas que fazem parte da comunidade python no brasil, tem mais pessoas trabalhando nela, é mais simples de mante-la porque não é tão complexa, tem um pouco de testes é mais pytonica (facil de manter), então eu vejo um bom potencial.

Eu ainda não revisei os trabalhos no repo https://github.com/odoo-brazil/odoo-brazil-banking, mas seria muito bom pensar na experiencia que tivemos com os módulos nfe e pensar em que possamos ter um módulo odoo l10n_br_boleto que implementar a parte comum de controle e geração dos boletos, campos, objetos e visões, e criar uma interface para ter um modulo l10n_br_boleto_pycnab.

Com isso usando o mesmo conceito que expliquei sobre os módulos nfe, poderíamos ter um módulo l10n_br_boleto_brcobranca e usar outros tipos de serviços para envio de boletos.

Nós não precisamos ficar pensando em outras soluções, podemos trabalhar com o pycnab, mas seria bom arquiteturar desta forma pela experiência que tivemos com o pysped.

cc @fernandomr

**Comment by mbello** [comment]
@mileo @renatonlima @rvalyi @danimaribeiro 
A funcionalidade de NFe é bem mais básica e necessária praticamente a toda empresa, o que não é o caso de boleto e CNAB, empresas pequenas podem tranquilamente trabalhar com os sistemas dos bancos e fazer conciliação bancária de forma manual.

Sendo assim, uma empresa que vá realmente se beneficiar do que o pyCNAB tem a oferecer, tem um volume de transações suficientemente grande que justificaria utilizar uma solução mais profissional para resolver as questões relacionadas ao módulo de banking.

Por melhor que seja o trabalho no pyCNAB, não teremos uma solução decente para oferecer às maiores empresas usuárias do Odoo. Teremos dedicado um bom tempo nessas tarefas e, ainda assim, com resultado pouco satisfatório.

Infelizmente, quando se trata de interface com bancos a gente rapidamente encontra um problema: o envio e o recebimento dos arquivos precisa ser feito de forma manual pelo usuário e isso por si só é uma grande fonte de dor de cabeça para as empresas.

Arquivos deixam de ser enviados, deixam de ser baixados, retornos de erro/ problemas de validação podem deixar de ser tratados, não há qualquer controle do histórico de transações com esses arquivos, é impossível para o ERP saber se algum arquivo deixou de ser carregado ou enviado, etc...

Ler e gerar o CNAB240 para um único banco é moleza, para diversos bancos é um trabalho um pouco maior, mas não é impossível. O grande problema é tratar todas as questões relacionadas ao fato de que sempre existirá um processo manual no meio do caminho entre o ERP e o banco, e não dá para assumir que o usuário vai fazer tudo certinho pois com processos do financeiro não dá pra brincar.

Com o fim do boleto sem registro, essa "ponte manual" entre o ERP e o banco vai se tornar um entrave ainda maior, baixa de boletos, alteração de vencimento, baixa de protesto, todas essas operações precisarão gerar registros que devem chegar até o banco e muitas dessa operações tem prazo para serem concluídas, nada disso é compatível com ter que contar que o usuário vá enviar e receber todos os arquivos da forma correta, no tempo correto. Além disso, esse número enorme de operações terá que ser suportado pelo pyCNAB, e aquele trabalho de ler e gerar CNAB240 para cada banco vai ficando mais complicado.

Por fim, alguns grandes bancos oferecem atualização intraday, agora que o TED eliminou o DOC quase que totalmente, essas atualizações intraday passaram a ser muito importantes, seus clientes vão querer trabalhar na velocidade da TED mas nós estaremos ainda na velocidade do DOC pois com a necessidade de importar e exportar arquivos manualmente, nossa solução ficará muito longe de trabalhar em tempo real.

Senhores, o EDI Financeiro da NeoGrid custa R$ 165 por mês e o Interbancos da eSales custa R$ 450,00 por mês. Ambas são bastante baratas comparado ao custo com pessoal de não ter automatização desses processos, qualquer cliente de vocês que realmente precise desse tipo de solução vai saber que não é caro. Ambas "traduzem" os formatos de cada banco para um padrão único, que será a única coisa que o Odoo terá que entender.

Optando por uma dessas soluções (eu tenho a proposta e detalhes das duas, quem quiser "pm me"), já teremos trabalho suficiente criando as interfaces no Odoo para cobrir todas as inúmeras operações, especialmente com boletos, que tal utilizarmos o pouco tempo de devs que temos na localização para fazer isso e deixar os detalhes "under the hood" com uma solução paga como as que mencionei acima?

**Comment by mbello** [comment]
Aproveitando para lembrar que boleto e NFe se relacionam, os clientes costumam exigir que no boleto conste o número da NFe e na NFe muitos clientes exigem que as tags sejam preenchidas corretamente. 

Um dos meus clientes tem essa exigência:
_Informar os dados da(s) duplicata(s) nos campos (tags) corretos da NFe e NÃO no quadro dos Dados Adicionais:
    No campo "nDup" informar o número da duplicata.
    No campo "dVenc" informar o vencimento da duplicata.
    No campo "vDup" informar o valor da duplicata.

```
A NF-e permite informar n duplicatas._
```

**Comment by marcos-mendez** [comment]
Eu tenho algumas coisas aqui

BRADESCO MODELO
[4008-524-0121-layout-cobranca-versao-portugues.pdf](https://github.com/OCA/l10n-brazil/files/2074609/4008-524-0121-layout-cobranca-versao-portugues.pdf)

SANTANDER MODELO
[262164752-Layout-Cobranca-400-102014-SANTANDER.pdf](https://github.com/OCA/l10n-brazil/files/2074611/262164752-Layout-Cobranca-400-102014-SANTANDER.pdf)

ITAU
[cobranca_cnab240.pdf](https://github.com/OCA/l10n-brazil/files/2074613/cobranca_cnab240.pdf)

São todos manuais atualizados, não sei como teria que fazer para integrar, ainda não tenho tanta experiência com o Odoo, porém eu consegui no Wordpress rsrs

**Comment by rvalyi** [comment]
Ola @marcos-mendez. Existem varias iniciativas, algumas que funcionam com Python 2, outras com Python 3. Mas ate onde eu sei poucas iniciativas sao faceis de se manter. Inclusive o que roda no Python 2, dificilmente vai rodar no Python 3.

Enfim na Akretion (co-fondador da OCA e do projeto de localizaçao no Brasil desde 2009), avisamos que iriamos lidar com isso botando a lib brcobrança (do boletosimples) dentro de um micro-service e consumindo lo a partir do Odoo. E foi que nos fizemos aqui ja faz alguns meses:
https://github.com/akretion/odoo-boleto-cnab
ver isso tb:
https://github.com/akretion/boleto_cnab_api

A principio, isso vai suportar todos boletos e CNAB do brcobranca aqui https://github.com/kivanio/brcobranca
Nos ja estamos usando Itau e Bradesco em produçao.

Isso foi implantado na v8 em cima do codigo da OCA. Mas qualquer ajuda para migrar os modulos de acordo com os guidelines da OCA https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md esta bem vinda.

Caso ninguem contribui-lo antes, eh provavel que a Akretion ira migrar esses modulos para a v10 ate setembro e para a v12 la para dezembro (temos pouco interesse na v11, mas poderia ser feito um backport da v12 facilemente).
Se for preciso, a Akretion tb vende serviços de consultoria e desenvolvimentos. Atts.

**Comment by rvalyi** [comment]
Bom entao isso foi implementado com os modulos:
https://github.com/OCA/l10n-brazil/tree/8.0/l10n_br_account_payment_boleto
https://github.com/OCA/l10n-brazil/tree/8.0/l10n_br_account_payment_mode
e o modulo CNAB que ainda falta extrair:
https://github.com/odoo-brazil/odoo-brazil-banking/tree/10.0/l10n_br_account_banking_payment_cnab
