### ISSUE TITLE
Aumentar o coverage dos arquivos

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#450]
![captura de tela de 2016-10-26 10-42-52](https://cloud.githubusercontent.com/assets/1975978/19726301/f91e3d50-9b68-11e6-8f56-08995c4079a0.png)

**Comment by rvalyi** [comment]
:+1:  sim. Tb tirando a rotina de export de nfe em txt agora obsoleta isso vai melhorar. Mas tb olha, e ai que a gente queria te passar um "dever de casa" porque na nossa opinao, e mais urgente botar testes no pysped e no electronic-doc hoje do que aqui... Mesmo se melhorias serao bem vindas tb.
