### ISSUE TITLE
[BUG] Escolher CFOP e/ou impostos diferentes na linha da fatura

### ISSUE THREAD

**Issue by mstuttgart** [OCA/l10n-brazil#451]
Para selecionar uma CFOP e/ou Imposto diferente na linha da fatura é necessário salvar a fatura primeiro e depois editá-la. Se o usuário criar a fatura, adicionar um produto e selecionar uma CFOP (ou impostos) diferentes, ao salvar a fatura, os valores de CFOP e Impostos inseridos são sobrescritos pelos respectivos campos trazidos da posição fiscal.
#### Como reproduzir:
- Base localização OCA branch 8.0 com dados demo. 
- commit (atualizado 26/10/2016) 144126de3a195b4aa053f18eecb7786cc732c979
- Instalar l10n_br_account_product e criar uma invoice
- Na invoice, inserir um produto e selecionar uma CFOP e/ou imposto (PIS, IPI e etc) diferente da trazida pela posição fiscal.
- Salvar a Invoice.
- Após ser salva a CFOP e/ou imposto (PIS, IPI e etc) selecionada anteriormente é substituída pela sua respectivo campo trazido da posição fiscal ou do cadastro do produto. Para alterá-la é necessário **salvar** o cadastro **primeiro** para somente depois editar a linha de fatura e selecionar uma CFOP  e/ou imposto (PIS, IPI e etc) diferente.

**Comment by aricaldeira** [comment]
Renato, só um detalhe: manter a CFOP isolado da configuração original na linha da fatura/item da NF permite que se mantenha o registro histórico, caso a configuração do produto mude ao longo do tempo.

Um exemplo disso é o NCM de produtos derivados de batatas (tipo Pringles); a partir de outubro houve alteração no PIS-COFINS e no ICMS;

Se um produto estava obrigado a ICMS ST, na venda, deveria sair com CFOP 5405, mas, nos estados em que o protocolo não tenha efeito, ou caso o produto saia do protocolo, a CFOP deveria passar a ser 5102;

Pelo que entedi, se isso acontecer e não se salvar a CFOP na linha da fatura, uma mudança na legislação alteraria todas as notas já emitidas sob a legislação vigente anterior, o que não pode acontecer.

Manter a CFOP separada na linha da fatura permite também que, se necessário, pode ser possível fazer uma nota que fuja completamente a configuração já estabelecida, mas que é necessária para o momento;

Um exemplo disso é uma fiscalização, em que o fiscal exige que se emita uma NF com os dados X ou Y para registrar a fiscalização; faz tempo que não vejo isso acontecer, mas acontece.

Outro exemplo são as notas de aproveitamento de crédito de ICMS ou PIS-COFINS, em que o contador orienta a cada vez os códigos corretos da CFOP etc. etc., e muitas vezes são diferentes conforme a situação do crédito.
