### ISSUE TITLE
Calculo da base dos impostos nas operações de Importação

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#457]
Hoje para fazer com que os impostos nas operações de importação seja calculados de forma correta é necessário que alterar o calculo das bases dos impostos, abaixo segue um explicação sobre como funciona estes calculos:

VMLE: Valor da Mercadoria no Local de Embarque. É o valor da mercadoria e outras despesas anteriores ao embarque. Também conhecido como valor FOB.

VMLD: Valor da Mercadoria no Local de Descarga. É o valor do VMLE acrescido do frete e do seguro. Também conhecido como valor CIF.

Isso significa dizer que, se uma mercadoria sai do exterior, o seu valor é o VMLE, ou valor FOB. No momento que ela chega em território nacional, seu valor é o VMLD, ou valor CIF. Vamos supor que uma determinada mercadoria custou $2,00 a unidade. Foram importadas 2000 unidades e a taxa de câmbio fechou em 2.50 R$ / $. Isso significa que o VMLE foi de $4000,00, ou $4000,00 x 2,50R$ / $ = R$10.000,00.

Vamos supor agora que o Frete + Seguro dessa mercadoria custou $1.000,00, ou convertendo para real, R$ 2.500,00. O VMLD dessa mercadoria é R$ 10.000,00 + R$ 2.500,00 = R$ 12.500,00. A partir daí temos a base para calcular os outros impostos.

**1) Imposto de Importação**

Base de cálculo: VMLD ou valor CIF

No nosso exemplo, vamos supor que o imposto de importação possui uma taxa de 20%. Logo, 20% de R$ 12.500,00 = R$ 2.500,00.

**2) IPI**

Base de Cálculo: Valor CIF + II

Em nosso exemplo, R$ 12.500,00 (CIF) + R$ 2.500,00 (II) = R$ 15.000,00.

Vamos supor que o IPI possui taxa de 10%. Logo, o valor do IPI seria 10% de R$ 15.000,00, ou seja, R$ 1.500,00.

**3) PIS e COFINS**

Base de Cálculo: Valor CIF

Vale lembrar que desde 08/10/2014 a base de cálculo do PIS e COFINS passou a ser apenas o valor aduaneiro, excluindo assim o ICMS, bem como as próprias alíquotas de PIS e COFINS. 

Para efeito de exemplo, vamos supor que a alíquota do PIS é de 2% e a do COFINS é de 10%, totalizando 12%. Sendo assim, nossa base de cálculo seria:

Base de Cálculo do PIS e COFINS: R$ 12.500,00 (CIF)

Valor do PIS: 2% de R$ 12.500,00 = R$ 250,00

Valor do COFINS: 10% de R$ 12.500,00 = R$ 1250,00

PIS + COFINS = R$ 1.500,00

**4) ICMS**

Finalmente, chegamos ao ICMS. Sua base de cálculo é calculada da seguinte forma:

Base de Cálculo: Valor CIF + II + IPI + PIS + COFINS + TX SISCOMEX + ICMS

Repare que o ICMS compõe sua própria Base de Cálculo. Por isso, devemos calcular de forma diferente.

Ora, para calcular a base de cálculo do ICMS precisamos do valor do próprio ICMS. Mas para calcular o valor do imposto precisamos da sua base de cálculo. Como resolver?

Em nosso exemplo, vamos suporte que a Taxa do Siscomex seja R$ 500,00. Para resolver esse problema vamos recorrer a matemática financeira. Para isso vamos fazer:

Base de Cálculo: Valor CIF + II + IPI + PIS + COFINS + TX SISCOMEX + ICMS

Base de Cálculo: R$ 12.5000 (CIF) + R$ 2.500,00 (II) + R$ 1.500,00 (IPI) + R$ 250,00 (PIS) + R$ 1.250,00 (COFINS)

Sendo assim:

Base de Cálculo = R$ 18.000,00 (CIF + II + IPI + PIS + COFINS) + R$ 500,00 (Siscomex) + ICMS

Base de Cálculo = R$ 18.500,00 + ICMS.

Suponha que, nesse exemplo, o ICMS seja de 16%. Então, para calcular sua base de cálculo, fazemos:

Base de Cálculo = R$ 18.500,00 / (100% - 16%)

Base de Cálculo = R$ 18.500,00 / (84%)

Base de Cálculo = R$ 18.500,00 / (0,84)

Base de Cálculo = R$ 22.023,81

Repare que 16% de R$ 22.023,81 = 3.523,81. Ou seja,

Base de Cálculo = R$ 18.500,00 + ICMS

Base de Cálculo = R$ 18.500,00 + R$ 3.523,81

Base de Cálculo = R$ 22.023,81

Logo, o ICMS é R$ 3.523,81 e sua base de cálculo é R$ 22.023,81.

É bom lembrar que muitas vezes existem taxas aduaneiras que são incluídas na base de cálculo do ICMS, juntamente com a taxa do SISCOMEX. Sempre peça para seu despachante detalhar na DI todas as taxas que são utilizadas na base de cálculo do ICMS, pois elas alteram o valor final da nota fiscal.

**Comment by edusferreira** [comment]
Fonte: https://blog.maino.com.br/calcular-nfe-de-importacao-como-seu-despachante/
