### ISSUE TITLE
Categoria e Posição fiscal no Rembolso de Clientes

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#46]
Ao criar um reembolso de clientes a partir de Ordem de entrega. A Regra de posição fiscal é aplicada somente no cabeçalho e não nos itens

**Comment by rvalyi** [comment]
ola Luis,

por iser tem algumas coisas para acertar nos refunds. Seria bom tb se alguem puder atualizar a proposta de merge do Florian para a gente fazer o merge no develop, apesar que acho que nao resolve essa exactamente: https://github.com/openerpbrasil/l10n_br_core/commit/1a40130a958144108f7a49bcbb7a861280bd10e9

**Comment by mileo** [comment]
Eu dei uma lida no código do Florian,  conforme for já faço o merge dele. 

Vou dar prioridade em resolver esse bug totalmente na develop. 

[]s

**Comment by renatonlima** [comment]
@mileo 

Na verdade a melhor maneira de fazer isso é criar na stock.move os campos de categoria fiscal e posição fiscal para ser replicado no momento da criação da nota fiscal, esta mudança também permitirá que ao fazer uma nota fiscal a partir da picking list com multiplos CFOPs por linhas, pois se você tiver uma linha de venda e outra de revenda, os CFOPs de devolução devem ser diferentes

@rvalyi 

O merge do Florian apenas implementa o campo de categoria fiscal no wizard de refund na invoice, o problema relatado pelo Luis esta no picking, O merge do Florian é interessante também ser integrado na branch develop (precisa de alguns refactorings) mas não tem utilidade neste caso, ja que a nota fiscal é feita através de um picking e outro wizard é utilizado.

**Comment by mileo** [comment]
@renatonlima 

Ontem estava debugando pensei em implementar no stock_invoice_onshiping, mas sem os campos nos stock.move(s). De forma que a posição fiscal stock.move viria do stock.picking.in.

Resolvendo o problema parcialmente, do jeito que vc falou é melhor. Vou implementar na develop.

[]s

**Comment by renatonlima** [comment]
Este recurso já foi implementado pelo pull request #48
