### ISSUE TITLE
Delete v9 branch

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#476]
Como a localização brasileira não vai passar pela v9. 

Acordou-se que a branch v9 não sera necessária.

cc: @renatonlima @leorochael @wagnerpereirasp

**Comment by rvalyi** [comment]
:-1: nao acho legal. Tem modulos usaveis na v9 depois de proceder os merges depois de recriar a branch assim que era planejado https://github.com/OCA/l10n-brazil/issues/416. Pode ter alguma empresa que ta na 9 e vai usar alguns modulos (temos uns clientes por examplo com esses PR's). Pode ter uma empresa gringa que usa a v9 e vai usar so alguns modulos da localizacao. Tem varias localizacoes na OCA onde a branch 9 nao e muito completa, e bem comum isso nao vejo problema em deixar essa branch para quem quer usar, assim com tem da 6 ou da 7. A gente nao obriga ninguem a usar e a branch 10 sera facil de achar mesmo.

**Comment by rvalyi** [comment]
E tem outro motivo de deixar uma branch 9: podem ter empresas que nao vao conseguir migrar direitamente da v8 para a v10, por exemplo porque algum modulo, sei la de MRP nao vai estar disponivel na v10. Entao dependente de quantas coisas da localizacao usa, uma empresa dessa poderia migrar da 8 para a v9 e talvez so depois migrar para v10.

**Comment by leorochael** [comment]
@rvalyi, Você conhece alguma empresa que:

 * Já está rodando em v9 hoje
 * **E** estava apenas esperando a localização brasileira ser portada para v9 para passar a usá-la com a v9?

Se você não conhece nenhuma empresa nesta situação, então é praticamente garantido que não vai haver nenhum tempo de desenvolvedor dedicado a manter a localização na v9, por mais supostamente fácil que seja manter a mesma base de código funcionando nas duas.

O fato de que o Odoo na v10 promoveu um purgo do nome "openerp" na base de código deles reduz drasticamente a quantidade de commits que poderiam ser aplicados "limpos" entre a v9 e a v10, o que aumenta muito o esforço de desenvolvimento necessário para manter os dois branches da localização sincronizados. 

O esforço de migração de qualquer empresa da v8 para v9 vai ser alto, tão alto quanto migrar de v8 para v10 diretamente, portanto não existe razão para alguém querer fazer duas migrações ao invés de pular diretamente da v8 pra v10 (a não ser que você possa mostrar evidências convincentes do contrário). Qualquer empresa que tenha tempo/dinheiro para investir em duas migrações vai preferir investir no porte de quaisquer módulos faltantes da v9 para v10 e depois investir em uma migração só.

Portanto, manter um branch v9 é um desserviço tanto para a comunidade brasileira do Odoo responsável por manter o código, quanto para potenciais utilisadores da plataforma, que poderiam se iludir de que há, ou vai haver em algum momento, suporte para rodar a localização brasileira na v9.

**Comment by rvalyi** [comment]
@leorochael sim temos um cliente grande em v9 usando o codigo dos PR's (esses modulos basicos) e talvez vamos extender um pouco o scope da localizacao antes de migrar.
Nao se pode desrespeitar o trabalho de quem ja adiantou a migracao para v9 ja um 1 ano atras. Se acha diferente tem que usar os canais do projeto para debater, nao querer impor algo sem nunca ter conversado do assunto nos canais do projeto. Valeu.

Quem migrou na v9 sem partir dos PR da 9 errou pois eles estavam la no projeto faz tempo. No minimo deveria ter perguntado como fazer se nao sabia. Agora quem quer pular a branch 9 agora errou tb porque nunca debateu sobre aqui no projeto.

Algumas das pessoas que tao fazendo pressaozinha para a migracao da v10, nunca ou quasi nunca ajudaram a revisar PR's no projeto. E muito facil nao fazer o trabalho e so chegar para reclamar mas nao e aceitavel. Algumas pessoas reclamam da lentidao mas alem de ter feito muito pouco no projeto queriam que a gente fosse botar ainda mais modulos na OCA. Veja o paradoxo: se tivesse ainda mais modulo nesse repo, e claro que seria ainda mais dificil esperar alguns refatores da 8 antes de recriar as branches 9 e 10... Essas pessoas tem que ter um minimo de coerencia antes de criticar...

**Comment by leorochael** [comment]
@rvalyi faço minhas as suas palavras: "tem que usar os canais do projeto para debater".

A decisão de não atrasar a migração pra v10 impondo um esforço desnecessário em manter compatibilidade com a v9 foi chegada por unanimidade em um hangout da comunidade com a presença de dois PSCs da localização brasileira.

Este issue criado pelo Mileo é apenas para documentar esta decisão.

Se você tem a necessidade de manter compatibilidade com a v9 para seus clientes, você tem toda liberdade de investir o tempo/esforço de desenvolvimento para fazê-lo (e vai da comunidade, através da decisão conjunta dos PSCs, decidir se eles vão querer incluir seu esforço ou não).

Mas até lá, manter um branch v9 dando a falsa ilusão de que vai haver o esforço de desenvolvimento necessário tanto para fazer o porte quanto para mantê-lo, é um desserviço a todas as partes envolvidas, como argumentei acima.

**Comment by rvalyi** [comment]
@leorochael eu nao sei ainda o que foi conversado ontem pois eu infelizmente nao tava disponivel. Sendo que hangout nao e canal oficial, nehnum outro projeto da OCA exige isso. Ajuda mas nao tem que ser usado para tomar decisoes importantes.

A questao e so de recriar a branch 10 a partir da v8 atualizada, passando pela 9. o merge dos PR's dos 2 modulos na v9 e trivial, pode ser feito no mesmo dia. Quem falou que tinha que proceder um montao de PR's da v8 colocado na ultima hora antes de fazer a migracao nao tem moral para negar um dia para fazer os 2 ou 3 merges dos PR's da 9, desclupa falar claramente assim.

Ai depois sim, ninguem quer esperar mais merges da v9 antes de tratar os PR da v10. Isso todos PSC do projeto concordamos. Mas refazer a branch da v10 a partir da v8 no minimo isso ai e muito importante para a tracabilidade e manutencao do projeto. Os 2 ou 3 PR's da 9 isso ai e um assunto de menos mas eu acho que e trivial de tratar.

**Comment by leorochael** [comment]
@rvalyi O assunto deste *issue* não é esperar ou não alguns PRs, antes de construir a v10. O assunto deste issue é: apagar o branch v9 para não dar a impressão de que ele será mantido.

Este *issue* nem mesmo especifica quando o branch será apagado, apenas documenta que ele será. Se ele precisa ficar vivo por mais alguns dias de forma a permitir que um processo mecânico de migração aconteça (processo este que precisa de um branch que, por acaso, se chama v9), isso não contradiz a decisão de que o branch v9 será, um dia, apagado.

E sim, o Hangout não é a oficialização da decisão, por isto esse *issue*, mas para reverter esta decisão será necessário mais do que simplesmente especular que alguma empresa, talvez, quem sabe, vai precisar da localização migrada pra v9. Vai ser necessário apresentar argumentos reais que convençam a comunidade, através dos PSCs, de reverter essa decisão.

**Comment by rvalyi** [comment]
@leorochael ta de boa eu acho entao. E que da a impressao que queriam usar a branch 10 sem re-criar la a partir da v8, o que seria chatinho. Sobre detonar a branch 9 depois eu realmente nao sei se e uma boa, mas entao acho que isso e um assunto de menos.

**Comment by mileo** [comment]
@renatonlima
