### ISSUE TITLE
Após a atualização a seguinte mensagem aparece ao tentar emitir NFE: Element 'pICMSInter': [facet 'enumeration'] The value '0.00' is not an element of the set {'4.00', '7.00', '12.00'}. Element 'pICMSInter': '0.00' is not a valid value of the local atomic type.

### ISSUE THREAD

**Issue by gglimass** [OCA/l10n-brazil#508]
Passos para reproduzir o problema:

Comportamento atual:

Comportamento esperado:

Videos/Screenshot link:

**Comment by mileo** [comment]
Vc está tentando fazer uma operação com difal.

Mas nas operações com difal o ICMS normal deve ser sempre. 7, 12 ou 4.

Por favor revize a parametrização tributária realizada
