### ISSUE TITLE
Nova cotação não puxando impostos.

### ISSUE THREAD

**Issue by gustavors01** [OCA/l10n-brazil#509]
Gostaria de relatar a seguinte situação:

1- Ao inserir um item em uma nova cotação não esta puxando os impostos, as posições fiscais estão configuradas, impostos na empresa tb, cliente ok, se eu gerar a fatura, puxa corretamente o CFOP, mas em nenhuma situação consigo puxar os impostos;

2- Em cotação, o campo descrição do produto esta puxando o nome do produto e não a descrição;

3- Em alguns momentos o no produto o TIPO FISCAL: Produto, desaparece, mas ainda não consegui entender exatamente quando que ele desaparece.

Segue em anexo minhas configuração.

Versões atualizadas ontem 01/01/2017.
Repositorios:
odoo/odoo 8.0;
oca/l10n-brazil 8.0;
oca/account-fiscal-rule 8.0;
odoo-brazil/odoo-brazil-electronic-documents 8.0;
oca/server-tools 8.0;
Todas atulizadas com os comandos "git pull origin 8.0" em cada folder, e após:
/opt/odoo/odoo.py -c /etc/odoo-server.conf --update=all --stop-after-init

OBS.: Não sou programador, mas posso ajudar com testes.

Desde já muito grato por qualquer ajuda.

![minha empresa fiscal](https://cloud.githubusercontent.com/assets/24878214/21592699/591a6f48-d0ee-11e6-948e-3fa730ee8b5e.gif)
![minha empresa documentos](https://cloud.githubusercontent.com/assets/24878214/21592698/591a590e-d0ee-11e6-80c2-f468b9d7b367.gif)
![minha empresa impostos](https://cloud.githubusercontent.com/assets/24878214/21592700/591aabfc-d0ee-11e6-87cb-3c6ed802f8e9.gif)
![minha empresa vendas](https://cloud.githubusercontent.com/assets/24878214/21592712/5948a5ac-d0ee-11e6-8727-6f25840696a6.gif)
![posicao fiscal impostos](https://cloud.githubusercontent.com/assets/24878214/21592702/591b76ae-d0ee-11e6-80c4-fb2cdfc2f2bf.gif)
![posicao fiscal fiscal](https://cloud.githubusercontent.com/assets/24878214/21592701/591b0ec6-d0ee-11e6-858a-ca50806d464d.gif)
![regra posicao fiscal 1](https://cloud.githubusercontent.com/assets/24878214/21592703/591c9fa2-d0ee-11e6-9bd3-d0e50319c633.gif)
![regra posicao fiscal 2](https://cloud.githubusercontent.com/assets/24878214/21592705/59311518-d0ee-11e6-8ba8-27e1904b995f.gif)
![cliente contabilidade](https://cloud.githubusercontent.com/assets/24878214/21592708/5934ceb0-d0ee-11e6-8072-3f9bcf8fbeec.gif)
![cliente outros](https://cloud.githubusercontent.com/assets/24878214/21592709/59359192-d0ee-11e6-9d8e-096dfb1aa342.gif)
![produto informacao](https://cloud.githubusercontent.com/assets/24878214/21592707/593458fe-d0ee-11e6-8be7-4f1a962ece13.gif)
![produto fiscal](https://cloud.githubusercontent.com/assets/24878214/21592706/5934424c-d0ee-11e6-8e88-a742bcab918a.gif)
![cotacao outros](https://cloud.githubusercontent.com/assets/24878214/21592710/5937b60c-d0ee-11e6-9248-56dc41af2a38.gif)
![cotacao itens](https://cloud.githubusercontent.com/assets/24878214/21592711/5946746c-d0ee-11e6-9809-4da474b004b3.gif)

**Comment by mileo** [comment]
Coloque o seu usuário no grupo **propriedades nas linhas.**

**Comment by gustavors01** [comment]
Prezado @mileo ,
Favor reabrir a ISSUE.

Ativei as propriedades nas linhas do usuário.
Fiz novas tentativas no mesmo banco de dados, onde continuaram os mesmos problemas.

Crie novo banco de dados, ativando a propriedade das linhas desde o inicio das parametrizações e continuam as falhas reportadas, de não puxar os impostos, e em alguns momentos continuam sumindo o tipo fiscal do produto.

Tentei cadastrar impostos separadamente, colocando pis e cofins nas configurações da empresa.
Coloquei ICMS e IPI nas configurações do NCM, e continua, não puxando nenhum imposto automaticamente.

Muito Obridado

![cotacao produto linhas](https://cloud.githubusercontent.com/assets/24878214/21668113/8497ae10-d2dd-11e6-9dfb-98e814289556.gif)

**Comment by pauloneda** [comment]
Faturamento Inicial e Final na Regra de Posição Fiscal está 0,00
Se não estiver mapeando as taxas preencha Faturamento Inicial 0,01 e Final 3600000,00

**Comment by gustavors01** [comment]
Prezado @pauloneda,

Preenchi faturamento inicial e final na regra de posição fiscal como sugerido, coloquei data inicial e final, nas configurações da empresa coloquei o faturamento dos últimos 12 meses com 10000,00.

Entretanto continua todos os mesmos sintomas relatados anteriormente.

Muito Obrigado

![regra fiscal faturamento](https://cloud.githubusercontent.com/assets/24878214/21700199/fc2fe672-d37d-11e6-9234-09ba02ea27e5.gif)
![empresa faturamento](https://cloud.githubusercontent.com/assets/24878214/21700200/fc33ce4a-d37d-11e6-80a9-e4621dc29af4.gif)

**Comment by gustavors01** [comment]
Prezado @mileo,

Muito Obrigado pela reabertura da ISSUE.

Desconfio de alguma relação com o "TIPO FISCAL" do Produto.

Na haba informação do produto, no "TIPO FISCAL", seleciono produto, salvo, consulto novamente, e esta salvo, após alguns minutos desaparece, se eu levar o mouse em modo depuração não aparecem o nome e descrições do campo, como ocorre em todos os outros.

Na haba fiscal do produto, o "TIPO FISCAL" esta ok, e fica salvo a propriedade PRODUTO.

Obrigado.

![produto haba informacoes](https://cloud.githubusercontent.com/assets/24878214/21700404/121adda6-d37f-11e6-924b-3eba250e5149.gif)


![produto haba fiscal](https://cloud.githubusercontent.com/assets/24878214/21700389/f404d786-d37e-11e6-9096-a661fea69506.gif)

**Comment by gustavors01** [comment]
Segue meus módulos instalados:

![modulos instalados](https://cloud.githubusercontent.com/assets/24878214/21701668/d910951c-d385-11e6-89d6-2e72bd3d6c35.gif)

**Comment by mileo** [comment]
Tente desinstalar o l10n_br_account_service. Pelo que me lembro havia um bug nele.

cc: @sadamo

**Comment by gustavors01** [comment]
Prezado @mileo,

Removi o modulo, removeu o "TIPO FISCAL" da Haba informação do produto.
Mas continua sem puxar os impostos automaticamente, na criação de nova cotação.

Com a remoção do modulo, passou a apresentar o erro abaixo, ao clicar no cliente ou tentar criar novo cliente, mesmo reinstalando o modulo novamente o erro abaixo continua.

Obrigado.

Erro:
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3148, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3183, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 3370, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/odoo/openerp/osv/fields.py", line 1462, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/odoo/addons/account/partner.py", line 284, in _invoice_total
    cr.execute(query, where_clause_params + [user_currency_id])
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "account_invoice_report" does not exist
LINE 11:                         FROM account_invoice_report account_...

**Comment by mileo** [comment]
@leticiadnsouza Vc tb teve problemas com as taxas da empresa com a OCA/8.0 nos testes com robot framework?

**Comment by leticiadnsouza** [comment]
@gustavors01 tenta adicionar a permissão de multi empresas no cadastro do usuário, e na posição fiscal você seta a empresa na qual os impostos estão cadastrados. Acredito que dessa forma os impostos sejam carregados na cotação

**Comment by gustavors01** [comment]
Prezados,
Considero como encerrada a ISSUE, fiz vários testes por aqui, agora os impostos estão sendo carregados automaticamente.

Segue meus comentários:

@leticiadnsouza: Ao habilitar a permissão "multi empresas", apareceu o campo empresa na posição fiscal, onde consegui selecionada, e após carregou os impostos, ou seja o usuário que cadastrar as posições fiscais precisa desta permissão, segue mais abaixo print screen.

@mileo: Sim, o usuário que fizer as cotações precisa ter a permissão para "propriedades nas linhas", para  carregar os impostos.

@pauloneda: Não vi necessidade do Faturamento inicial e final, nesta configuração básica, mesmo setando valor 0 no inicial e alto no final, e editando o faturamento da empresa para fora desta margem, nos meu testes não houveram mudanças, então numa configuração básica não vejo necessidade.

Muito obrigado a todos.

Duvida:
1- Devo abrir ISSUE para o campo "TIPO DO PRODUTO", na haba informação do produto, relacionado a bug no modulo "l10n_br_account_service", informado pelo MILEO?
2- Devo abrir ISSUE para o campo "Descrição do Produto" na cotação de venda, que carrega o campo "Nome do Produto" ao invés da descrição?

Mais uma vez muito obrigado a todos.

![posicao fiscal empresa](https://cloud.githubusercontent.com/assets/24878214/21772223/216197ae-d669-11e6-9444-95b4d8680acb.gif)
