### ISSUE TITLE
Função para criar classificações fiscais, gerando listagem incompleta

### ISSUE THREAD

**Issue by gustavors01** [OCA/l10n-brazil#510]
A função para gerar as regras de classificação fiscal dos produtos (NCM), só esta gerando 9165, do template com 14979.

Versões atualizadas ontem 01/01/2017.
Repositorios:
odoo/odoo 8.0;
oca/l10n-brazil 8.0;
oca/account-fiscal-rule 8.0;
odoo-brazil/odoo-brazil-electronic-documents 8.0;
oca/server-tools 8.0;

Segue em anexo print screen.

Muito grato,

Gustavo

![clasificacao fiscal](https://cloud.githubusercontent.com/assets/24878214/21596479/7b2f6e5e-d11a-11e6-9229-345cdce96e7d.gif)
![clasificacao fiscal template](https://cloud.githubusercontent.com/assets/24878214/21596480/7b30b9b2-d11a-11e6-801c-96b1160b5f1c.gif)

**Comment by falexandresilva** [comment]
Existe alguma maneira de contornar, enquanto o bug não é resolvido?
