### ISSUE TITLE
Elemento '<button name="invoice_open">' n\xe3o pode ser localizado na vis\xe3o pai

### ISSUE THREAD

**Issue by gabrielcontessotto** [OCA/l10n-brazil#519]
Quando vou fazer a instalacao do modulo apresenta esse erro:

ParseError: "ValidateError
Campo(s) `arch` falhou contra uma restri\xe7\xe3o: Invalid view definition

Detalhes do Erro:
Elemento '<button name="invoice_open">' n\xe3o pode ser localizado na vis\xe3o pai

Contexto de erro:
Veja `l10n_br_envio_account.invoice.form`
[view_id: 1052, xml_id: n/a, model: account.invoice, parent_id: 558]" while parsing /usr/lib/python2.7/dist-packages/openerp/addons/nfe/views/account_invoice_view.xml:38, near
<record model="ir.ui.view" id="view_l10n_br_envio_account_invoice_supplier_form">

Alguem já passou por isso aguardo! :)

**Comment by mbcosta** [comment]
Ola @gabrielcontessotto isso acontece em um banco de dados novo ? Qual a versão do Odoo ?

**Comment by gabrielcontessotto** [comment]
Desculpa a demora removi o banco e instalei novamente funcionou tudo ceto a vesao era a 8
