### ISSUE TITLE
Estado da Placa do Veículo, buscando errado

### ISSUE THREAD

**Issue by pauloneda** [OCA/l10n-brazil#528]
@Passos para reproduzir o problema:

[https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/sped/nfe/document.py#L570](https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/sped/nfe/document.py#L570)

invoice.vehicle_id.plate.state_id.code
for
invoice.vehicle_id.state_id.code

**Comment by mbcosta** [comment]
Ola @pauloneda você poderia explicar melhor o problema ou propor um PR ??

**Comment by mbcosta** [comment]
Hi PSCs @renatonlima @rvalyi @mileo this issue seems outdated now, I belive we can close.
