### ISSUE TITLE
Erro no Travis

### ISSUE THREAD

**Issue by mbcosta** [OCA/l10n-brazil#531]
Parece existir um problema no Travis ( https://github.com/OCA/l10n-brazil/pull/530 ) relacionado a biblioteca Pillow

Will not install to the user site because it will lack sys.path precedence to Pillow in /home/travis/virtualenv/python2.7_with_system_site_packages/lib/python2.7/site-packages
The command "travis_install_nightly" failed and exited with 1 during .

**Comment by mileo** [comment]
Segue a solução: https://github.com/odoo-brazil/l10n-brazil-wip/blob/10.0-develop/requirements.txt#L3
