### ISSUE TITLE
Error while importing module 'l10n-brazil-10.0': u'depends'

### ISSUE THREAD

**Issue by gustavocaloi** [OCA/l10n-brazil#535]
Boa noite caros colegas.
Irei postar uma dúvida de iniciante, entretanto não encontro uma solução.
Estou utilizando o Odoo SaaS e preciso emitir NFe. Estou tentando importar o modulo brazil e estou enfrentando o seguinte problema.

Passos para reproduzir o problema:
No modulo de importação de modulo, assim que seleciono o l10n-brazil-10.0.zip ocorre o seguinte erro: Error while importing module 'l10n-brazil-10.0': u'depends'

Vejo que existem soluçoes para Odoo (instalaçao local), porem para o SaaS nao vi soluçao.
Alguem enfrentou problema parecido?

Videos/Screenshot link:
<img width="1679" alt="captura de tela 2017-05-18 as 23 11 14" src="https://cloud.githubusercontent.com/assets/19421257/26231225/71f9b874-3c24-11e7-8aad-34c9389e170b.png">

**Comment by gustavocaloi** [comment]
Boa noite caros,
Consultei a Odoo e o SaaS não possui suporte para esse modulo.
Fiz uma instalação local e o erro persiste, alguém já passou por isso?

**Comment by mileo** [comment]
A versão 10.0 ainda esta em desenvolvimento e pode ser encontrada no repositório:

https://github.com/odoo-brazil/l10n-brazil-wip

Duvidas ficamos a disposição
