### ISSUE TITLE
Instalação do Modulo Base num servidor Windows

### ISSUE THREAD

**Issue by emersonbottero** [OCA/l10n-brazil#543]
Passos para reproduzir o problema:
1 - Baixar o modulo de localização Brasileira em um servidor windows e tentar instalar.
aparece o erro: "Unable to install module "l10n_br_base" because an external dependency is not met: No module named num2words"
2 - Instalar o modulo faltante com "pip install num2words"
3 - Testar se foi realmente instalado importando o modulo no python, o que não deve dar erros ou tentando reinstalar o modulo com o comando citado em 2. A resposta deve ser "Requirement already satisfied: num2words in c:\python27\lib\site-packages"

Comportamento atual:
O erro continua aparecendo e a instalação não é finalizada

Comportamento esperado:
Instalação proceder sem problemas.

Windows 10 e Odoo 10. Já procurei por soluções mas todas as perguntas iguais que eu encontrei responderam ficaram sem respostas. é como se o Odoo tivesse um python só dele que não encontra os módulos instalados.

Videos/Screenshot link:

**Comment by fnegrini** [comment]
Amigo,

Já "naveguei por estas águas" e posso afirmar com conhecimento de causa que
tentar rodar Odoo (ou qualquer produto python) em Windows, apesar de
possível, é inviável. Fica muito instável, difícil de gerenciar e
controlar. Sugiro fazer uma máquina virtual Ubuntu Server ou Lubuntu se
quiser uma interface gráfica e fazer seus testes nela. O Oracle VM
VirtualBox por exemplo, é gratuito e oferece bastante suporte de
comunicação entre o computador e a VM permitindo que você rode a VM mas
visualize o Odoo no seu navegador. A propósito, para não ter que iniciar do
zero, tem uma dessas pronta para desenvolvimento aqui:

https://sourceforge.net/projects/openerpbrasilvm/files/vm/

Deve estar um pouco desatualizado, mas nada que alguns comandos GIT não
resolvam.

Espero ter colaborado.

Abs,

Fabio Negrini

Em 6 de junho de 2017 19:14, emersonbottero <notifications@github.com>
escreveu:

**Comment by emersonbottero** [comment]
Vou fazer isso.
Obrigado pelo feedback.

**Comment by rvalyi** [comment]
Na Akretion a gente criou a ferramenta Voodoo para virtualizar os ambientes de dev e ate alguns ambientes de prod. Como é baseado no Docker Compose, hoje teoricamente funcionaria no Windows direitamente, mas faz muito tempo que nao testamos porque ninguem usa Windows na Akretion. Se alguem quiser testar e nos dar algum feedback:
https://akretion.github.io/voodoo/
