### ISSUE TITLE
Erro no Frete em uma Cotação

### ISSUE THREAD

**Issue by pauloneda** [OCA/l10n-brazil#55]
Para replicar o erro;
Criar uma Cotação, adiciona 2(Dois) itens, adiciona o frete e atualiza a ordem.

Excluir um ítem e atualizar o Valor da cotação.

Preço total da ordem fica incorreto.

Att

**Comment by mileo** [comment]
Obrigado por reportar Paulo,

Vou dar uma olhada até o fim da semana

[]s

Em 12 de maio de 2014 17:34, Paulo Ricardo notifications@github.comescreveu:

> Para replicar o erro;
> Criar uma Cotação, adiciona 2(Dois) itens, adiciona o frete e atualiza a
> ordem.
> 
> Excluir um ítem e atualizar o Valor da cotação.
> 
> Preço total da ordem fica incorreto.
> 
> Att
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/55
> .

## 

_Luis Felipe MiléoKMEE_
+55 35 8876-3662
+55 21 4063-8872
mileo@kmee.com.br
kmee.com.br

**Comment by pauloneda** [comment]
Olá Luiz,
Você já deve ter visto, mas exemplo:
Salvo uma cotação com o valor de R$ 60,00 de frete.

Em outro momento resolvo retirar o frete, se apenas limpar o campo, ele não exclui na tabela, mantendo os R$ 60,00. Para que funcione é obrigado colocar 0(Zero) no valor do frete.

Att

**Comment by mileo** [comment]
Eu fiz uma modificação em que o botão atualizar recalcula o valor do frete
dos itens.

Vc chegou a atualizar e testar?

Abraços

Em 27 de maio de 2014 15:56, Paulo Ricardo notifications@github.comescreveu:

> Olá Luiz,
> Você já deve ter visto, mas exemplo:
> Salvo uma cotação com o valor de R$ 60,00 de frete.
> 
> Em outro momento resolvo retirar o frete, se apenas limpar o campo, ele
> não exclui na tabela, mantendo os R$ 60,00. Para que funcione é obrigado
> colocar 0(Zero) no valor do frete.
> 
> Att
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openerpbrasil/l10n_br_core/issues/55#issuecomment-44319534
> .

## 

_Luis Felipe MiléoKMEE_
+55 35 8876-3662
+55 21 4063-8872
mileo@kmee.com.br
kmee.com.br

_Você sabia que o OpenERP agora é odoo? Saiba mais
em: kmee.com.br/novidades http://kmee.com.br/novidades_

**Comment by pauloneda** [comment]
Sim, Atualizei, mas continua dando o erro

**Comment by mileo** [comment]
Podemos fechar esse?

**Comment by pauloneda** [comment]
Sim

**Comment by mileo** [comment]
@renatonlima please close this one
