### ISSUE TITLE
Erro na exportação da NFe, quando destinatário é diferente do cliente

### ISSUE THREAD

**Issue by gwsilva** [OCA/l10n-brazil#56]
Quando o endereço de entrega (account_invoice.partner_shipping_id) é diferente do endereço do cliente à faturar na NFe (account_invoice.partner_id), o módulo de serialização da NFe (txt.py linha 276 e document.py linhas 91 e 100) estão buscando informação do código do estado (UF) em um campo inexistente (address_invoice_id). Os módulos deveriam buscar a informação do código UF no campo partner_shipping_id

obs.: já corrigido na branch develop

**Comment by danimaribeiro** [comment]
Poderia enviar um patch para a versão 7.0?

**Comment by mileo** [comment]
Corrigido

**Comment by mileo** [comment]
@renatonlima Please close this issue
