### ISSUE TITLE
Campo BIC no cadastro dos Bancos

### ISSUE THREAD

**Issue by mbcosta** [OCA/l10n-brazil#588]
Olá amigos, 
   Estou trabalhando no PR https://github.com/OCA/l10n-brazil/pull/586 o erro no travis tem relação com uma nova dependência adicionada, o modulo account_banking_payment_export que inclui uma "constraint" para validar o campo BIC https://github.com/OCA/bank-payment/blob/8.0/account_banking_payment_export/models/res_partner_bank.py#L13 https://github.com/OCA/bank-payment/blob/8.0/account_banking_payment_export/models/res_partner_bank.py#L27 , na localização estamos usando esse campo para colocar o código do banco https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_data_base/data/res.bank.csv por isso no repo odoo-brazil-baking foi feito um " return true " para não validar o campo https://github.com/odoo-brazil/odoo-brazil-banking/blob/develop/l10n_br_account_payment_mode/models/res_bank.py#L12 https://github.com/odoo-brazil/odoo-brazil-banking/blob/develop/l10n_br_account_payment_mode/models/res_partner_bank.py#L12 , porém pesquisando vi que mesmo os bancos brasileiros possuem esse código também http://banksbrazil.com/codes/banco-do-brasil-swift-bic-codes-in-brazil http://rodrigors.com/como-encontrar-o-codigo-iban-e-o-codigo-swift/ , por isso parece que aqui deveríamos manter o campo BIC com essa informação e criar outro campo para o código que pelo cadastro no banco central parece ser o " Código Compensação " http://www4.bcb.gov.br/fis/cosif/rest/mostrar-instituicao.asp#?cnpj=60701190&pais=1058 , em uma futura implementação um cliente se trabalhar a nível internacional pode precisar dessa informação ( não tenho certeza sobre isso ), o que vocês acham ?

cc @renatonlima @rvalyi @mileo

**Comment by mileo** [comment]
Na época optamos por criar colocar o return True para agilizar a entrega e isto acabou passando.

Na minha opinião poucas pessoas conhecem o numero BIC. Então esta validação deve ser opcional, através de uma configuração. 

Se vc for resolver o problema sugiro sobrescrever a validação e usar uma abordagem semelhante ao grupo validar total da fatura.

**Comment by rvalyi** [comment]
concordo com o @mileo,

por padrao, vc poderia pular essa validaçao, mas poderia criar um parametro de configuraçao que se tivesse preenchido, o campo BIC seria visivel e a validaçao aconteceria. Vc entao tambem poderia criar novos campos para deixar o campo BIC para o uso original dele caso precisasse.

Vc pode dar uma olhada nos parametros de configuraçao da contabilidade para ver como fazer isso:
https://github.com/odoo/odoo/blob/10.0/addons/account/models/res_config.py

cc @renatonlima

**Comment by mbcosta** [comment]
Na versão 8.0 vou ignorar essa validação para os bancos brasileiros, mas pretendo deixar em aberto esse issue para retoma-lo depois da migração para tentar dar uma solução definitiva

**Comment by renatonlima** [comment]
Atualmente o código do banco central esta sendo inserido no campo BIC (Swift code), o que gera um conflito pois existe um módulo na OCA no repo bank-payment que valida este campo que deve ter de 8 a 11 caracteres.

Para resolver este problema, deve ser criado um campo para ser inserido o código do banco central do brasil (code_bc) e deixar o campo BIC para ser inserido o código Swift de 8 digitos, no res.bank. O código swift de 8 corresponde ao código da instituição financeira (composta código do banco 4 caracteres, país 2 caracteres e local (2 caracteres). O código Swift de 11 tem os mesmos 8 caracteres do swift de 8 caracteres + 3 caracteres de identificação da agência. Hoje o Odoo não tem um cadastro de agências, e estes 3 últimos caracteres deveria ficar no objeto res.partner.bank (cadastro de conta bancária onde tem a identificação da agência).

Alguns códigos Swift de instituições financeiras do Brasil: https://pt.bic-swift.com/brasil/4/ neste site também há uma breve explicação sobre o BIC (Swift Code)

**Comment by mbcosta** [comment]
Olá PSCs @mileo  @rvalyi  @renatonlima 
Vou encerrar esse "issue", já foi feito o merge na 10.
