### ISSUE TITLE
concertar o test no modulo l10n_br_base

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#59]
para poder rodar com --test-enable
algo foi quebrado no dispatch dos testes de cnpj ou inscriçao estadual parece

**Comment by danimaribeiro** [comment]
O issue pode ser fechado.

**Comment by mileo** [comment]
@rvalyi please close

**Comment by renatonlima** [comment]
@mileo @danimaribeiro 

I will clone this issue

cc @rvalyi
