### ISSUE TITLE
extender o uso do web_context_tunnel

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#60]
identificar os lugar onde ainda accrescentamos parametros nos on_change e tentar o usar o web_context_tunnel para aumentar a compatibilidade com os outros modulos.

Tentar obter merges no core nos metodos onde isso nao pode ser feito porque o context nao esta nos argumentos do on_change (vou tentar durante os community days).

**Comment by mileo** [comment]
@rvalyi Sabe me dizer como esta o uso do webcontext na v8? Estou realizando uns testes para melhorar os on_changes do stock.

Abraços

**Comment by renatonlima** [comment]
@rvalyi 

I did this changes in l10n_br_account, l10n_br_sale and l10n_br_purchase, I think we can close this issue

cc @mileo @danimaribeiro

**Comment by mileo** [comment]
LGTM

**Comment by mileo** [comment]
l10n_br_stock too?

**Comment by rvalyi** [comment]
sim podemos fechar
