### ISSUE TITLE
[RFC][10/11/12]: make the Brazilian localization to play nice with other localizations

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#614]
supposing our Brazilian localization is installed along other well behaved localizations (the Spanish one for instance but apparently no many modules from the French one for instance), we should play nice with the other localizations, that is we should:

1. avoid enforcing mandatory fields or field validation at the database level
2. properly enforce the fields presence and correctness at the model level, but according to the partner or company country (in python constraints).
2. display or hide the localization fields/buttons according to the country of the partner or company.
4. trigger or not our main localization overrides only if the partner or company is Brazil.
5. eventually have a default setting in our localization making partners be Brazilian (so localized interface) unless set otherwise.
6. [EDIT] from the thread: we could check the chart of account rather than the country eventually
7. [EDIT] playing nice also means avoiding field conflicts, specially the numerous fields coming from the XSD schemas. That will be addressed with nfelib and related projects in v11 and onward versions.

This way of doing has been discussed with the fellow @pedrobaeza and me during the last Odoo Experience in 2017.

At this time, an experiment with this is known in the alternative localization (who made some advances but is terrible in the sense that it is extremely poorly integrated with the Odoo core or the OCA because it is basically an new ERP written in the Odoo framework that tries to matches later on with Odoo objects), and is implemented in the form of an is_brazilian computed Boolean field that is injected via a mixin in nearly all our localization class overrides:

```python
    is_brazilian = fields.Boolean(
        string='Is a Brazilian partner?',
        compute='_compute_is_brazilian',
        store=True,
    )
```

https://github.com/kmee/l10n-brazil/blob/10.0/l10n_br_base/models/inherited_res_partner.py#L25
then this field is propagated often as a related field for instance:
https://github.com/kmee/l10n-brazil/blob/10.0/l10n_br_base/models/inherited_res_company.py#L24
https://github.com/kmee/l10n-brazil/blob/10.0/sped_account/models/inherited_account_invoice_line.py#L33

and the method overrides are properly triggered or skipped:
https://github.com/kmee/l10n-brazil/blob/10.0/sped_account/models/inherited_account_invoice.py#L128
https://github.com/kmee/l10n-brazil/blob/10.0/sped_account/models/inherited_account_invoice.py#L206

```python
    @api.multi
    def action_move_create(self):
        for invoice in self:
            if invoice.is_brazilian:
                continue
            super(AccountInvoice, self).action_move_create()
        return True
```

[EDIT] such a filter would better be implemented as a decorator.

Generalizing this behavior in all the OCA localization is a hard and long run work. If we attempt to do it entirely in v10.0, we may delay too much the migration from v8.0 and make the migration too difficult.

But mostly it is also useless to have too much ambition for v10.0 as as long as you will install the Brazilian localization with another localization that isn't so carefully designed, the other localization will prevent you from using Odoo in Brazil. And believe me, very few localization actually take care of this.

As a first step, I propose that we focus one the topmost modules in v10.0, that is:

1. l10n_br_base
2. l10_br_account
3. l10_br_account_service

If we do that, we will ate least make it possible that a CRM, or project/service oriented company can work with service electronic invoices along with other localizations. That's a nice start. And till v12 we may eventually cover the last miles for the companies with electronic invoices (NFe's).

cc @renatonlima @mbcosta @mileo 
@alexis-via I put you in copy as you are the main committer in the French localization and can also think about this...
cc @sebastienbeau

**Comment by danimaribeiro** [comment]
Take a look at those commits:
https://github.com/Trust-Code/odoo-brasil/pull/541/commits/afa6d2b24e71b7d9dd522ee0805528f9d2dfc119
https://github.com/Trust-Code/odoo-brasil/pull/541/commits/a1b4c9ed1f976777f9adcb816c83838ecc1612f4

**Comment by rvalyi** [comment]
@danimaribeiro yeah looks part of the solution.
In fact, if you were to be this paranoid about field conflicts, you would end up having to put a module prefix in ALL the modules (OCA or not) and not just for the Brazilian localization...

Guess what, some ERP's like Compiere did just that. Well the result is that the theory is nice but the code is unreadable and Compiere is dead...

So unless we have a an Odoo or OCA framework consensus/solution for this, I think this is a matter of risk management:
were actually is the risk? The risk is in the fiscal information that comes from the fiscal schemas mostly. So for instance for the NFe we have around 700 potential fields so yes the risk of conflict would be significant (and probably thousands of fields with all the fiscal documents around).

In fact, I will soon introduce a solution to generate ALL the fiscal documents based on code-generation and Odoo mixin to avoid nearly any dangerous mapping. For these fields, I prefix the fields by the name of the schema, like nfe_ and thus I already decrease the likehood of conflict vastly.

I will soon update these libs, but you can be able to see these mixins/fields in the second part of these generated files:
https://github.com/akretion/nfelib/blob/generated_odoo/odoo/models/v4_00/leiauteNFe.py
(and BTW we are likely to use your great NFe/NFSe lib for the transmission so we will at least converge on that).

But in any case, that is too much of a stretch to try to achieve this in v10.0 already and this is useless as other localizations that don't care so much will block you.

All that being said, I find it very strange that you suddenly seem to feel interested in the OCA localization when you forked it 2 years ago and made NOT A SINGLE PR or comment here or in any of the other upstream OCA module you use. Could a RFC or a PR not be made in the OCA earlier?

In every open source project, entering a project 5 years after the battle and being accepted as a charting member or having commits rights in the project is based on how much you help the project and not based upon childish newcomer caprice neither upon paying something to Odoo SA which never supported the OCA or even us. So I am all for you to participate in the project, but you have to understand that you cannot simply have a freeloader attitude here, so eventually you fix this in the coming years and we come back on the same page.

At the time you asked for being PSC, you were still quite a beginner and you were defending absurd technical choices that would have undermined the projects such as depending on the pysped lib in all the OCA codebase. In fact this was so absurd that even you didn't make that choice in your fork and ended up re-writing a pysped alternative (which is GREAT)... But I hope you understand that we were not convinced by your project vision and commitment at the time you asked for the PSC and the attitude over the last 2 years just confirmed we were right about this...

Regards.

**Comment by danimaribeiro** [comment]
We are using this approach to implement in our localization.

The idea is to prefix all the fields from existing core models, and just the new models from the localization.
The prefix is to help hidding the fields in view, and also to know where it came from.


> All that being said, I find it very strange that you suddenly seem to feel concerned about the OCA localization when you forked it 2 years ago and made NOT A SINGLE PR or comment here or in any of the other upstream OCA module you use. Could a RFC or a PR not be made in the OCA earlier?

I keep reading the emails, I comment when I have something to contribute, as I don't use the OCA localization anymore I can't contribute with code.

> I will soon update these libs, but you can be able to see these mixins/fields in the second part of these generated files:

I personally don't like solutions that generate code.

> At the time you asked for being PSC, you were still quite a beginner and you were defending absurd technical choices that would have undermined the projects such as depending on the pysped lib in all the OCA codebase.

But you do depend!
https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/sped/nfe/document.py#L778

**Comment by rvalyi** [comment]
> as I don't use the OCA localization anymore I can't contribute with code. 

It is very common in the OCA that we use some and not all modules from a given repo. You d'on differ too much on the l10n_br_base, l10n_br_crm or l10n_br_account top modules for instance. That would have been a very different attitude if you tried to contribute on these modules or other OCA modules even if you would differ on usability layers or even electronic document layers. All main Odoo integrators do that, everybody never agree on everything and keep having their own modules but what matters is that we do still build a common solid base. In fact now that you removed the pysped from your code, guess what at Akretion we are much more in line with your fork...

> I personally don't like solutions that generate code.

I found that such code generating can replace in 1 single command 10 000 lines of hand maintain stupid buggy pysped code. So it is certainly a win against pysped.
I know your template based solution, it is quite better than pysped, but still I think we can do better with the code generation, like much cheaper to maintain.
But mostly, we can ensure that the XSD validation occurs early right in the user interface and not too late when the accountant tries to generate the electronic invoice... That is something that increase usability dramatically I think.
But even we want to evolve the localization in a way you could easily serialize the XML documents your own way. So think again if you want to jump on the band-wagon...

> But you do depend!
> https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account_product/sped/nfe/document.py#L778

This has always been a very limited overridable dependency to show we can generate the invoice XML  at the OCA level, but as we emphatized many times, we always found it was a technical debt we wanted to remove as soon as an alternative would emerge. And yes, it was an architectural choice to LIMIT the contact with pysped. Today this is what is saving us unlike the re-rewrite from Aristides at Kmee which created a born-dead localization relying entirely of endless human work to maintain the pysped based data model manually at every SPED and fiscal documents updates (and they don't update at the same time so this was totally doomed to fail).

In the beginning of the v10 port, we will likely still have this pysped usage, because it will make it easy to migrate the v8 folks, But after v8, unless pysped suddenly meet the OCA coding and community standards, we will try to remove totally its dependency from the OCA modules (eventually use nfelib to serialize the documents and your lib to transmit them). Then at least we will be able to team on your transmission lib, but it could have been way more. Let's see that again in the future.

Regards.

**Comment by pedrobaeza** [comment]
> display or hide the localization fields/buttons according to the country of the partner or company.

More than the country, it can be the account chart, which is available since v9. See for example https://github.com/OCA/l10n-spain/blob/dc1d2add9990a27f711901149d2a9fbfb9dda24c/l10n_es_account_invoice_sequence/models/account_invoice.py#L16-L27

**Comment by danimaribeiro** [comment]
> Today this is what is saving us unlike the re-rewrite from Aristides at Kmee which created a born-dead localization relying entirely of endless human work to maintain the pysped based data model manually at every SPED and fiscal documents updates

I agree that they are creating too much dependencies and code that will be very hard to mantain, specially with Odoo releasing every year, in the next couple of months we will have version 12 of Odoo, but in the other hand they are adding great functionalities.
We cannot have a localization that does not send eletronic invoices directly (spanish localization does, mexican does), the invoice eletronic in Brazil is more than 10 years old. 
We should have balance, we cannot wait three years to wait for a lib become stable, we have to make it stable working bit by bit, if is not the best solution right now, but it was the best we have that moment.

You have a stable localization, I agree, but it doesn't send invoice eletronics, doesn't have boleto, doesn't have payroll (kmee branch), do not send invoice eletronic for services (for our company we have fully automated our process of billing and invoices for Florianópolis, it save us hours of generating invoices for our customer). I do not want a localization that just technical people can use and have to take days to configure, or have to integrate with external software to do a simple thing that is generate a xml and send over http.

Again, balance is the right word. balance between technical debt and functionalities, and the official brazilial localization is way behind in terms of functionality.

And now we are doing our part adapting localization to work besides another localizations (we have to evolve fast, that's how technology works).



> More than the country, it can be the account chart, which is available since v9

In fact we check the chart account, not country! 
https://github.com/Trust-Code/odoo-brasil/blob/afa6d2b24e71b7d9dd522ee0805528f9d2dfc119/br_localization_filtering/models/br_localization_filtering.py#L14

**Comment by rvalyi** [comment]
hello Danimar, the purpose of the OCA is NOT to be an Odoo distribution or at least not yet. It is to promote maintainable modules and educate the community about how modules can be designed maintainable or not and work together. You could probably debate the OCA rules if you don't like them and help shaping them, like we often do, but ultimately we cope with them. It is also very hypocrite to criticize us for years for a discipline you would not even try to adopt yourself...

Sorry but saying our localization doesn't have electronic invoicing or boletos is just PLAIN FUD. You know very well it does thanks to public non OCA extra repositories just like your Trustcode repo is not an OCA repo. And probably from v10 and onward the NFe transmission will be integrated in the OCA just like in your fork. The thing is that designing the whole localization this way in fact will allow us to finally have a pysped alternative. In fact I can show you another localization that wasn't so carefully designed and is now dying altogether with pysped so may be we were just right with these choices you see...
As for boletos Akretion and Kmee do differently and none of these solution fit the OCA criteria, so we took the common basis and put it in the OCA (without your help sadly) but at least we have that clean common basis, we find it better than having all out of the OCA like you do.

The only thing different you do is you drop all modules along in the same directory, like we were doing like 10 years ago before knowing better ways to overcome the limited Odoo package system and making our way with git and sevral repos like every other prominent Odoo integrator. Now of course you can play the populist game of telling people your localization is simpler because everything is in your unique repo. Well we will prove you in the long run it is simply not, because by doing that you are unable to feedback improvements in the OCA repos you fork (not speaking only about this one). And then it is pointless to complain about some repo if you didn't even contribute to it or so little.  But you are free to keep not believing us. Others did too before you.

In France many people install these non OCA extra modules to get Odoo do the work:
https://github.com/akretion/odoo-usability
In Beligium they would install rather:
https://github.com/luc-demeyer/noviat-apps
all extending OCA repos and here you go.

Not putting everything in the same vendor repo doesn't prevent people from collaborating. In Fact you would be surprised to find PRs from Noviat, Acsone or CamptoCamp in our Akretion repos and vice-versa.

But even if all integrator do that to bring the final layers of usability not covered in the OCA yet, we are still civilized enough to team on the core OCA modules and this makes us different from you who just forked 5 years of OCA work and re-painted it under your company flag, probably to please your investors. That is your right, but that is not the way we work and you won't earn a charting seat with false victimization here sorry.

Regards.

**Comment by danimaribeiro** [comment]
I'm not a victime, I've just decided two years ago to not colaborate anymore with code for brazilian localization in this repo.
And I didn't start this conversation, I just sent two links showing how we decided to do to solve the problem.

Also, I'm not complaining, I'm just giving my point of view about the OCA localization, you are free to accept or not the points noted. As I don't accept the OCA point of view about the Brazilian localization I've decided to fork and keep working with Odoo, that's the beauty of open source, power of choice.

**Comment by rvalyi** [comment]
another remark: IMHO the Mexican localization is NO EXAMPLE: for once it is simpler and second it is not even fucking opens source! I mean where on earth taking a fucking VC to create proprietary software is a challenge? It is the old model, the one we believe it is on decline but certainly not a model for the OCA. Spain is different, yes it is a model. There are several reasons for that, some of them being:

1. Spain got very early TinyERP partners very active since 2006 but then they were betrayed by Odoo SA in the license change and banged the door for Tryton but still leaving a good start for the community.
2. Spain is a special balance were it is a country who has been poor and small enough for not being very well addressed by major global ERP players and still it is a country with a different past than Brazil and a  very much higher education level were it is 10x easier to find potential contributors or smarts SMBs that will pay for it than say in Brazil (even in Belgium which is 20x smaller than Brazil it is easier sadly...).
3. They have Pedro in the team.
4. They have Tecnativa...

And still Spanish electronic invoicing is may be 10x simpler than Brazil. In fact one of our customer got it even backported on 6.1 which would be totally impossible here in Brazil. In France for instance the electronic invoicing has a XSD 15x shorter than Brazil (not talking about taxes computation) so yes it is way simpler and even with this the factur-x electronic invoicing bundled by Odoo SA is way behind what you can do with the OCA and you don't even know that Antony Lesuisse Odoo CTO got hours on phone with Alexis De Lattre from Akretion to know how we were doing at Akretion and do this poor copy in the Odoo v12 core... So there is much to be said...

**Comment by rvalyi** [comment]
and there is another critic I couldn't let unanswered:

Danimar you both say that the OCA repo isn't going fast enough but at the same time:

- first you didn't help very much to be otherwise (and again one cannot require to lead a decade long project of this size just because he made a few commits during a few months).
- but also you critic us because we din't put all modules into this repository like you did in your non OCA fork.

Well my friend, **leaving modules that are really far away from OCA standards (or in their dependencies) outside from this OCA repo, was exactly a way to get them mature faster than the OCA bureaucracy would allow** and also it was a way to state clearly things were not up to the mark and eventually incentive competition toward better solutions. So this is exactly what happened with the pysped dependent modules and you actually made a better alternative and could make it that fast because exactly because you didn't have to cope with the OCA bureaucracy during the maturing stages.

Again this very much all the discussion about the "satellites" more loosen repositories in the OCA that Akretion always defended. We could have the pypsed dependent modules be such a satellite repo but at the same time the folks who authored these modules (and not even you) didn't make huge efforts to bring them up to the OCA quality and meanwhile you built a better alternative, so that's life and personally I would recommend using the alternative you built. But I mean despite this technical achievement here, I had to protest about your whole argumentation.

**Comment by pedrobaeza** [comment]
Hey, guys, no need to fight! We both want to get the best possible localization. Although OCA standards are hard to achieve sometimes, I think you both agree that it's the goal to achieve. Why don't you put a common roadmap for getting this and split the work between both for avoiding to repeat each time the same work? I can coordinate the efforts if you want.

**Comment by rvalyi** [comment]
Hello @pedrobaeza. Well as you can see in the PR's. the v10 migration is getting very well with the main project collaborators working hard together, meeting the criteria and will be finished by the end of the month. As the coverage and quality increase, subsequent migrations will be faster. If Danimar helps in the PR and starts enforcing the OCA migration rules, his help will of course be welcome. Now if they keep believing into a commercial motivated fork as they did since 2 or 3 years, well it is better they keep outside of the project, we won't miss their work here.

In fact, what Trustcode made is a new electronic invoicing transmission library that could replace in part the legacy unmaintainable pysped lib we used so far (but with extreme care) that we can use after python 3. But this can be done with or without @danimaribeiro collaboration.

Another field were field were we always acknowledged an advance from Trustcode is the service electronic invoices. 3 or 4 years ago we offered @danimaribeiro to start taking their load in the project according to the OCA rules and then he could eventually take the lead of a new electronic service invoice satellite OCA repo that would be created. (We did such an incubator repo for the pysped product invoice transmission but it didn't meet the OCA standards, it is likely it will not go to Python 3 due to the lack of test in the codebase and probably we substitute it by the @danimaribeiro alternative lib along with an Akretion lib)

There is not really a national standard for service invoices. Well there is one (ABRASAF) but it is not used and even the official xsd is not even a valid XML (incredible). So every city has its own SOAP system. And actually there are a half dozen of vendors implementing it. So it means there is specific work to be done and yes @danimaribeiro made the most advanced work here and in ways that are compatible with the OCA.

So this door is still open, if Trustcode comes back into working with the OCA project instead of just forking it without contributing back (some of the v10 PRs are 2 years old and @danimaribeiro didn't try to help while doing it in secret in their own repo that was maintained unpublished for months, likely as an investor strategy to take over the project, so there is really an **attitude problem** here, and the attitude is not different with the other OCA repo they use), we can still integrate these new service invoicing modules in a new satellite repo and give @danimaribeiro some responsability here. On the other hand with less than 2% of the commits in the current OCA repo, very few PRs and generally an offensive fork behavior, and not such an experience vision of the core of the project, it is out of question to let @danimaribeiro decide something inside the current OCA repo. Had we done that earlier, people would have bet on the OCA codebase would have been screwed for the migrations and the project would have been crippled in many aspects we can elaborate further if there is still need for explanations.

**Comment by pedrobaeza** [comment]
OK, but keep the mind opened, please, and try to be polite with other people.

@danimaribeiro are you willing to follow a common path and give a hand on current work? It's not needed to put everything on your shoulders, but review the PRs for example as a first sight of collaboration spirit. Is this good for you?

**Comment by mbcosta** [comment]
Hi all,
There is a issue https://github.com/OCA/l10n-brazil/issues/588 related, is about field BIC on the Banks
