### ISSUE TITLE
[10.0][MIG] Cherry-pick 8.0 l10n_br_account

### ISSUE THREAD

**Issue by mbcosta** [OCA/l10n-brazil#616]
After the creation of https://github.com/OCA/l10n-brazil/pull/603 some commits are included in branch 8.0 ( date used is after 22/11/2016 https://github.com/OCA/l10n-brazil/commits/8.0/l10n_br_account ), we need to integrated it, below the list of commits to check:

Depois da criação do PR de migração do modulo l10n_br_account alguns "commits" foram incluídos na "branch"8.0 ( a data usada foi depois de 22/11/2016 ). nós precisamos integrar isso, abaixo a lista de "commits" para verificar:

- [ ] https://github.com/OCA/l10n-brazil/commit/3a875b36c20487ba75c260dc30b5670096a25daf#diff-f686a39ef949b8a5fbab4e9087891530

- [x] https://github.com/OCA/l10n-brazil/commit/f6dcd899cb005269eafaacc2eb14f8ef39cbb670#diff-f686a39ef949b8a5fbab4e9087891530

- [x] https://github.com/OCA/l10n-brazil/commit/30d6fa66189718dc6fc4f92dc63854b94ca8fb7a#diff-f686a39ef949b8a5fbab4e9087891530

- [x] https://github.com/OCA/l10n-brazil/commit/7276ca32bfa4fa26f877f449fdf65abb4c71b505#diff-f686a39ef949b8a5fbab4e9087891530

- [x] https://github.com/OCA/l10n-brazil/commit/57e8d702d76e3c41086d656820749b65e32d97a5#diff-f686a39ef949b8a5fbab4e9087891530

- [x] https://github.com/OCA/l10n-brazil/commit/78694e93b533314e3bf3c4b3b18f8636de0c8343#diff-f686a39ef949b8a5fbab4e9087891530

- [x] https://github.com/OCA/l10n-brazil/commit/5e607eedfdaff825ac239b9ec8c568f682f3e969#diff-f686a39ef949b8a5fbab4e9087891530

- Não incluir https://github.com/OCA/l10n-brazil/commit/e16989b68711571f644d1427677886cdd307d663#diff-f686a39ef949b8a5fbab4e9087891530

- Não incluir https://github.com/OCA/l10n-brazil/commit/9e46d39b6ef29e5803ff26fd3b5c774a8cd31a44#diff-f686a39ef949b8a5fbab4e9087891530

- [x] https://github.com/OCA/l10n-brazil/commit/89c13e83c4090642b68bb8efeb7b3887abb1ebca#diff-f686a39ef949b8a5fbab4e9087891530

- Não incluir  https://github.com/OCA/l10n-brazil/commit/7fcf066ac64929fa96479f631ad5dc6e5edb38fe#diff-f686a39ef949b8a5fbab4e9087891530

**Comment by mileo** [comment]
Este commit não deve ser incluído https://github.com/OCA/l10n-brazil/commit/e16989b68711571f644d1427677886cdd307d663#diff-f686a39ef949b8a5fbab4e9087891530 visto que modelos transientes não precisam de permissão

**Comment by mileo** [comment]
E nem este https://github.com/OCA/l10n-brazil/commit/7fcf066ac64929fa96479f631ad5dc6e5edb38fe#diff-f686a39ef949b8a5fbab4e9087891530

**Comment by mileo** [comment]
@mbcosta 3a875b3#diff-f686a39ef949b8a5fbab4e9087891530 esse commit é um merge, vc tem certeza?

**Comment by mbcosta** [comment]
ola @mileo , obrigado. Acabei incluindo todos os commits que apareceram na lista, bom tem esse teste https://github.com/OCA/l10n-brazil/commit/9e46d39b6ef29e5803ff26fd3b5c774a8cd31a44#diff-f686a39ef949b8a5fbab4e9087891530 que teria que ser portado de yml para python, mas é apenas um teste de acessos, um commit https://github.com/OCA/l10n-brazil/commit/28f220ce41dc2c015aabdd665b6a631b798f0a8c#diff-be1168f1734b154567e113d8808e98b6R11 onde inclui o "_order = "  no objeto account.move.line, você acredita que isso deveria ser incluído ?

**Comment by mileo** [comment]
@mbcosta o do teste não precisa, visto que o core já tem o teste e removemos os commits do wizard.

Referente a ordem este commit já foi integrado de alguma forma:

https://github.com/akretion/l10n-brazil/blob/10.0-migration/l10n_br_account/l10n_br_account/models/account_move_line.py
