### ISSUE TITLE
[RFC][10] kill the l10n_br_account_data module

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#628]
when Akretion designed l10n_br_account_data back around 2012, the idea was we would install the Brazilian accounting/fiscal engine l10n_br_account for quick developement work. But for production usage we would additionally install l10n_br_account_data where there would be a lot of settings data that would take time to load. It was version 6.1, loading data was slow...

Now in 2018,  l10n_br_account_data is only one data file. In fact for many tests we still need to install it and new comers often run into errors because they forget to install it.

So all in all, we should just merge l10n_br_account_data into the l10n_br_account module. It is a simple change, it can be done in 10.0.

**Comment by renatonlima** [comment]
Implemented by PR #641
