### ISSUE TITLE
[RFC][10.0] Mover campo union_entity_code para os módulos de HR

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#636]
Com o merge do PR https://github.com/OCA/l10n-brazil/pull/625 adicionando o campo union_entity_code no módulo l10n_br_base, faz sentido mover o campo para algum módulo de l10n_br_hr, já que é um campo muito especifico dos módulos de HR. Esta alteração não é prioritária e pode ser feita depois que finalizada a migração de todos os módulos da localização brasileira.

**Comment by rvalyi** [comment]
eu concordo com o @renatonlima, tb nao gostei desse merge, nao faz logica ter o campo no l10n_br_base.

**Comment by nogueira-raphael** [comment]
Também não faz sentido exibir este campo quando o company_type = 'person' uma vez que este código é uma particularidade de sindicatos e sindicatos são pessoa jurídica('company').
