### ISSUE TITLE
Campos de endereço da localização brasileira nos contatos de parceiros

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#66]
Atualmente ao incluir um novo contato de parceiro na sessão endereço não existe na visão os campos de endereço criados na localização brasileira como: número, bairro, município (campo relacional com a tabela l10n_br_base.city), é necessário incluir estes campos para o preenchimento correto dos endereços do contato.

**Comment by mileo** [comment]
Em andamento
