### ISSUE TITLE
[RFC][12.0] Substituir a biblioteca suds por zeep no módulo l10n_br_zip_correios

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#668]
Alterar a consulta de CEP pelo correios que hoje utiliza a biblioteca suds pela biblioteca zeep.

**Comment by renatonlima** [comment]
Eu pesquisei uma lib feita pelo @mstuttgart https://github.com/mstuttgart/pycep-correios parece bem madura, esta documentada, tem coverage de 91%, acho uma boa opção substituir as funções de consulta de CEPs por essa lib

**Comment by rvalyi** [comment]
concordo, a lib do @mstuttgart parece bem razoável!

**Comment by mbcosta** [comment]
A lib parece boa. Se for feita a substituição acredito que podemos ver dois pontos que vi revisando o https://github.com/OCA/l10n-brazil/pull/654 : 

- No retorno do webservice dos correios existe um campo chamado complemento2, precismos avaliar se seria necessário inclui-lo no objeto l10n_br.zip

- No objeto l10n_br.zip existe o campo street_type que não existe no retorno do webservice, acredito que se trata das definições de Rua, Avenida, Alameda etc, porém isso já está incluído no logradouro portanto o campo pode ser removido

**Comment by mstuttgart** [comment]
Olá pessoal, que bom que gostaram da lib. :smile: 
Eu a utilizo em produção (no Odoo) faz um bom tempo. Tem funcionado legal para a gente.

Inclusive na ultima atualização, eu adicionei a consulta usando a _zeep_, justamente pela mesma ser bem documentada, fácil de usar e estável. 

Dúvidas, estou a disposição.

**Comment by rvalyi** [comment]
Eu accredito que se a gente for usar a lib do @mstuttgart, o codigo no l10n_br_zip_correios ficaria tao reduzido que de repente vale ate a pena matar o modulo (porque nao vai ser nehnum risco de manutenção para assumir e todo mundo vai querer mesmo) e botar o que precisa direito no l10n_br_zip ou l10n_br_base (mas accredito que seria no l10n_br_zip mesmo).
Valeu @mstuttgart pela lib de qualidade!

**Comment by mileo** [comment]
Pessoal testando a biblioteca esta semana encontrei um erro no retorno do webservice, fiz um PR: https://github.com/mstuttgart/pycep-correios/pull/39

**Comment by mstuttgart** [comment]
Nova versão [3.2.0](https://pypi.org/project/pycep-correios/) já lançada com a correção do @mileo . Obrigado pessoal!

**Comment by renatonlima** [comment]
Thank you @mileo and @mstuttgart!

I think we can merge PR #703 @mileo feel free to finish your review.

**Comment by renatonlima** [comment]
Feature implemented and merged in PR #703
