### ISSUE TITLE
[RFC][12.0] Replace PySPED/pybrasil for NFeLIB

### ISSUE THREAD

**Issue by mbcosta** [OCA/l10n-brazil#669]
Trocar a biblioteca PySPED pela NFeLIB https://github.com/akretion/nfelib o código é gerado de maneira automática baseado nas especificações do XSD usando o generateDS. Cheguei a fazer um PR simples para gerar ainda de forma manual o XML da NFe na versão 10.0 https://github.com/akretion/l10n-brazil/pull/81 mas a idéia é que mesmo o modulo que será criado para integrar com o odoo seja gerado de forma automática.

@renatonlima @rvalyi @mileo

**Comment by rvalyi** [comment]
o import e export automatico com o nfelib sera possivel quando o modulo l10n_br_account_product (que sera renomeado em l10n_br_account_nfe) passara a usar esses mixins para os campos da NFe:
https://github.com/OCA/l10n-brazil/pull/658
Tou trabalhando nisso...
