### ISSUE TITLE
Criação de bibliotecas de transmissão / assinatura e helpers para documentos fiscais gerados com GenerateDS

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#670]
Pessoal conforme conversei com @renatonlima em reunião presencial 02/04/2019 no Google Campus.

No ano passado trabalhei em um protótipo para emissão / assinatura e outros com documentos gerados através do GenerateDS.

Já é possível se comunicar/emitir com sucesso com os webservices:
- NFE;
- MDF-E (usado em produção desde setembro);
- NFS-E (http://www.ginfes.com.br);

E fiz alguns testes pontuais em outros serviços:
- GNRE;
- E-social;

Vou organizar esse código em 3 libs a serem criadas em odoo-brazil:

1. Transmissão: Responsável somente pela transmissão dos e-docs para os diversos webservices;
2. Assinatura: Responsável pela assinatura digital de documentos (xml e pdf) com certificados arquivo digital e token;
3. Helpers:  Responsável chave eletrônica, importação e exportação e outros pequenos detalhes;
4. Impressão

Qualquer sugestão é bem vinda. Quando quiserem podemos fazer um hangout onde posso mostrar o código existe.

Att

@rvalyi @renatonlima @hendrixcosta @mbcosta @lfdivino

**Comment by hendrixcosta** [comment]
Massa! 
O @rvalyi ja fez até alguns PRS, vocês estão em sinergia com isso tudo, certo?

Se eu puder ajudar com algo só me falar

**Comment by mileo** [comment]
Vc pode implementar a parte do e-social. 

Semana q vem vou fazer o básico e marcamos um pair programing. 

[]s 


De: "Hendrix Costa" <notifications@github.com> 
Para: "OCA/l10n-brazil" <l10n-brazil@noreply.github.com> 
Cc: "Luis F Mileo" <mileo@kmee.com.br>, "Author" <author@noreply.github.com> 
Enviadas: Quinta-feira, 4 de abril de 2019 10:36:50 
Assunto: Re: [OCA/l10n-brazil] Criação de bibliotecas de transmissão / assinatura e helpers para documentos fiscais gerados com GenerateDS (#670) 



Massa! 
O [ https://github.com/rvalyi | @rvalyi ] ja fez até alguns PRS, vocês estão em sinergia com isso tudo, certo? 

Se eu puder ajudar com algo só me falar

**Comment by rvalyi** [comment]
@mileo @hendrixcosta acho otimo uma lib Python para isso. O @renatonlima tb tava pensando nisso. Olhamos a lib zeep e com certeza virou muito mais facil e permite finalmente algo generico.

Vem aqui algumas considerações.

Primeiro, vamos aqui ressaltar que tem problemas de natureza differente:

1. ter lib de serializacao/deserialzacao XML dos documentos electronicos. Isso o generateDS faz numa boa hoje com Python 3 e os patches que eu contribui.
2. ter estruturas de dados no Odoo para persistir os dados fiscais. Isso sao meus PRs que eu fiz e que usamo o plugin generateDS que eu fiz para gerir modelos Odoo, ver https://github.com/akretion/edoc-gends. Novamente eu acho bom isolar o codigo que representa de forma fiel os XSD's ou manuais PDF de leiautes (caso do SPED) ate porque isso da especificação eh meio que indiscutivel, enquanto que o uso de cada modelo de dados no Odoo, a forma de casar ou nao com o que ja existe no Odoo ou na OCA iso ja eh muito mais debativel, gera muito mais trabalho e deve ser discutido caso a caso em modulos separados.
3. a tranmissao dos e-docs e ai sim uma lib boa para isso seria bem vindo.

Hoje em dia, ainda sera possivel transmitir a NFe usando o pysped ou entao a lib da Trust https://github.com/danimaribeiro/PyTrustNFe que vamos combinar ja representa um saldo de qualidade comparando com o pysped.

Mas vamos tambem lembrar que precisamos de uma solução para imprimir o DANFE. Ai novamente poderia ser pelo pysped ou pelo PyTrustNFe https://github.com/danimaribeiro/PyTrustNFe/blob/master3/pytrustnfe/nfe/danfe.py

Mas na verdade, tentar imprimir o DANFE pelo pysped seria ser um tiro no pe, pois nos nao pretendemos mais montar os objetos das NFe's com os objetos do pysped na v12, pretendemos serializar as notas fiscais automaticamente usando os mixins e o nfelib (ja tout testando input/output disso e vai funcionar bonitinho sim). A gente poderia apostar na funcionalidade do pysped de importar o XML para transforma-lo em objetos e depois imprimir pelo pysped, mas novamente eu acho um loucura ir de novo apostar nesse codigo tudo manual que eh um pesadelo para manter.

Portanto eu pessoalmente acho mais razoavel hoje para o DANFE sera pelo PyTrustNFe.
A ideia de pegar o XML como input e usar o Reportllab eh super razoavel. Alias a Trust nao inventou isso, pego de outro projeto e melhorou.

Eu tb concordo com o que o @mileo conversou com a gente: as vezes vc tem que customizar muito o DANFE sim, mas isso principalmente para a NFC-e. Ai sim o melhor para isso sera pelo py3o. Mas requerer o py3o, com a complexidade adicional da instalação, da manutenção e o desempenho nao eh legal por padrao. Por isso sugiro que o modulo de DANFE pelo py3o seja um addon separado, que pode ir no repo da localização OCA, mas que seja opcional. O DANFE pelo py3o nao fica muito legal num supermercado ou um SaaS barrato (com pouca RAM) ou numa instalação amador num servidor pequeno.

Conclusao, hoje em dia, vamos usar o PyTrustNFe pro DANFE (pode ser um teste dinamico sem ter dependencia). Ai como a lib tb transmite a NFe de forma boa, temos que levar isso em consideração.
Alem disso, a lib PyTrustNFe tb eh o que ha de mais avançado e open source para transmitir NFSe's de varios tipos (a questao de usar templates mako para a NFSe's em vez dos mixins pega muito menos na medida que tem poucos campos e que tem sim varios esquemas o que tornaria o usa de mixin com o sistema OCA/connector/component complexo).

Entao eu diria que para a gente passar a usar nova lib para transmitir a NFe, vai ter que ser bastante melhor do que a PyTrustNFe. Eu diria que isso eh possível. a PyTrustNFe tem uma certa complexidade que herdou de quando usava Suds para Python 2. Com Zeep da para ser mais simples. Tambem, seria legal um script Python que pega os URLs dos serviços e atualiza a lista usada pela lib em vez da gente ter que ficar atento com isso e vulnerável a queda de serviço a cada atualização.

UM API que vc poderia copiar eh esse, pois a lib eh bem feita com muita gente competente em cima no mundo Java:
https://github.com/wmixvideo/nfe
Essa lib ate imprime o DANFE tb. A gente poderia ate usar num micro-serviço. Mas ja que transmitir com o Zeep ficou facil, talvez nao vale o custo da infra do micro-serviço eh vale mais a pena ter um lib Python mesmo. Ao meu ver o custo nessa lib vai ficar na porra do DANFE porem.


Por fim, a respeito do esocial: gerei a lib de serializacao/deserializacao XML e os mixins.
A Akretion não tem interesse em implementar o funcional do e-social (ou seja o uso dos mixins no Odoo) e nem a transmissao. Acho otimo a Kmee faze-lo baseado na experiencia que vcs tiveram nisso.

Porem o uso dos mixins no Odoo requere um pouco mais de tecnologia, pois as vezes vc quer ter uma hierarchia menos funda do que o XML e ai precisa trabalhar em cima dos comodels dos campos relacionais dos mixins qdo vc herda varios deles assim como tb qdo vc injecta eles em objetos Odoo existentes como res.partner ou hr.employee. Faz 2 anos que trabalho nisso e cheguei a um codigo bastante limpo que faz ate as visoes automaticamente caso a gente quer. Nesses dias eu vou subir esse prototipo para o caso da NFe. Ai baseado nesse inteligencia que ira cair no modulo fiscal (extraido do l10n_br_account mas que nao depende do account), vcs poderao trabalhar na questao dos mixins do esocial.

Por fim, os XSDs do esocial, tem a maldita especificidade que tem poucas tag annotation. Entao muitos dos campos dos mixins nao tem labels legal ao contrario do que acontece na NFe ou os outros esquemas (sendo que quando o label nao eh legal, eh possivel herdar e trocar). Um outro ponto eh que o esocial tem muito mas muito codigo. Portanto vale a pena superar essa limitação dos XSDs para nao ter que manter isso manualmente.

Mas o esocial, tem esses labels legal nos pdfs de leiaute. O formato eh muito semelhante aos pdfs de leiautes do SPED.

Portanto, minha suggestao eh estender meu plugin de geracao de mixins Odoo de forma a poder pluggar uma função de lookup de label que poderia sim usar uma tecnica semelhante a que eu desenvolvi com o Camelot para gerir os modelos do SPED aqui: 
https://github.com/akretion/l10n-brazil-sped/tree/11.0/l10n_br_spec_sped/scripts
O sistema de extencao pode ser semelhante ao que faz o generateDS: tentar carregar um modulo Python custom passado pelo comand line e caso tiver, pegar a função desse modulo em vez da funcao padrao.


Comentarios?
