### ISSUE TITLE
[RFC][10.0][12.0] Remover a dependência do módulo l10n_br_account_product no l10n_br_account_payment_mode

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#671]
Como conversado no PR #655,

Existe um erro de dependência no módulo l10n_br_account_payment_mode que dependente do módulo l10n_br_account_product, na verdade o módulo l10n_br_account_payment_mode deveria depender apenas do l10n_br_account

Para corrigir essa dependência seria necessário mover dois campos em: https://github.com/akretion/l10n-brazil/blob/8.0/l10n_br_account_payment_mode/models/payment_mode.py#L12

type_sale_payment e type_payment para o módulo l10n_br_account_product, inclusive esses campos estão duplicados, só deveria existir o campo type_payment

Também deveria ser refatorado a estrutura dos módulos de cobrança e boletos pois existem outros problemas de modularidades que deveriam ser resolvidos, mas eu acredito que no processo de migração na branch 10.0 devemos deixar como estar e deixar para fazer a mudança de depedencia junto com o refatoramento da modularidade de todos os módulos de cobrança e boletos na versão 12.0

cc @mileo @hendrixcosta @rvalyi @mbcosta

**Comment by mbcosta** [comment]
Ola @renatonlima , como a alteração para remover a dependência do l10n_br_account_product já está sendo feita no no PR https://github.com/OCA/l10n-brazil/pull/695 assim como a reestrutura do modulos sugiro alterar a "tag" 12.0 para 10.0
