### ISSUE TITLE
 [v12]-l10n_br_crm - Erro nas Views

### ISSUE THREAD

**Issue by fmnapoli** [OCA/l10n-brazil#677]
Nas "Form Views" de prospecto e oportunidade, após a instalação do l10n_br_crm , o campo email "vira" 4 (fica agrupado com mais três - nome, cpf, e RG), como indicam as imagens:

Oportunidade Antes
![Oportunidade_antes_localizacao](https://user-images.githubusercontent.com/15277350/56929326-b03b2d00-6aaf-11e9-924d-45461e59ecfe.png)

Oportunidade Depois
![Oportunidade_depois_localizacao](https://user-images.githubusercontent.com/15277350/56929328-b0d3c380-6aaf-11e9-87db-e9e2fd7dd5f8.png)

Prospecto Antes
![prospecto_antes_localizacao](https://user-images.githubusercontent.com/15277350/56929331-b0d3c380-6aaf-11e9-84d1-7c2a7b2de959.png)

Prospecto Depois
![prospect_depois_localizacao](https://user-images.githubusercontent.com/15277350/56929330-b0d3c380-6aaf-11e9-9d93-0057c771ca71.png)

Os campos legal_name, cnpj, inscr_est e suframa não aparecem no form Oportunidade, verifiquei que trocando  partner_name por partner_id (crm_opportunity_view.xml) corrige:

>             <field name="partner_id" position="after">
>                 <field name="legal_name"/>
>                 <field name="cnpj"/>
>                 <field name="inscr_est"/>
>                 <field name="inscr_mun"/>
>                 <field name="suframa"/>

**Comment by renatonlima** [comment]
Olá @fmnapoli, 

Obrigado por reportar o erro, provavelmente é apenas um erro da visão, vou subir um PR para corrigir este bug.

**Comment by renatonlima** [comment]
@fmnapoli Eu fiz o PR #679 você pode fazer o review?

**Comment by fmnapoli** [comment]
Os campos legal_name, cnpj, inscr_est e suframa não aparecem no form Oportunidade, verifiquei que trocando partner_name por partner_id (crm_opportunity_view.xml) corrige:

>         <field name="partner_id" position="after">
>             <field name="legal_name"/>
>             <field name="cnpj"/>
>             <field name="inscr_est"/>
>             <field name="inscr_mun"/>
>             <field name="suframa"/>

**Comment by fmnapoli** [comment]
Agora tá ok!
