### ISSUE TITLE
Linhas do lançamento do diário com valores de débito/crédito 0,00

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#68]
Ao contabilizar um documento fiscal, existe alguns casos em que são geradas linhas de lançamentos de diário com os campos de crédito e débito iguais a zero, o que gera uma serie de registros inúteis da contabilidade, seria importante ao gerar a contabilização dos documentos e dos lançamentos do diário ter uma consistência para não permitir lançamentos com valores de débito/crédito iguais a 0,00.

**Comment by mileo** [comment]
info:progress-50

**Comment by mileo** [comment]
@renatonlima  Fechamos esse issue? Ou falta o pull para a 7.0?

**Comment by mileo** [comment]
@renatonlima FIXED

**Comment by mileo** [comment]
@renatonlima Please close this issue
