### ISSUE TITLE
Contabilização dos documentos fiscais que não existe movimentação financeira

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#69]
Hoje quando são criados documentos fiscais que não tem movimentação financeira na contabilidade os lançamentos não são feitos corretamente, pois ficam apenas uma parte do lançamento, é necessário a implementação de uma rotina que ao ser confirmado um documento fiscal sem movimentação financeira seja automaticamente feito todos os lançamentos para o documento fiscal não ficar eternamente com status de "aberto".

**Comment by mileo** [comment]
@renatonlima Marca pra mim 8.0

**Comment by danimaribeiro** [comment]
Um caso que isto é necessário é nas notas de simples remessa e faturamento antecipado.
Achei este link com um exemplo de como ficam os impostos e os lançamentos contábeis:

http://www.contabeis.com.br/forum/topicos/15988/faturamento-antecipado-versus-venda-para-entrega-f/

Pelo exemplo 1 apresentado, esta talvez opção talvez não seja o correto.
"seja automaticamente feito todos os lançamentos para o documento fiscal"

Para o exemplo 2, poderia ser feito o lançamento automático:
D - Venda para Entrega Futura (PC) R$ 10.000,00 
C - Receita de Vendas (CR) R$ 10.000,00
