### ISSUE TITLE
[12.0][RFC] Migração e refactoring dos módulos l10n_br_account e l10n_br_account_product

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#699]
Olá pessoal,

Estou escrevendo este RFC para documentar as modificações da localização brasileiras para a versão 12.0, atualmente os principais módulos da localização brasileira já foram migrada para a versão 10.0 e os módulos básicos da localização também já foram portados para a versão 12.0. Os módulos mais localizados e críticos da localização serão refatorados para melhorar a estrutura e dar suporte a mais funcionalidades contábeis e fiscais, a estrutura atual dos módulos contábeis e fiscais:

![image](https://user-images.githubusercontent.com/211005/58279625-442dab00-7d75-11e9-80d3-cdc7f7a1ac0a.png)

O Diagrama acima representa apenas os módulos responsáveis pelo calculo dos impostos e gestão do documento eletrônico NF-e.

O objetivo deste refatoramento é melhorar a modularização da localização para dar suporte:

* Mais documentos fiscais (nfe, nfse, cte, gnre, mdfe)
* Simplificar parametrização fiscal
* Melhorar a comunicação com a Sefaz
* Gerenciar os schemas dos documentos fiscais de forma automatizada
* Geração dos arquivos do SPEDs Fiscal (ICMS IPI, Contribuições, Reinf)
* Melhorar a contabilização dos lançamento e adequar algumas operações para as normas brasileiras

Com base nestes objetivos, a modularização da localização fiscaria desta forma:

![image](https://user-images.githubusercontent.com/211005/58280151-607e1780-7d76-11e9-83d6-c2e8f64973bc.png)

* **fiscal**: #657 Refatoramento dos módulos l10n_br_account e l10n_br_account_product, não tem dependência com o módulo account do core e armazena os dados fiscais, e calculo dos impostos, sendo o módulo base para gestão dos documentos fiscais;

* **l10n_br_account**: Módulo que vai integrar o fiscal com o módulo account

* **nfe**: #694 Módulo responsável pela a gestão da NF-e
* **nfe_specs**: #658 Módulo com os schemas e objetos da NF-e

* **nfse**: Módulo responsável pela a gestão da NFS-e
* **nfse_specs**: #662 Módulo com os schemas e objetos da NFS-e

* **cte**: Módulo responsável pela a gestão do CT-e
* **cte_specs**: #661 Módulo com os schemas e objetos do CT-e

* **mdfe**: Módulo responsável pela a gestão da MDF-e
* **mdfe_specs**: #660 Módulo com os schemas e objetos da da MDF-e

* **gnre**: Módulo responsável pela a gestão da GNRE-e
* **gnre_specs**: #663 Módulo com os schemas e objetos da GNRE-e

A modularização pode ser acompanhada neste PR #694 o módulo fiscal apesar de ainda esta sendo refatorado, já pode é possível instala-lo, caso tenha alguma dúvida ou sugestão ao projeto fique livre para faze-la.

**Comment by renatonlima** [comment]
Segue algums imagens do módulo fiscal:

![image](https://user-images.githubusercontent.com/211005/58281682-126b1300-7d7a-11e9-82a9-0e55734bdf6b.png)

![image](https://user-images.githubusercontent.com/211005/58281701-2151c580-7d7a-11e9-87b6-952477563829.png)

![image](https://user-images.githubusercontent.com/211005/58281718-2b73c400-7d7a-11e9-9590-3425edb42a33.png)

**Comment by marcos-mendez** [comment]
Po ficou top, valeu pela explicação

**Comment by marcos-mendez** [comment]
@renatonlima só uma dúvida que não entendi, o NFS-e é tipo uma NF-e só que do account_service?

**Comment by rvalyi** [comment]
> @renatonlima só uma dúvida que não entendi, o NFS-e é tipo uma NF-e só que do account_service?

Ola @marcos-mendez a NFSe eh um l10n_br_fiscal.document particular, implementado atraves desse novo modulo https://github.com/OCA/l10n-brazil/tree/12.0/l10n_br_nfse e geralmente derivado para cada familia de NFSe (Ginfes, Betha...)
Veja um exemplo para Ginfes aqui https://github.com/OCA/l10n-brazil/pull/942

Geralmente, uma NFSe eh gerido atraves de um account.invoice Odoo (entao por uma venda do modulo sale por examplo), mas pode ser tb lancada de forma independente de um account.invoice (caso de uso raro a meu ver).
