### ISSUE TITLE
Incluir NCM/Classificação fiscal nas linhas de mapeamento da posição fiscal

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#70]
Para uma maior flexibilidade na configuração dos impostos, deve ser incluído o campo NCM/Classificação Fiscal para permitir se seja criados mapeamentos de impostos por NCM/Classificação Fiscal, desta forma evitamos que seja criadas muitas posições fiscais e regras de posições fiscais.

**Comment by renatonlima** [comment]
O desenvolvimento deste recurso esta em andamento.

**Comment by mileo** [comment]
Feito

**Comment by renatonlima** [comment]
Eu já implementei esta funcionalidade na OCA/8.0
