### ISSUE TITLE
[12.0] Campo com o número FCI deve ser validado

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#712]
O Campo Número de FCI no cadastro de produtos e linha do documento fiscal deve conter uma validação pois esse número é um GUID e deve conter apenas números e letras (de A a F) hexadecimal, é possível validar usando a lib uuid.

**Comment by mileo** [comment]
Seria interessante colocar esta lidação na lib https://github.com/erpbrasil/erpbrasil.base

**Comment by rvalyi** [comment]
lembrando que qdo chegar ao nivel de modulos que implementam documentos fiscais como da NFe, tem uma porrada de validações de REGEXP que sera feita pelos validadores do generateDS. Mas qdo a validação tem que ser mais inteligente, como ter unicidade/GUID, ou ainda que o campo pode ser usado fora do contexto do documento fiscal, ai eh valido sim de criar a validação manualemente e ate no modulo erpbrasil.base qdo for o caso.
