### ISSUE TITLE
runbot builds fail with a timeout. 

### ISSUE THREAD

**Issue by gurneyalex** [OCA/l10n-brazil#728]
All builds get killed.

reported by @rvalyi

**Comment by gurneyalex** [comment]
This is caused by the use of sudo to change the locale.

travis2docker runs this with the odoo user, and then sudo hangs for a password prompt during `docker build` and the job gets killed.

**Comment by gurneyalex** [comment]
Attempt to fix this is in https://github.com/Vauxoo/travis2docker/pull/126

**Comment by renatonlima** [comment]
Now runbot works! I will close this issue.

thanks @gurneyalex for your help.
