### ISSUE TITLE
[12.0] l10n_br_hr Tests

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#747]
Os módulo da localização na versão 12.0 tem uma cobertura de testes de 91% a 97%, em uma das últimas analises o módulo l10n_br_hr https://coveralls.io/builds/26400402 esta com uma cobertura de 81%, seria importante aumentar a cobertura de testes do módulo.

cc @hendrixcosta @mileo

**Comment by mileo** [comment]
Issue duplicado: https://github.com/OCA/l10n-brazil/issues/736
