### ISSUE TITLE
[12.0] Implementação de Features do módulo l10n_br_base

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#762]
No PR #600 

Foi fechado, mas existe algumas features que podemos implementar no módulo l10n_br_base na branch 12.0:

* Parâmetros de sistema para habilitar ou desabilitar as validações dos campos de CPF/CNPJ, IE;
* No res.city adicionar os campos: siafi_code (Código SIAFI), anp_code(Código ANP);
* Adicionar no res.partner crc_code (Conselho Regional de Contabilidade), crc_uf (UF do CRC), 
rntrc_code (RNTRC), cei_code (CEI).

**Comment by hendrixcosta** [comment]
Resolvido no PR https://github.com/OCA/l10n-brazil/pull/774

**Comment by rvalyi** [comment]
valeu @hendrixcosta
