### ISSUE TITLE
Reimplement account.invoice.report

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#784]
Reimplement accoint.invoice.report as removed in:

https://github.com/OCA/l10n-brazil/pull/782/commits/48cb5681503aa6ab2f3cc3ce8d941f816c207e78

Similar to version 8: https://github.com/OCA/l10n-brazil/blob/8.0/l10n_br_account/report/account_invoice_report.py but with 12.0 fields.

**Comment by mbcosta** [comment]
Hi @mileo , it is done on last June https://github.com/OCA/l10n-brazil/blob/12.0/l10n_br_account/report/account_invoice_report.py , please check if everything is right to close this issue.
