### ISSUE TITLE
Rename l10n_br_account to l10n_br_account_fiscal

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#792]
Rename l10n_br_account to l10n_br_account_fiscal to open space to create a dedicated accounting module.

**Comment by antoniospneto** [comment]
@OCA/local-brazil-maintainers 

isso eu também acho interessante, hoje o l10n_br_account é totalmente voltado para fazer a integração do account x fiscal.

Fazendo a pr para incluir os dados da chaves pix, percebi que faz falta um módulo especifico para herdar as funcionalidades básicas do account, sem ter que puxar o fiscal junto.

**Comment by rvalyi** [comment]
Olá @netosjb. De um lado vc tem razão, puxamos logo o l10n_br_fiscal, pois é graça a ele que o básico da contabilidade financeira pode funcionar. Mas olha que temos TB alguns módulos que dependem do account sem depender do fiscal.

Por outro lado, vc tem que ver que o próprio módulo account do Odoo, apesar do nome, virou meramente um módulo de faturamento. Que TB cuida minimamente dos lançamentos e olha que de um jeito até meio escondido no Odoo CE. Nisso na OCA, os vários outros aspectos da contabilidade estão trazido por dezenas de outros módulos. Módulos que podem muito bem ser estendidos na localização, como fazemos pro CNAB por exemplo.

Considerando o fato que o próprio módulo account já tem um nome não muito apropriado e considerando o trabalho que daria de mudar o nome (imagina os cherry-pick iriam deixar de funcionar por examplo) eu não sei se vale muito a pena... O que certamente vale a pena é ter um README que explica o scope do módulo isso sim. A gente tava mais preocupado em fazer o básico da migração para a v14, mas agora a gente pode de novo pensar nessas coisas para explicar melhor os módulos.
