### ISSUE TITLE
Transformar o campo propriedade property_fiscal_classification para um campo relacional ncm_id

### ISSUE THREAD

**Issue by renatonlima** [OCA/l10n-brazil#8]
Hoje a classificação fiscal dos produtos é um campo prorperty e deve ser definido para cada empresa, o que gera um retrabalho quando existe mais de uma empresas no OpenERP, A sugestão é criar um novo campo chamado ncm_id do tipo many2one permitindo que seja definida o ncm para todas as empresas, facilitando a configuração fiscal.

**Comment by renatonlima** [comment]
Desenvolvimento já realizado na branch develop

**Comment by rvalyi** [comment]
Futuramente talvez a gente pode propor um upstream da funcionalidade no product_account_fiscal_calssification...
