### ISSUE TITLE
Tabela de NCM esta sendo deletada ao atualizar o fiscal

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#836]
Pessoal ainda não consegui diagnosticar este problema com calma, mas percebi que a tabela de NCM esta sendo deletada ao atualizar o fiscal.

O @gabrielcardoso21 tb comentou estar com um problema parecido.  Vou ver se o erro se repete e posto o log aqui.

**Comment by hendrixcosta** [comment]
Tive esse problema também =\

**Comment by gabrielcardoso21** [comment]
Eu consegui resolver esse problema mudando no arquivo hooks todos os parâmetros noupdate setados para True na instalação. Nas vezes em que me esqueci de fazer isso na instalação tive que mudar no banco os ir_model_data, setando o noupdate como true para os registros dos modelos l10n_br_fiscal.ncm, l10n_br_fiscal.nbm, l10n_br_fiscal.nbs e l10n_br_fiscal.cest.

**Comment by marcelsavegnago** [comment]
Eu estava testando os addons do fiscal no openupgrade e tinha dado uns paus por conta do arquivo de migração que estão neste módulo.. Masss lembro se tinha relação e não aprofundei o teste mas tive que "retirar" o arquivo pre-migration para conseguir rodar.

**Comment by rvalyi** [comment]
vcs estao falando de prod ou de demo? Se for demo seria esperado por conta de https://github.com/OCA/l10n-brazil/pull/819
Agora se for prod, eh um problema...

**Comment by hendrixcosta** [comment]
MAs em base demo, as tabelas deverão ser deletadas e instanciadas novamente na atualização do módulo l10n_br_fiscal ?
