### ISSUE TITLE
Erro ao instalar l10n_br_fiscal em nova instalação limpa

### ISSUE THREAD

**Issue by mliell** [OCA/l10n-brazil#847]
Módulo Fiscal
Instalação nova, limpa. (Testei em VM a partir do docker e na minha máquina, obtive o mesmo erro em ambas)
Exception: Cannot update missing record 'base.user_demo'
Detalhe: instalação sem dados de demonstração.

Erro completo:
https://pastebin.com/nrBwPnun

**Comment by marcelsavegnago** [comment]
@mliell ./core/odoo-bin -c odoo.conf -d basenova -i l10n_br_account,l10n_br_fiscal --without-demo=all --stop-after-init

Ou arruma este parametro no odoo.conf -> without-demo=all

**Comment by rvalyi** [comment]
Na vdd, apenas  -i l10n_br_account ja basta e puxa o l10n_br_fiscal

**Comment by mliell** [comment]
Obrigado pelo feedback @marcelsavegnago e @rvalyi !  Funcionou. Fica o issue para identificação e correção no código.
