### ISSUE TITLE
[RFC] Escrituração Nota de entrada

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#890]
https://docs.google.com/document/d/1W5ClrYWdVoXNqZKUgJSzCbFwvRDm-s6R-F8kC5ZAets/edit#

@renatonlima @rvalyi

**Comment by marcelsavegnago** [comment]
Transcrevendo o documento do drive.

## Necessidade: 
Permitir a escrituração correta dos diversos documentos fiscais de entrada através do módulo l10n_br_fiscal

O modelo l10n_br_fiscal.document deve permitir a inserção manual ou através de automação, que o usuário visualize uma cópia fiel do documento que se está dando entrada no sistema.

## Premissas 

1. Alguns campos devem ser imutáveis:
2. A descrição do produto do fornecedor;
3. O código do produto;
4. Unidade de medida;
5. Atributação e os campos calculados;

Alguns campos devem ser linkados com modelos do ERP:

1. O “código e descrição” deve ser linkado com o produto do ERP;
2. Devemos ter a quantidade e a unidade de medida do ERP, convertendo os dados da unidade de medida do documento e sua quantidade;

Alguns campos são de importância fiscal e devem ser escriturados manualmente pelo usuário:

1. Documentos Fiscais: Nota fiscal em Papel, CT-E, NF-E e etc :
1.1. CFOP de Saída vs Entrada;
1.2. CST de Saída vs Entrada;

### Linhas do documento fiscal

As linhas do documento fiscal que ainda não foram escrituradas, devem ser destacadas em vermelho, chamando a atenção do usuário;

As escrituradas devem ser marcadas em azul;

### Automatização / Inteligência Fiscal

Caso um produto já tenha sido importado uma primeira vez, na segunda vez o mapeamento dos requisitos acima deve ser facilitado:

1. Os produtos devem ser mapeados com os dados da última compra deste fornecedor e/ou com os dados do cadastro do produto do fornecedor (product.supplierinfo ou outro modelo pertinente);
2. Os produtos mapeados automaticamente devem ser marcados de amarelo;

### Wizards para facilitar a escrituração

TODO

### Integração com outros módulos

#### Integração com o Faturamento/Account

_Código a ser implementado no l10n_br_account_

Quando o documento for confirmado o mesmo deve gerar a fatura e nesse caso temos que contemplar os seguintes cenários:

1. A tributação de um dos itens está incorreta, conforme a parametrizada no sistema;
2. Geração das parcelas / contabilidade;

#### Integração com o Estoque
Código a ser implementado no l10n_br_stock_account

Deve ser gerada uma movimentação de estoque caso necessário, o custo do produto deve ser observado.

1. A quantidade de produtos recebidas se comparada ao documento fiscal está incorreta:
1.1. Será gerada uma nota de devolução;
1.2. O valor da fatura será alterado a maior ou a menor;
1.3. O produto e a unidade de medida já estará na unidade e produto do ERP;

#### Integração com Compras
Código a ser implementado no l10n_br_purchase

Caso o documento fiscal esteja associado a um pedido de compra, deve ser validado o preço dos itens.

**Não obrigatório:** Também deve ser possível chamar o wizard de escrituração a partir dos itens do pedido de compras.
