### ISSUE TITLE
[12.0][RFC] Módulo de Controle de EPIs - OCA/hr

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#892]
Pessoal, 

Estamos trabalhando no desenvolvimento de controle de EPIs. A principio, não estamos trabalhando já considerando dados do e-social até porque estamos submetendo o módulo para o projeto OCA/hr. Porém, entendemos que um dos requisitos para seguir com este projeto é que o mesmo sirva de base para projetos futuros como o e-Social que faz a entrega de informações pertinentes aos EPIs.

Segue o link da PR. Qualquer dúvida, critica ou sugestão será bem vinda.

https://github.com/OCA/hr/pull/846

Pré-requisitos:

- [ ] Alinhamento com o projeto da localização Brasil (aceite do PSC e contribuidores ativos)
- [x] Alinhamento com os interesses dos membros do projeto OCA/hr
- [x] PR Aceita e mesclada

**Comment by mileo** [comment]
@hendrixcosta

**Comment by marcelsavegnago** [comment]
Módulo criado https://github.com/OCA/hr/pull/846
