### ISSUE TITLE
[12.0][RFC] Tradução Módulos Core

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#896]
Relacionei alguns módulos do core que precisam de ajuda com a tradução.

Quem quiser colaborar pode acessar o link abaixo para saber como.. é bem fácil:

https://github.com/OCA/l10n-brazil/blob/12.0/CONTRIBUTING.md#tradu%C3%A7%C3%A3o-do-core

Peço que sinalizem aqui pela Issue os módulos que foram traduzidos

https://www.transifex.com/odoo/odoo-12/language/pt_BR/

- [x] account
- [x] account_payment
- [x] analytic
- [x] auth_oauth
- [x] auth_password_policy_signup
- [ ] base
- [x] board
- [ ] crm
- [ ] crm_phone_validation
- [x] decimal_precision
- [ ] delivery
- [ ] digest
- [ ] event
- [ ] fleet
- [x] hr
- [ ] ht_appraisal
- [x] hr_attendance
- [ ] hr_contract
- [ ] hr_contract_salary
- [ ] hr_holidays
- [ ] hr_recruitment
- [ ] hr_timesheet
- [ ] lunch
- [ ] mail
- [ ] mrp
- [ ] mrp_account
- [ ] mrp_bom_cost
- [ ] mrp_byproduct
- [ ] mrp_workorder
- [x] partner_autocomplete
- [x] payment
- [x] point_of_sale
- [x] portal
- [x] product
- [ ] project
- [x] purchase
- [x] purchase_stock
- [ ] resource
- [ ] sale
- [x] sale_management
- [x] sale_purchase
- [x] sale_quotation_builder
- [ ] sale_team
- [x] sale_stock
- [x] stock
- [x] stock_account
- [x] stock_dropshipping
- [ ] uom
- [ ] web
- [ ] website
- [x] theme_bootswatch 
- [x] payment_paypal 
- [x] mass_mailing_sale
- [x] pos_cash_rounding
- [x] base_automation_hr_contract
- [x] website_partner

@mileo @rvalyi @renatonlima @hendrixcosta se tiver algum módulo que acreditam que deve ser incluído aqui  ou que precise de prioridade.. por favor informem.

Obs. Módulos OCA podemos abrir outra PR e deixar esta somente para o core.

**Comment by rvalyi** [comment]
valeu @marcelsavegnago .
Seguem 2 modulos OCA que usamos em quase todos os projetos e que nao estao bem traduzidos:
https://github.com/OCA/account-financial-tools/tree/12.0/account_move_template
https://github.com/OCA/bank-payment/blob/12.0/account_payment_mode (para CNAB/boletos)

**Comment by mileo** [comment]
@marcelsavegnago será que vc consegue criar um dicionário de termos?

Pode ser uma planilha no google docs por hora.

Pois tem muitas traduções que em cada lugar esta de um jeito, creio que esse seja o principal problema.

Obrigado.

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago será que vc consegue criar um dicionário de termos?
> 
> Pode ser uma planilha no google docs por hora.
> 
> Pois tem muitas traduções que em cada lugar esta de um jeito, creio que esse seja o principal problema.
> 
> Obrigado.

@mileo consigo.. vou criar uma pagina wiki para isso.. oq acha ?

**Comment by marcelsavegnago** [comment]
> valeu @marcelsavegnago .
> Seguem 2 modulos OCA que usamos em quase todos os projetos e que nao estao bem traduzidos:
> https://github.com/OCA/account-financial-tools/tree/12.0/account_move_template
> https://github.com/OCA/bank-payment/blob/12.0/account_payment_mode (para CNAB/boletos)

@rvalyi 

https://github.com/OCA/l10n-brazil/issues/897
https://github.com/OCA/l10n-brazil/issues/898

**Comment by mileo** [comment]
> > @marcelsavegnago será que vc consegue criar um dicionário de termos?
> > Pode ser uma planilha no google docs por hora.
> > Pois tem muitas traduções que em cada lugar esta de um jeito, creio que esse seja o principal problema.
> > Obrigado.
> 
> @mileo consigo.. vou criar uma pagina wiki para isso.. oq acha ?

Pode ser tb, se não ficar mais complicado de usar.... Se não bota um link pra planilha no wiki.

**Comment by marcelsavegnago** [comment]
> > > @marcelsavegnago será que vc consegue criar um dicionário de termos?
> > > Pode ser uma planilha no google docs por hora.
> > > Pois tem muitas traduções que em cada lugar esta de um jeito, creio que esse seja o principal problema.
> > > Obrigado.
> > 
> > 
> > @mileo consigo.. vou criar uma pagina wiki para isso.. oq acha ?
> 
> Pode ser tb, se não ficar mais complicado de usar.... Se não bota um link pra planilha no wiki.

Blzz..

**Comment by mileo** [comment]
A planilha é facil pra criarmos comentários e marcarmos as pessoas caso tenhamos dúvidas, depois que tivermos o dicionário determos, colocamos no wiki.

**Comment by marcelsavegnago** [comment]
@mileo comecei na wiki mas se precisar jogo em uma planilha e vou ordernar pelo termo em inglês.

https://github.com/OCA/l10n-brazil/wiki/Dicion%C3%A1rio-de-Termos

**Comment by fcolus** [comment]
> Relacionei alguns módulos do core que precisam de ajuda com a tradução.
> 
> https://www.transifex.com/odoo/odoo-12/language/pt_BR/
> 
> * [x]  account
> * [x]  account_payment
> * [x]  analytic
> * [x]  auth_oauth
> * [x]  auth_password_policy_signup
> * [x]  base
> * [x]  board
> * [x]  crm
> * [x]  crm_phone_validation
> * [x]  decimal_precision
> * [x]  delivery
> * [x]  digest
> * [ ]  event
> * [ ]  fleet
> * [ ]  hr
> * [ ]  ht_appraisal
> * [ ]  hr_attendance
> * [ ]  hr_contract
> * [ ]  hr_contract_salary
> * [ ]  hr_holidays
> * [ ]  hr_recruitment
> * [ ]  hr_timesheet
> * [ ]  lunch
> * [ ]  mail
> * [ ]  mrp
> * [ ]  mrp_account
> * [ ]  mrp_bom_cost
> * [ ]  mrp_byproduct
> * [ ]  mrp_workorder
> * [ ]  partner_autocomplete
> * [ ]  payment
> * [ ]  point_of_sale
> * [ ]  portal
> * [ ]  product
> * [ ]  project
> * [ ]  purchase
> * [ ]  purchase_stock
> * [ ]  resource
> * [ ]  sale
> * [ ]  sale_management
> * [x]  sale_purchase
> * [x]  sale_quotation_builder
> * [ ]  sale_team
> * [x]  sale_stock
> * [x]  stock
> * [ ]  stock_account
> * [ ]  stock_dropshipping
> * [ ]  uom
> * [ ]  web
> * [ ]  website
> 
> Para conseguir traduzir o máximo possível é importante que outras pessoas possam ajudar na tradução. Quem estiver interessado pode obter mais informações no link abaixo:
> 
> https://github.com/OCA/l10n-brazil/blob/12.0/CONTRIBUTING.md#tradu%C3%A7%C3%A3o-do-core
> 
> E para fins de acompanhamento acredito que seja válido sinalizar aqui na Issue qual módulo foi concluído.
> 
> @mileo @rvalyi @renatonlima @hendrixcosta se tiver algum módulo que acreditam que deve ser incluído aqui ou que precise de prioridade.. por favor informem.
> 
> Obs. Módulos OCA podemos abrir outra PR e deixar esta somente para o core.

Últimos módulos traduzidos
The resource website_partner of the project Odoo 12.0 has been 100% translated in Portuguese (Brazil).
The resource base_automation_hr_contract of the project Odoo 11.0 has been 100% translated in Portuguese (Brazil).
The resource base_automation_hr_contract of the project Odoo Master has been 100% translated in Portuguese (Brazil).
The resource base_automation_hr_contract of the project Odoo 13.0 has been 100% translated in Portuguese (Brazil).
The resource base_automation_hr_contract of the project Odoo 12.0 has been 100% translated in Portuguese (Brazil).
The resource pos_cash_rounding of the project Odoo 12.0 has been 100% translated in Portuguese (Brazil).
The resource mass_mailing_sale of the project Odoo 12.0 has been 100% translated in Portuguese (Brazil).
The resource payment_paypal of the project Odoo 11.0 has been 100% translated in Portuguese (Brazil).
The resource payment_paypal of the project Odoo 12.0 has been 100% translated in Portuguese (Brazil).
The resource theme_bootswatch of the project Odoo 13.0 has been 100% translated in Portuguese (Brazil).

**Comment by marcelsavegnago** [comment]
@fcolus pode focar apenas na versão 12.0. A 11.0 e 13.0 não precisa focar em traduzir.

**Comment by marcelsavegnago** [comment]
Módulos adicionais traduzidos.

- [x] theme_bootswatch 
- [x] payment_paypal 
- [x] mass_mailing_sale
- [x] pos_cash_rounding
- [x] base_automation_hr_contract
- [x] website_partner

@fcolus todas as traduções são válidas mas se puder priorizar os itens da lista é melhor.
Vlwww

**Comment by mliell** [comment]
Traduzido:
portal

**Comment by mliell** [comment]
Traduzido:
product

**Comment by mliell** [comment]
Traduzido:
partner_autocomplete

**Comment by mliell** [comment]
Traduzido:
decimal_precision

**Comment by fcolus** [comment]
TRADUZIDOS
 account
 account_payment
 analytic
 auth_oauth
 auth_password_policy_signup
 board

**Comment by marcelsavegnago** [comment]
@fcolus valeu. Já atualizei o controle dos módulos feitos.

**Comment by vanderleiromera** [comment]
Payment concluido

**Comment by vanderleiromera** [comment]
sale_purchase concluido

**Comment by and2carvalho** [comment]
Traduzido: hr e hr_attendance
*só a parte de mensagens motivacionais que vai ser necessário alguem da área de rh msm rsrs

**Comment by vanderleiromera** [comment]
sale_stock concluido

**Comment by vanderleiromera** [comment]
sale_quotation_builder concluido

**Comment by vanderleiromera** [comment]
stock concluído

**Comment by vanderleiromera** [comment]
stock_account, 
stock_dropshipping, 
sale_management 
concluído

**Comment by vanderleiromera** [comment]
purchase_stock concluído.

**Comment by vanderleiromera** [comment]
point_of_sale concluido.

**Comment by vanderleiromera** [comment]
Purchase concluído.

**Comment by marcelsavegnago** [comment]
Fechando a Issue. Acredito que o agora devemos mudar o foco para v14 e/ou v15
