### ISSUE TITLE
[12.0][RFC] Tradução Projeto OCA/account-financial-tools

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#897]
Módulos do projeto OCA/account-financial-tools que ainda não estão com a tradução em 100% 

https://translation.odoo-community.org/projects/account-financial-tools-12-0/

- [x] [account_move_template](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_move_template/pt_BR/)
- [ ] [account_loan](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_loan/pt_BR/)
- [x] [account_cost_center](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_cost_center/pt_BR/)
- [x] [account_chart_update](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_chart_update/pt_BR/)
- [x] [account_check_deposit](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_check_deposit/pt_BR/)
- [x] [account_renumber](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_renumber/pt_BR/)
- [x] [account_invoice_currency](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_invoice_currency/pt_BR/)
- [x] [account_fiscal_month](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_fiscal_month/pt_BR/)
- [x] [account_move_fiscal_month](https://translation.odoo-community.org/projects/account-financial-tools-12-0/account-financial-tools-12-0-account_move_fiscal_month/pt_BR/)

Quem quiser ajudar pode acessar este link para obter mais informações no link abaixo:

https://github.com/OCA/l10n-brazil/blob/12.0/CONTRIBUTING.md#tradu%C3%A7%C3%A3o-oca

E para fins de acompanhamento acredito que seja válido sinalizar aqui na Issue qual módulo foi concluído.

**Comment by mliell** [comment]
Traduzido
account_cost_center

**Comment by mliell** [comment]
Traduzido 
account_renumber

**Comment by mliell** [comment]
Traduzido:
account_move_template

**Comment by mliell** [comment]
Traduzido:
account_fiscal_month
account_move_fiscal_month
account_invoice_currency

**Comment by mliell** [comment]
Traduzido:
account_check_deposit
