### ISSUE TITLE
[12.0][RFC] Tradução módulo OCA/bank-payment/account_payment_mode

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#898]
Tradução do módulo OCA/bank-payment/account_payment_mode

https://translation.odoo-community.org/projects/bank-payment-12-0/bank-payment-12-0-account_payment_mode/pt_BR/

Obs. Já estou finalizando

**Comment by marcelsavegnago** [comment]
@rvalyi  e @mileo estou finalizando a tradução do account_payment_mode. 

Dúvida sobre a tradução dos seguintes termos:

Texto Original | Texto Traduzido
-- | --
Payment Method | Método de Pagamento
Payment Mode | Modo de Pagamento

 Podemos seguir assim ou tem alguma sugestão?

**Comment by mileo** [comment]
Isso é um grande dilema.

Do meu ponto de vista, temos os seguintes conceitos:

Forma de pagamento:

12x no cartão
Débito a vista
Dinheiro a vista
Cheque 30/60
Boleto 30/60/90

(Assusta um pouco, mas manter o modo de pagamento junto com a forma, facilita os dados do SPED, da NF-e, PDV e 9 cálculo de juros, descontos e condições.)

Entendido isso vamos para os próximos conceitos:

O boleto por exemplo pode ser gerado através de diversas carteiras de cobrança.

A transferência, também: Ted, doc, pix e etc.

E existe o meio de transmissão, pode ser por cnab240, 400, API, manual e etc.

Então na venda/compra vc define as condições e descontos conforme o "plano de pagamento : forma e modo"

E na hora da efetivação do pagamento isso pode ser alterado por diversos motivos: do lado do cliente, operacionais e do lado do banco.

Por exemplo se vc está gerando uma cobrança em boleto que vc não tem certeza que o cliente irá pagar, por exemplo um e-commerce. Vc deve usar a carteira que vc não paga por registro de boleto, somente para as taxas caso o cliente pague.

Já no caso de vendas b2b vc usa a carteira q vc paga quando registra o boleto, pois tem "aceite" e tb as taxas bancárias são muito mais baratas.

Então:

Na minha opinião a melhor opção é:

Usar o account.payment.term como forma de pagamento e nela embutir o modo, por exemplo:

[Crédito] 12x
[Cheque] 30/60/90

Usar o payment mode parar o conceito de carteira.

E o payment method para a forma de transmissão.

Vai ser a forma que menos vamos precisar adaptar tudo, mantendo menos código.

Isso se associa com os pr #820 e do boleto que o @mbcosta está trabalhando e seu último comentário.

Precisamos definir isso certinho.

Obs: respondi do celular, se precisarem de links depois eu coloco.

**Comment by mileo** [comment]
cc: @rvalyi e @renatonlima

**Comment by marcelsavegnago** [comment]
@mileo eu acho que faz sentido e não descaracteriza o produto

Dados demo de Modos de Pagamento
![image](https://user-images.githubusercontent.com/3595132/84533048-c1e49180-acbd-11ea-9be9-33d907c7eaba.png)

Dados demo de Métodos de Pagamento
![image](https://user-images.githubusercontent.com/3595132/84533015-b42f0c00-acbd-11ea-9398-df76991e72f3.png)

**Comment by marcos-mendez** [comment]
> Isso é um grande dilema.
> 
> Do meu ponto de vista, temos os seguintes conceitos:
> 
> Forma de pagamento:
> 
> 12x no cartão
> Débito a vista
> Dinheiro a vista
> Cheque 30/60
> Boleto 30/60/90
> 
> (Assusta um pouco, mas manter o modo de pagamento junto com a forma, facilita os dados do SPED, da NF-e, PDV e 9 cálculo de juros, descontos e condições.)
> 
> Entendido isso vamos para os próximos conceitos:
> 
> O boleto por exemplo pode ser gerado através de diversas carteiras de cobrança.
> 
> A transferência, também: Ted, doc, pix e etc.
> 
> E existe o meio de transmissão, pode ser por cnab240, 400, API, manual e etc.
> 
> Então na venda/compra vc define as condições e descontos conforme o "plano de pagamento : forma e modo"
> 
> E na hora da efetivação do pagamento isso pode ser alterado por diversos motivos: do lado do cliente, operacionais e do lado do banco.
> 
> Por exemplo se vc está gerando uma cobrança em boleto que vc não tem certeza que o cliente irá pagar, por exemplo um e-commerce. Vc deve usar a carteira que vc não paga por registro de boleto, somente para as taxas caso o cliente pague.
> 
> Já no caso de vendas b2b vc usa a carteira q vc paga quando registra o boleto, pois tem "aceite" e tb as taxas bancárias são muito mais baratas.
> 
> Então:
> 
> Na minha opinião a melhor opção é:
> 
> Usar o account.payment.term como forma de pagamento e nela embutir o modo, por exemplo:
> 
> [Crédito] 12x
> [Cheque] 30/60/90
> 
> Usar o payment mode parar o conceito de carteira.
> 
> E o payment method para a forma de transmissão.
> 
> Vai ser a forma que menos vamos precisar adaptar tudo, mantendo menos código.
> 
> Isso se associa com os pr #820 e do boleto que o @mbcosta está trabalhando e seu último comentário.
> 
> Precisamos definir isso certinho.
> 
> Obs: respondi do celular, se precisarem de links depois eu coloco.

Carteira de crédito interno você se refere quando você fala do Payment_Mode @mileo ?

**Comment by marcelsavegnago** [comment]
@mileo e @rvalyi traduzi este módulo e utilizei os termos que eu havia citado acima https://github.com/OCA/l10n-brazil/issues/898#issuecomment-642968708

**Comment by mbcosta** [comment]
ola @mileo vou precisar entender melhor a necessidade e as justificativas para juntar o Modo de Pagamento com a Forma de Pagamento, veja hoje por estarem separados esses campos permitem uma configuração com menos dados:
Hoje

Modo de Pagamento
Boleto A
Boleto B
Cheque

Forma de Pagamento
30/60/90
45/90/120
15/30/45

O operador seleciona 2 campos no Pedido de Venda/Compra ou Documento Fiscal. Sua proposta seria ter isso junto

Modo/Forma de Pagamento
Boleto A 30/60/90
Boleto A 45/90/120
Boleto A 15/3045
Boleto B 30/60/90
Boleto B 45/90/120
Boleto B 15/3045
Cheque 30/60/90
Cheque 45/90/120
Cheque 15/3045
 
Existe também um questão de isso poderia alterar o comportamento de outros modulos que usam esses objetos. A sua justificativa para alteração seria  "(Assusta um pouco, mas manter o modo de pagamento junto com a forma, facilita os dados do SPED, da NF-e, PDV e 9 cálculo de juros, descontos e condições.)" por isso pergunto

Aonde facilita os dados do SPED, da NF-e, PDV  ? Pelo o que entendo o SPED é um DE PARA de documentos fiscais, portanto poderiam ser mapeados de forma independente já que até onde sei eles também estão separados nos documentos fiscais, ou não ?

Acredito que essa parte " cálculo de juros, descontos e condições." e "Então na venda/compra vc define as condições e descontos conforme o "plano de pagamento : forma e modo"" são os motivos que levaram vocês a juntarem esses objetos, seria isso ? 

Porque que se for a minha sugestão seria que poderíamos criar um novo modulo Plano de Pagamento onde teríamos um novo objeto exemplo acccount.payment.plan onde seria possível criar regras e politicas de cálculo de juros, descontos e condições ( que parecem ser a necessidade que levou a isso ) baseadas na combinação do Modo e na Forma de Pagamento, na localização ainda poderíamos adicionar outros campos Fiscais nessa combinação como o Tipo Fiscal do Parceiro e etc, e incluir isso nos metodos de calculos dos valores no Pedido de Venda/Compra e Documentos Fiscais de forma independente e sem ter necessidade de juntar os objetos e pelo que parece com uma melhor possibilidade de criar regras de juros/descontos, o que você pensa sobre isso ?

"E na hora da efetivação do pagamento isso pode ser alterado por diversos motivos: do lado do cliente, operacionais e do lado do banco."

Isso parece ser a questão do CNAB de retorno, acredito que deve ser tratado de forma separa não vejo relação com a idéia de juntar o Modo e Forma de Pagto, qual seria ?

"Por exemplo se vc está gerando uma cobrança em boleto que vc não tem certeza que o cliente irá pagar, por exemplo um e-commerce. Vc deve usar a carteira que vc não paga por registro de boleto, somente para as taxas caso o cliente pague.

Já no caso de vendas b2b vc usa a carteira q vc paga quando registra o boleto, pois tem "aceite" e tb as taxas bancárias são muito mais baratas."

Esse exemplo parece ser bem operacional e de responsabilidade do operador, mas a proposta do modulo que fiz acima parece que pode atender em partes essa necessidade, adicionando os campos Tipo Fiscal do Parceiro ou algum outro campo Fiscal na combinação, ou não ?

Acredito que sempre que for possível é melhor manter o funcionamento padrão dos objetos, mas talvez eu não estou vendo a necessidade, problema que levaram vocês a fazer essa alteração, se puder explica-la podemos buscar chegar em uma solução que atenda a todos.

**Comment by mbcosta** [comment]
Pessoal o ponto inicial para esse debate e a implementação é a alteração do leiaute da NFe 4.0 que passou a permitir mais de um Modo de Pagamento por Nota, como isso será feito é o que vai definir se será melhor juntar os objetos, já há o PR https://github.com/OCA/l10n-brazil/pull/820 tratando isso, sobre a NFe 4.0

https://blog.oobj.com.br/campos-de-pagamento-nfe-4-00/ https://nstecnologia.com.br/blog/formas-de-pagamento-da-nfe-4-0/
https://blog.tecnospeed.com.br/como-preencher-o-grupo-de-pagamento-na-nf-e-4-00/

**Comment by marcelsavegnago** [comment]
Pessoal, estou deixando a Issue aberta por conta deste alinhamento. Se for o caso, sugiro uma nova RFC especifica sobre esta arquitetura.

**Comment by mbcosta** [comment]
ola @marcelsavegnago desculpe não menciona-lo na reposta, se quiser pode manter Fechado, acredito que a partir de agora o debate vai ser feito diretamente no PR https://github.com/OCA/l10n-brazil/pull/820 que está implementado isso.

**Comment by marcelsavegnago** [comment]
Grande @mbcosta sem problemas meu amigo. Estou fechando então.
