### ISSUE TITLE
[12.0][BUG] Erro ao duplicar Operação (Módulo Fiscal)

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#899]
Ao duplicar uma operação fiscal ocorre a seguinte mensagem de erro:

Fiscal Operation already exists with this code !

**Como Reproduzir**

- Acesse o módulo Fiscal / Configurações / Operações / Operação
- Escolha uma Operação
- Clique em Ações / Duplicar

**Comportamento esperado**
O esperado é que a operação seja duplicada com um novo código.

**Capturas de Tela**

![image](https://user-images.githubusercontent.com/3595132/84456107-9027e800-ac35-11ea-9805-98835c6cf882.png)

**Comment by mileo** [comment]
É necessário sobrescrever o método copy, alterando o código para um código que não exista.

Ou colocar o atributo copy=False no campo código.

Pelo que me lembro isso está em um modelo abstrato e pode se repetir em outros registros.

**Comment by marcelsavegnago** [comment]
@mileo Blzz.. Eu lembro que vc mostrou como faz. 

Obs. optei por registrar como um bug para não esquecer e deixar aqui na fila.. blz ?
