### ISSUE TITLE
[RFC] l10n_br_contract - Integração com contratos

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#910]
Pessoal o @gabrielcardoso21 começou a trabalhar hoje na integração com o https://github.com/OCA/contract/tree/12.0/contract

Se alguém tiver uma sugestão, inicialmente o código esta no PR https://github.com/OCA/l10n-brazil/pull/813

**Comment by mileo** [comment]
https://github.com/odoo-brazil/l10n-brazil/tree/feature/12.0-l10n_br_contract

**Comment by gabrielcardoso21** [comment]
https://github.com/OCA/l10n-brazil/pull/911
