### ISSUE TITLE
l10n_br_zip Inoperante

### ISSUE THREAD

**Issue by aledr** [OCA/l10n-brazil#918]
module: l10n_br_zip
version: 12.0

**Steps to reproduce**
Instalação Odoo branch 12.0 + l10n-brazil branch 12.0.
Instalado módulo l10n_br_base e l10n_br_zip.
pycep-correios-4.0.3

**Current behavior**
- A tabela na base de dados não é populada com os CEPs.
- O botão para pesquisa de CEP não é exibido.

**Expected behavior**
- Popular tabela na base de dados com os CEPs.
- Nos endereços de parceiro, empresa e prospectos deveria exibido ao lado do campo CEP um botão para pesquisa de CEP.
- O CEP deveria ser consultado ao não ser encontrado.

**Comment by mileo** [comment]
![image](https://user-images.githubusercontent.com/1975978/86103940-cbc70c80-ba93-11ea-8604-d2b056a1bbe3.png)

@aledr testei no runbot e esta pegando.

http://3428373-12-0-13e771.runbot1.odoo-community.org/web?debug=1#id=17&action=129&model=res.partner&view_type=form&menu_id=95

Veja se vc consegue reproduzir o seu erro ai plz.

**Comment by aledr** [comment]
Me apeguei ao texto que dizia que a tabela de CEPs deveria ser populada com a instalação do módulo e fiz uma avaliação rasa do caso.
- Desativei o tema *MuK Backend Theme* e o botão de busca apareceu.
- Após inserir e pesquisar um CEP a tabela começou a ser populada com os CEPs pesquisados.

Como o tema *MuK Backend Theme* é popular é interessante adicionar uma nota sobre a incompatibilidade.

**Comment by marcelsavegnago** [comment]
@aledr eu uso o Muk Backend e não notei o problema

**Comment by aledr** [comment]
@marcelsavegnago ativei novamente o tema e agora a tela mostrou corretamente o botão e o campo de CEP (no começo da seção Endereço, antes estava ao lado do bairro.)
Abaixo a evidência dos dois testes exibindo a tela corretamente.

![image](https://user-images.githubusercontent.com/47945/86149349-3bf48300-bad2-11ea-91f2-96de1c3ce142.png)

![image](https://user-images.githubusercontent.com/47945/86151720-7f9cbc00-bad5-11ea-966a-90100798cab4.png)
