### ISSUE TITLE
[BUG][12.0] nao eh possivel apagar uma nota de remessa, nem o invoice nem o documento fiscal

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#936]
nao eh possivel apagar uma nota de remessa, nem o invoice nem o documento fiscal

**Reproduzir**
Etapas para reproduzir o comportamento:

Isso acontece com alguns merges dos modulos stock_account ( https://github.com/OCA/l10n-brazil/pull/758 ) em particular, mas deixo registrado aqui para nao esquecer. Acontece se vc confirmou uma nota fiscal de remessa.

**Comportamento esperado**

Deveria ser facil apagar uma nota fiscal de remessa confirmada. Mas hoje nao eh possivel porque o invoice da remessa tem estatuto 'paid' o que impede de cancelar facilemente ou detonar a nota. O statuto eh paid para que o Odoo nao peca o pagamento. Mas nisso um account.move com valor 0 eh gerido e unlik do account.invoice bloca https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_invoice.py#L810

** Workaround com SQL **
* set NULL do move_id e do move_name do account_invoice, set state='draft'
* cancelar o account_move, detonar o account_move
* pela interface detonar o invoice.
* no SQL set edoc_state='em_digitacao' no l10n_br_fiscal_document do documento fiscal
* pela interface detonar o documento fiscal de remessa.

A gente vai lidar com isso na Akretion.

**Comment by marcelsavegnago** [comment]
@rvalyi se for gerado em um diário do tipo diversos ao invés de diários do tipo compra ou venda ?

**Comment by rvalyi** [comment]
Eh o caso sim, porem nao sei muito dizer se eh melhor botar o status como 'paid' para nao interferir nas funcionalidades nativas do Odoo ou se teria melhor formas. O valor do invoice ja ta resolvido para nao interferir, mas tem outras partes do codigodo Odoo que vao puxar os invoices 'ainda nao pagos' por isso que botamos 'paid'.
Quem trabalhou mais nisso eh o @renatonlima . Mas na hora de ver o merge #758 vamos ter que dar uma checada nisso.
