### ISSUE TITLE
[12.0][RFC] Criar um cadastro de alíquotas mensais de ISS

### ISSUE THREAD

**Issue by gabrielcardoso21** [OCA/l10n-brazil#939]
Para empresas prestadoras de serviço do Simples Nacional, a alíquota de ISS depende do faturamento do mês e muitas vezes não é um valor fixo.

A configuração pode ser feita manualmente todo mês, mas é uma modificação complexa e que pode levar um usuário não experiente a cometer erros nas configurações padrão de impostos na empresa e necessitar de suporte técnico todo mês. 

Outro problema é que o sistema atualmente não guarda um histórico de alterações nos impostos padrão, de forma que um usuário somente poderia saber seu histórico de alíquotas de ISS mensais se as guardasse numa ferramenta externa, como uma planilha por exemplo.

A solução mais simples seria um cadastro bem acessível e amigável ao usuário, no qual pudesse cadastrar as alíquotas de cada mês antecipadamente e o sistema escolhesse a alíquota adequada com base na data de emissão da nota fiscal. O cadastro poderia ser um modelo com um campo "ano" e um campo one2many com outro modelo que teria o mês (selection de "Janeiro", "Fevereiro", etc.) e a alíquota de ISS. Poderia ser colocado no menu "Configurações" do módulo Fiscal e ser visível somente se a empresa atual for do Simples Nacional e prestadora de serviços.

**Comment by renatonlima** [comment]
@gabrielcardoso21,

Na localização já existe a tabela de faixas do simples nacional onde tem essa informação sobre o percentual de todos os impostos que compoe a aliquota do simples nacional

![Screenshot from 2020-10-14 12-30-24](https://user-images.githubusercontent.com/211005/96011734-ae873580-0e19-11eb-9262-dd9d60bf04fe.png)

No cadastro de empresa é definido o anexo e a faixa atual padrão:

![Screenshot from 2020-10-14 12-36-07](https://user-images.githubusercontent.com/211005/96011883-e4c4b500-0e19-11eb-9339-f4f680c6e0e5.png)

A medida que é gerado os documentos fiscais, nas linhas dos documentos fiscais é armazenado a faixa do simples para que na emissão do documento fiscal e na apuração tenha as informação da aliquotas que podem variar.

![Screenshot from 2020-10-14 12-40-29](https://user-images.githubusercontent.com/211005/96012687-bf847680-0e1a-11eb-99ce-94947196a7df.png)
