### ISSUE TITLE
Erro de mapeamento entre document_events e outras classes

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/l10n-brazil#95]
O mapeamento feito entre esta classe, e outras como cce, invalid.number, invoice.cancel está incorreto.

Passos para reproduzir:
Com uma base vazia se for feito por exemplo a criação de uma inutilização de número, depois tentar enviar ao sefaz vai ocorrer erro ao tentar salvar um document_event.

Versões:
- develop

Isto porque na classe a propriedade document_events_id está relacionada a account.invoice.
![document-event-invoice](https://cloud.githubusercontent.com/assets/854781/4601231/13cd74c6-50f3-11e4-8559-e6f40064bfba.PNG)

Na classe invalid.number por exemplo ela referencia aquele campo, porém o campo não referencia de volta.
![invalid-number](https://cloud.githubusercontent.com/assets/854781/4601233/1805dea2-50f3-11e4-836b-05c8605a6cc8.PNG)

**Comment by mileo** [comment]
:+1:

**Comment by danimaribeiro** [comment]
Era esse erro que aconteceu ontem no hangout :)
