### ISSUE TITLE
[12.0][Q&A] l10n_br_stock_account - PRs duplicadas

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/l10n-brazil#971]
@renatonlima 

Este módulo tem 2 PRs... independente do motivo desta divisão, tem alguma sugestão do que pode ser feito ou em qual devemos focar a revisão e teste ?

Como os esforços se complementam, acredito que o caminho mais adequado deveria ser que as contribuições fossem na mesma PR. 

No momento tenho testado a PR mais nova.
https://github.com/OCA/l10n-brazil/pull/758
https://github.com/OCA/l10n-brazil/pull/956

cc @mileo

**Comment by mileo** [comment]
@marcelsavegnago estamos trabalhando no #956 que esta no fork http://github.com/odoo-brazil/l10n-brazil

Nós da @kmee, o pessoal da @akretion e outros contribuidores tem acesso, caso você queria contribuir comente no PR que vai assumir algum dos itens. Fique a vontade para commitar direto ou fazer um PR.

O @gabrielcardoso21 assumiu algumas tarefas relacionadas a ele hoje e vai continuar provavelmente até finalizar, pois toquei com ele na parte do CNAB e Boletos.

Comentei com ele para já ir pensando nos itens citados abaixo e se possível delegar para alguém.

l10n_br_sale_stock,
l10n_br_delivery,
l10n_br_purchase.

ABS!
