### ISSUE TITLE
[BUG][12.0] NFe: serializacao da tag <NFref> ta zoada

### ISSUE THREAD

**Issue by rvalyi** [OCA/l10n-brazil#973]
isso eh relacionado aos PRs de NFe em aberto. Mas apenas para nao esquecer botando aqui que o export de uma NFe com NFe relacionada nao se exporta correctamente. Exporta dessa forma com as tags <refNF/>, <refNFP/> e <refECF/> vazias.

```
<NFref>
<refNFe>42200975277525000259550010000282771228112214</refNFe>
<refNF/>
<refNFP/>
<refECF/>
</NFref>
```

Isso deve ser porque NFref acaba apontando pro mesmo modelo da NFe e ai o spec_models/models/spec_export.py acaba tropeçando. Vai ter que dar uma atencao nesse grupo na hora do merge da NFe.

**Comment by rvalyi** [comment]
(fiz uma gambiarra no spec_models/models/spec_export.py cliente nosso, mas vamos ter que resolver de forma limpa)

**Comment by rvalyi** [comment]
cc @gabrielcardoso21

**Comment by gabrielcardoso21** [comment]
Comecei a desenvolver a solução para isso, está lá mesmo no PR, só não consegui resolver alguns detalhes. Quando formos dar o merge eu volto nessa questão.

**Comment by rvalyi** [comment]
> Comecei a desenvolver a solução para isso, está lá mesmo no PR, só não consegui resolver alguns detalhes. Quando formos dar o merge eu volto nessa questão.

perfeito. Resolvemos la na frente, so botei aqui para nao esquecer.

**Comment by rvalyi** [comment]
@gabrielcardoso21 nao sei se vc viu mas eu comentei bastante detalhadamente no GTalk e Telegram o que eu fiz para empacotar a nfelib de forma que eu acho sustentavel para ser dependencia da OCA. E que pedi para vcs fazer uma coisa semelhante na nfselib (podendo ser mais frouxo no nfselib sem problema), no espirito da coisa que eu mostrei pro Luis 2 anos atras embora launcher de generateDS estar em Bash e faltar esquemas.

Ja que o erpbrasil.edocs vai puxar tudo junto (infelizmente mas tudo bem), fazer essa limpeza basica eh o primeiro passo para rolar os merges disso na OCA sem isso criar uma bola de neve la na frente com cada um tendo que dar suporte de forma conflitual a bibliotecas sem teste nem processo de geração claro.
