### ISSUE TITLE
[RFC] Contabilização das movimentações de estoque

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#979]
Pessoal abro este espaço para falarmos sobre a questão da contabilização das movimentações de estoque. 

Vou reunir alguns materiais sobre o assunto e semana q vem e posto aqui.

**Comment by rvalyi** [comment]
ver o trabalho do @marcelsavegnago aqui https://github.com/OCA/stock-logistics-workflow/pull/703

**Comment by marcelsavegnago** [comment]
Acredito que o stock_landed_cost não vai influenciar na questão da emissão de fatura via picking já que tanto o picking (se configurado método de valorização automático) e a invoice vão gerar os lançamentos contábeis da mesma forma de antes. Já  o stock_landed_cost vai gerar um lançamento no diário de estoque baseado no picking de entrada. Enfim, se não for alterado o modo nativo de contabilização do estoque.. acredito que não teremos problemas.

Mas de fato é importante esta avaliação para garantir a contabilização de gastos adicionais do produto.
