### ISSUE TITLE
[BUG][l10n_br_account_product] Calculo dos impostos incorretos

### ISSUE THREAD

**Issue by mileo** [OCA/l10n-brazil#99]
1 - Crie uma nova fatura;
2 - Selecione um cliente;
3 - Adicione um produto e coloque uma quantidade por ex: 10 un;
4 - Clique em atualizar;
5 - Altere a quantidade dos produtos;
6 - Clique em atualizar;
7 - Confirme a fatura.

A Base de calculo e valores dos impostos não será recalculada com a nova quantidade.

**Comment by renatonlima** [comment]
Olá Luis,

Eu também vi este problema, parece que no método create ou write ele não chama o compute que faz o calculo dos impostos e o estranho é que se você ir no botão "Atualizar Impostos" ele recalcula corretamente os valores dos impostos, parece que existe algum método na localização não esta chamando o compute dos impostos.

**Comment by rvalyi** [comment]
so comentando, na v8 eu vi um problema semelhante no core (sem localizaçao) um mes atras. Na epoca com pressa nao reportei mas tava bem zoado. Nao sei se o problema permanece no caso mas so aproveito para avisar de ficar com pe atras nesse ponto na v8 tb.

**Comment by renatonlima** [comment]
@rvalyi,

Eu tbm tinha testado a versão 8.0 e notado esse problema, porém na 7.0 pode ser uma regressão no core ou na localização, @mileo você chegou a testar sem localização?

**Comment by mileo** [comment]
Corrigido, mas está no branch da nfe 3.1. Sobrando um tempo eu extraio e faço o commit. 

Era mesmo problema da localização.

**Comment by mileo** [comment]
@renatonlima Issso foi corrigido na OCA?
